- avocado/core/plugins/virt_test.py
- avocado/core/plugins/virt_test_list.py
Disable the vt plugins when virt-test is not initialized.
This avoids the error:
Cannot access 'vt_list_all': File not found
When virt-test was not bootstrapped and you are trying to
list available virt-tests.
Changes from v3:
* Removed the changelog from the commit message, per adereis's suggestion.
Changes from v2:
* Removed custom SetupError exception for builtin EnvironmentError, per ldoktor's suggestion
* Do not store elements of downloads dir in the module, per ldoktor's suggestion
> [V3] avocado-vt: Fail to load plugins on uninitialized virt-test

- avocado/core/plugins/virt_test.py
When adding cmdline arguments, setting is read to find default values,
but they are used only for help, not for the real defaults. The code
underneath uses other methods to obtain the value than settings in case
of None value making it impossible to use the settings.
This patch uses the settings values as defaults instead the None value.
> plugins.virt_test: FIX: Use defaults instead of None

- avocado/core/plugins/virt_test.py
The way the virt plugin selects its tests is by passing
the user provided URL to the cartesian parser. Some of
the identifiers the user might pass are illegal in this
context (example, examples/tests/sleeptest.py contains
slashes, that are illegal for the cartesian parser).
The fact the identifier is illegal for the cartesian
parser already means it's invalid, no need to propagate
exceptions. Just return an empty list and let other
test loader plugins to try to identify it.
> avocado.core.plugins.virt_test: Return empty test list on LexerError

- etc/avocado/conf.d/virt-test.conf
I forgot to update that reference, let's fix it.
> virt-test.conf: Fix old env variable name on comment

- avocado/core/plugins/virt_test.py
mux_entry option was renamed in avocado to mux_path, we should follow
this modification in avocado-vt too.
> plugins.virt_test: Rename mux_entry to mux_path

- avocado/core/plugins/virt_test.py
Turns out it's unnecessary and a bad idea, since this
will get logged in the avocado job log even if users
are not directly using the vt plugin.
> plugins.virt_test: Remove unnecessary logging

- avocado/core/plugins/virt_test.py
The machine and arch need to be regularly updated between test runs thus
it makes sense to set it on cmdline.
> plugins.virt_test: Support to override machine/arch on cmdline

- avocado/core/plugins/virt_test.py
Guest os is highly dependant on arch and machine type. It's quite useful
to have this information listed when erroring-out.
> plugins.virt_test: Improve error message on missing guest os

- avocado/core/plugins/virt_test.py
Introduced with commit 802ccb7d96c158566828b6fc9906815133a59a45,
this bug is caused by the fact that importing from the core
avocado test class causes the logging configuration stage
to be skipped, causing the individual test logs to come up
empty.
> avocado-vt: Fix bug - Individual test log files come up empty

- avocado/core/plugins/virt_test.py
It was pointed out that using the API available
to test writers is a layer violation (plugins are
supposed to be 'core' code), so let's have a different
fix -> one of the refactors of the test class turned
the .start_logging and .stop_logging methods 'private'.
The fix that keeps the boundaries intact involves
renaming the methods in the VirtTest class implementation
to have the same names as the parent class -> this will
make them to be executed, logging calls that go to the
root logger also get logged in the test log.
> avocado-vt: Another fix for the empty logs

- avocado/core/plugins/virt_test.py
Introduced with commit ef1411bb, the print statement
is a leftover that shouldn't be there. Let's remove it.
> avocado.core.plugins.virt_test: Remove debugging statement

- avocado/core/plugins/virt_test.py
This patch removes the job dependency in VirtTestLoaderPlugin and
adjusts the method names accordingly to the new API.
__IMPORTANT: This patch has to be merged together with https://github.com/avocado-framework/avocado/pull/721__
v1: https://github.com/avocado-framework/avocado-vt/pull/27
Changes:
v2: Support to run  `--vt-config` without any params
v2: Adjust the loader to the updated API
> plugins.virt_test: Reflect changes in avocado loader [v2]

- requirements-travis.txt
Inspektor 0.1.15 has a bug (it doesn't require pep8,
so people trying to use it without pep8 are in for a
treat).
With the 0.1.16 release, that bug is fixed, so, let's update.
> requirements: Update inspektor requirement to 0.1.16

- requirements-travis.txt
- requirements.txt
aexpect is required by virt-test. Also add generic requirements.txt for
users.
> requirements: Add aexpect and generic requirements

- virttest/utils_misc.py
The output of "qemu -cpu ?" is not that important and was not logged
before.
> virttest.utils_misc: Don't log the qemu -cpu ? output

- avocado-plugins-vt.spec
Use 'nc' as a dependency instead of 'nmap-nc' in the
spec file, given that the later is only available on
newer Fedora versions, while the former is available
in both Fedora, RHEL 6 and RHEL 7.
> avocado-plugins-vt.spec: Fix 'nmap-nc' dep to 'nc'

- avocado/core/plugins/virt_test.py
The author meant vt_netdst instead of netdst.
> avocado.core.plugins.virt_test: Fix typo

- virttest/qemu_vm.py
That particular command must be executed with shell=True,
as it uses shell features. In some supported platforms,
such as RHEL6, we noticed problems, so let's send this
fix.
> virttest.qemu_vm: Use shell=True getting help_info

- virttest/qemu_vm.py
I found this one while trying out custom configs. Sometimes
it's possible that the VMMigrateProtoUnsupportedError gets
called without params, in which case we should provide
default params to the class.
> virttest.qemu_vm: Fix exception class called without params

- virttest/bootstrap.py
- virttest/data_dir.py
Fixes #56
Basically, in some conditions [1], the base backend dir and the local backend dir might be out of sync and some files might be missing, causing the plugins to fail. Let's play safe and synchronize the backend directories and make sure all files are there after a vt-bootstrap.
[1] For example, user interrupts the bootstrap and starts it again
Changes from v1:
* Dropped the use of `rsync` to use the standard library python module `distutils`.
> [V2] Ensure bootstrap always updates the local backend directory

- avocado/core/plugins/virt_test.py
- avocado/core/plugins/virt_test_list.py
- docs/source/conf.py
- scripts/build_docs.py
- scripts/github/cache_populate.py
- scripts/github/example.py
- scripts/github/label_issues.py
- scripts/github/pulls_applied.py
- scripts/github/stale_pulls.py
- scripts/github/unassigned_issues.py
- shared/cfg/base.cfg
- shared/cfg/guest-hw.cfg
- virttest/asset.py
- virttest/bootstrap.py
- virttest/data_dir.py
- virttest/env_process.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
- virttest/staging/backports/_itertools.py
- virttest/standalone_test.py
- virttest/utils_misc.py
- virttest/utils_test/libvirt.py
We were still referring to virt-test in many places
of the code. Let's fix all but the ones that are
actually valid (when we refer the old virt-test runner).
> avocado-vt: Update references to virt-test

- avocado-plugins-vt.spec
- virttest/env_process.py
- virttest/video_maker.py
Make video generation work without deprecated messages in avocado-vt, by adding a new class that can use the newer gobject introspection infrastructure to use gstreamer to encode the videos.
Changes from v1:
* Follow @ldoktor's suggestions in the encoding class
> [V2] Video generation

- docs/source/extra/DownloadableImages.rst
> docs: Change reference to old 'tools' subdir to 'scripts'

- virttest/staging/service.py
It's really not necessary to have that command output
to be logged.
> virttest.staging.service: Silence process.run call

- avocado/core/plugins/vt.py
- etc/avocado/conf.d/vt.conf
- virttest/env_process.py
- virttest/libvirt_vm.py
- virttest/staging/lv_utils.py
- virttest/tests/unattended_install.py
- virttest/utils_net.py
- virttest/utils_test/__init__.py
- virttest/utils_test/libvirt.py
It's my fault and I didn't test the libvirt backend nearly enough. After these fixes, I'm able to run virsh tests. An example command line that runs 3 tests (libvirt guest `install`, one virsh test, then libvirt guest removal):
sudo avocado run unattended_install.import.import.default_install.aio_native type_specific.io-github-autotest-libvirt.virsh.find_storage_pool_sources_as.positive_test.local_source.nfs_type remove_guest.without_disk --vt-type libvirt --vt-setup
Yes, you have to use `sudo`, because that's the way `libvirt` tests can access the `system://` session, unfortunately. And this all assumes you are running from the rpm install. For the source install, the instructions are slightly different:
sudo scripts/avocado run unattended_install.import.import.default_install.aio_native …
> [V3] `--vt-type libvirt` Fixes

- virttest/storage.py
Hello guys,
this patch avoids partial backups on interruption. Anyway while working on this I spent some time analyzing how the backup is performed and there are few differences.
```
1. try to get asset file
2. unpack the asset file (7z archive)
1. (unless --keep-image) Create first raw ".backup" backup
2. Execute test
3. (unless --keep-image-between-tests) revert the image from raw ".backup"
4. while test goto 2
```
```
1. try to get asset file
2. unpack the asset file (7z archive)
1. (if --vt-setup) Unpack the asset file
2. Execute test
3. (unless keep_image_between_tests) revert the image from raw ".backup"
4. while test goto 2
```
I tried to unify it, but it turned out to be a bit more complicated, so I'd like to get your opinion first... So far my preferred solution would be:
1. use …
> virttest.storage: Secure the backup handling

- virttest/cartesian_config.py
This commit extends cartesian config format with keywords: 'suffix' and 'join'.
Justification:
Cartesian configs were invented as a part of virt-test framework.  Purpose of
cartesian configs is flexible configuration VMs for various kinds of tests.
SpiceQE team faced with one problem: all existing configs were written to run
only one VM at same time. For example: only RHEL6 or only RHEL7. But not both
at the same time.
This commit tries to full fill this gap.
virt-test can run different VMs with different configurations, each of VMs
should have some suffix.  With extended caretesian config syntax it is possible
to use existing different configs at the same time.
Additional info:
<pre><code>
virttest|master ⇒ cd   
~|⇒ cat 1.cfg 
a = …
> Add suffix & join to cartesian_config.py

- avocado-plugins-vt.spec
For some reason, I've missed that pretty badly. aexpect
is required for the plugin to work properly, yet we don't
have it as a dependency on our spec file. Let's fix that.
> spec file: Add aexpect dependency

- avocado/core/plugins/vt.py
Currently you suppose that 1 test == 1 entry at subtests.cfg
SpiceQE team uses one script wich can take many options at input.
Actual test name will be quite different from script name.
Test name and it meaning can be generated on second step,
depending on actual run requests.
I ask to take test-name from from different config.
> Print test name for spice tests as sub-test variant

- virttest/asset.py
- virttest/bootstrap.py
Up to this time, avocado-vt repo should hold cartesian configs for each known
backend at backends/<backend>/cfg/*.cfg
Each modification to above files should become a pull-req to avocado-vt tree.
This commit allows store cartesian configs at test-provider git-repo. As a
result escape pull-reqs.
Cartesian files specified at tp's ini will be copied to backends/<backend>/cfg/
at `avocado vt-bootstrap' stage.
It is possible to specify few cartesian configs using next technique:
[spice]
subdir: spice/
configs: tests.cfg, tests-shared.cfg, spice-vm-install.cfg, tests-spice.cfg
> Specify backend's cartesian configs in tp-ini file

- virttest/asset.py
- virttest/data_dir.py
In a similar vein to the test backend dirs, when new test
provider .ini files are added to avocado-vt, sync them with
their local avocado data dir counterparts. This way we don't
risk getting our test provider info out of sync.
This fixes a bug when running vt-bootstrap --vt-type spice
on local dir structures already created would prevent the
new test provider to be downloaded/updated.
> virttest: Update providers dir whenever tp names are checked

- shared/cfg/guest-hw.cfg
ARM64/PPC64 doesn't support ide cd-interface. This patch only sets it
when i440fx is used (q35 already uses ahci in the same fashion)
> shared.cfg.guest-hw: Set cd_format only for i440fx/q35

- avocado/core/plugins/vt.py
- avocado/core/plugins/vt_list.py
- backends/libguestfs/cfg/tests.cfg
- backends/libvirt/cfg/tests.cfg
- backends/openvswitch/cfg/tests.cfg
- backends/qemu/cfg/tests.cfg
- backends/v2v/cfg/tests.cfg
- requirements.txt
- shared/cfg/base.cfg
- shared/cfg/guest-hw.cfg
- virttest/asset.py
- virttest/bootstrap.py
Hello guys, while working on power I found few problems. See each patch for details. The only important ones are:
* virttest: Import distutils.dir_util properly - some versions of distutils doesn't export dir_util by default making avocado-vt unusable
* shared.cfg.base: Change the default for migrate_vms - this troubles me for a while now (internally I remove migrate_vms for about a year now). I studied the code and it should be safe to remove it completely, because it extends the list of vms of the vms before usage. Without this fix all tests with `vms = ""` create the VM, which causes false-negatives or just runs longer (of boot+shutdown time). With this patch migrate_vms ends up with the same content so it should work.
* virt-test: remove display configuration - backport of a fix …
> Couple of mixed fixups [v2]

- avocado/core/plugins/vt.py
Problem:
list command does not setup default value for vt_guest_os
run command setups default value for vt_guest_os
run / list get different only-filters
tests from tp-spice use several different VM at same time with different OSes.
tp-spice specifies OS at config file.
> Ignore vt_guest_os for vt-type==spice at all

- virttest/libvirt_vm.py
- virttest/qemu_vm.py
- virttest/tests/unattended_install.py
A long time ago, back in 2012 (see commit
feaa5e5a21733d4d1568e08879974ac55ef7bbad), unattended
install started to use the serial log file contents
instead of the serial console aexpect session. The
change was motivated by unattended install tests
with ping pong migration, that made the finish
message to be lost because of the switch between
src and dst.
Later on, we unified libvirt and qemu unattended
install mechanism, by making both read from the
log. Unfortunately, keeping up both implementations
working simultaneously was difficult, given that
people working with libvirt rarely tested on qemu
and vice-versa.
So here we go again. The QEMU implementation got
broken by patch 319887f26ada824033fde48812aa7715a0f4317e,
by yours truly, made when working on the libvirt
subtest bugs.
This …
> avocado-vt: Fix unattended install

- Makefile
This patch adds link/unlink targets used by main avocado Makefile.
It requires https://github.com/avocado-framework/avocado/pull/780 patch in order to work the same way as before.
> Makefile: Add link/unlink targets

- virttest/data_dir.py
Make the root dir detection in avocado-vt more robust
(sometimes the virttest dir is not a symlink, so let's
treat this case). Additionally make the code a bit more
clear, with the help of intermediate variables.
> virttest.data_dir: Make the root dir detection a bit more robust

- docs/source/GetStartedGuide.rst
THe "avocado list" requires --vt-type when not using qemu. Let's make it
clear that people needs to supply it when not using default (qemu).
> docs..GetStartedGuide: Add --vt-type to list

- virttest/qemu_monitor.py
This reverts commit 73c0754f1692136d44ce705fbccf1fc6621ab398.
This commit has been found to cause a single image to be
touched by several QEMU processes, so it has to be
reverted.
> Revert "virttest.qemu_monitor: Add vm.name for monitor log"

- virttest/data_dir.py
Use `os.path.realpath` which returns absolute path instead of reading
the link.
> virttest.data_dir: Simplify root dir detection

- virttest/ovirt.py
- virttest/utils_v2v.py
All type VMs(qemu, libvirt and v2v) are using the same pattern to
create VM object in utils_env.create_vm.
> ovirt: Fix the missing param bug

- avocado/core/plugins/vt.py
avocado-vt relies on the output (eg. migration status), set LANG=C to
avoid such problems.
> vt: Set "LANG=C" to avoid locale problems

- avocado-plugins-vt.spec
Instead of python-gstreamer, it should've been gstreamer-python.
> avocado-plugins-vt.spec: Fix dependency naming

- avocado/core/plugins/vt.py
tp-spice has special configs set, that does not uses
subtests.cfg at all
Currently test name is based on subtests.cfg part.
This commit allows get test-name for tp-spice when subtests.cfg not in
action.
> Get test name if subtests.cfg is absent

- virttest/utils_spice.py
The library utils_spice was removed in commit 34cf172ea7cf2460f7bfe0dc1dce6d7d415430c0.
However, as long as we have spice tests in tp-qemu, not having utils_spice.py
makes us to effectively ship broken code. When tp-spice is stable
and fully functional, the correct move is to remove the library
and the tests from tp-qemu altogether.
> virttest: Bring back utils_spice.py

- virttest/cartesian_config.py
Config example:
variants:
- one:
- two:
variants:
- x:
- y:
only one..y, two
only one
Should produce:
dict    1:  y.one
> Fix filters processing for cartesian configs

- virttest/tests/unattended_install.py
General answer files locate at: avocado-vt/shared/unattended
SpiceQA asked few times to add special answer files
It would be fine to have ability keep such files in test-provider repo
And after this patch
shared/unattended/RHEL-6-spice.ks
shared/unattended/RHEL-7-spice.ks
can be removed from avocado-vt
> Lookup for unattended_file at test provider dir

- shared/unattended/SLES-12.xml
Currently ssh related config does not work in SLES12.0
This patch is to moving ssh related config to post-scripts
ID:1258777
Signed-off-by: Mike Cao \<bcao@redhat.com\>
> avocado-vt: modify SLES12.0 ssh config

- shared/deps/run_autotest/boottool.py
No need to temporarily store the return of subprocess.call().
self.check() is responsible for checking the result of operation.
> run_autotest/boottool: cleanup and remove unused variable

- shared/cfg/guest-os/Windows/Win2012/x86_64.cfg
- shared/cfg/guest-os/Windows/Win8/i386.cfg
- shared/cfg/guest-os/Windows/Win8/x86_64.cfg
Most Windows ISO images have prefix: isos/windows.
Only 3 fixed above ISOs had strange prefix.
It would be fine to have all ISOs at the same dir.
It is necessary to notify: Xiaoqing Wei <xwei@redhat.com>
He was a author who introduced the strange prefix.
> Path to Windows ISOs should have same prefix

- virttest/qemu_vm.py
-boot is usually broken or not supported on ARM. ARM developers said
they do not care about -boot and will not fix it in the near future.
Avocado-vt doesn't yet support -bootindex properly, but in most cases
it suffice and works fine. Let's just skip -boot on ARM and let users
adjust their tests to use -bootindex instead.
> virttest.qemu_vm: Skip -boot on ARM

- avocado/core/plugins/vt.py
- virttest/bootstrap.py
- virttest/standalone_test.py
- virttest/utils_env.py
- virttest/utils_misc.py
- virttest/utils_net.py
- virttest/utils_test/libvirt.py
The find_command in utils_misc is already implemented in
avocado.utils.path.
This command deprecate this function and show a warning logging
if some command still using it.
We can't change the existing reference of this function in
virt-test providers, since it will fail if someone still using
virt-test.
Also some reference to path.command is changed to path.find_command
since the command function no longer exists.
> utils_misc: Deprecate find_command to avoid duplicate

- virttest/remote.py
Add new param 'linesep' to indicate the content of file
ends up with newline or not.
> virttest/remote.py: Add new param for RemoteFile.add()

- virttest/utils_test/__init__.py
For run_autotest, after copy the autotest to VM, we need clean up
the local tarball.
> virttest/utils_test: Remove the local compressed tarball

- virttest/bootstrap.py
avocado.utils.path.find_command raises
avocado.utils.path.CmdNotFoundError and not ValueError.
> virttest.bootstrap: find_command raises CmdNotFoundError

- virttest/qemu_vm.py
"virtconsole" is a device and not qemu option, therefor we have to use
"has_device" instead.
> virttest.qemu_vm: Fix improper use of has_option for virtconsole

- avocado/core/plugins/vt.py
- virttest/env_process.py
- virttest/iscsi.py
- virttest/postprocess_iozone.py
- virttest/staging/utils_koji.py
- virttest/standalone_test.py
- virttest/utils_conn.py
- virttest/utils_misc.py
- virttest/utils_net.py
- virttest/utils_test/libvirt.py
1) replace avocado-vt.virttest.utils_misc.find_command with
avocado.utils.path.find_command.
2) avocado.utils.path.find_command raises
avocado.utils.path.CmdNotFoundError and not ValueError.
This is a complement to commit eaeb01b.
> avocado-vt: Fix usages of avocado.utils.path.find_command

- virttest/asset.py
- virttest/data_dir.py
- virttest/gluster.py
- virttest/iscsi.py
- virttest/libvirt_vm.py
- virttest/libvirt_xml/pool_xml.py
- virttest/lvm.py
- virttest/qemu_monitor.py
- virttest/qemu_virtio_port.py
- virttest/qemu_vm.py
- virttest/remote.py
- virttest/remote_build.py
- virttest/remote_commander/remote_runner.py
- virttest/test_setup.py
- virttest/utils_env.py
- virttest/utils_misc.py
- virttest/utils_net.py
- virttest/utils_test/__init__.py
- virttest/utils_test/qemu.py
- virttest/utils_v2v.py
- virttest/virt_vm.py
This is a follow up to PR #155 
This PR is part of the solution to the card https://trello.com/c/YvSmaKD5/449-bug-insecure-usage-of-tmp-in-avocado-vt-virt-test
Basically this tidies up uses of `/tmp` in avocado-vt, replacing it with the securely created, per-instance avocado temporary directory. This allows the files to be created securely, solving most of the problems.
This still doesn't touch https://trello.com/c/VMoQ2DPU/390-provide-a-locking-api-for-shared-resources,
that's why the supposedly global vm lock and address db file and lock were all moved to the avocado temporary directory.
Changes from v1:
* Used os.path.join() in all path join situations as opposed to plain string substitution as recommended by @clebergnu 
* Removed incorrect avocado data_dir import noticed by …
> [V2] TMP dir management updates

- avocado/core/plugins/vt_bootstrap.py
- virttest/asset.py
- virttest/data_dir.py
This makes the git clone and bootstrap code more robust against corrupted git repositories and user interruption (issues I commented about on pull request #164). Most importantly, it won't try to delete the test provider directory unless we know it didn't exist yet and was just created by vt-boostrap.
> git clone + user interruption safety

- virttest/utils_misc.py
1) Fix typo (s/amen/name/g)
2) Check if the specified compression is supported
3) Use tarfile.open() instead of tarfile.TarFile()
Please refer to
https://docs.python.org/3/library/tarfile.html
> virttest/utils_misc: improve archive_as_tarball

- avocado/core/plugins/vt.py
Avocado loaders must an additional extra_params argument. Current implementation silently ignores the extra_params, which is not that bad given the fact that it supports only one test_type. For a while I thought about supporting `--vt-type` as extra params, which would make it possible to define default `vt_type` in settings, but then I thought it would be more confusing.
This patch should be accepted ones https://github.com/avocado-framework/avocado/pull/810 is accepted, otherwise `avocado-vt` would stop working.
> vt: Adjust vt_loader to new API

- backends/v2v/cfg/tests-shared.cfg
Both vm_type and connect_uri should be defined before including other
config files, so they can be overwirte in specific cases, just like
the way in libvirt/cfg/test-shared.cfg.
> v2v.cfg: Let the default definitions have lower priority

- virttest/asset.py
We end up asking the question of whether the user wants
to download the asset file twice. Let's cut the redundant
question.
> virttest.asset: Remove redundant question to user

- shared/deps/run_autotest/boottool.py
- virttest/postprocess_iozone.py
1)
virttest/postprocess_iozone: rename variable to avoid conflicts
rename a variant name to avoid conflict with the imported module.
2)
run_autotest/boottool: cleanup and remove unused variable
No need to create the path variable that won't be used.
> two trivial fixes

- virttest/tests/unattended_install.py
If the output string comes up empty, it's not possible
to access its first element. Fix that by properly
handling the resulting exception.
> unattended_install: Fix IndexError

- shared/cfg/base.cfg
- virttest/tests/unattended_install.py
When using the http_ks variants of the unattended install
test, avocado-vt can detect the IP of the main netdst (by
default, virbr0). So instead of leaving an old hardcoded
value in base.cfg, remove it and fix the logic to ensure
the auto detected value is picked over empty values
present in the configuration file.
> unattended_install.py: Bridge IP auto detection for content server

- shared/cfg/guest-os/Linux/SLES/11.4.i386.cfg
- shared/cfg/guest-os/Linux/SLES/11.4.x86_64.cfg
id: 1262205
Note:
There is no difference for xml from SLES.11.2, still using it for SLES.11.4 testing.
> shared/cfg/guest-os: Add SLES.11.4 cfg.

- avocado/core/plugins/vt.py
avocado-vt for each test runs post_command= (if it is supplied).
This patch pass to specified command test's result.
> Export test instance result to env

- virttest/libvirt_xml/vm_xml.py
- virttest/utils_misc.py
Main modification as following,
* Polish the docstring and comments
* Keep consistent for VM status
* No catch CmdError as same as other calls for define
* If define or undefine failed,
No change for original VM and raise LibvirtXMLError
* Update name and uuid if rename succeeded
* Check UUID if it's expected
> virttest/libvirt_xml/vm_xml: refactor vm_rename()

- virttest/utils_misc.py
Rename a variant name 'stat' to avoid conflict with
imported module.
> virttest/utils_misc: fix conflict with builtin module

- virttest/libvirt_xml/devices/hostdev.py
- virttest/libvirt_xml/vm_xml.py
Currently hostdev addition supported adding only pci type device for
passthrough. This commit has added capability to within framework to 
generate a hostdev xml section for USB device passthrough.
Guest VM xml add hostdev will now be able accept USB specific parameters
and add respective xml clause to guest VM accordingly.
> USB type device passthrough using add_hostdev

- virttest/libvirt_xml/devices/hostdev.py
Currently the code to insert hostdev clause for USB device type
has  2 classes defined for vendor id and product id. This patch will
remove these classes and have them as accessors.XMLAttribute
under Source class.
> Patch for usb hostdev type

- selftests/unit/test_utils_env.py
Now that the Environment file is cleaned by the Environment
class at the __del__ method, the tearDown method is unnecessary
(and we can get to a race - at cleanup time the environment time
is still there, but when we try to delete it, it won't be anymore).
> selftests/test_utils_env.py: Don't manually clean environment file

- virttest/bootstrap.py
One of those sneaky copy and paste mistakes. Let's
fix it.
> virttest.bootstrap: Fixup info message

- Makefile
- avocado-plugins-vt.spec
Instead of trusting in rpmbuild to do the rpm builds,
use mock - a program that builds the rpms from fresh
chroots. This ensures that BuildRequires are correct
and that the binary rpms build cleanly.
This requires a few changes to the Makefile targets
and the avocado spec file, laid out in this patch.
Also, add instructions on how to fulfill deps to build
RPM packages.
> Makefile: Use mock to build RPMs

- avocado/core/plugins/vt.py
- virttest/utils_net.py
Fix to the trello card:
https://trello.com/c/AThbmafK/518-bug-incorrect-handling-of-the-missing-adress-pool-lock
I did take a look at the solution discussed at the Monday (2015/10/12) meeting, but I found a problem, explained at the 2nd commit message.
---
Changes from v1:
* Put a "TODO" note about the deprecation of env file
> Fix env file lock problem [v2]

- virttest/asset.py
While testing my fixes to the problem with the env
file, I've ran a lot of avocado jobs, and pressed
several Ctrl+C sequences while they were being executed
in different times.
At some point, my tests started failing every time I
ran a test, and the problem would go away if I ran
vt-bootstrap, but it would come back right after it.
After some time at a loss, I finally figured out what
was wrong: My .backup file was corrupted from one of
the Ctrl+Cs pressed during the backup procedure.
Every time the good, pristine file would be replaced
by a corrupt backup, making my tests fail.
So I propose that at asset restore time, to check
if there's a backup file present, if so, restore
it with the pristine file contents. This way, we
ensure that after --vt-bootstrap new tests are
safe to go. …
> virttest.asset: Restore backup file during bootstrap

- virttest/utils_test/libvirt.py
In Subprocess module, it split command into a list as the first arg
of Popen() if shell is False, but the 'cat' command here can not run
in that way.
> virttest.utils_test.libvirt: Run command in a subshell

- virttest/utils_conn.py
1. Add missing parameter for ConnPrivKeyError
2. Avoid commands split by process.run as some have special characters
> Fix process run failure

- selftests/unit/test_utils_misc.py
- virttest/utils_misc.py
- virttest/utils_test/libvirt.py
process.run use subprocess.Popen to run a command, the command
string will be splitted to a list if shell parameter is False.
If command string includes some special characters such as
'|, &&, ||', the command wouldn't be executed correctly. It need
to set shell to 'True' in parameter for this kind of commands.
Signed-off-by: Ruifeng Bian <rbian@redhat.com>
> virttest: Add 'shell' parameter if using process.run function.

- docs/source/advanced/Networking.rst
- docs/source/extra/DownloadableImages.rst
- shared/downloads/jeos-19-64.ini
- shared/downloads/jeos-20-64.ini
- shared/downloads/jeos-21-64.ini
- shared/downloads/winutils.ini
- virttest/defaults.py
This introduces a simple HTTP server, based on OpenShift, and hosted
at:
http://assets-avocadoproject.rhcloud.com
The asset information files and documentation have been updated to
use this new location.
Also, while at it, remove the F19 JeOS for two reasons: it's old and
we don't have much storage space to spare.
> Replace asset storage HTTP server

- virttest/libvirt_vm.py
The prompt variable isn't used by aexpect.ShellSession.
In fact,
Different distros have declared different shell_prompt
in ./shared/cfg/guest-os/Linux/*.
so it's better pass it to aexpect.ShellSession.
> virttest/libvirt_vm: Fix unused prompt for ShellSession

- avocado/core/plugins/vt.py
The 'list_tests' parameters is used to select which tests should be
listed.  IMHO, it sounds like a boolean kind of parameter, which will
either list tests or not. Let's replace that parameter name with
'which_tests', that IMHO give a better message about its intended
usage.
Also, let's standardize the docstrings, and use the declared supported
symbols for these parameters (DEFAULT, AVAILABLE or ALL) instead of their
values (False, etc).
> Test loader: replace list_tests parameter name for a better description

- virttest/gluster.py
- virttest/utils_test/libvirt.py
NFS should not be used to support the lock volume used by CTDB as NFS does not currently support locking. Instead, use the Gluster native mount.
> virttest: Turn off export of volume through NFS

- avocado/core/plugins/vt.py
legency tp-qemu are still using test.resultsdir but it shows
None in avocado ,this patch is to set logdir to resultsdir
1277031
Signed-off-by: Mike Cao <bcao@redhat.com>
> aovcado-vt: set test.resultsdir = test.logdir

- virttest/staging/service.py
On RemoveRunner.run there is no parameter named "verbose"
> remove parameter "verbose" as it may access RemoteRunner

- virttest/asset.py
- virttest/gluster.py
- virttest/iscsi.py
- virttest/libvirt_vm.py
- virttest/libvirt_xml/pool_xml.py
- virttest/lvm.py
- virttest/qemu_monitor.py
- virttest/qemu_virtio_port.py
- virttest/qemu_vm.py
- virttest/remote.py
- virttest/remote_build.py
- virttest/remote_commander/remote_runner.py
- virttest/test_setup.py
- virttest/utils_misc.py
- virttest/utils_net.py
- virttest/utils_test/__init__.py
- virttest/utils_test/qemu.py
- virttest/utils_v2v.py
- virttest/virt_vm.py
This reverts commit 052f74ed0eef3b9310f920af030e230d13c8633b.
The reason is that the env file, still present, still references
the various temporary files, which are not kept on '/tmp', but
on directories there are really temporary and removed. Subsequent
runs of Avocado-vt would fail because of this broken reference.
> Revert "virttest: Replace uses of /tmp with data_dir.get_tmp_dir()"

- shared/cfg/guest-os/Windows/Win10/i386.cfg
- shared/cfg/guest-os/Windows/Win10/x86_64.cfg
cd1 always been the installation iso in current setup
This patch is removing it for installation case 
ID: 1279315
Signed-off-by: Mike Cao <bcao@redhat.com>
> avocado-vt: fix static content in cd1

- virttest/libvirt_xml/devices/disk.py
The current implementation caused the Exception:
TypeError: super(type, obj): obj must be an instance or subtype of type
It should use self.__class__ as the type parameter in this function.
> Fix TypeError for IOTune and Encryption class in disk xml.

- shared/cfg/guest-os/Linux/RHEL.cfg
For some reason pxe initrd/vmlinuz is not located in images/pxeboot for
ppc64, but in ppc/ppc64.
> shared.cfg.guest-os: Change boot_path for ppc64

- avocado/core/plugins/vt.py
- shared/cfg/guest-hw.cfg
- shared/cfg/machines.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
Hello guys,
this PR is trying to cleanup the way other architectures are handled in order to be able to run various machine types on different host machines.
Additionally it adds `arm64-pci` machine type which is arm constructed using PCI devices (the old one is renamed to arm64-mmio). I tested it for a while, the only problem I'm having is that when the machine is installed as `arm64-pci` and then ran as `arm64-mmio` (and vice-verse), network won't start. I'll investigate this on Thursday, for now please have a look at the implementation and let me know if you see something obviously wrong.
v0: https://github.com/avocado-framework/avocado-vt/pull/187
v1: https://github.com/avocado-framework/avocado-vt/pull/205
Changes:
v1: "--vt-additional-params" renamed to "--vt-extra-params"
v2: Added …
> shared.cfg.machines: Add pci-based arm64 machine [v2]

- avocado/core/plugins/vt.py
The vt_extra_params might not be defined (eg. in avocado list).
> vt: Fix missing attribute error

- shared/cfg/cdkeys.cfg
Populate cdkey list with KMS/OEM. The keys are publicly accessible. This should
simplify auto-installation.
> Add OEM/KMS cd keys for Windows

- shared/cfg/guest-os/Windows/WinXP/x86_64.cfg
Windows XP image name should be the same as at MSDN.
PYTHONPATH=./avocado avocado-vt/scripts/cd_hash.py
avocado-data/avocado-vt/isos/windows/en_win_xp_pro_x64_vl.iso
Hash values for file en_win_xp_pro_x64_vl.iso
md5    (1m): e812363ff427effc512b7801ee70e513
sha1   (1m): f0d623c9323e9dacde270e466d04047286fb2355
md5  (full): a2fd5aee7719466bcf091c5adb8a65b3
sha1 (full): a70b118316a9a451b966a082e7c1dd0e8018718d
md5 for 1m remains the same.
md5 for full iso is different
> Unified image name for Windows XP 64

- virttest/utils_test/libvirt.py
Fix for the following execption when executing the test
virsh.blockpull.normal_test.network_disk.iscsi.notimeout.shallow
line 2068, in set_vm_disk
'source_name': iscsi_target + "/" + lun_num,
TypeError: cannot concatenate 'str' and 'int' objects
> libvirt.py: int/str concatenation exception fix

- shared/cfg/guest-os/Windows/Win10/i386.cfg
- shared/cfg/guest-os/Windows/Win10/x86_64.cfg
Windows10 ISOs should be at the same path as all another Windows ISOs
> Change location of Windows 10 ISOs

- virttest/data_dir.py
In many virt cases, they create image files under the temp dir for
VM using, and which need executable permission.
BTW, here the 'executable' is True, which can avoid lots of update that calling this function. If anyone think this's inappropriate, leave your comments, thanks.
> virttest/data_dir: Let the temp dir public by default

- test-providers.d/io-github-autotest-libvirt.ini
- test-providers.d/io-github-autotest-qemu.ini
Usually, http port not be blocked by firewall,
And proxy setup steps are easy than git protocol.
> test providers: Change test provider download protocl to http

- shared/unattended/win10-32-autounattend.xml
- shared/unattended/win10-64-autounattend.xml
- shared/unattended/win10-64-autounattend_ovmf.xml
This commit fix win10 unattended_install failed issue. Root cause is that windows network location notification window pop at first login, which blocked post installation script execution.
> unattened.xml: workaround win10 network location issue

- avocado/core/plugins/vt.py
- virttest/asset.py
- virttest/gluster.py
- virttest/iscsi.py
- virttest/libvirt_vm.py
- virttest/libvirt_xml/pool_xml.py
- virttest/lvm.py
- virttest/qemu_monitor.py
- virttest/qemu_virtio_port.py
- virttest/qemu_vm.py
- virttest/remote.py
- virttest/remote_build.py
- virttest/remote_commander/remote_runner.py
- virttest/test_setup.py
- virttest/utils_misc.py
- virttest/utils_net.py
- virttest/utils_test/__init__.py
- virttest/utils_test/qemu.py
- virttest/utils_v2v.py
- virttest/virt_vm.py
Virttest supports storing the environment in env file and reusing it in the latter jobs (eg. keep_guest_running). Avocado-vt want's to support this feature, but only withing one job. But the tests are isolated, so they don't know whether they should or should not cleanup the environment after the testing.
There are several ways of handling this with some pros and cons, some of them are:
* Register each resource in avocado - would be the cleanest solution, but it'd require changing everything in `virttest`. I rejected this because some people still have to use `autotest` to run jobs and they'd have to implement this resource-handling in there (avocado-vt still doesn't support multi-host tests).
* __Register env-cleanup on job-exit - It's the way I used in this PR, because it does not …
> Cleanup the virttest env on job exit

- avocado/core/plugins/vt_bootstrap.py
vt_bootstrap.py has a double entry for vt_tests.
Removing one of them because they are duplicated
inside method run().
Signed-off-by: Julio Faracco <jcfaracco@gmail.com>
> vt_bootstrap.py: removing duplicated args.

- virttest/utils_test/libvirt.py
The 1b86901 added iothread option to create_disk_xml, but not used.
later, the fb6704d introduced iothread option for disk paramters
in set_vm_disk.
In fact, set_vm_disk calls create_disk_xml and pass the iothread
option to it by disk paramters.
The code in create_disk_xml becomes meaningless and redundant,
so remove it.
> utils_test/libvirt: cleanup for iothread option

- virttest/utils_test/libvirt.py
Take full advantage of partition helper function,
such as mk_label, mk_part, mkfs.
> utils_test.libvirt: use helper function to part disk

- virttest/data_dir.py
Adding +r permissions to get_tmp_dir() public=True case.
Otherwise currently the newly created temporary
directory's contents will not be readable by public.
> data_dir.py: public permissions read flags added

- virttest/test_setup.py
48feee4 updated the way used to update kvm module param,
No longer need the kvm_re_probe in sr_iov_cleanup.
> virttest/test_setup: cleanup unused variable

- virttest/env_process.py
socket connect timeout in qemu_monitor is 30s bigger
that wait_for_create_monitor timeout default value(20s),
it will cause create_monitor loop only run once.
> increase vm_create_timeout value

- virttest/libvirt_xml/vm_xml.py
Adding support for https://bugzilla.redhat.com/show_bug.cgi?id=1146886
(libvirt commits f1f68ca33433825ce0deed2d96f1990200bc6618,
f674dc6794e0946f89313f477aa7886a4a28188e)
Abstract from the libvirt commit:
"qemu: Fix access to auto-generated socket paths
We are automatically generating some socket paths for domains, but all
those paths end up in a directory that's the same for multiple domains.
The problem is that multiple domains can each run with different
seclabels (users, selinux contexts, etc.).  The idea here is to create a
per-domain directory labelled in a way that each domain can access its
own unix sockets."
> Fix access to auto-generated socket paths

- shared/cfg/guest-os/Windows.cfg
For windows guests, there is a problem that driver letter will be changed when bootup VM.
Copy those useful tools to 'C:' after OS installation to avoid such driver letter problems.
id: 1273263
> guest-os/Windows.cfg: update all windows tools path.

- virttest/libvirt_vm.py
Hello guys,
while running on F23 I got an error saying, virt-install does not support --os-type list. This PR adds the new "osinfo-query" method to query for supported types and one error message improvement.
I'm not sure, how the `virt-install` output looks like, so I choose the simplest approach by using the full `osinfo-query` output, which looks like:
```
debian7              | Debian Wheezy                                      | 7        | http://debian.org/debian/7              
debian8              | Debian Jessie                                      | 8        | http://debian.org/debian/8              
fedora-unknown       | Fedora                                             | unknown  | http://fedoraproject.org/fedora/unknown 
fedora1              | Fedora Core 1 …
```
> virttest.libvirt_vm: Add support for osinfo-query

- docs/source/extra/DownloadableImages.rst
The new host for the avocado project assets does not allow
for inspecting contents of folders - that is, if you go
to http://assets-avocadoproject.rhcloud.com/static/, you'll
get a 404 error. Update the docs with that limitation (or
feature, depending on how you see it), and pass full urls
to the JeOS images and SHA1SUM files.
Signed-off-by: Lucas Meneghel Rodrigues <lookkas@gmail.com>
> docs: DownloadableImages.rst - Update info on the JeOS download location

- virttest/tests/unattended_install.py
Due to a race condition, when virtual machine was detected as shut down, there may not have been time for the post finish string to be read from serial log.
unattended_install then reported "ERROR" even though installation ended successfully.
The actual fix is in the third commit, the other two just do some refactoring.
> Fix undetected unattended install success 

- virttest/libvirt_vm.py
Use only "short-id" field in the osinfo-query to avoid possible
false-negative matches.
> virttest.libvirt_vm: Filter osinfo-query fields

- virttest/utils_test/libvirt.py
setup_or_cleanup_gluster should always use "pool_name" parameter
for cleanup purpose, otherwise it will cleanup whole tmp dir.
Signed-off-by: Ruifeng Bian <rbian@redhat.com>
> utils_test.libvirt: Fix setup_or_cleanup_gluster parameter problem.

- virttest/qemu_devices/qcontainer.py
That is breaking avocado-vt's CI, let's fix it.
Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>
> virttest.qemu_devices.qcontainer: Remove unused import

- virttest/tests/unattended_install.py
1) 1edc32b introduces string_in_serial_log() and
no longer need 'serial_log_msg', so remove it.
2) remove one of the double 'the'
> unattended_install: trivial fixes

- avocado/core/plugins/vt.py
- virttest/qemu_devices/qcontainer.py
Currently we initialize params, env, then begin the try/finally block
where the test file is found, env_preprocess and the test is executed.
In finally block env_postprocess is executed.
There is a asymetry between env_preprocess and env_postprocess, when
the test file is not found/corrupted and only env_postprocess is
executed. It's not necessarily wrong, but can be confusing.
This patch puts the look-up for test file outside the try/finally block
as it does not modify env or anything cleanup-related. This way on
corrupted test pre- nor post-process is called (similarily to params
parsing error, ...).
> vt: Reorder test initialization

- virttest/tests/unattended_install.py
Some distros (i.e. PowerKVM) may print an error message and wait for
input when installation fails. In this case, there is no need to wait
for timeout.
> Add param install_error_str to immediately shutdown the virtual machine when an installation error message is detected.

- shared/cfg/guest-os/Linux.cfg
- virttest/tests/unattended_install.py
RHEL uses "ks=" to set kickstart file in kernel.
This may not be true for other distros; i.e. Fedora uses "inst.ks="
and PowerKVM uses "kvmp.inst.auto=".
Set "ks" as default kernel_unattended_option for Linux.
> Make unattended file (kickstart) setting in kernel more flexible

- virttest/test_setup.py
This command containing stdout redirection requires shell to be enabled
or the call will be useless.
> virttest.test_setup: Fix system call to use shell

- shared/cfg/guest-hw.cfg
Qemu reported following failure while installing guest with using virtio-blk interface:
> output: 'qemu-kvm: -drive snapshot=off,aio=native,media=cdrom,file=/usr/share/avocado/data/avocado-vt/isos/linux/RHEL6.7-Server-ppc64.iso,index=2,bus=0,unit=0: index cannot be used with bus and unit'
Specified `cd_format` to scsi to fix this issue.
ID: 1244701
> shared.cfg.guest-hw: fix cdrom issue with using virtio-blk interface

- shared/cfg/guest-os/Linux.cfg
- shared/cfg/guest-os/Windows.cfg
instead of devcon.exe find * | find "details driver name"
as the driver name maybe updated, we can get all virtio driver
info when test failed
> Update driver_id_cmd in driver_load case

- avocado_vt/plugins/vt.py
- virt.py
- virttest/ovirt.py
- virttest/qemu_vm.py
- virttest/virt_vm.py
The commit c405ccc changed the name of function that
used to generate a qemu command line.
> Fix no attribute 'make_qemu_command' for 'VM' object

- virttest/qemu_monitor.py
When host on heavy load status, monitor response very slowly,
MonitorProtocolError exception raised because not read ID
from socket, so increase related timeout to avoid this kind
of issue.
> qemu_monitor: increase monitor timeout in qemu_monitor module

- avocado_vt/plugins/vt.py
We have been tryging to call "register_plugin" from the loader module
instead from the loader instance. This wasn't caught before because:
1) The same loader would be registered on `vt_list.py` (on purpose)
2) The dispatcher class on Avocado core (avocado/core/dispatcher.py)
would not propagate exceptions when running `map_method`.
This issue is a fix to the issue #322, together with other changes
on Avocado core (on the loader and dispatcher code).
> avocado_vt/plugins/vt.py: fix VirtTestLoader registration

- avocado_vt/plugins/vt.py
And not as the module. So, the fix on a877173, while valid, now
causes breakage because of the refactor work on 76ff51e.
> avocado_vt/plugins/vt.py: loader is now imported as the instance

- test-providers.d/io-github-autotest-libvirt.ini
- test-providers.d/io-github-autotest-qemu.ini
Previously on f0a1d00, the protocol was changed to from git to http,
because of firewall issues.
Then, came bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1289984
Which showed that git on EL6 fails to retrieve content via http.
So, HTTPS seems to do the trick for everyone.
> test providers: Change test provider download protocol to HTTPS

- avocado_vt/plugins/vt.py
It looks like those functions are leftovers from previous iterations.
Let's clean them up.
> avocado_vt/plugins/vt.py: cleanup usunsed logging functions

- virttest/ssh_key.py
Add setup_remote_ssh_key() and get_remote_public_key() which exist
originally in autotest for bi_directional migration test
> virttest.ssh_key: Add two functions from autotest

- virttest/libvirt_vm.py
- virttest/libvirt_xml/vm_xml.py
Latest package should be used for testing, we need to update packages if it's
installed, such as qemu-guest-agent, selinux-policy.
Signed-off-by: Ruifeng Bian <rbian@redhat.com>
> virttest.libvirt_vm: Perform package update if package was already installed

- Makefile
With the recent change in avocado, the link/unlink targets should also
call "python setup.py develop --user" (--uninstall) to enable/disable
egg links.
NOTE: This should be merged when https://github.com/avocado-framework/avocado/pull/966 is accepted
> Makefile: Add "python setup.py develop --user" to the "link" target

- virttest/utils_conn.py
Add one parameter in conn_setup() with default value to specify the
timeout period when waiting for the prompt on remote server.
> virttest/utils_conn.py: Fix ssh login timeout error on remote server

- virttest/test_setup.py
Remove unused variable and codes.
> virttest/test_setup: cleanup for class PciAssignable

- virttest/utils_misc.py
virttest have evolved into avocado-vt and became
a part of avocado. so,
keep log_last_traceback to remove dependencies on autotest.
Just do the same thing as 24b0ba3,
utils.log_last_traceback => utils_misc.log_last_traceback
> virttest/utils_misc: modify log_last_traceback annotation

- virttest/utils_misc.py
Extract get_guest_service_status from tp-qemu as API function,
which is called by both sr_iov_irqbalance.py and
migration_with_dst_problem.py.
> utils_misc: Add new function to get service status in VM

- selftests/unit/test_iscsi.py
- virttest/iscsi.py
Current iSCSI target standard is the LIO target, so we try to use it in
a high priority. And, check the iscsi-initiator-utils separately and
print the prompt error.
> iscsi: Using targetcli in a high priority

- virttest/utils_v2v.py
In commit bda251d8, it replace all '/tmp' to data_dir.get_tmp_dir(). But
for this case, we need do screenshot on a remote host where does not
have that dir, so change it back to use '/tmp'.
> utils_v2v: Fix the screenshot path on a remote host

- avocado_vt/test.py
This functionality does not apply to VT tests, and with the recent
changes on Avocado (7c967bb) this causes the following test ERROR:
AttributeError: 'VirtTest' object has no attribute 'check_reference_stdout'
> VirtTest: remove all record/check code for stdout/stderr

- avocado_vt/options.py
If no configuration is given, we have to load defaults instead
of failing.
Reference: https://trello.com/c/8ES2KM6Z
Signed-off-by: Amador Pahim <apahim@redhat.com>
> avocado-vt: set configuration defaults

- virttest/test_setup.py
Parameter 'expected_hugepage_size' is not always exist, and the value
also need check when convert it to an integer.
> virttest/test_setup: Catch TypeError when convert expected_hugepage_size

- virttest/qemu_virtio_port.py
The destination for the virtio_console script is in guest, therefor the
AVOCADO_TMPDIR is not created. Let's use /tmp instead.
> virttest.qemu_virtio_port: Use /tmp in guest

- virttest/qemu_vm.py
User can't connection to VM's monitor during test running to do debug if VM status is incorrect.
Add below configure in your tests.cfg to add a debug-only monitor.
monitors += " monn"
debugonly_monn = yes
> qemu_vm: add debug only monitor support

- virttest/test_setup.py
After migrate from autotest to avocado, source code
become to a essential argument in make(). this commit
will fix it.
> test_setup: fix sytanx issue

- shared/cfg/base.cfg
- shared/cfg/machines.cfg
- virttest/qemu_devices/qcontainer.py
On ppc64&ppc64le platform , there is no uhci controller supported. instead of this , pci-ohci is supported. So add the pci-ohci controller to the script. 
Modified some cfg files to let it works better.
> fix usb ehci bug on powerpc, and make the ohci as default controler

- avocado_vt/loader.py
- avocado_vt/test.py
- selftests/unit/test_test.py
This patch uses a new Avocado feature to initialize params directly
by superclass and then moves the self.params to the expected location
(self.avocado_params) and initializes the cartesian-based params instead.
v1: https://github.com/avocado-framework/avocado-vt/pull/353
Changes:
v2: Added avocado_vt.test.Test docstrings to avoid confusion
> test: Rework the params handling [v2]

- virttest/utils_net.py
viobr0 is added by libvirt which not device added by vm,
so remove it.
ID: 1283531
> virttest/utils_net.py: Remove viobr0 in get_linux_ifname

- avocado-plugins-vt.spec
So far the RPM packages have not been strict about the version
of avocado that they require.  The same version has probably
been used because of newer package availability on the repos.
Anyway, let's require the same package versions so that users
may not be surprised with breakage because of different version
and interfaces.
> SPEC file: require avocado package of the same version

- virttest/qemu_qtree.py
Make the get method can get the correct QtreeDisk device
on different platform.
id: 1211151
> virttest/qemu_qtree.py: Update guess_type() for QtreeDev

- virttest/utils_test/qemu.py
1. Some memory related func() in Class MemoryHotplug are general
func(), it's better to move them out instead of write them in
Class MemoryHotplug.
2. Add get_guest_free_mem().
id: 1231037
> virttest/qemu.py: Move some memory related func() from Class MemoryHotplug.

- shared/cfg/guest-os/Windows.cfg
id: 1231015, 1230674, 1231007
Based on: https://github.com/autotest/tp-qemu/pull/439
> Windows.cfg: add Windows cfg for case netkvm_in_use.

- avocado_vt/options.py
the mem set in test_examples doesn't work, 
/usr/bin/avocado run --vt-config ...
always read from vt.conf currently
ID: 1313650
> add vt_config check for mem assign

- shared/unattended/win10-32-autounattend.xml
- shared/unattended/win10-64-autounattend.xml
- shared/unattended/win10-64-autounattend_ovmf.xml
- shared/unattended/win2012-autounattend.xml
- shared/unattended/win2012-autounattend_ovmf.xml
- shared/unattended/win2012r2-autounattend.xml
- shared/unattended/win2012r2-autounattend_ovmf.xml
- shared/unattended/win8-32-autounattend.xml
- shared/unattended/win8-64-autounattend.xml
- shared/unattended/win8-64-autounattend_ovmf.xml
Telnet server is not supported by win10, so remove related
configuration
> shared.unattended: update telnet server installation cmd

- virttest/qemu_vm.py
There is a duplicate entry to check if the parameter 'boot_drive' has the
value 'no'. One is at the beginning and the other is at the end. There is no
function or line of code that changes this value to do another comparasion.
image_params = params.object_params(image_name)
if image_params.get("boot_drive") == "no":
continue
if params.get("index_enable") == "yes":
drive_index = image_params.get("drive_index")
[...]
else:
if image_boot in ['yes', 'on', True]:
if self.last_boot_index > 0:
image_boot = False
self.last_boot_index += 1
if image_params.get("boot_drive") == "no":
continue
Removing the second IF to iterate to the next loop if 'boot_drive' is present.
Signed-off-by: Julio Faracco <jcfaracco@gmail.com>
> qemu_vm.py: removing unnecessary 'boot_drive' param checking.

- shared/cfg/guest-os/Windows.cfg
- virttest/virt_vm.py
Update the method to get windows guest TotalMemory.
ID: 1295311
> virttest/virt_vm.py: Update get_memory_size() for windows guest

- selftests/unit/test_utils_misc.py
- virttest/utils_misc.py
When cpus great then 62, bitmask will be force convert to long integer,
so taskset failed to parse cpu mask.
Signed-off-by: Maosheng Zhang <mazhang@redhat.com>
> Fixed pin cpu failed.

- shared/cfg/base.cfg
Fix typo in comment and add the "usb_type" to avoid problems when
"usb_type" default changes.
> shared.cfg.base: Fix typo and reorder usb defaults

- virttest/nfs.py
- virttest/utils_misc.py
Default timeout 10 seconds is short for NFSClient and SELinuxBoolean to
create SSH connection sometimes. So new implementation will use
'ssh_timeout' to set a timeout if any.
> nfs utils_misc: Fix ssh connection timeout

- virttest/utils_misc.py
For some network FS such as glusterfs, it may use fuse.glusterfs
FS type in /etc/mtab, it should use wildcard matching in the function.
> virttest.utils_misc: Fix the bug of is_mounted function.

- virttest/utils_test/libvirt.py
The output of this command could possible contains an EOL so we have
to strip it before use.
Or the generated XML will be wrong and pool creation will fail.
> utils_test.libvirt: Strip output before use

- virttest/utils_test/libvirt.py
Origin pattern to match authentication name is too short which may cause
incorrect match result. So it is safe to use 'username', not 'name'.
> libvirt.py: Update incorrect search pattern

- virttest/virt_vm.py
get output of serial console not always return data, it caused
syntax issue if return is None. fix it by return driectly if no
data get.
> virttest.virt_vm: fix TypeError in verify_kernel_crash function

- docs/source/BuildingTestApplications.rst
- docs/source/CartesianConfig.rst
- docs/source/GetStartedGuide.rst
- docs/source/GlusterFs.rst
- docs/source/InstallOptionalPackages.rst
- docs/source/InstallWinVirtio.rst
- docs/source/Introduction.rst
- docs/source/ListingGuests.rst
- docs/source/MultiHostMigration.rst
- docs/source/Networking.rst
- docs/source/PerformanceTesting.rst
- docs/source/RegressionTestFarm.rst
- docs/source/RunQemuUnittests.rst
- docs/source/VirtualEnvMultihost.rst
- docs/source/WritingTests/DefiningNewGuests.rst
- docs/source/WritingTests/WritingSimpleTests.rst
- docs/source/conf.py
The default Sphinx highlighting language is python is not explicitly
specified.
When using next-version Sphinx (>=1.4a) to build docs with non-python
snippets without highlighting language specified will cause a warning
message:
```
WARNING: Could not lex literal_block as "python3". Highlighting skipped.
```
This fix change default highlighting language to `none` and explicitly
specify highlighting languages each snippets pygments supported.
This fix also fixed several typos.
> Change default doc highlighting and fix typos

- shared/cfg/base.cfg
- virttest/env_process.py
- virttest/utils_test/__init__.py
Install client tests in local before run autotest client tests in
guest to avoid copy client tests failed.
> virttest.utils_test: make autotest control tests work

- avocado_vt/loader.py
Fixes the below issue:
Searched /usr/share/avocado/data/avocado-vt/images for guest images
Available guests in config:
Avocado crashed unexpectedly: 'module' object has no attribute 'term_support'
> avocado_vt.loader: Fixup: wrong module name used for TERM_SUPPORT

- virttest/qemu_monitor.py
fix human_monitor_cmd call _log_command function with default debug
argument issue.
> qemu_monitor: fix debug arg not work in function  human_monitor_cmd

- virttest/libvirt_xml/devices/panic.py
Add support for the new 'model' attribute in panic device.
More info:
http://libvirt.org/formatdomain.html#elementsPanic
> libvirt_xml: Add model attribute for panic device

- virttest/qemu_vm.py
verify_alive has call verify_kernel_crash, so no need to call
again.
> virttest.qemu_vm: remove duplicate call verify_kernel_crash

- virttest/utils_misc.py
Sometimes there is a need to check if qemu has a certain capability in
order to determine if some features are supported. This new function
implements this.
> utils_misc: new function to check qemu capability

- virttest/utils_misc.py
'XMLTreeFile' is not imported.
> utils_misc: fix import missing

- virttest/defaults.py
Added support for choosing default machine type
based on machine architecture
Addresses https://github.com/avocado-framework/avocado-vt/issues/420
> virttest.defaults: Added support for default machine type based on arch

- avocado_vt/plugins/vt_list.py
The --vt-machine-type option is supported in avocado run command
to filter out certain machine type cases to run.
Add this option into list command to support filter certain machine
type cases.
> vt_list: Add --vt-machine-type option

- virttest/virt_vm.py
> virttest.virt_vm: fix typo in virt_vm.commander

- avocado_vt/options.py
- avocado_vt/plugins/vt.py
1. Added a new option for only filters (--vt-only-filter) this will
be working even with config option enabled.
2. Enabled no filter option even with config option.
Sample Command line:
avocado run --vt-type libvirt --vt-config /usr/share/avocado/data/avocado-vt/backends/libvirt/cfg/cpu.cfg --sysinfo on --vt-only-filters "RHEL.7.2.ppc64le pseries" --vt-no-filters "xen lxc"
Addresses https://github.com/avocado-framework/avocado-vt/issues/423
> vt.plugins: Added only filter option and enabled no filter with config option

- avocado_vt/plugins/vt_list.py
In a recently merged commit vt-only-filter is introduced in options
but no option is added in vt_list module. This will making avocado
failed to list any of virt test cases.
> Also add vt-only-filter to vt_list

- selftests/unit/test_qemu_devices.py
- virttest/qemu_devices/qcontainer.py
We call "qemu ... ?" on several places, which could fail if bash
replaces it with the matching file name. Couple of these were already
fixed by escaping the '?', this patch adds the remaining ones.
PS: I'm wondering why are we not using "help" instead of '?'. Is it not supported by some qemu versions?
> Escape the '?' when calling it via "process"

- avocado_vt/test.py
timeout = test_status.early_status.get('timeout')
timeout = float(timeout or self.DEFAULT_TIMEOUT)
DEFAULT_TIMEOUT is always used currently, need to make timeout configuable.
> Add test_timeout params

- virttest/remote_commander/messenger.py
- virttest/remote_commander/remote_interface.py
- virttest/remote_commander/remote_master.py
- virttest/remote_commander/remote_runner.py
Example follows.
VM side::
#!/usr/bin/env python
import logging
import time
import sys
def run(helper):
for i in range(50000):
t = time.time()
reply = helper.query_master(i, t)
logging.info("Reply %s: %s", i, str(reply))
Master side::
#!/usr/bin/env python
import os
import copy
import time
import logging
"""Test example for avocado-vt for using remote_commander with run_test()
method. The purpose of this technique is to provide remote test running on VM
with callback. Test can be run remotelly on VM, and decision about success is
made in one place. run_test() accpepts Python script that has run(helper)
method. Remote test can call helper.query_master() with any picable arguments.
More info at: https://github.com/autotest/virt-test/pull/1449
"""
class EchoResponder(object):
"""Call-able …
> Add run_test to remote_commander.

- avocado_vt/loader.py
When the url contains ':' (eg. "passtest.py:foobar") the
cartesian_config raises the main ParserError, not the LexerError so we
should handle that correctly.
> loader: Catch ParserError instead of LexerError

- virttest/qemu_monitor.py
- virttest/qemu_vm.py
If VM memory big than 16G, original connect timeout 30s
is not enough. 60s timeout test pass with 32G VM,
so increase default timeout to 60s to avoid
MonitorConnectTimeout exception.
And original default timeout of wait_for_create_monitor
less than default socket connect timeout, it cause wait for
try to create connection only once, so increase default
create monitor timeout too.
> virttest.qemu_monitor: increase socket connect timeout

- virttest/virt_vm.py
If serial console is not ready, get output of serial console will cause TypeError issue. Fix it by return driectly if no data get.
> virt_vm: fix TypeError in verify_illegal_instruction function

- virttest/virt_vm.py
Pass the timeout from wait_for_login to sub function, which will reduce the time to execute the test.
> virt_vm: Set timeout for update_mac_ip_address

- virttest/qemu_monitor.py
Reconciliation __getinitargs__() with __init__().
https://docs.python.org/2/library/pickle.html#object.__getinitargs__
.... should return a tuple containing the arguments to be passed to the
class constructor (init() for example).
> Fix __getinitargs__() in qemu_monitor.py

- virttest/utils_test/libvirt.py
MigrationTest.do_migration function always raises an exception when
migration fails. But sometimes it is not needed. The fix is to provide a
way to avoid of raising an exception and just set the boolean result.
> utils_test.libvirt: add a parameter ignore_status

- virttest/utils_net.py
Update mac address, using ":" as the separator instead of ".".
> utils_net: Update mac address with correct format

- virttest/utils_test/__init__.py
generate default mini-configuration for autotest
client tests in guest OS to avoid setting error.
> virttest.utils_test: fix setting error in run_autotest

- MAINTAINERS
There used to be MAINTAINERS file in virttest, but it was not transfered.
This commit uses active volunteers with commit rights from the community.
I'd like to ask the majority of these people for confirmation (hopefully I used the right GH name).
Most active from the last year: @lmr @xutian @ldoktor @clebergnu @will-Do
Ex virttest maintainers: @lmr @clebergnu @jzupka @ldoktor @ypu @FengYang @cevich @yumingfei @yangdongsheng @leonstack @chuanchang
v1: https://github.com/avocado-framework/avocado-vt/pull/461
Changes:
v2: removed Guannan Wayne Sun <gsun@redhat.com>
v2: added Xu Tian <xutian@redhat.com>
> Create MAINTAINERS [v2]

- virttest/storage.py
We'd better to check the existence of src-file first, and then,
output the appropriate log.
Otherwise, the following is likely to mislead user.
Copying ../jeos-21-64.qcow2.backup -> ../jeos-21-64.qcow2.backup
No source file ../jeos-21-64.qcow2.backup, skipping
> virttest.storage: Correct the log out of backup_image_file

- avocado_vt/plugins/vt_list.py
- avocado_vt/test.py
If AUTOTEST_PATH has been declared and setup_modules.py is missing,
avocado will throw IOError for both vt_list and vt,
and without any useful details to user.
So, It's better to check if it exists.
> Check the existence of setup_modules.py before loading it

- virttest/utils_test/libvirt.py
Change the migration function to also return command
output messages which may be useful for the caller to parse.
> utils_test.libvirt: support return output messages

- shared/cfg/guest-os/Linux/RHEL/7.0/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.devel/ppc64.cfg
Somehow Fedora urls were copied over to RHEL definition. Let's remove
them to avoid confusion.
> shared.cfg.guest-os: Remove incorrect urls from RHEL definition

- virttest/qemu_vm.py
The function make_create_command() has a function called add_name() who
expect an argument "devices". But this argument is never used. So, there
is no reason to keep this argument.
Signed-off-by: Julio Faracco <jcfaracco@gmail.com>
> qemu_vm: removing unecessary arguments inside add_name.

- avocado-plugins-vt.spec
It was observed that, on EL6 only, python-simplejson is not added as
an indirect dependency of its own dependencies.  Let's add an explicit
requirement.
> avocado-plugins-vt.spec: add explicit python-simplejson dep on EL6

- virttest/qemu_monitor.py
For qmp monitor, the unit of set_downtim  must be in seconds,
like as: 1 is 1s, 0.1 is 100ms.
> virttest/qemu_monitor.py: Small fix in migrate_set_downtime() for qmp

- virttest/utils_libvirtd.py
Current logging_handler don't support passing any parameters. This
would limit the function of handler to send out any informations.
Adding a method to pass arguments to handler will make this possible.
> utils_libvirtd: Add one more kwarg to pass arguments

- .travis.yml
- avocado_vt/loader.py
- avocado_vt/test.py
Avocado-vt requires a special test-name handling. Currently it does that
inside the `loader` and then it drops it only to evaluate it again. This
patch moves the `VirtTest.__init__` name handling into the `loader` and
replaces the non-used handling there.
This should not have any impact on the test name whatsoever as the
original name was not used at all and the loader now creates the name
according to the originally used `VirtTest.__init__` handling, with the
only difference that the test is set earlier in the process.
> avocado_vt: Move the special name handling to loader

- scripts/scan_results.py
Sometimes, user need to get test status info druing test, this script implement it via  dump test journal info from test_journay database. 
limitation of this script is that user need to start avocado with '--journay' option. And it doesn't report pending tests number and name because this info leak in DB.
> script: add script to dump test journal info script

- virttest/utils_misc.py
- virttest/utils_test/libvirt.py
The command cause 'Leaked clusters were noticed during image check'
error in the test.
> utils_test.libvirt: workaround to delete external disk snapshot.

- avocado-plugins-vt.spec
While Avocado-VT needs additional packages, which are checked
bootstrap, the bootstrap process itself needs git.  It even crashes
without it:
17:37:30 INFO | 3 - Updating all test providers
Avocado crashed unexpectedly: Command 'git' could not be found
in any of the PATH dirs: ['/bin', '/sbin', '/usr/bin',
'/usr/local/sbin', '/usr/libexec', '/root/bin', '/usr/sbin',
'/usr/local/bin']
Let's add it as a package requirement.
> avocado-plugins-vt.spec: add git to requirements

- virttest/bootstrap.py
This debug line was really intended for debugging during development,
it is not useful enough to users.  If there are conflicts to he
handled, then those files names are going to be printed.
> virttest/bootstrap.py: remove debug print of download files

- docs/source/GetStartedGuide.rst
The "make link" is a convenient target to link and deploy all avocado
projects, let's mention it in GetStartedGuide.
The "make link" documentation is added in https://github.com/avocado-framework/avocado/pull/1171
trello: https://trello.com/c/LdXWhQ2Z/641-add-documentation-of-make-link-target
> docs: Mention "make link" in GetStartedGuide

- virttest/qemu_qtree.py
Sometimes, we need to get device properties from qtree, but a property
could be put either in device node or its sub-nodes. So add the
'traverse' function to iterate those nodes.
> qemu_qtree: add function 'traverse'

- scripts/scan_results.py
The timestamp information causes the output exceed the screen line,
and looks a bit messy.
In most cases, we only care about whether it passed or not.
'-s' will leave 'status' and 'result' only.
> scripts.scan_results: introduce '-s' to disable timestamp output

- virttest/staging/lv_utils.py
- virttest/utils_test/libvirt.py
In some cases, the new created VG/PV may not clean up completely, which
may lead to a failure when create VG next time:
Incorrect metadata area header checksum on /dev/sdd at offset 4096
Failed to write VG vg_test_0.
In fact, these  commit 2aadb5b tried to fix this problem in an inappropriate
place, and it was removed by commit 03d92e5b without a new fix.
> Update lvm cache timely

- virttest/utils_net.py
avocado.utils.path.find_command raises CmdNotFoundError,
not ValueError.
> utils_net: Use CmdNotFoundError instead of ValueError

- virttest/qemu_devices/qcontainer.py
> qemu_devices.qcontainer: fix cdrom cache miss when aio is native

- avocado_vt/test.py
The `Test.get_state()` method reports basic Test's properties including
"params". The problem is that avocado-vt's VirtTest replaces the
`VirtTest.params` for avocado-vt params. This patch modifies the
`get_state` method to report the correct params instead.
> avocado_vt: Report avocado params in get_state

- setup.py
C source file not be include in virttest packages which caused test failed. (eg, passfd.c not found caused nic_hotplug..migration test failed which exception compile error gcc exit with status 4'')
> fix c source code file not found issue

- virttest/utils_misc.py
I'm not sure if this is all that's needed, but fixes the following:
2016-05-12 20:02:08,330 stacktrace L0036 ERROR|
2016-05-12 20:02:08,330 stacktrace L0039 ERROR| Reproduced traceback from: /avocado/avocado-vt/avocado_vt/test.py:393
2016-05-12 20:02:08,332 stacktrace L0042 ERROR| Traceback (most recent call last):
2016-05-12 20:02:08,333 stacktrace L0042 ERROR| File "/avocado/avocado-vt/avocado_vt/test.py", line 169, in runTest
2016-05-12 20:02:08,333 stacktrace L0042 ERROR| self._runTest()
2016-05-12 20:02:08,333 stacktrace L0042 ERROR| File "/avocado/avocado-vt/avocado_vt/test.py", line 301, in _runTest
2016-05-12 20:02:08,333 stacktrace L0042 ERROR| params = env_process.preprocess(self, params, env)
2016-05-12 20:02:08,333 stacktrace L0042 ERROR| File …
> Adding s390x arch support

- selftests/unit/test_iscsi.py
- virttest/iscsi.py
Systmed has a frequency limit to restart serivce in a short time,
and a workaround is using 'systemctl reset-failed service' before
restart the service.
> iscsi: Control service by using exist module

- avocado_vt/loader.py
- docs/source/CartesianConfig.rst
- docs/source/WritingTests/WritingSimpleTests.rst
Currently the `subtests.cfg` and `guest-os.cfg` files are always re-
created on `vt-bootstrap` and during each invocation of `avocado-vt`
loader (during `avocado list` and `avocado run`), which is not optimal
and wrong for several reasons.
1. `avocado run` should not modify any configs, it should only run test
2. parallel execution of `avocado run`/`avocado list` causes issues
3. even documentation refers to update on `vt-bootstrap` on some places
This behavior is convenient for test developers, but it does not belongs
to production environment. So this patch improves the documentation and
removes the `subtests.cfg`/`guest-os.cfg` recreation from the loader.
Every since this commit test developers need to run `avocado vt-
bootstrap` to propagate the changes to subtests/guest-os!
v1: …
> avocado_vt: Avoid re-creating subtests/guest-os on run [v3]

- virttest/utils_test/libvirt.py
1. Replace 'localhost' by '127.0.0.1' 
When ipv6 enabled on the host, iscsiadm discovery target will fail
with localhost portal, so set the IP address explicitly to avoid this
problem.
2. Set ip address when create iscsi target
We need set the ip address explicitly to enable IPv6 when create iscsi target.
> utils_test.libvirt: two iscsi related bugs fix

- virttest/libvirt_xml/vm_xml.py
VM's name is better than the object address of VMXMLBase.
> libvirt_xml.vm_xml: Use self.vm_name instead of self

- virttest/utils_net.py
Set option 'shell=True' to resolve the pipe notation.
```
INFO | Running 'ip route | awk '/default/ { print $3 }''
DEBUG| [stderr] Command "|" is unknown, try "ip route help".
```
ID: 1337020
> virttest.utils_net: fix CmdError for get_host_default_gateway

- virttest/storage.py
Pass 'shell=True' to function get_image_filename_filesytem for resolving filename wildcards.
The issue:
```
17:43:08 INFO | Running 'ls -1d /dev/sd*'
17:43:08 DEBUG| [stderr] ls: cannot access /dev/sd*: No such file or directory
17:43:08 ERROR| Command 'ls -1d /dev/sd*' failed (rc=2)
```
ID: 1334978
> virttest.storage: pass 'shell=True' to function get_image_filename_filesytem for resolving filename wildcards

- virttest/utils_misc.py
> virttest.utils_misc.py: typo fix of module name.

- virttest/utils_misc.py
If we only setup SELinux boolean on one side, we should not clean up the
other side when done. So fix it.
> utils_misc: Fix the cleanup for one side setup

- virttest/utils_test/libvirt.py
1. 'export_dir' should be passed through for nfs setup
2. Add one parameter of the disk image path converted to for the caller
to use.
> utils_test.libvirt: Some parameters fix

- virttest/qemu_devices/qcontainer.py
so fallback aio to 'threads' if snapshot is on and
aio is not 'threads'.
Signed-off-by: XuTian <xutian@redhat.com>
> qemu_devices.qcontainer: aio=native requried cache.direct=on

- virttest/utils_test/libvirt.py
Enable to set the disk cache for the newly created disk for the guest.
> utils_test.libvirt: set disk cache

- virttest/asset.py
- virttest/bootstrap.py
The test providers are defined in ini files stored in user's datadir.
For convenience these were synced from the avocado base dir on every
`virttest.asset` import, which is unexpected as only bootstrap should
update data dir. This patch moves this update to the bootstrap instead.
Note that the ini files are synced even when the providers are not
downloaded (as before).
This extends the cleanup started in https://github.com/avocado-framework/avocado-vt/pull/514
@Andrei-Stepanov, I remember that spice uses extended providers utilities, can you please double check this wont break your workflow? Basically it's the same story as the https://github.com/avocado-framework/avocado-vt/pull/514 usually nothing changes, only when test developer changes these files locally he needs to re-run the …
> virttest.asset: Avoid providers update on asset import

- virttest/qemu_vm.py
- virttest/test_setup.py
- virttest/utils_misc.py
- virttest/utils_net.py
commit a3657b85533cd5886594ece953622c7f02ca5c04
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Fri May 27 11:06:00 2016 +0800
Fix CmdError caused by omitting shell=True
commit 00fa76bbeae2643dfbe5286fa2a88ea1397c1e04
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Fri May 27 10:36:40 2016 +0800
virttest.qemu_vm: fix output of system_ouput()
If 'shell=True' is ommitted,
The output of process.system_ouput() will be None.
> Two issue about param shell

- Makefile
- avocado_vt/plugins/vt_joblock.py
- docs/source/ParallelJobs.rst
- docs/source/index.rst
- etc/avocado/conf.d/vt_joblock.conf
- setup.py
This introduces a Pre/Post Job type of plugin, that attempts to create
a lock file in a common location before the job is started, and remove
the lock file after the job has finished.  The goal is to prevent
multiple runs of avocado (with VT tests) to corrupt files such as
guest OS images.
It's still possible to have multiple parallel jobs running on the same
machine, as long as their configuration point to different lock
directories, which should follow different data directories, to
prevent the original problem of data file corruption.
The mechanism used for locking is a simplistic one, similar to daemon
PID files.  It should be possible to either rewrite or improve the
lock mechanism completely without bringing changes to the user
expected behavior of, by default, not having multiple …
> Job lock: plugin that prevents multiple runs of VT jobs [v4]

- virttest/qemu_vm.py
The function make_create_command() has many functions inside with unused
"devices" parameter. This parameter is not being used inside many of
them.
So, this commit clean up the functions.
Referecing the commit number: c3ae587.
This commit introduces an 'else' conditional inside add_sga() to keep the
pattern of other functions.
Signed-off-by: Julio Faracco <jcfaracco@gmail.com>
> qemu_vm: removing unecessary arguments inside add_{floopy,uuid,vnc...} [v2].

- virttest/libvirt_vm.py
- virttest/qemu_vm.py
Use 'skip_hash_xx' together with 'md5sum_xx' and 'sha1sum_xx',
and it's value must be 'yes' or 'no', default is 'no'.
> define the value of 'skip_hash'

- virttest/utils_test/__init__.py
The parameter timeout is defined as function argument.
Here, it alway change timeout to 600s, and will cause some
jobs ended prematurely in error:
INFO | Running autotest control file ctcs.control on guest, timeout 600s
...
ERROR| ERROR ... TestError: Timeout elapsed while waiting for job to complete
Signed-off-by: Haishuang Yan <yanhaishuang@cmss.chinamobile.com>
> virttest.autotest: Fix timeout when running autotest

- virttest/qemu_monitor.py
- virttest/qemu_vm.py
commit 85d37a3257bbf8a03cb5c3fc9d45f4492895f5fe
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Tue May 31 10:53:27 2016 +0800
virttest/qemu_monitor: Improve the output of creating monitor
1) Output the accurate qemu version that doesn't support QMP.
2) Output the type of monitor, new former '<type> <monitor_name>'.
It's useful to distinguish the kind of monitor for user.
for example,
<virttest.qemu_monitor.HumanMonitor> hmp
or <virttest.qemu_monitor.QMPMonitor> qmp
3) Fix typo, s/iff/if
commit 061b0f13448f213b8599483f9e956516c8e7ebe9
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Tue May 31 10:51:07 2016 +0800
virttest.qemu_vm: Add member 'qemu_version' for class VM
Signed-off-by: Wei Jiangang …
> Improve the output of creating monitor

- shared/cfg/guest-hw.cfg
negative test steps include in qemu_io_blkdebug test, and check image after negative operation is not make sense, so skip the step.
Signed-off-by: Ping Li pingl@redhat.com
> guest-hw: skip image check step in qemu_io_blkdebug test

- virttest/virsh.py
In function cmd_status of  aexpect/client.py, a new parameter 'safe' is
added. The function invokes function cmd_status_output in
virttest/virsh.sh which does not accept the newly added parameter, so it
causes TypeError: cmd_status_output() takes at most 5 arguments (6
given). The fix is to add this parameter to function cmd_status_output
with default value certainly.
> virttest.virsh: Fix syntax error

- virttest/bootstrap.py
The `config_filter` was set on import using `_get_config_filter`
function. The problem is, when the directory does not exists yet, then
this filter is incorrect and files like `test-shared.cfg` are included
in the generated `subtests.cfg` (because they are not filtered-out using
the `config_filter`).
This patch removes the cached `config_filter` and renames the
`_get_config_filter` function to `get_config_filter`, which is then used
in functions to get the filter at the time of the function invocation,
which should give the correct results.
This patch fixes the issue where `avocado vt-bootstrap --vt-type spice
--vt-no-downloads --vt-update-config` on empty `~avocado/data` generates
incorrect `subtests.cfg`.
> virttest.bootstrap: Avoid config_filter caching on import

- virttest/qemu_monitor.py
- virttest/qemu_vm.py
disconnect session object used caused server-runing-lock
file not found error.
> virttest.qemu_vm: fix use disconnect session in reboot

- virttest/qemu_devices/qcontainer.py
Since qemu commit d657c0c, aio=native will error out without
cache.direct=on or cache=none.
Signed-off-by: Lin Ma <lma@suse.com>
> qemu_devices.qcontainer: set cache=none while aio=native

- avocado_vt/plugins/vt.py
- avocado_vt/plugins/vt_bootstrap.py
- avocado_vt/plugins/vt_list.py
This adjusts, while keeping compatibility, with the proposed change
for a better module name and location for the plugin interface
definitions.
This is related to https://github.com/avocado-framework/avocado/pull/1235
> RFC: Plugin interfaces: adjustments for changes in Avocado

- virttest/utils_test/libvirt.py
Add an extra option used after virsh, like 'virsh -c xxx migrate xxx'.
> utils_test.libvirt: Add extra option for virsh

- virttest/libvirt_vm.py
While creating a new VM using virt-install, libvirt_vm provides only
the total number of cpus. It does not provide the cpu topology
information to virt-install. Fix this by allowing an option to provide
the cpu-topology.
Signed-off-by: Gautham R. Shenoy <ego@linux.vnet.ibm.com>
> libvirt_vm : Add socket, core, thread info to the virt-install commandline

- virttest/qemu_qtree.py
qemu commit a5f5429 introduced named GPIOs. Some qemu devices(say hpet)
present multiple gpio-in(s) or gpio-out(s) with different string keys
in qtree information. In this case, It causes device_option_check test
failure because it doesn't recognize the string keys, Example:
......
(monitor hmp1) Response to 'info qtree'
(monitor hmp1)    bus: main-system-bus
(monitor hmp1)      type System
(monitor hmp1)      dev: hpet, id ""
(monitor hmp1)        gpio-in "" 2
(monitor hmp1)        gpio-out "" 1
(monitor hmp1)        gpio-out "sysbus-irq" 32
......
ValueError: Property gpio-out = "" 1, not rewriting with "sysbus-irq" 32
......
This patch adds the named GPIOs support to fix this issue.
Signed-off-by: Lin Ma <lma@suse.com>
> virttest: Add named GPIOs support

- virttest/libvirt_vm.py
- virttest/virsh.py
process.CmdError has a result attribute, not result_obj.
> virttest: Use result instead of result_obj

- virttest/utils_test/qemu.py
Hotpluged memory is offline state by default, this commit online
unusable memory(offline state memory) via kernel sys filesystem
if the memory is not online by systemd.
> utils_test.qemu: online hotpluged memory before check memory

- avocado_vt/plugins/vt_joblock.py
This attempts to implement the good points raised on issue #567.
It changes the behavior of how locks are acquired, by first creating the process own lock, and then checking if other exist.  If other lock files exist, check if they're stale.  If they're stale, remove them. If they're not stale, that is, the process is alive, bail out.
--
Changes from v1 (#578):
* Added the stack trace output when lock is failed to be acquired
* Adapted to the the change of plugin interface location
> Job lock create then check v2

- virttest/qemu_vm.py
Currently qemu fails when missing rom even though it's not being used.
At the same time arm guys decided they really don't want to ship the
unused binaries which together makes qemu fail, unless the rom is
disabled by by using rombar=0.
This is the same approach libvirt is going to use according to:
https://bugzilla.redhat.com/show_bug.cgi?id=1337510
> virttest: Add ",rombar=0" to virtio nic on aarch64

- virttest/utils_test/qemu.py
33aeebc introduces check_driver_verifier() to
check driver verifier status, which needs 'driver'.
But no param passed in it's caller clear_win_driver_verifier.
> virttest.utils_test.qemu: Fix missed param 'driver'

- requirements.txt
An extra argument "safe" was added to aexpect.ShellSession.cmd_output(),
which is used in virttest/virsh.py. It will break in earlier aexpect versions.
> Update aexpect version requirement

- shared/cfg/guest-os/Linux/Fedora/23.s390x.cfg
- shared/unattended/Fedora-23.ks
- virttest/qemu_devices/qcontainer.py
This PR adds Fedora.23.s390x profile along with necessary fixes to be able to run `unattended_install` test.
@liwbj as you are the `s390x` author, would you please also take a look at this?
PS: I tested this a week ago on s390 machine and it worked well. Now I rebased and polished it a bit so I need to re-run the functional test, still waiting for a free machine. Anyway the changes were minimal and I verified it produces the correct cmdline on `x86` machine using `avocado run unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads --vt-arch s390x --vt-machine-type s390-virtio --vt-guest-os Fedora.23 --show-job-log --vt-qemu-bin /usr/local/bin/qemu-system-s390x --vt-extra-params enable_kvm=no`. I'll let you know when the real test on s390 machine finishes (as emulation of s390 …
> virttest: Add support for virtio-scsi-ccw and add F23.s390x definition

- avocado_vt/test.py
The first patch adds the avocado feature to finish with WARN when `self.log.warn` is used and the test did not fail.
The second commit changes the way `env.save` failures are treated. Previously they simply crash the test without any sophisticated cleanup. This version only logs the warning and when the last `env.save` fails it additionally cleans the `env` to avoid left-over machines.
Trello: https://trello.com/c/l0R4FqY1/721-avocado-vt-avoid-env-pickle-when-keep-guest-running-is-disabled
> avocado_vt: Treat env.save exception as warning

- avocado_vt/plugins/vt_joblock.py
The locks are usually created in TMP directory, which often does not
allow removing other users files, which makes the vt_joblock fail even
on non-existing pids. This patch only logs a warning in such case and
proceeds.
Note the process still fails when it's unable to read the file or when
the file does not contain pid.
v1: https://github.com/avocado-framework/avocado-vt/pull/592
v2: https://github.com/avocado-framework/avocado-vt/pull/595
Changes:
```yaml
v2: Stalled -> stale
v2: Use arguments to format string in log
v3: Improved commit message
```
> avocado_vt: Make vt_joblock more lenient [v3]

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
Hello guys, especially @xutian, I'm sorry but although the https://github.com/avocado-framework/avocado-vt/pull/594 fixed the `aarch64-pci` machine it broke the `aarch64-mmio`, because the `rombar` property is not available on `virtio-net-device`. Instead of hardcoding this patch checks whether `rombar` is supported and sets it only when available.
While working on this I noticed the `execute_qemu` is broken on arm as it requires `-machine` to be specified even to query for `-device ...,?`. I incorporated the patches here as well.
@xutian would you please take a look at this as this time I broke my other setup by that PR? This one seems to be working fine on both (I'm sorry for not checking this previously)
> virttest: Fix the execute_qemu and "rombar" property setting

- virttest/utils_misc.py
1. As the value of 'scale' here is always positive，so the if...else
block is unnecessary.
2. Using 'str' to format a long float number may output a scientific
notaion number, which is not acceptable here. So control the precision
by ourself when format it.
> utils_misc: Bug fix for data size convert

- virttest/iscsi.py
- virttest/utils_test/libvirt.py
1.
utils_test.libvirt: Try to get volume repeatedly
For iscsi type pool, after it start, the volume may not appear
immediately, and the volume path(cooresponding to a scsi disk) also
need verify.
2
iscsi: Get the right attached disk name
For now, the regex pattern may match to another target disk if the
corresponding target disk not attached yet.
> Two iscsi related bugs fix

- virttest/utils_v2v.py
Since all windows guests are activated, remove code of comparing
screenshots and other operations on booting windows guests except
for win2003 guests.
> utils_v2v: remove operations of booting windows guests

- virttest/ovirt.py
for single network/bridge, nothing changes
for multiple network/bridge, return the MAC address of the first interface to get ip address
> ovirt: make get_mac_address adapt to multiple network interfaces

- shared/cfg/guest-os/Windows.cfg
id: 1231103
Based on: https://github.com/autotest/tp-qemu/pull/617
> Windows.cfg: Add windows related cfg for case "win_virtio_driver_update_test..with_netkvm".

- virttest/utils_test/libvirt.py
If the given pool target is not a valid path, create it in the tmp dir.
> Create target for dir type pool

- virttest/env_process.py
These occurrences of `process.run()` and `commands.getoutput()` are
only insterested in the command output, so Avocado's
`process.system_output()`, which is used on many more places, is more
adequate.
> virttest/env_process.py: use the more adequate system_output function

- virttest/utils_env.py
IMHO, 'timeout' should be greater than 'first' and 'step' for
utils_misc.wait_for().
> virttest/utils_env: update the check for tcpdump status

- virttest/env_process.py
Recently a "qemu -help" command was added to detect the version. There
is no need to have this verbose as the version is logged on the next
line.
> virttest.env_process: Silence the "qemu -help" output

- virttest/qemu_vm.py
The s390x branch should be part of the big if/elif/elif condition, it
should not start a new block.
> virttest.qemu_vm: Fix add_nic model conditions

- virttest/utils_misc.py
In style fix this variable was left unchanged causing crashes as the
variable does not exist (it's a builtin type)
> virttest.utils_misc: Fix incorrect variable name

- shared/cfg/base.cfg
Modify minor error in base.cfg,which is variant of serial commented out to serials
Signed-off-by: MiramDeng mdeng@redhat.com
> Typo fix serial commented out to serials in base.cfg

- avocado_vt/test.py
According to the notes left on the test class:
https://github.com/avocado-framework/avocado/blob/38.0/avocado/core/test.py#L144
https://github.com/avocado-framework/avocado/blob/38.0/avocado/core/test.py#L194
String based named and the tag parameter should have been removed on release 37.0.
This has been tested with the following combination of versions:
* Avocado 36lts (ab66fba) + Avocado-VT "test_name_remove_deprecated" (b82c0ac) = OK
* Avocado master (c0ebd3f) + Avocado-VT "test_name_remove_deprecated" (b82c0ac) = OK
* Avocado "test_name_remove_deprecated" (6baeeed) + Avocado-VT "test_name_remove_deprecated" (b82c0ac) = OK
The combination of Avocado "test_name_remove_deprecated" branch
(6baeeed) + Avocado-VT master branch (1af13fd) does *not* work, as
Avocado-VT users …
> Remove use of test tags

- virttest/iscsi.py
- virttest/libvirt_storage.py
Libvirt don't discovery iscsi target automatically currently, it
lead to fail to create iscsi pool. Add discovery step in target
export function.
> iscsi: Add discovery for iscsi target export function.

- virttest/utils_misc.py
Correct the regex pattern for match the decimal part.
> utils_misc: fix decimals conversion between differen units

- scripts/package_jeos.py
Older versions of QEMU are be able to use Qcow2 images created by
newer versions.  That was the case with the first version of the
JeOS.23 image, which has now been updated with with an image that was
created with "0.10" compatibility level.
Let's make that the norm for newly created JeOS images, by means of
this utility script.
Reference: https://trello.com/c/1RlcP6Ji
> scripts/package_jeos.py: add compatibility flags to qemu-img

- virttest/cartesian_config.py
postfix string '_fixed', '_max' and '_min' doesn't work, because
'postfix_parse' not call in get_dict function. this commit enable
it, because tp-qemu tests need these params.
> virttest.cartesian_config: enable postfix_parse

- virttest/nfs.py
This is to enable the ability to set the ssh connection automatic
recovery.
> virttest.nfs: set ssh automatic recover

- virttest/qemu_vm.py
If the vm contains virtconsole, session is established automatically,
but it's not cleaned, which makes the test hang for infinity as there is
still a background process. This patch uses the existing
`VM.cleanup_serial_console` function, which should clean both, serial
and virt consoles.
> virttest.qemu_vm: Cleanup virtio_console in VM.destroy

- shared/cfg/guest-hw.cfg
- shared/cfg/machines.cfg
- virttest/libvirt_vm.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
The `arm64` works quite well with `qemu` provider, but it fails terribly on `libvirt` provider. This is a initial patchset to make arm64 supported by both. Note that `arm64-pci` definition is not yet supported at least on RHEL's libvirt.
Please see the details in each commit. Also note that this only prepares the ground to start using `--vt-provider libvirt` along with `--vt-machine-type arm64-mmio`, more work is needed to declare it stable.
> virttest: Initial work to support arm64 with libvirt provider

- virttest/test_setup.py
The original used build.make function could not run command on a subshell, so change to use function process.system with parameter 'shell=True' instead.
ID: 1359005
> vittest.test_setup: Change to use function process.system to install egd.pl

- virttest/libvirt_xml/vm_xml.py
Traceback observed if graphics device is not defined in guest xml, this
patch handles it.
> Fixup vm_xml.py

- virttest/cartesian_config.py
This reverts commit 81c6ce860b2f625ec31533779c479cf9bf14af38.
I cannot parse cartesian config for SpiceQE with the above commit. The
error is:
File "/mnt/tests/spice/qe-tests/avocado-vt/virttest/cartesian_config.py", line 2145, in get_dicts_plain
for d in self.get_dicts(n, ctx, new_content, shortname, dep):
File "/mnt/tests/spice/qe-tests/avocado-vt/virttest/cartesian_config.py", line 1942, in get_dicts
postfix_parse(d)
File "/mnt/tests/spice/qe-tests/avocado-vt/virttest/cartesian_config.py", line 2244, in postfix_parse
if key.endswith("_max"):
AttributeError: 'tuple' object has no attribute 'endswith'
> Revert "virttest.cartesian_config: enable postfix_parse"

- virttest/utils_test/libvirt.py
func(func_params) couldn't handle more than 1 commands like
process.run(cmd1 && cmd2), as shell=True couldn't be passed.
This patch fixes it.
> Fixup libvirt.py

- shared/cfg/guest-os/Windows.cfg
devcon.exe is copied to C:  in xcopy option, so C:devcon.exe is available,
but  C:\devcon.exe is used when run devcon.exe cmd, so always show not available cmd
update C: to C:\ in xcopy
> Update devcon path

- virttest/asset.py
Previously location for .INI asset files had strictly predefined
location: avocado-vt/shared/downloads/asset_name.ini.
This commit allows to specify path to .INI file. This would allow to
test-providers use their own .INI asset files, as well as, it is
possible to use multi-section .INI files. For example, SpiceQE team
need to have asset file for SeleniumHQ stand-alone-server. This asset
is useful only for SpiceQE team. It doesn't have any usage for other
QE teams. Moreover, SpiceQE would have a way to define the version and
location of Selenium stand-alone-server necessary for SpiceQE tests.
Example usage
-------------
Selenium asset ini file located at "$provider_download_dir/assets/selenium.ini":
[Selenium]
title = SeleniumHQ
url = …
> Allow to use asset .INI files at any directory.

- virttest/utils_v2v.py
To avoid problem that occationally timeout when getting return data
from 'driverquery' command
> utils_v2v: retry 5 times to get driver info for windows guest

- virttest/qemu_vm.py
Currently virtio1.0 behaviour on latest RHEL.7.2/RHEL.7.3 hosts is default, we don't need to specify the disable-legacy and disable-modern options explicitly.
ID: 1366941
> virttest.qemu_vm: Change to not set the disable-legacy and disable-modern options

- virttest/test_setup.py
Currently once we use available free VFs [got via _get_vf_pci_id] for any operation.. "occupied" flag for that VF would get set to "True". But when we release that vf device [via _release_dev] we are not resetting the "occupied" flag for the VF. Newly committed code in this PR will fix this issue.
> Fix SR-IOV VF release dev

- virttest/nfs.py
The mount "-o" option is not needed when there is no argument for it.
"-o" option returns an error if there is no argument used after it.
> fix for mount issue in the nfs.py #685

- virttest/libvirt_xml/vm_xml.py
Added function which returns the cpu topology as dict
for example:
cputopology content in vm xml:
` <topology sockets='1' cores='4' threads='8'/>`
function returns:
{'cores': '4', 'threads': '8', 'sockets': '1'}
> libvirt_xml.vm_xml: Added function to get cpu topology

- avocado_vt/plugins/vt_list.py
- avocado_vt/test.py
If AUTOTEST_PATH is set in env, then load the setup_modules will
fail due to wrong file name.
> Fix can't find setup_modules problem

- virttest/utils_test/libvirt.py
Adding adapter_type input for pool prepare
Signed-off-by: Harish <harisrir@linux.vnet.ibm.com>
> Fix: adding adapter type while pool prepare

- virttest/qemu_vm.py
Originally, params for memory device not format by function
'object_params()', that caused params for special memory
device can't be detect (eg. node_dimm_mem1 =1); Format memory
device test params to fix this issue.
> virttest.qemu_vm: fix pc-dimm leak node option issue

- shared/cfg/guest-hw.cfg
rng devices set in case will be covered by guest-hw.cfg
update default to += " rng0"
> update default rng_device to make it appendable

- virttest/utils_net.py
Pass 'shell' parameter to make some commands run in a shell correctly.
> utils_net: Fix to make a command run in a shell

- virttest/env_process.py
- virttest/utils_misc.py
to avoid calltrace in host dmesg impact comming test if
"verify_host_dmesg = yes" option in test params, we need
to unloading host dmesg.
> virttest.utils_misc: unloading calltrace in host dmesg

- virttest/libvirt_xml/vm_xml.py
- virttest/utils_test/libvirt.py
- virttest/virsh.py
The new commands are for Get/Add/Delete domain IOThreads, and
control domain IOThread affinity.
Signed-off-by: Ruifeng Bian <rbian@redhat.com>
> Add some iothread virsh commands support

- shared/cfg/guest-hw.cfg
> shared.cfg: add e1000e configuration in guest-hw.cfg

- selftests/unit/test_libvirt_xml.py
- virttest/libvirt_xml/capability_xml.py
Added maxcpus field in a guest capability method
to get the default maxcpus for a given arch.
Right now it takes the maxcpus of a default(first)
machine for a given arch which is needed for
the https://github.com/autotest/tp-libvirt/pull/878
the same can be extended further for each machine later
when there is a requirement as identified in TODO.
> Adding maxcpus for given arch in guest capability

- virttest/utils_net.py
Currently if ovs packages are not present on host, tests error out with improper message. This minor fix will Fail test with proper message
> Minor fix: Fail testcase with proper message

- virttest/utils_net.py
The commit 0953cecf24864697029f27fe11b01edc6512e295 makes all executions
fail when OpenVSwitch is not available, even though it's not needed for
the execution. IIRC OpenVSwitch is optional (at least it was for many
years) and that commit broke all my CI checks.
> Revert "Minor fix: Fail testcase with proper message"

- virttest/staging/lv_utils.py
According to commit 2e070abe:
As lvmetad could not running, the vgscan will fail, do not raise
error and fail then.
That commit was removed (mistakenly) and 'vgscan' was reintroduced
later without ignoring failure.
> utils_test.libvirt: Ignore vgscan failure again

- selftests/unit/test_nfs.py
- virttest/nfs.py
The nfs service will fail to start with "rpc.nfsd: unable to set any
sockets for nfsd" when the rpcbind service is not running. So the fix is
to ensure rpcbind is running before starting the nfs service.
> nfs.py: Ensure rpcbind running before starting nfs

- virttest/qemu_storage.py
- virttest/tests/unattended_install.py
- virttest/utils_test/__init__.py
1. Add function for suncommand amend of qemu-img
2. Add function to update qcow2 image version
3. When failed to install a guest, will copy an existed image.
Upgrade the image version if the version is older.
Signed-off-by: Ping Li pingl@redhat.com
ID: 1363946
> unattended_install: update QCOW image version to v3

- avocado_vt/options.py
By default nettype value from params is overridden by per-execution
value from config (net_type). The supported options are "user", "bridge"
and "none", where the "none" is not to set the type to none, but to get
the option from cartesian (test config). This patch removes the
cartesian assignment, which returns the correct handling.
> avocado_vt: Don't override nettype=none

- virttest/libvirt_vm.py
Added emulator path option for virt-install, this
will help in case of custom qemu binary to be used for
running libvirt tests
> Added emulator path option for virt-install commandline

- virttest/utils_misc.py
Encapsulate session.cmd_status_output() with getting a new session.
Signed-off-by: Cong Li coli@redhat.com
id: 1231041
> virttest.utils_misc.py: add get_guest_cmd_status_output().

- virttest/virsh.py
In a negative testcase scenario where empty vmname is given,
sometimes next parameter, here "vcpu number" matches "vm id", which
results in a valid command combination resulting netaive tests to fail.
This patch adds explicit prefix for params which will skip
such scenario.
> Added prefix for vcpupin command params

- avocado_vt/options.py
Ignore network options from vt.conf for tp-spice. SpiceQE team need to have an
ability to vary and dynamically choose network type for different tests.
> Ignore hardcoded network settings for tp-spice.

- virttest/nfs.py
Replaced nfs-server as service name for handling nfs service in ubuntu
Signed-off-by: Harish S <harisrir@linux.vnet.ibm.com>
> Fix nfs.py: nfs-server for Ubuntu nfs service

- virttest/libvirt_vm.py
Added warning log messages to user incase of missing
emulator and maxmemory suboption in virt-install.
> Added warning message incase of missing options

- virttest/test_setup.py
Restarting polkit.service fails in ubuntu, instead polkitd.service
needs to be used.
> Fixup test_setup

- virttest/qemu_monitor.py
Follow seabios and serial logfile name format to rename
monitor logfile name to '${monitor}-${vm-name}.log'.
ID: 1218964
> virttest.qemu_monitor: rename monitor log file

- virttest/utils_misc.py
Some cmd is put in winutils.iso, we can set a letter of winutils.iso in cmd (WIN_UTILS as default),
and replace it with real winutils.iso letter with this function
> Replace letter in cmd to real winutils cdrom letter

- virttest/env_process.py
- virttest/test_setup.py
For KVM to work in POWER8 systems we need to have SMT=off and it is common
that we have it SMT=on by default in all the distributions.
This patch checks whether we are satisfying that condition for POWER8,
if not it will make it off, otherwise errors out.
Signed-off-by: Balamuruhan S bala24@linux.vnet.ibm.com
Signed-off-by: Satheesh Rajendran sathnaga@linux.vnet.ibm.com
> Added check for SMT state in power system before test run

- virttest/env_process.py
we should throw an exception earlier if /dev/kvm doesn't exist.
No need to add "enable-kvm" option in make_create_command(),
which will lead the following error,
"Could not access KVM kernel module: No such file or directory\n
failed to initialize KVM: No such file or directory'"
> virttest.env_process: optimize the check for kvm module

- virttest/remote.py
When the aexpect matches the expected contents, sometimes the console
session will prompt '...Escape character is...' string, then the user
need to type an Enter key to show the 'login:' prompt. So this special
string should be considered to match.
> virttest.remote: Enable to match the console prompt

- shared/cfg/machines.cfg
The 6801faa1f6cff32869a510d7a2c79f3b366d5fd4 added the necessary
`--nvram` to arm64-mmio variant. This is fine as arm64-pci is not yet
supported by libvirt, but let's keep the definitions in sync to avoid
confusion when it is.
> shared.cfg.machines: Add the "--nvram" to arm64-pci

- virttest/utils_test/__init__.py
Loading stress tool on host can be much easiler. There is no need to
depend on autotest.
> utils_test: Directly load stress tool on host

- virttest/remote.py
In commit f5ccf3da, the regex introduced is not valid and has an asterisk
at the beginning of it. It will cause failure following failure of many
cases using this function:
```
error: nothing to repeat
```
> remote: Fix typo in regex to avoid failure

- docs/source/WritingTests/WritingSimpleTests.rst
Add a note about possible data corruption in the `session` output, which
is a known guest OS bug.
> docs: Add note about possible corrupted output in session

- requirements-travis.txt
- requirements.txt
- shared/cfg/guest-hw.cfg
- virttest/qemu_vm.py
- virttest/test_setup.py
This patch introduces support for setting up SR-IOV devices
on Mellanox CX4 hardware on ppc64le platform.
> Enable test setup for Mellanox CX4 SR-IOV on ppc64le

- shared/cfg/guest-os/Windows.cfg
devcon copy is dropped from driver_load.py, 
devcon.exe is put in winutils.iso, update the path 
> Update path of devcon cmd

- virttest/utils_test/__init__.py
These three imports are mistakenly removed in commit 6e1d2bc4.
They looks like unused imports, but is acctually useful to make these
submodules accessible directly from utils_test name space.
Removing these imports will make many test cases those using this way
fail. Added comments and a pylint disablement to avoid future removal.
> utils_test: Revert mistakenly removed importing

- virttest/iscsi.py
When calling `iscsiadm` to log out existing sessions, command will fail
when no existing session matches. This failure makes sense when logging
out a specific target. But when logging out all sessions, this failure
does not match common sense.
This issue can be easily reproduced by calling following command:
```
python -c "from virttest import iscsi; iscsi.iscsi_logout()"
```
This patch fix this issue by catching and forgiving this failure if
target name is not given.
> iscsi: Avoid failure when logout all without existing session

- virttest/libvirt_xml/devices/controller.py
The two attributes are needed in some test scenarios.
> Controller: Add two attributes

- virttest/ssh_key.py
Some tests execute commands to test machine remotely from other server
using,
virsh -c qemu+ssh://\<ipaddress\>\/system \<command\>
where it performs StrictHostKeyChecking and test fails even after
successful ssh key setup. For permitting virsh to use ssh with
StrictHostKeyChecking=no, the option can be set from ~/.ssh/config
Also if any other tests needs to config options can be used by this
same API.
> Option to set ssh_key config

- avocado_vt/plugins/vt.py
The `vt_qemu_bin` defines which qemu binary will be used in testing. It
has several special handlings to allow various manipulations, one of
them is that when `vt_qemu_bin` is None and `vt_config` is used, it
won't try to determine `qemu_binary` related params in order to allow
cartesian config to set those.
The problem is, that when `vt_qemu_bin` default is the current qemu
path, it won't allow users to set it to None, therefor this feature is
unavailable and the cartesian config params are overridden by `options`,
which might not be desired.
Even by setting the default to `None` the `qemu_binary` will be
processed and suitable binary found, therefor in reality the default is
still the same, only set later in the code (unless `--vt-qemu-bin` is
used).
Signed-off-by: Lukáš Doktor …
> avocado_vt: Change default for --vt-qemu-bin

- virttest/utils_test/libvirt.py
When command expect fail but run success, add command detail in
the raise error to quickly identify problem.
> utils_test.libvirt: Add command string in negative fail message

- shared/cfg/guest-os/Windows/Win10/i386.cfg
- shared/cfg/guest-os/Windows/Win7/i386.cfg
- shared/cfg/guest-os/Windows/Win8/i386.cfg
- virttest/qemu_vm.py
qemu_vm:
1.modify function add_memorys for 32bit windows guest
2.correct pep8 error
Signed-off-by: Aihua Liang<aliang@redhat.com>
ID:1388321,1388309
> qemu_vm:windows 32bit guest's maximum mem limit to 3G

- virttest/virsh.py
Work together with tp-libvirt: PR #959
PR #959: virsh.guestvcpus: Add test cases for guestvcpus
> virsh: Add function for guestvcpus

- virttest/libvirt_xml/vm_xml.py
It will be helpful to get xml file content in
case of failure rather than the temporary xml filename.
This patches changes the error log to print the
failed xml file content.
Signed-off-by: Satheesh Rajendran sathnaga@linux.vnet.ibm.com
> Fixup: Changed to log xml content during failure

- virttest/utils_test/__init__.py
shell_prompt=None as default parameter fails even for successful login by timing out if the API is called without regex for shell prompt. This patch fixes it.
> Utils_test: update shell_prompt default param with proper regex

- virttest/libvirt_xml/devices/hostdev.py
Add adapter's 'name', address's 'target', 'unit' attributes.
It's required by a npiv device passthrough, such as:
```
<hostdev managed="no" mode="subsystem" type="scsi">
<source>
<adapter name="scsi_host111" />
<address bus="0" target="0" unit="1" />
</source>
</hostdev>
```
> Add xml attributes for scsi hostdev

- shared/deps/finish/finish.bat
start serialport.exe in the end of installation, to avoid
serial port engross by the application.
And loop write 'Post set up finished' strings to serial port
to avoid keywords miss-catch issue.
ID: 1364425
> shared.deps: update finish.bat file

- shared/cfg/base.cfg
- virttest/virt_vm.py
When VM have multiple interfaces and
when IP gets assigned to random interface,
get_address hang on single interface and timeout for boot(import)test results to failure.
This patch will address it by introducing
a parameter""flexible_nic_index"",
when set it will try to poke all the interface and
check which has valid IP and connect to it.
Fixes: https://github.com/avocado-framework/avocado-vt/issues/617
> Fixup: VM with multiple interfaces boot failure

- virttest/libvirt_vm.py
Forming uri with given protocol and port where migration tests can use it to form uri dynamically and also avoids redundancy
> libvirt_vm.py: support to form uri with protocol and port

- virttest/utils_misc.py
ssh connection setup fails as server ip details will not be
available for local setsebool setup.
> Fixup utils_misc:  SELinuxBoolean local setup

- virttest/cartesian_config.py
The current Cartesian parsing performance is very low. It'll take
several minutes to list all the cases in a test provider.
After some CPU performance profiling, we can find the bottleneck of
current Cartesian parsing process is a function named postfix_parse.
This function is used to clip the range of a value if its key ends with
'_min', '_max' or '_fixed' and is called after the whole configuration
is combined and generated. Since the combination may generates very huge
number possible results, this function then will be called too many
times.
This patch reduce the calculation by calling this function right before
parser reach a leaf node. This will greatly decrease the number of
calling this function thus increase the performance of list large number
of test cases.
Signed-off-by: Hao …
> cartesian: Parsing suffix before yielding dict

- virttest/remote.py
- virttest/utils_misc.py
- virttest/utils_test/qemu/__init__.py
close function of session object use variable '_open_log_file'
in module 'aexpect.utils.genio' to collect opened fds, this
commit put fd opened by 'log_line' function in it to avoid
fd not closed after close session.
ID: 1408179
> virttest: fix _open_log_file namespace issue

- virttest/utils_config.py
The sysconfig file location is set for RHEL by default, but it different for Ubuntu. This patch setting the config path based on the distro.
Signed-off-by: Sudeesh John sudeesh@linux.vnet.ibm.com
> Sysconfig file location is set for RHEL by default

- shared/cfg/guest-os/Linux.cfg
- virttest/utils_netperf.py
utils_netperf:
1.extract shell,linesep and status_test_command as params for both "ssh" and "nc"
Signed-off-by: Aihua Liang<aliang@redhat.com>
ID:1261786,1263919
> utils_netperf: Extract "prompt,linesep and status_test_command" as params

- shared/cfg/base.cfg
cfg.base:use xhci as the default controller on ppc platform
Signed-off-by: Xujun Ma <xuma@redhat.com>
ID:1410309
> cfg.base:use xhci as the default controller on ppc platform

- virttest/qemu_vm.py
need to check VM status after send monitor command pause
or cont to ensure the command take effect really.
> virttest.qemu_vm: add vm status check

- selftests/doc/test_doc_build.py
- virttest/virt_admin.py
In order to automate the test case of the new feature virt-admin, I have
added module virtadmin.
> Add module virtadmin

- virttest/utils_misc.py
old qemu covert file path to real-path, so convert path in
p_dict to real-path. so that we can avoid error.
ID: 1388326
> virttest.qemu_vm: use abspath when get block device

- shared/cfg/guest-os/Windows/Win2016.cfg
- shared/cfg/guest-os/Windows/Win2016/x86_64.cfg
- shared/unattended/win2016-autounattend.xml
- shared/unattended/win2016-autounattend_ovmf.xml
shared.unattended:
1.add win2016-autounattend.xml
2.add win2016-autounattend_ovmf.xml
shared.cfg.guest-os.Windows:
1.add Win2016.cfg
2.add x86_64.cfg under folder "Win2016"
Signed-off-by: Aihua Liang<aliang@redhat.com>
ID:1398079
> Shared: add xml and cfg for Win2016 installation

- virttest/bootstrap.py
fix KeyError, if 'type_' is  prefix for a key of test params.
ID: 1405926
> virttest.bootstrap: fix KeyError exception

- virttest/qemu_vm.py
Fix bug of assigning reg for multiple spapr-vty devices.
ID: 1412103
> virttest.qemu_vm: fix bug of assigning reg for multiple spapr-vty devices

- shared/cfg/machines.cfg
ID: 1414244
For ppc platform , no soundcards support for qemu, remove it
> Empty soundcards params for ppc64le platform

- virttest/qemu_devices/qcontainer.py
qemu 0.12 use image real-path but qemu2.0 not, so convert
cdrom image file to real path to aviod get cdrom device
failed on different qemu.
ID: 1413549
> virttest.qcontainer: get cdrom device failed issue

- shared/control/parallel_dd.control
parallel_dd:Replace check_output by Popen for python compability
shared.control.parallel_dd:
1.import PIPE and Popen from subprocess
2.replace check_output by Popen to provide compability between python 2.6 and 2.7
Signed-off-by:Aihua Liang <aliang@redhat.com>
ID:1412031
> parallel_dd:Replace check_output by Popen

- shared/cfg/guest-os/Linux/RHEL/6.7/i386.cfg
- shared/cfg/guest-os/Linux/RHEL/6.7/x86_64.cfg
shared.cfg.guest-os.Linux.RHEL.6.7:
1.update cd_md5sum in x86_64.cfg
2.update cd_md5sum in i386.cfg
Signed-off-by:Aihua Liang <aliang@redhat.com>
ID:1411210
> RHEL.6.7:update cd_md5sum for latest RHEL6.7 ISO

- virttest/test_setup.py
- virttest/utils_misc.py
Meet block pipe caused deadlock when call wait() function in avocado.utils.process module. Will do funture debug to fix it. instead it with subprocess.check_call temporarily.
And fix bug in kill incorrect signal when kill ksmtuned daemon.
ID: 1347633
> Fix start ksmtuned  process hang issue

- virttest/utils_misc.py
1) Update cmd 'list_disk_cmd = "lsblk -p -oKNAME,MOUNTPOINT,SERIAL,SIZE,MODEL,WWN"' to 'list_disk_cmd = "lsblk -oKNAME,MOUNTPOINT,SIZE,MODEL"' to make it suitable for both RHEL6 AND RHEL7 guests
2) Add code to handle the default 'mountpoint=None' and 'size=None' scenarios
3) Add detailed code to get a did list which includes kname, serial and wwn of a disk, so the did can be any of them
ID: 1378325
Signed-off-by: Nini Gu ngu@redhat.com
> Virttest.utils_misc: Update function format_windows_disk/format_linux_disk

- docs/source/GetStartedGuide.rst
The 7za is not hard-dependency, let's add a note how to bypass the 7za
check to the documentation.
> docs: Add note about bootstrap without 7za

- virttest/libvirt_vm.py
- virttest/virt_vm.py
As get_distro() can be used from both libvirt and qemu tests,
placed it in virt_vm.py
> Moving get_distro() from libvirt_vm.py to virt_vm.py

- virttest/env_process.py
Selinux permits libvirt to access NFS shared image, if virt_use_nfs
is set as on during guest import.
> Enable virt_use_nfs for guest with NFS shared image during guest_import

- shared/cfg/guest-os/Windows.cfg
it will cover the setup in case cfg file,
but {$install_path} still use the cfg in case, which will make the test failed
> Remove fio_windows cfg set from Windows.cfg

- virttest/utils_test/libvirt.py
Some of the tests requires to add or remove iptable rules locally or remotely,
Example: For migration tests, 49152 to 49216 ports have to be opened
for libvirt to permit migration
This patch add the support and can be used by other tests.
> Support to add or remove iptable rules to local or remote machine

- virttest/virsh.py
pool type can be scsi, but it was not listed in _poo_type_check
Sign-off by: Yi Sun (lentosun@163.com)
> Add 'scsi' in _pool_type_check

- avocado-plugins-vt.spec
The python-netaddr is required by avocado-vt, it's already defined in
requirements.txt but is missing in the RPM spec file.
Note I tested this on F25 and I verified python-netaddr package exists on RHEL.7. Hopefully it's called the same on other supported variants.
Fixes: https://github.com/avocado-framework/avocado/issues/1755
> spec: Add python-netaddr to RPM spec file

- avocado-plugins-vt.spec
- requirements-travis.txt
- requirements.txt
- virttest/qemu_vm.py
- virttest/utils_net.py
Instead of using utils_net.get_host_ip_address(self.params) to translate ipv4 address to ipv6, real ipv6 address of utilized interface is used.
The ipv6 addresss of host interface cannot be obtained using get_ip_address_by_interface(ifname).
I added a parameter to function to choose from family address: get_ip_address_by_interface(ifname, ip_ver).
This PR is correction of https://github.com/avocado-framework/avocado-vt/pull/855 proposed by @xutian.
> Support for ipv6 connection to Spice client/server

- virttest/qemu_vm.py
mem in directory is still the original value when mem > maxmem
id: 1416233
> mem in directory is not updated when maxmem is used

- virttest/utils_misc.py
There are two function references in a latest patch that mistaken
referred class functions as module functions, thus leading several
test cases failed with:
```
NameError: global name 'get_all_node_meminfo' is not defined
```
> utils_misc: Fix function name scope typos

- shared/cfg/guest-os/Linux/RHEL.cfg
The efi-rtc=noprobe workaround to boot on arm was necessary years ago,
but is not necessary anymore. Let's remove it.
> shared.cfg: Remove ancient workaround

- docs/source/DownloadableImages.rst
- shared/downloads/jeos-21-64.ini
As it was explained on the mailing list, we're dropping JeOS 21
to make room for JeOS 25 and also to switch to a new compression
format (xz).
For now, this only removes JeOS.21 from the list of available
downloads.
Reference: https://www.redhat.com/archives/avocado-devel/2017-February/msg00077.html
Reference: https://trello.com/c/hJiQaKPu/
> JeOS image: deprecate JeOS version 21

- avocado_vt/test.py
When the https://github.com/avocado-framework/avocado/pull/1817 is applied Avocado-vt won't be able to override the params as before. This patch set adjusts the VirtTest to be able to work with the new proposed way (including the params handling) while allowing to work with the current and even 36lts version.
This should only be applied if we decide to go with the https://github.com/avocado-framework/avocado/pull/1817 and could be simplified if we decide to skip the params protection (demonstrated in https://github.com/avocado-framework/avocado/pull/1809 ).
__This patch needs to be applied before merging any of the Avocado patches!__
> avocado_vt: Cope with recent changes in Avocado

- .travis.yml
The newly released Avocado-46.0 does not support python-2.6 anymore.
Let's use 36lts to check on python-2.6
> travis: Use avocado-36lts for python2.6 check

- selftests/checkall
1. Now we pass all the disable rules explicitly to inspektor.
2. Disable W503. It complain 'line break before binary operator',
but PEP8 do recommend to break after binary operator and it looks
really better. See more:
https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator
> selftest: Custom inspektor style check rules

- virttest/utils_iptables.py
- virttest/utils_test/libvirt.py
API setup_or_cleanup_iptables_rules() to configure and cleanup
iptable rules for the tests to handle iptables related configurations.
> utils_iptables: Moving setup_or_cleanup_iptables_rules()

- virttest/qemu_vm.py
- virttest/utils_misc.py
'erms' flag is required by Win10 and Win2016 guest OS, if VM CPU model is 'Penryn' or 'Nehalem', and it's harmless for other guest OS, so add it with guest OS insensitive.
ID: 1419399
> avocado-vt: add erms for cpu model 'Penryn' and 'Nehalem'

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
add auto-increament 'slot' params when add root port
> virttest: order pci controller devices before insert

- virttest/libvirt_xml/vm_xml.py
xml topology miss in guest xml is not a error
hence reduced log level to debug.
> Fixup: Changed topology miss from error to debug log

- avocado-plugins-vt.spec
Fix issue#888 - not module named simplejson in rhel7 host
> avocado-plugins-vt.spec: add python2-simplejson for rhel7

- shared/cfg/guest-os/Linux/Fedora/25.x86_64.cfg
- shared/downloads/fedora-25-x86_64.ini
- shared/unattended/Fedora-25.ks
This introduces the Fedora 25 (for the x86_64 arch).  This has
been tested with both "cdrom" and "url" methods, and with the
delivery of the "unattended file" (the kickstart file) with
"extra_cdrom_ks" and also the builtin HTTP server.
One particular difference in the kickstart file is that it
includes the installation of Avocado from the official repos.
This may open the way for other types of tests and uses for images
generated with this guest OS type.
---
Changes from v1 (#911):
* Added download definition file
* Removed unnecessary `serial` kernel parameter
* Limit the `mem` parameter overwrite to the `url` variant
> Guest OS Support: add Fedora 25 (x86_64)

- virttest/utils_misc.py
As get_all_nodes() returns all the nodes including offline nodes,
which doesn't have meminfo file, instead using get_online_nodes()
fixes it.
> utils_misc: get_all_node_meminfo() uses get_all_nodes instead of get_online_nodes

- virttest/bootstrap.py
- Fix exception message.
- Handle ValueError exception on nonexistent guest
Reference: https://trello.com/c/Lb81Sxjs/934-bug-avocado-vt-boostrap-crashes-with-unexisting-guest
> Fix crash on unexisting guest

- virttest/libvirt_vm.py
- virttest/utils_test/libvirt.py
- virttest/virsh.py
Add a parameter providing virsh option when executing virsh command.
Migration function also adds this parameter for its caller to use.
> virttest.virsh: Add one parameter for virsh option

- virttest/qemu_vm.py
- virttest/utils_net.py
Make host_ip variable accessible after vm creation if listening_addr specified.
> Store host_ip as vm parameter

- virttest/utils_misc.py
The function `utils_misc.log_line` does not respect the system encoding,
which works fine for ascii strings, but recently the serial console
started to write \xff which makes the writer to crash.
> virttest.utils_misc: Allow writing unicode in log_line

- virttest/nfs.py
When use 'ssh-keygen -R hostname' to remove host key, if
known_hosts file not exist, command will return error with 'No
such file or directory'.
This happens when set in ssh_config with:
UserKnownHostsFile=/dev/null
this should not fail the setup as no known hosts recorded when
ssh connect.
> nfs: Skip ssh key remove fail when known_hosts not exist

- virttest/nfs.py
'ignore_status' should be True in order to avoid of raising an exception
when the command execution fails.
> virttest/nfs: Minor parameter fix for process.run

- virttest/utils_test/__init__.py
On SLES guests, session.cmd()/session.cmd_output might exit without any error WHILE the real cmd is still in progress in the guest; so add 'wait ${!}' for the issue code point.
ID: 1360676, 1361468
> virttest/utils_test/__init__.py: Fix session.cmd issue on SLES guests

- shared/cfg/guest-os/Linux/JeOS/25.x86_64.cfg
- shared/downloads/jeos-25-64.ini
- shared/unattended/JeOS-25.ks
- virttest/defaults.py
This introduces JeOS 25, based on Fedora 25.  Differences from previous versions include an added Python 2 interpreter.
> Guest OS Support: add JeOS 25 (x86_64)

- virttest/qemu_vm.py
Some of our testcases does not require to specify `--spice port=foo` option.
> Added option to not specify spice_port

- requirements.txt
Bumped latest aexpect version in requirements.txt
to get "UnicodeDecodeError" fix.
> Bumped latest aexpect version in requirements.txt

- virttest/libvirt_xml/devices/controller.py
This attribute is needed in some test scenarios.
> devices/controller.py: Add one attribute

- virttest/qemu_vm.py
Commit 9ca0c3ea incorrectly removed some codes that is used for waiting
for guest accomplishing the shutdown operation in the case of using a
net session. This patch will bring them back.
ID: 1434307
> qemu_vm: fix bug of the reboot function

- virttest/env_process.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
Reset vm memory size according host free memory size if 'automem' params is 'yes'(default is 'yes'). For
migration related test case 'automem' should be 'no' to avoid migration failed.
And add device check before add 'slots' and 'maxmem' option for memory devices.
ID: 1426892
> qemu_vm: add params for add memory devices

- virttest/asset.py
git pull origin step update local repo to latest, it made
ref-commit configured in test-providers useless, so
drop the step.
> virttest.assert: fix ref-commit not works issue

- avocado_vt/test.py
- virttest/utils_misc.py
Avocado now supports status CANCEL, which is basically what SKIP was
being used for in Avocado-vt. Let's move the test execution back to
"runTest" phase and use `self.$status` to map the Avocado-vt exceptions
to Avocado ones, which, unlike exceptions, should be stable.
Fixes: https://github.com/avocado-framework/avocado-vt/issues/934
> avocado_vt: Move runTest to test phase and improve exceptions

- shared/deps/finish/finish.bat
kill serailport.exe to release serialport to finished program
to write string to serialport.
> share.deps: kill serialport server before install finished

- virttest/utils_misc.py
- virttest/utils_package.py
Use LocalPackageMgr which is subclass from software_manager in
avocado to decide the package manager and install or remove
package on local host.
If remote session is given, use the RemotePackageMgr class
to find out the package manager on remote for install or remove
packages.
> virttest.utils_package: Add package manager module

- virttest/utils_misc.py
The 9043d263c7bd935474191dcf38fa5a24f60ce4a8 breaks the unicode support
again. Before that commit both, unicode() and str() were supported, when
they followed the defined encoding, anyway I can see that probably
someone tries to log already encoded unicode, which might fail. So let's
remove all those different handlings and use the `astring`
implementation of the lenient encode, which first assumes the right
encoding and when that fails it assumes it is already encoded string.
Please don't break this function anymore as it is crucial for
unattended_install and breaks the CI!
> virttest.utils_misc: Remove the non-woring decode

- virttest/utils_misc.py
utils_misc:correct "parm" to "param"
virttest.utils_misc:
correct "parm" to "param" in functions get_free_disk(),
get_free_mem() and get_used_mem()
Signed-off-by:Aihua Liang<aliang@redhat.com>
ID:1439602
> utils_misc:correct "parm" to "param"

- virttest/utils_test/__init__.py
when get guest time with format "3/30/2017 3:28:47 PM", re.match can not match "PM" as it is not at the beginning of string.
id: 1437455
> utils_test.get_time:Correct to match "PM" when get guest time with "PM" doesn't at the beginning

- virttest/utils_net.py
second no-empty line of wmic output is interesting line because first line is a header line, so return second no-empty line to instead last line. And report stderr in exception message if the command execute failed.
ID: 1436129
> virttest.utils_net: get correct output of wmic batch command

- backends/v2v/cfg/convert_destination.cfg
- backends/v2v/cfg/convert_source.cfg
- backends/v2v/cfg/tests-shared.cfg
These configurations including infomations of source hypervisors
and destinations are needed by almost every v2v cases. Therefore
organize and store them in public config files will be make future
case implementing job easier and cfg files lighter.
> Add public config file for v2v

- virttest/utils_selinux.py
get_status() breaks if selinux is not installed, it is handled and appropriate
exception is raised.
> utils_selinux: Handling exception if selinux not installed

- shared/cfg/guest-os/Linux/SLES/12.2.ppc64le.cfg
After the occurrence of SLES12 SP2, add its ppc64le related configuration file into guest-os
ID: 1436138
> shared/cfg/guest-os/Linux/SLES: Add SLES12.2 cfg file - ppc64le

- virttest/qemu_vm.py
It is unreasonable to check whether a new thread is created for
doing migration in function `migrate` because the behavior is
implementation-dependent. Suggest to make this as an unittest for the
corresponding version of QEMU if do have the need.
ID: 1321505
> qemu_vm: Remove thread check from function migrate

- shared/cfg/guest-os/Windows.cfg
it has been set, no need to set again
ID: 1413860
> Remove config_cmd for win_heavyload test

- virttest/virt_vm.py
The original prompt is a bit of inaccurate, when running a command with
'#' or '$' in the output(such as install a package), it will lead to
get_cmd_status fail. So use a more accurate prompt to fix the problem.
> virt_vm: Using a more accurate prompt

- virttest/utils_test/__init__.py
output of ping command in windows is different with it output
in linux(output in win10 like:'.. Lost = 8 (80% loss)',
output in linux like:' 100% packet loss, time 8999ms'),so update
regex to made it works on both windows and linux.
ID: 1397690
> virttest.utils_test: update regex for getting ping loss ratio

- virttest/qemu_vm.py
SGA (Serial Graphics Adapter) support in qemu as device, so
replace qcontainor.has_option with qcontainor.has_device to
avoid add 'sga' device failed.
ID: 1443432
> fix add SGA device failed issue

- virttest/virt_vm.py
Param 'flexible_nic_index' should also works to get IPv6 address of nic
> virttest.virt_vm: add wrapper function for get_address

- virttest/asset.py
When you are downloading the JEOS image and you lost the connection,
avocado chrashes with an error:
6 - Verifying (and possibly downloading) guest image
Verifying expected SHA1 sum from
http://assets-avocadoproject.rhcloud.com/static/SHA1SUM_JEOS25
Expected SHA1 sum: 7f5a440f6eb83577d42f9f68987534b1076967d8
File
/home/jfaracco/Desktop/c4eb/git/virt-test/tests/data/avocado-vt/images/jeos-25-64.qcow2.xz
not found
Would you like to download it from
http://assets-avocadoproject.rhcloud.com/static/jeos-25-64.qcow2.xz?
(y/n) y
Avocado crashed unexpectedly: <urlopen error [Errno -2] Name or service
not known>
You can find details in
/var/tmp/avocado-traceback-2017-04-11_12:34:08-PF3PjA.log
Adding try/except will avoid this problem because urllib2 inside
url_download_interactive() will not throw …
> asset: Adding try/except to avoid connection issues during download [v5].

- virttest/asset.py
- virttest/bootstrap.py
This is a collection of a few improvements and fixes to the asset related part of the bootstrap module (and thus `avocado vt-bootstrap` user experience).
---
Changes from v1 (#957):
* Enable shell on uncompress commands
> Bootstrap: improve xz and other asset related checks and actions [v2]

- avocado_vt/test.py
avocado_params is now a property. This patch fixes the state['params']
attribution accordingly.
Fixes: https://github.com/avocado-framework/avocado/issues/1971
> fix avocado_params state report

- avocado_vt/plugins/vt_joblock.py
- setup.py
Avocado has changed the Pre/Post job interfaces.  Basically,
"JobPre" will really be run before the job, while "JobPreTests" will
be run as part of the job, but before the test execution.  The same
logic applies to "JobPost".
> VT JobLock: adapt to Avocado's Pre/Post Job interface changes

- virttest/ovirt.py
- virttest/virt_vm.py
Raise exception that next procedure could catch and deal with
other than throw it out if get_mac_address returns None for mac
address.
set_mac_address method should be called with an object of
virttest.utils_net.VirtNet
update param list of function get_address() of ovirt.VMManager
> virt_vm:fix issue of cannot connect to guests after v2v conversion

- virttest/libvirt_vm.py
When close console, the object is still exist, but not function anymore.
> libvirt_vm: Fix create console bug

- virttest/utils_test/libvirt.py
handled setting default value if empty string is used
> libvirt.py: empty string param might break the API

- virttest/utils_net.py
'IPAddrGetError' could be caught afterwards by other functions while
'TestError' would be thrown out.
> utils_net:it should be 'IPAddrGetError' in get_ip_address_by_interface

- avocado_vt/plugins/vt_joblock.py
When the plugin "pre" phase is called, but the job has not created
a test suite, trying to iterate it will cause a failure such as:
Failure trying to set Avocado-VT job lock: 'NoneType' object is not iterable
Reproduced traceback from:
/usr/lib/python2.7/site-packages/avocado_vt/plugins/vt_joblock.py:125
TypeError: 'NoneType' object is not iterable
It's actually safe to skip the lock if there are no tests in the suite
(and thus no VT test).
This bug was actually revealed by the dispatcher calling the "JobPre",
but the fix is approapriate to any situation.
> VT JobLock: avoid iterating the test suite when one doesn't exist

- .travis.yml
- avocado_vt/test.py
- selftests/functional/test_basic.py
- selftests/run
- setup.py
- virttest/data_dir.py
The intention of this PR is to start functional testing of Avocado, but that requires deploying it in Travis which unveiled some issues with venv support:
```
$ virtualenv -p python venv
$ source venv/bin/activate
$ pip install avocado-framework aexpect netifaces simplejson netaddr
$ cd /home/medic/Work/Projekty/avocado/avocado-vt
$ make install
$ avocado vt-bootstrap
Failed to load plugin from module "avocado_vt.plugins.vt_list": ImportError('No module named autotest.client.shared',)
Failed to load plugin from module "avocado_vt.plugins.vt": ImportError('No module named autotest.client.shared',)
Failed to load plugin from module "avocado.plugins.yaml_to_mux": NameError("name 'Loader' is not defined",)
Running bootstrap for qemu
1 - Checking the mandatory programs and headers
/bin/xz OK …
```
> Fix venv support and add functional selftest

- avocado_vt/plugins/vt_bootstrap.py
- backends/libvirt/cfg/tests-shared.cfg
- backends/qemu/cfg/tests-shared.cfg
- virttest/bootstrap.py
This introduces the generation of another file doing bootstrap time,
host-os.cfg.
This file contains the name, version and release of the host OS.  That
information comes, by default, from the Avocado distro detection, but
can be overriden by command line arguments.
This should allow for some tests in some providers, such as tp-qemu,
to properly enable or disable tests that should be available only
for some distros.
---
Changes from v2 (#1009):
* Include `Host_arch_` prefix when compatibility mode is used
* Dropped the `compat` parameter on utility functions
Changes from v1 (#1007):
* Moved `host-os.cfg` to right after `subtests.cfg` (affects the full name of the variants, but it's cosmetic only).
* Improved docstrings
* Added distro …
> Bootstrap: generate host os configuration [v3]

- etc/avocado/conf.d/vt.conf
Currently the default disk drive is `virtio_blk`, which used to be the
best option, but for quite a long while `virtio_scsi` is recommended as
more standardized way. Let's change our default to by default utilize
what's recommended.
> etc: Change default disk drive

- avocado_vt/plugins/vt_bootstrap.py
- virttest/bootstrap.py
The --vt-host-distro-compat option was introduced to start fresh and
provide clean host configuration. There is one issue with that and that
is that cartesian_config does not behave correctly when clashes occur
and in the fresh version they are likely to happen. Let's keep what has
been working for years downstream and that is:
* Host OS is prefixed with "Host_"
* Major version is prefixed with "m"
* Minor version is prefixed with "u"
* Architecture is prefixed with "Host_arch_"
This should minimize the possible clashes as Fedora.25.0.x86_64 becomes
Host_fedora.m25.u0.Host_arch_x86_64.
Possible clashes are usually recognizable by multiple/no produced
variants. Without this fix one easy clash is to use:
avocado run boot --vt-guest-os RHEL.7.devel --dry-run
...
(1/4) …
>  bootstrap: Remove the --vt-host-distro-compat option

- virttest/utils_test/libvirt.py
since readonly attribute need be set explicitly
> Enable readonly attribute when attaching rbd disk with snapshot

- virttest/libvirt_xml/vm_xml.py
Handle LibvirtXMLError if device is not available in guest xml
> vm_xml: get_agent_channel tracesback if channel device not available

- avocado_vt/options.py
- etc/avocado/conf.d/vt.conf
The current handling of configuration values from `/etc/avocado/*` overwrite whatever is set in the cartesian configuration by default.  Let's change that behavior, so that, by default, no value is set and nothing is overriden.  If users set the value in the Avocado config file, than it will overwrite whatever is set in the cartesian config.
> Config from `/etc/avocado/*` should not overwrite cartesian by default

- virttest/utils_hotplug.py
This addes a commonly used functions across most
of the cpu hotplug and other cpu related virsh API functions.
> Added library for virsh cpu(hotplug) utilities

- .travis.yml
- avocado_vt/plugins/vt_bootstrap.py
- virttest/asset.py
- virttest/bootstrap.py
This is a collection of (hopeful) improvements to the bootstrap process.
Included are:
* cleanups to options processing
* reorganization of some phases
* one change in behavior: `--vt-no-downloads` won't attempt *any* downloads (including test providers)
* a new option `-vt-skip-verify-download-assets` will skip the phase about downloads asset files (usually JeOS images)
> Bootstrap improvements

- virttest/virsh.py
It's a easier way to just provide a plaintext password and
do the encoding inside this method. So when encode=True,
a base64 encoding will take effect.
Sign-offed by: Yi Sun(yisun@redhat.com)
> Add 'encode' parameter for secret_set_value

- virttest/utils_test/__init__.py
The purpose for 'image_copy' test is copy some prestine image to work image.
This patch introduces 'specimen_image' option. With this option we can specify
which image should be taken as source image.
> Add to 'image_copy' test 'specimen_image' parameter

- virttest/utils_test/__init__.py
typo fix to succeed grubby --remove-args
> utils_test: fix a typo in update_boot_option() to succeed grubby --remove-args

- virttest/qemu_vm.py
Cartesian config can have empty parameters:
param =
There are a few test-cases where Spice params are initialized to
empty value. In batch test runs such parameters are skipped. This
commit fix this.
Note. Avocado-VT uses the same VM objects in batch tests. Which is a
part of cause of such behaviour. More info:
https://www.redhat.com/archives/avocado-devel/2017-February/msg00000.html
> Respect empty parameters for Spice protocol

- virttest/virsh.py
Some existing cases will use virsh.secret_set_value() as follow:
result = virsh.secret_set_value(uuid, secret_string, options, debug=True)
So avocado-vt PR#1036 will cause case failure because an new param 'encode'
inserted before 'options'.
Sign-offed by: Yi Sun(yisun@redhat.com)
> Fix params sequence of secret_set_value

- virttest/test_setup.py
process errors out some shell commands as "shell=True" is missed
causing improper sriov setup or cleanup in PciAssignable()
> test_setup: shell commands errors in PciAssignable()

- virttest/test_setup.py
request_devs() function doesn't have error_context decorator which causes
traceback in error_context as "IndexError: list assignment index out of range"
> test_setup: request_devs() function doesn't have error_context decorator

- shared/unattended/RHEL-7-devel.ks
Adding the sg3_utils package installs the sginfo command which is required by
the type_specific.io-github-autotest-qemu.physical_resources_check test for
RHEL guests
> Add sg3_utils package to RHEL-7-devel.ks file

- avocado-plugins-vt.spec
python-aexpect files are already present on EPEL7 and Fedora.  Also,
the previous requirement was now causing conflicts with the
installation of python-aexpect from Avocado's own repo.
> avocado-plugins-vt.spec: replace aexpect with python-aexpect

- shared/unattended/Fedora-10.ks
- shared/unattended/Fedora-11.ks
- shared/unattended/Fedora-12.ks
- shared/unattended/Fedora-13.ks
- shared/unattended/Fedora-14.ks
- shared/unattended/Fedora-15.ks
- shared/unattended/Fedora-16.ks
- shared/unattended/Fedora-17.ks
- shared/unattended/Fedora-18.ks
- shared/unattended/Fedora-19.ks
- shared/unattended/Fedora-20.ks
- shared/unattended/Fedora-21.ks
- shared/unattended/Fedora-22.ks
- shared/unattended/Fedora-23.ks
- shared/unattended/Fedora-25.ks
- shared/unattended/Fedora-8.ks
- shared/unattended/Fedora-9.ks
- shared/unattended/RHEL-3-series.ks
- shared/unattended/RHEL-4-series.ks
- shared/unattended/RHEL-6-spice.ks
Adding the sg3_utils package installs the sginfo command which is required by
the type_specific.io-github-autotest-qemu.physical_resources_check test for
RHEL guests
This is a follow-up commit to https://github.com/avocado-framework/avocado-vt/pull/1055
After discussing with @clebergnu on Friday, he suggested that we update all Fedora and RHEL kickstart files so users can expect a consistent experience when running Avocado-VT with these guests.
@luckyh Could you kindly review and merge ?
Thanks.
> Add sg3_utils package to Fedora and RHEL kickstart files

- virttest/utils_misc.py
A sample of ARM machines supported by RHEL is listed below. Apparently
the ARM machine type description is not ended with "PC", which is x86
specific. So get_support_machine_type() parsing returns a incorrect
result. This patch fixes the regular expression by removing "PC", to
make it work on ARM platform.
* virt-rhel7.4.0       RHEL 7.4.0 ARM Virtual Machine (default)
* virt-rhel7.3.0       RHEL 7.3.0 ARM Virtual Machine
* none                 empty machine
Signed-off-by: Wei Huang <wei@redhat.com>
> virttest.utils_misc: fix support machine type parsing for RHEL ARM

- virttest/env_process.py
- virttest/utils_misc.py
Added host_dmesg_level, host_dmesg_ignore params
which would help testers to define the log level needs
to be asserted and whether test need to fail if messages
present in given log level, by default it fails the tests
for log level 3(emerg,alert,crit)
Supported Log level:
1 - emerg
2 - emerg,alert
3 - emerg,alert,crit
4 - emerg,alert,crit,err
5 - emerg,alert,crit,err,warn
Config usage:
verify_host_dmesg = yes(by default)
host_dmesg_level = 3(by default)
host_dmesg_ignore = False(by default)
> Fixup: error verification in host dmesg

- virttest/utils_test/libvirt.py
Faced issue on running ubuntu: TestError: Interface 'lo' not exists
Signed-off-by: Mallesh Koti <mallesh@linux.vnet.ibm.com>
> utils_test/libvirt.py: get network interface file for any distro

- virttest/qemu_monitor.py
'info block- can generate output such as:
drive_image1 (#block188): /path/to/image.qcow2 (qcow2)
Cache mode:       writeback
When parsing those lines, the device name was including the extra
information (' (#block188)' in this example), which makes matches
against the information present on qtree fail.
This doesn't happen when a QMP monitor is used, though, so it only
affects tests running with HMP and with QEMU >= 1.5.0.
> Fix HMP parsing of 'info block' on QEMU >= 1.5

- virttest/libvirt_xml/domcapability_xml.py
There is an requirement to gain the vcpu infomration in domcapabilities
XML, so this is to provide a way.
> domcapability_xml: Add an attribute

- shared/cfg/guest-os/Windows/Win10/i386.cfg
- shared/cfg/guest-os/Windows/Win10/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2003/i386.cfg
- shared/cfg/guest-os/Windows/Win2003/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2008/i386.cfg
- shared/cfg/guest-os/Windows/Win2008/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2016/x86_64.cfg
- shared/cfg/guest-os/Windows/Win7/i386.cfg
- shared/cfg/guest-os/Windows/Win7/x86_64.cfg
- shared/cfg/guest-os/Windows/Win8/i386.cfg
- shared/cfg/guest-os/Windows/Win8/x86_64.cfg
- virttest/qemu_vm.py
There are max memory limit for windows 32bit guests,
the memory can not be recognized which out of the limit.
id: 1442987
> virttest.qemu_vm: Add windows guest max memory limit.

- virttest/utils_net.py
net_utils function get_ip_address_by_interface raising exception if a network interface is up without ip address configured.
Signed-off-by: Sudeesh John sudeesh@linux.vnet.ibm.com
> net_utils function get_ip_address_by_interface raising exception

- virttest/utils_net.py
API to generate ipv4 address and can be used inside tests for
assigning static IP address to guests/hosts
> utils_net: simple ipv4 address generator

- shared/cfg/guest-os/Linux/RHEL/7.0.cfg
- shared/cfg/guest-os/Linux/RHEL/7.1.cfg
- shared/cfg/guest-os/Linux/RHEL/7.2.cfg
- shared/cfg/guest-os/Linux/RHEL/7.3.cfg
- shared/cfg/guest-os/Linux/RHEL/7.devel.cfg
Setting memory parameter to 4096 for RHEL 7.0, 7.1, 7.2, 7.3 and 7.devel
guests when running unattended_install.url test as installing RHEL over
http fails with memory set to 1024.
> Increase memory assigned to guest when installing using URL v2

- shared/unattended/OpenSUSE-Leap-42.1.xml
* drop duplicated lines.
* fix virtio-scsi installation test.
* don't use the fixed mac address
* set up 'Turn Off the Machine after the First Stage' to avoid the vm
installation infinite loop.
* Add post-script to modify sshd_config to set PasswordAuthentication
to enable tunneled clear text passwords.
Signed-off-by: Lin Ma <lma@suse.com>
> Fix couple issues in OpenSUSE-Leap-42.1.xml

- shared/cfg/base.cfg
- virttest/libvirt_vm.py
Added support for user defined additional args to
virt-install command line, will be usefull for new
features to test till proper method to add
commandline and flexible negative cases.
Usage:
define additional commadline args(string) in this
param "virtinstall_extra_args"
E:g:- virtinstall_extra_args = "--controller type=usb,model=nec-xhci"
> Added support for additional args for virt-install

- virttest/nfs.py
- virttest/utils_test/libvirt.py
Add option to support clean up new created dir in nfs module.
Enable cleanup both new created export and mount dir in libvirt
nfs setup and clean function.
> nfs: Cleanup new created export dir

- virttest/utils_test/libvirt.py
Previously we cannot prepare a iscsi pool with auth enabled.
With this patch, we can provide chap username/password and a
libvirt secret usage to prepare a auth-enabled iscsi pool.
> Add authentication info in pre_pool() for iscsi pool

- shared/cfg/guest-hw.cfg
guest-hw.cfg:change rng backend to /dev/urandom 
RNG backend /dev/random has bad performance,especially generate random
numbers continuously.So change backend to /dev/urandom.
Signed-off-by: lijin <lijin@redhat.com>
ID:1477573
> guest-hw.cfg:change rng backend to /dev/urandom

- virttest/utils_test/__init__.py
ID: 1477485
Correct a typo.
Signed-off-by: Zhengtong <zhengtli@redhat.com>
> virttest.utils_test.__init__.py: correct a typo

- virttest/libvirt_vm.py
virt-install takes MiB as default memory unit for --memory option and
in KiB as default memory unit for --cpu option while adding numa nodes.
Due to this behavior virt-install boots guest with memory value in --memory
but with KiB due to libvirt issue.
> libvirt_vm: Fixup virt-install takes conflicting memory unit with --memory and --cpu

- avocado-plugins-vt.spec
With the introduction of python-avocado packages on EPEL 7, the
general installation workflow of Avocado + Avocado-VT broke.  The
reason is that for the installation of Avocado itself from Avocado's
own repo, EPEL is necessary.  Then, given that 51.0 is the latest
major release on both Avocado's repo and EPEL, the package from EPEL
gets installed.
When comes the time to install avocado-plugins-vt, the requirement for
"avocado >= 36.4" can not be satisfied, because it's only present in
Avocado's version of the "python-avocado" RPM.
If RPM supported boolean operators on all versions that we need, we
could do a:
Requires: (avocado >= 36.4 or python-avocado >= xx.y)
But unfortunately that is only present in RPM >= 4.13.  The solution
proposed here is to switch the package name that is …
> RPM: also satisfy avocado requirement with EPEL package

- shared/unattended/Fedora-16.ks
- shared/unattended/Fedora-17.ks
- shared/unattended/Fedora-18.ks
- shared/unattended/Fedora-19.ks
- shared/unattended/Fedora-20.ks
- shared/unattended/Fedora-21.ks
- shared/unattended/Fedora-22.ks
- shared/unattended/Fedora-23.ks
- shared/unattended/Fedora-25.ks
- shared/unattended/RHEL-6-series.ks
- shared/unattended/RHEL-6-spice.ks
- shared/unattended/RHEL-6.3.ks
- shared/unattended/RHEL-7-devel.ks
- shared/unattended/RHEL-7-series.ks
Adding the net-tools package installs the ifconfig command which is required by the io-github-autotest-qemu.jumbo test for Fedora and RHEL hosts.
> Add net-tools package to Fedora and RHEL kickstart files

- shared/cfg/guest-os/Linux.cfg
qemu option "-no-kvm-pit-reinjection"  is unsupported in arm, remove it.
id: 1480178
> guest-os.Linux.cfg: Remove "-no-kvm-pit-reinjection" option for ARM

- virttest/utils_misc.py
Due to different disk return format on win2008-32/64 and others,
change the disk status(Offline)re.search format.
id: 1472063
Signed-off-by: peixiu <phou@redhat.com>
> Change the disk Offline status check format

- virttest/qemu_devices/qbuses.py
The param port_prefix is initialized with value None.
It will not work, if set usb devices up by specifying usb device port
on the bus. Because it will always return False or try to get len of
a None object.
id: 1480109
> virttest.qbuses: support to specify the port of usb device on the bus

- selftests/unit/test_cartesian_config_lint.py
- shared/cfg/guest-os/Linux/RHEL/5.11/i386.cfg
- shared/cfg/guest-os/Linux/RHEL/6.4/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/6.9/i386.cfg
- shared/cfg/guest-os/Linux/RHEL/6.9/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/6.9/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.0/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.0/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.1/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.1/ppc64le.cfg
- shared/cfg/guest-os/Linux/RHEL/7.1/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.2/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.2/ppc64le.cfg
- shared/cfg/guest-os/Linux/RHEL/7.2/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.3/aarch64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.3/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.3/ppc64le.cfg
- shared/cfg/guest-os/Linux/RHEL/7.3/x86_64.cfg
This introduces a series of checks, initially limited to:
* unattended files (the default root password on kickstart files)
* RHEL configuration files, making sure things such as image names,
ISO files adhere to a standard
The idea is to make sure configuration is predictable, and to increase
the coverage where it makes sense.
---
Changes from v3 (#1109):
* Fix ISO names for RHEL 5.11 (i386) and 6.9 (i386, x86_64 and ppc64) 
Changes from v2 (1062):
* Fix typo (s/withing/within)
Changes from v1 (#1031):
* Added aarch64 coverage
* Rebased
> Selftests: cartesian config lint [v4]

- .travis.yml
- Makefile
- avocado_vt/test.py
- requirements-travis.txt
- scripts/cd_hash.py
- scripts/download_manager.py
- scripts/logging_config.py
- virttest/nfs.py
- virttest/utils_hotplug.py
- virttest/utils_net.py
- virttest/virt_vm.py
The latest version of inspektor won't ignore all E messages and brings other improvements across the board. Fix the problems found by static analysis and update CI scripts to use the latest version.
At the moment, this still needs some testing, as some of the bugs were in some critical places, but not on commonly used code paths.
> Update CI scripts to use inspektor 0.4.5

- virttest/virt_vm.py
MemTotal in /proc/meminfo would display total
usable memory(i.e. physical ram minus a few reserved
bits and the kernel binary code)
So, this method helps to get physical memory as discovered
by system in Kb
Note: Have tried with simpler solution to get
no. of blocks, failed due to the below issue,
so had to choose this little time consuming approach.
E:g:-
```
-bash: /bin/grep: Argument list too long
0
real	3m14.631s
user	2m30.930s
sys	0m53.794s
131072
```
> Added method to get near real guest memory size

- virttest/qemu_devices/qcontainer.py
Added param "serial" for usb devices, so that usb devices can
be identified in the guest.
id: 1482404
> virttest.qbuses: enable "serial" for usb devices

- virttest/utils_test/libvirt.py
When clean up, nfs export dir is forcely removed. But sometimes we do
need keep the export dir. So this is to provide a way to determine if we
want to remove it by the user function.
> utils_test.libvirt: Support to keep nfs export dir

- virttest/utils_misc.py
Add wait_for(is_mounted) to make sure mount info has updated in /etc/mtab already
> Add wait_for for mounted status check

- virttest/utils_misc.py
Utils_misc: add support to get machine types for ppc and s390
Signed-off-by:Aihua Liang<aliang@redhat.com>
Bug id:1487520
> Utils_misc: add support to get machine types for ppc and s390

- virttest/test_setup.py
Return "skip"  when host environmnet does not meet test requirement.
> virttest.test_setup.HugePageConfig:Skip test when host environmnet does not meet test requirement

- shared/cfg/guest-os/Windows.cfg
Due to telnet does not work well on Win10 and Win2016,
switch virtio-win rng cases back to netcat
id: 1438136
> shared.cfg.guest-os: switch virtio-win rng cases back to netcat

- virttest/virsh.py
domrename <domain> <new-name>. This command changes current inactive
domain name to the new name specified in the second argument.
> virttest/virsh.py: Add virsh command "domrename"

- virttest/virsh.py
handle virsh sendkey api options properly for the tests to use appropriately
> virsh: enable sendkey api with respective options

- shared/cfg/base.cfg
- virttest/libvirt_vm.py
This patch enables option to pin hugepage to back Numa using virt-install
and start the guest, unattended_install can be used to boot guest with Numa
pinned with hugepage by setting param "hugepage_pin = "yes" in cfg. But for
using this option guest should have Numa nodes(numa = "yes") and backed
by hugepage(hugepage = "yes")
> libvirt_vm: Enablement to boot guest with Numa nodes pinned with Hugepage

- virttest/virsh.py
nodedev-event <event>. This command list event types,
or wait for node device events to occur.
Signed-off-by: Jingjing Shao <jishao@redhat.com>
> Add virsh command "nodedev-event"

- virttest/utils_test/__init__.py
This patch adds method to run guest tests in background
which should help running from tests like hotplug, migration
etc.
> Add method to run avocado guest tests in background

- virttest/env_process.py
Added guest dmesg verification during postprocess
Config usage:
verify_guest_dmesg = yes(by default)
guest_dmesg_level = 3(by default)
guest_dmesg_ignore = False(by default)
> Added guest dmesg verification during postprocess

- virttest/tests/unattended_install.py
Specifies a installation disk by adding the option "ignoredisk --only-use".
ID: 1489761
> multi_disk_install: specifies a installation disk

- virttest/env_process.py
This patches fixes below issue, caused by wrong usage
of verify_dmesg method of guest
'module' object has no attribute 'verify_dmesg'
Fixes: https://github.com/avocado-framework/avocado-vt/issues/1168
> Fixup: incorrect usage of guest verify_dmesg method

- selftests/unit/test_env_process.py
- virttest/env_process.py
The regex being used can doesn't match with the QEMU versions I've
tried.  Let's update the regex, and test it, to match various QEMU
versions syntax.
---
Changes from v1 (#1167):
* More flexible regex to account for optional "PC" and optional parentheses (say in "Copyright (c)")
* Made the regex available at module level
* Added tests
* Fixed incorrect syntax (`matches.groups[0]`)
> QEMU userspace version logging: attempt to better detect the version [v2]

- virttest/qemu_vm.py
The function _get_pci_bus expects the q35 machine to always have
x3130-upstream available, which might not be True. In that case the
ValueError might be emitted. Let's proceed with `pci.0` in such case.
> virttest.qemu_vm: Avoid failures when no pcic are available

- virttest/qemu_vm.py
This is an update of previous PR https://github.com/avocado-framework/avocado-vt/pull/1144.
In `vm.spice_options` are preserved outdated `params` from previous testcase. This is 
because `vm` instance is not recreated when another test run from job suite is performed.
example:
TC 1 `params`:
> spice_port = no
> spice_port_closed = no
> spice_seamless_migration = on
> spice_secure_channels = 
> spice_ssl = yes
> spice_tls_ciphers = DEFAULT
> spice_tls_port = blabla
qemu-kvm spice cmd:
-spice disable-ticketing,tls-port=blabla,x509-dir=/tmp/spice_x509d,seamless-migration=on
`params` for following TC_2 in the same job:
> spice_addr = 127.0.0.1
> spice_port = generate
> spice_port_closed = no
> spice_seamless_migration = on
(notice `spice_tls_port = blabla` is not in `params`)
qemu-kvm spice …
> Empty vm.spice_options before its another population

- shared/cfg/base.cfg
- virttest/libvirt_vm.py
This patch will enable virt-install to pin guest numa with host numa
using unattended_install if param numa_pin = "yes" is set, it also have
a pre-requisite to have guest numa enabled by setting numa = "yes". The
patch checks if host numa nodes are available online to pin.
> libvirt_vm: Enablement to pin guest numa with host numa

- virttest/utils_test/libvirt.py
This is to add one parameter to make this funtion support other ports
enabled for migration.
> utils_test.libvirt: Enable to specify other ports

- avocado_vt/options.py
Currently when nettype is not set in config it's set according to
provider. For qemu it's always "user". This commit changes the default
(only for qemu) to either "bridge" (when running as root) or "user"
(otherwise). This should give better user experience.
Note the default for spice or other providers hasn't changed, only
slight simplification was made.
@KarMez-Redhat @clebergnu would this work for you?
> avocado_vt: Improve the nettype detection

- virttest/env_process.py
When vm starts and then pauses quickly, it may cause some setup problems
> Fix postprocess bug

- virttest/qemu_devices/qcontainer.py
Device 'virtio_serial_pci' will be hotplugged two times in simple_hotplug function. This error affects the devices which can be catched by 'info qtree'.
id: 1491577
> qcontainer: fix duplicated device hotplug in simple_hotplug

- docs/source/WritingTests/DefiningNewGuests.rst
This fixes a syntax error in foo.cfg example of DefiningNewGuests.rst.
Fixes https://github.com/avocado-framework/avocado-vt/issues/1189
Signed-off-by: Murilo Opsfelder Araujo <muriloo@linux.vnet.ibm.com>
> docs: Fix foo.cfg syntax error in DefiningNewGuests.rst

- virttest/libvirt_xml/devices/input.py
For passthrough input device to guest, we have to specify
its source device.
> Add passthrough input device xml implementation

- shared/cfg/guest-os/Windows.cfg
Due to telnet does not work well on Win10 and Win2016,
switch multi_disk cases to use netcat.
id: 1503414
> shared.cfg.guest-os: switch multi_disk cases to use netcat

- shared/cfg/guest-hw.cfg
- shared/cfg/machines.cfg
- virttest/qemu_devices/qbuses.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
1. qbuses.py: class QPCIEBus: Add individual pcie-root-port for each
virtio device.
2. qcontainer.py: Modify q35 bus type from QPCIBus to QPCIEBus. Use
"pcie-root-port" as default root port type for new qemu version.
3. qemu_vm.py:
_get_pci_bus: Use pcie.0 as default bus instead of "x3130-upstream".
add_pci_controllers: Add "pcie-root-port" to order list. Remove slot
assignment part, which will be unified to qbuses.QPCIEBus.
4. guest-hw.cfg: Remove all q35 related device default bus
specifications, which are unified to qbuses.QPCIEBus.
5. machines.cfg: q35: Remove default pci controller root_port and
pcie_switch, which is not default need in the new topology.
id: 1490226
> virttest.qemu_devices: Add QPCIEBus to extend pcie bus support.

- virttest/qemu_monitor.py
- virttest/virt_vm.py
Recently my CI hanged, because of unfinished qemu processes caused by `dmesg` check without `nic` interface. The first commit fixes the hang, the second commit uses serial console to access the machine when no nics are attached.
> virttest: Two fixes to avoid Avocado hangs

- virttest/libvirt_xml/nodedev_xml.py
Add the function of getting the pci devices addresses
sharing the same iommuGroup.
> Implementation of getting the iommu pci devices address

- virttest/libvirt_vm.py
Add condition to rule out rescue kernel in case to be set as
default kernel when it shoud be debug kernel to be set as default.
> libvirt_vm:rule out rescue kernel when set debug kernel to default

- virttest/env_process.py
- virttest/libvirt_vm.py
For bringing up hugepage backed VM from virt-install, hugepages have to be configured in host. setup_hugepages from env_process can be reused for configuring hugepages in host to avoid redundancy and cleanup issues.
Signed-off-by: Balamuruhan S \<bala24@linux.vnet.ibm.com\>
> utilize setup_hugepages from env_process for hugepage backed vm bringup 

- shared/cfg/guest-os/Windows/Win10/i386.cfg
- shared/cfg/guest-os/Windows/Win10/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2016/x86_64.cfg
Remove cdrom "virtio" and its related params from cfgs under Win10
and Win2016. Reasons as bellow:
1.cdrom "virtio" is defined but no virtio_iso_path given in upstream,
which will cause installation of win10/win2016 fail.
2.i440fx only support 4 ide units. If we install Win10/Win2016 guest
with virtio_iso_path defined manually, 5 ide disks/cdroms will be
created, so start vm failed.
3.no "virtio" defined for other windows' cfgs in upstream, like Win2012,
so i think it's better to keep uniform among windows.
Bug id:1491991
> Fix installation of Win10/Win2016 fail issue 

- shared/scripts/rh_perf_log_guestinfo_script.sh
- shared/scripts/rh_perf_log_hostinfo_script.sh
Add selinux/watchdog/tuning profile/qdisc/coalescing parameters information in system report.
ID: 1502520
> Collect usefull information in system report

- virttest/virt_vm.py
Replace colon with dash to get better compability with different OSes.
> virt_vm: Change session log name pattern

- virttest/bootstrap.py
The provider might not have tests for all known "backends" (generic and
multi_host_migration). In the function bootstrap.create_subtests_cfg,
the info dict does not contain an entry for the backend in this case,
and accessing it without a check results in an exception being raised.
> bootstrap: Check if the provider has tests for the known backends

- virttest/qemu_vm.py
Qemu 2.10 introduced image file locking feature which would cause
the following automation error during migration.
QMPCmdError: QMP command 'cont' failed (arguments: None, error message: {u'class': u'GenericError', u'desc': u'Failed to get "write" lock'})
This patch will fix this problem by not sending `cont` to the
destination before migration started.
> qemu_vm: Fix bug of migration with qemu 2.10

- virttest/libvirt_xml/devices/lease.py
Element include lockspace, key and target.
> Enable lease device xml

- virttest/staging/utils_memory.py
- virttest/test_setup.py
1. Calculation of available hugepages from buddyinfo
is arch dependant(,due to the different page_size),
it was hardcoded for x86, this patch tries to make
it generic by adding getpagesize method.
2. Additionaly powerpc does not have different buddy
regions added support for same.
> Fixup: Available hugepage from buddyinfo for ppc64

- virttest/test_setup.py
The function should fetch the total no.of PF devices in the host, and multiply the same with the VF's to get the total number of VF's.
Multiplying with a fixed number of PF's will error out if there is mismatch in number of
network interfaces.
> Modify check_vfs_count to include the total no.of PF interfaces rather than fixed values.

- virttest/utils_test/libvirt.py
param selinux_status_bak is not initialized for ubuntu and breaks with keyerror
in set_vm_disk() where this param is retrieved as res['selinux_status_bak']
> libvirt: initialize param selinux_status_bak to avoid key error

- virttest/qemu_vm.py
The `pci_devices` test does not work anymore because of multiple changes in pci controllers handing. This PR contains 2 fixes required in virttest in order to be able to make that test to work again. Please see the details in each commit.
> virttest: Two fixes required for pci_devices test to work again

- etc/avocado/conf.d/vt.conf
A while ago we changed the default disk backend to "virtio_scsi", which
is not supported on WinXP (and ancient qemu versions). Let's include a
note in config to help our users.
Addresses comment from https://github.com/avocado-framework/avocado-vt/commit/e010cf166aa67f883ba7b0d2658f425ef4e53c42
> etc: Add note about WinXP not working with virtio_scsi

- shared/cfg/guest-os/Linux.cfg
- shared/cfg/guest-os/Linux/RHEL.cfg
- shared/cfg/guest-os/Linux/RHEL/7.devel/s390x.cfg
- shared/cfg/machines.cfg
- shared/unattended/RHEL-7-devel.ks
- shared/unattended/RHEL-7-series.ks
- virttest/qemu_devices/qcontainer.py
This adds the s390x variant of RHEL.7.devel.
If you are checking this on RHEL 7, note that you need kernel with KVM support enabled and you must use `nettype=user` because of https://bugzilla.redhat.com/show_bug.cgi?id=1505330
Also note that running this test from z/vm guest might result in many timeouts so it's advised to run directly from lpar.
> shared: Add RHEL.7.devel on s390x

- virttest/env_process.py
- virttest/qemu_storage.py
QEMU commit 244a566 introduced the image locking feature which brought
a new option '-U' to the qemu-img command as the result. This patch
adds the support to pass the new option to qemu-img when user needs
to do so.
> qemu_storage: Support '-U' for QemuImg

- virttest/libvirt_xml/devices/interface.py
For hostdev interface, we have to specify the address nested in the source.
> Add hostdev interface xml implementation

- shared/cfg/guest-os/Linux/Fedora/26.aarch64.cfg
- shared/cfg/guest-os/Linux/Fedora/27.aarch64.cfg
This patch adds the AArch64 guest config files for Fedora 26 and 27.
Because Fedora-25.ks still works for this release, we re-use this
kickstart script instead of creating a new one. Both URL and CDROM
unattended installation passed successfully with these config files
on AArch64 machines.
Signed-off-by: Wei Huang <wei@redhat.com>
> Guest OS Support: Add Fedora 26/27 AArch64 guests

- virttest/utils_env.py
On some (buggy?) system when `_start_tcpdump()` is being executed,
the job emits "Could not start tcpdump" and then will stuck at
this point since it is waiting for a file lock held by another
process. This is caused by the wrong result given by the following
check: it returns `None` because time has already expired before
invoking the callback function (btw, we should consider about the
time resolution of `wait_for` when we use it next time).
```python
utils_misc.wait_for(lambda: self._tcpdump.is_alive(),
1.0, 0.1, 0.1)
```
The fix removes `wait_for` from the check because `_tcpdump.is_alive`
is already safe enough.
> utils_env: Fix a stuck issue

- virttest/utils_misc.py
1. Add param "remove_alias", make the opreation optional.
2. Split every line of the output of "qemu_binary -M ?" to three part.
such as:
"pc-i440fx-rhel7.4.0","RHEL 7.4.0 PC (i440FX + PIIX, 1996)","(default)"
As some test only use the seconde part, put the second and the third
part together is unreasonable.
id: 1510738, 1510766
> utils_misc: Improvement of get_support_machine_type

- virttest/libvirt_storage.py
_2:07:40 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-55.0-py2.7.egg/virttest/libvirt_storage.py", line 175, in pool_state
02:07:40 ERROR|     return self.list_pools()[name]['State']
02:07:40 ERROR| KeyError: 'virsh_pool_acl_test'_
-----------------------------------------------------------------------------------------------------------------------
above error occurred while running the test case. 
even though we mention KeyError exception it is not handled because syntax is wrong, when we want to handle multiple exceptions open braces are () mandatory in syntax. 
Signed-off-by: prudhvi <mprudhvi@linux.vnet.ibm.com>
> Fix the 'except' syntax error

- virttest/test_setup.py
The static IP assignment for PF devices for mlx5_core driver is happening after re-probe.
Introduced a function for setting the static IP for the PF devices , which can be referenced before probe and after as well.
> Introduced function for setting static IP for the PF devices of mlx5_core driver.

- virttest/qemu_devices/qcontainer.py
The ICH9-LPC device which is present on q35 machines is named "ICH9-LPC"
and not "ICH9 LPC" which makes the pci_device to fail.
I'm not certain whether the name changed but I tried qemu-2.7.1 with all
q35 machine types as well as qemu-2.10.92 and tried to grep qemu sources
and couldn't get to the point where it was changed so I think changing
it to the current name should work in most cases, but let me know if you
identify really old qemu with the other name so we can add some
heuristic. Anyway I don't think it's necessary as q35 is probably tested
on the later qemu versions so it should be fine.
> virttest: Change the q35's ICH9-LPC device name

- virttest/qemu_vm.py
The valgrind_memalign test requires to boot machine without serial
ports and I believe it might not be the only test. Let's just log
information about no serial ports being available and proceed rather
than failing the test.
Reproducer "avocado run boot --vt-extra-params serials=''"
> virttest: Allow booting guests without serial

- virttest/iscsi.py
iscsi: clear iscsi targetcli configuration on cleanup
"AttributeError: 'NoneType' object has no attribute 'export_flag'" as the
iscsi target configuration is not cleared,
this patch handles it by clearing during cleanup.
This fix also reduces the test execution time for forthcoming cases.
Signed-off-by: prudhvi <mprudhvi@linux.vnet.ibm.com>
> This patch clears the targetcli configuration.

- virttest/utils_net.py
Instead of trusting PATH, let's use a more reliable way to
get the brctl command path.
Signed-off-by: Amador Pahim <apahim@redhat.com>
> utils_net: find brctl command

- virttest/qemu_vm.py
- virttest/utils_misc.py
Using vm_mem_minimum can specify minimum guest memory.
If params["mem"] is provided, it will use this value.
Otherwise, it will use an auto calculated usable mem.
All these two should be within the range between
vm_mem_limit and vm_mem_minimum, if these max and min
values are provided.
id: 1514381
> qemu_vm: update for minimum guest memory

- virttest/libvirt_xml/devices/disk.py
After libvirt commit 37537a7c64b43be2eebf8b0cea7c6d445e214806,
<encryption> and <auth> elements can be put into disk->source xml.
So add them in class DiskSource.
> Add encryption and auth xml in disk source xml

- virttest/qemu_vm.py
During migration, destination vms were not closed if error
occurs and  not_wait_for_migration=False. This patch fixed it.
id: 1510286
> qemu_vm: fixed destination vm process handling issue

- avocado_vt/plugins/vt_bootstrap.py
- shared/cfg/guest-os/Linux/JeOS/27.cfg
- shared/downloads/jeos-27-64.ini
- shared/downloads/jeos-27-aarch64.ini
- shared/downloads/jeos-27-ppc64.ini
- shared/downloads/jeos-27-ppc64le.ini
- shared/downloads/jeos-27-s390x.ini
- shared/unattended/JeOS-25.aarch64.ks
- shared/unattended/JeOS-25.ks
- shared/unattended/JeOS-25.ppc64.ks
This PR improves a bit the old JeOS.25 kickstart to be multi-arch friendly and then adds JeOS.27 (based on the old ks) in all variants. The ks is simplified to only work with `url` installation as users are not expected to usually install it, but they should download it during vt-bootstrap.
As a consequence of multi-arch support the default value of guest-os changed in the last commit to avoid usually unwanted questions to download all variants of this guest-os.
> Add JeOS.27 with multiple architectures

- docs/source/DownloadableImages.rst
- docs/source/Networking.rst
- shared/downloads/jeos-23-64.ini
- shared/downloads/jeos-25-64.ini
- shared/downloads/winutils.ini
We've got a new server, and the asset repo is already there.  Let's
use that new server in the documentation and download definition
files.
> Assets: update location for ISO and other images location

- virttest/qemu_devices/qcontainer.py
When launching VM with scsi devices on some platforms, the following
error would be emitted if param scsi_hba is not set.
```
DeviceError: Failed to insert device:
...
driver = virtio-scsi-pci
...
ParentBus({'aobject': 'pci.0'}): No matching bus
```
The patch fixes this error by setting the default value of param
scsi_hba to virtio-scsi-pci since virtio-scsi-pci does be the
default option of the images_define_by_variables function.
ID: 1515543
> Set default value for param scsi_hba

- virttest/utils_disk.py
- virttest/utils_misc.py
1. Add guest support for mount function in utils_disk
2. Import utils_disk directly in utils_misc for same function, it should be removed, but just keep it for existed import.
id: 1490235
> utils_misc.py: add support for guest disk mount

- virttest/utils_misc.py
get_mem_info api can be used get memory information from /proc/meminfo
based on attribute regex in host/guest
> utils_misc: get_mem_info() api to retrieve meminfo attributes

- shared/cfg/guest-os/Linux/RHEL.cfg
ID: 1528540
The default directory of kernel.img for s390x is different from
that of other platforms, this patch add the additional configurations
to let installation job find the *.img files
Signed-off-by: Zhengtong Liu <zhengtli@redhat.com>
> s390x: modify the directory of kernel.img for s390x

- virttest/libvirt_xml/devices/serial.py
'model' is newly added into 'targe' tag since libvirt 3.10.
So modify code to adapt this change.
Signed-off-by: czhang0 <47047802@qq.com>
> Add 'model' subelement into target for serial element

- virttest/env_process.py
The host/guest dmesg verification should not interrupt the
env_process.postprocess, otherwise the environment can be spoiled and
many processes can be left behind hanging avocado. Let's use the usual
postprocess handling by appending the details about the failure.
@sathnaga @clebergnu @Hao-Liu this issue stuck our CI last week. Can you please review this?
> virttest.env_process: Fix dmesg verification error handling

- shared/cfg/machines.cfg
- virttest/env_process.py
- virttest/test_setup.py
- virttest/utils_test/libvirt.py
This patch address this kernel commit
torvalds/linux@6d6ab94
and make sure prerequisite is set to run
power8(compat mode) guest on current power9 hardware.
disable and enable(restore) smt can be controlled by
two params, power9_compat, restore_smt.
> Fixup: To run compat mode(power8) guest power9 host

- shared/cfg/base.cfg
- virttest/libvirt_vm.py
Add virt-install param support for cpu's suboptions
mode, model, vendor, match.
> Add virt-install param support for cpu sub options

- virttest/env_process.py
- virttest/ip_sniffing.py
- virttest/utils_env.py
- virttest/utils_net.py
- virttest/virt_vm.py
Make the framework support various ip sniffers, and add the support of
tshark (wireshark).
The reason to do so is because tcpdump till now (the current latest
version is 4.9.2) has some problem to deal with the bootp/dhcp packet:
it will not show the 'vendor extensions/options' field when a packet
has the 'sname' or 'file' field, and that would forbid address_cache
being updated properly. So let us use tshark to workaround this issue.
---
Changes from v2 (https://github.com/avocado-framework/avocado-vt/pull/1256):
* Give warning when using tshark with ipv6 env, since it is not supported yet
* Improve accuracy of the detection about unexpected termination of the process
* Fix argument order issue of tshark
Changes from v1 (https://github.com/avocado-framework/avocado-vt/pull/1249):
* …
> Support various ip sniffers [v3]

- virttest/lvsb_base.py
The SandboxCommandBase class now has a name conflict of method
`__set_name__`, it is treated as a special method from python 3.6,
let's rename it and its related methods since they are just
"normal" methods.
Reference:
https://docs.python.org/3/reference/datamodel.html#object.__set_name__
> Fix ci check

- virttest/qemu_vm.py
ID: 1532138
On s390x platform, the name of virtio rng name is virtio-rng-ccw instead
of virtio-rng-pci. this patch fixed the name bug on s390x
Signed-off-by: Zhengtong Liu <zhengtli@redhat.com>
> s390x: fix the virtio rng device name for s390x platform

- virttest/libvirt_storage.py
support locking feature or not. If yes, additional -U suboption
need be added for some subcommands:info, compare, check, bench,
convert, dd, map, snapshot, rebase
> add one method to determine whether current qemu-img command

- docs/source/contributing/ContactInfo.rst
The virt-test-devel does not exist anymore and the irc channel is
dormant.
> docs: Update contact informations

- shared/cfg/machines.cfg
The default gic-version set by qemu is always gicv2, which does not work
on gicv3 machines. Let's use "gic-version=host" by default to at least
match the gic version, but later when "gic-version=max" is supported we
should start using that.
> shared: Always set gic-version on arm64

- virttest/utils_test/__init__.py
transfer_timeout does not have a default value set in
any of global config, so if not set explicitly will
lead to below error, as it got typecasted
to int while accessing.
TypeError: int() argument must be a string or a number, not 'NoneType'
This patch avoids it by setting the default value.
> Fixup: add default transfer_timeout to avoid test failure

- virttest/tests/unattended_install.py
Unattended install uses wget command to download kernel and initrd
files from URL. However in some very strict testing environments wget
is never installed, thus unattend install test fails with an error
log that may be hard to understand this scenario.
This change replaces wget with calls to download#get_file()
from avocado.utils.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
> Stop using wget in unattended install test

- virttest/utils_disk.py
traceback when process fails or required package (psmisc) is not installed,
handle it with package checking and shell=True
> utils_disk: check package and provide shell param for executing fuser

- virttest/libvirt_xml/vm_xml.py
Change in check_feature_name():
readline() only get oneline, not whole output lines, so use
readlines().
> libvirt_xml/vm_xml: use readlines() to get all output lines

- virttest/utils_numeric.py
Add function to align a value to a particular multiples
example: When given '512000' to align with '1024' multiples then
'524288' will be returned.
Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>
> utils_misc: Add function to align values to a particular multiples

- virttest/utils_env.py
Modify params.get['remote_node_address'] to params.get('remote_node_ddress')
TypeError: 'instancemethod' object has no attribute '__getitem__'
Signed-off-by: weikunzz kuwei@redhat.com
> virttest/utils_env.py:params.get('remote_node_address')

- Makefile
When run from the source tree, Avocado-VT's configuration files
must now be linked to a different directory.
While at it, let's also clean up the `vt_joblock.conf` file, which
was missing from the unlink target.
---
**Note**: this change depends on https://github.com/avocado-framework/avocado/pull/2402
> Makefile: adjust to the configuration file path change in Avocado

- virttest/utils_misc.py
Tests uses uptime of the system to validate, like migration uses to
know whether reboot occurred during migration or not.
> utils_misc: get uptime of system/VM

- virttest/virsh.py
when migration is enabled with --postcopy (without --postcopy-after-precopy)
in virsh command line, postcopy logic is enabled but doesn't actually start
to perform postcopy unless migrate-postcopy command is sent from virsh. This
migrate_postcopy() can be used to serve the purpose.
> virsh: migrate_postcopy() API for triggering postcopy migration

- shared/cfg/machines.cfg
- virttest/env_process.py
- virttest/test_setup.py
For Power8 and Power9 (compat mode) host smt have to be turned off and indep_thread_mode have to
be configured as 'N' for guest to boot successfully. This configuration have to be considered for local host
and for remote host (In case of migration).
> configure smt and indep_thread_mode for Power8 and Power9 (compat mode) 

- Makefile
The "etc" config files location in Avocado sources changed recently and
included fix to switch to the new location. This location does not work
for older and LTS releases so let's change the behavior to link all
files to both locations, if "conf.d" directory exists.
> Makefile: Support old and new "etc" location in "make link"

- virttest/ip_sniffing.py
It might happen that the reader thread is faster than the main thread
which sets the "self._process", which then crashes as "self._process" is
not yet set. Let's allow waiting for it for a while.
> virttest.ip_sniffing: Wait for "self._process" to be set

- virttest/ip_sniffing.py
Some packet does not contain sufficient information and it will
cause an `IndexError`, we can ignore such the problematic packet.
ID: 1536309
> ip_sniffing: Fix bug of tshark sniffer

- virttest/utils_misc.py
When run virtio_storage_in_use..data_disk..during_bg_test cases,
will hit a error on re-called disk format module.
The re-format action is no needed on these cases.
Here add disk format status check, if the disk has been formated,
cancel the re-format action.
id: 1511355
> Virttest.utils_misc: add disk format status check

- shared/downloads/jeos-27-x86_64.ini
- virttest/defaults.py
Currently the JeOS.27 works on all archs except x86_64, where it fails to get the file. Let's take this opportunity to use the proper name (based on arch), rather than the "usual" one (manual shortcut).
Also the 27 is long deployed so let's make it the default one, which should give the best experience as 27 is the first multi-arch JeOS we shipped.
> Fix JeOS.27 file location and make it the default version

- virttest/virsh.py
memtune_get() require return one integar. If there is no limit for one
memtune type, "virsh memtune" will output "unlimited", so change return
value to -1 in this case.
Signed-off-by: czhang0 <47047802@qq.com>
> virsh.memtune_get: return -1 if got "unlimited"

- virttest/env_process.py
- virttest/utils_version.py
It enabled using required_kernel and required_qemu to ensure
the test runs only on certain versions.
id: 1519710
Signed-off-by: Haotong Chen hachen@redhat.com
> env_process: added check host component version functionality V2

- virttest/utils_v2v.py
Because uefi guest has no device.map file
Signed-off-by:  Kun Wei kuwei@redhat.com
> Resolve uefi guest fail to check device.map

- shared/cfg/base.cfg
- virttest/env_process.py
Some test could produce additional images to be used by itself, and
these images would be less likely to be used by other tests. Based
on this fact, we can be able to remove test-produced images as the
default operation.
> Remove test-produced images as default

- virttest/utils_test/libvirt.py
when multiple VMs are used for migration, this method can be used for
maintaining temp disk by making the name configurable which is hardcoded
currently, also source_file_list param is enabled and used for setup/cleanup
> utils_test/libvirt.py: enable param source_file_list and disk name configurable

- virttest/utils_test/__init__.py
When autotest_tarball==None and directory_exists(destination_autotest_path)==None,extract(vm, autotest_tarball, destination_autotest_path) will fail as autotest_tarball is none. So modify it.
ID:1483484
> run_autotes: Autotest installation fail when file hash differ but autotest path existing.

- avocado_vt/loader.py
In VirtTestLoader._fill_optional_args(), it is called
"_add_if_not_exist('vt_config', None)" two times.
Removed one of that redundant call.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
> Remove redundant call in VirtTestLoader._fill_optional_args()

- MAINTAINERS
let us update the avocado-vt maintainers list
> MAINTAINERS: update maintainers list

- backends/qemu/cfg/tests-shared.cfg
- shared/cfg/machines.cfg
Currently machine.cfg works after subtests.cfg, which prevents q35
controllers topology redefinition in subtests, so move it upper.
Remove unattended_install..cdrom, unattended_install..extra_cdrom_ks
configuration from machine.cfg, it will not take effect after above
modification. Actually it is not proper to define such parameters
here, it will be moved to unattended_install itself in tp-qemu.
id: 1537394
> tests-shared.cfg: Move machine.cfg prior to subtests.cfg

- virttest/utils_numeric.py
Rename align_factor to align_value
align_value is having a better meaning than align_factor
Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>
> utils_numeric: rename align_factor to align_value

- virttest/utils_disk.py
The handle is closed implicitly when its reference count goes to
zero, eg. when it goes out of scope or the program ends, and we
need a way to force close the handle when it is not out of scope.
ID: 1537363
> utils_disk: add method to explicitly close guestfs handle

- virttest/libvirt_xml/devices/video.py
As now the xml of video devices look like,
`<video>
<model type='qxl' ram='65536' vram='65536' vgamem='16384'/>
</video>`
Change its parent class to UntypedDeviceBase
> virttest.libvirt_xml: Fix the parent class of video class

- virttest/utils_test/libvirt.py
For executing commands during migration of guests, ensure the migration is really started and execute it. supporting APIs are included as part of this patch.
> utils_test/libvirt: API to check migration triggered and vm state

- virttest/libvirt_xml/domcapability_xml.py
domcapability_xml: add two CPU related methods
Since libvirt3.9, libvirt query qemu/kvm to get all supported features
and store them in domcapabilities.
Since libvirt3.9, domcapabilities give the overall features supported
by current host/qemu/kvm via CPU model and a bunch of additional features. CPU
model is one set of features defined by libvirt in '/usr/share/libvirt/cpu_map.xml'
Specific features described in domcapabilities are addtional features, the valid
policy values are 'require' and 'disable', 'require' means the feature can be emulated
by host/qemu/kvm, 'disable' which means feature is disabled by current system due to
host CPU doesn't support or qemu/kvm has no ability to emulate it or some other
reasons like the feature block migration and so on.
Added:
1. …
> domcapability_xml: add two cpu related methods

- virttest/libvirt_xml/devices/interface.py
coalesce is newly added tag, format like below:
```
<interface>
...
<coalesce>
<rx>
<frames max='32'/>
</rx>
</coalesce>
...
</interface>
```
This commit is to add new attribute 'coalesce' to manipulate
coalesce operatation.
> libvirt_xml/devices/interface.py: Add coalesce support

- shared/cfg/base.cfg
HMP is not officially supported except some basic commands,
set QMP instead as default monitor type.
id: 1539557
> shared/cfg/base.cfg: Set qmp as default monitor type

- virttest/libvirt_xml/base.py
As when parent_xpath does not exist, it will raise accessor error during `__eq__`
operation so add exception catch for this error
> Fix del_device accessor error

- docs/source/DownloadableImages.rst
- docs/source/Networking.rst
- shared/downloads/jeos-23-64.ini
- shared/downloads/jeos-25-64.ini
- shared/downloads/jeos-27-aarch64.ini
- shared/downloads/jeos-27-ppc64.ini
- shared/downloads/jeos-27-ppc64le.ini
- shared/downloads/jeos-27-s390x.ini
- shared/downloads/jeos-27-x86_64.ini
- shared/downloads/winutils.ini
HTTPS has been enabled on the avocado-project.org server, so let's use
it by default on docs and when downloading images from it.
> Server infrastructure: switch default URLs to HTTPS

- virttest/libvirt_xml/vm_xml.py
memory attribute is used for allocation of memory for the guest at
boot time, enable this attribute in VMXMLBase
> libvirt_xml/vm_xml: support for memory attribute in VMXMLBase

- avocado_vt/loader.py
The loader accepts optional arguments, let's allow to specify
"vt_extra_params" this way so users can extend the params provided on
cmdline by "--vt-extra-params". This can be used in "--mux-suite" by
setting "test_reference_resolver_extra".
Note if you want to provide the resolver_extra in a yaml file you need
to use !!python/dict tag to make sure you're passing dictionary:
test_reference_resolver_extra: !!python/dict
"avocado_vt_extra_params": ["nettype=bridge"]
> avocado_vt: Allow to extend vt_extra_params from loader

- virttest/utils_package.py
In ubuntu distro, for installation of packages incorrect parameter for automatic
yes causes test to error out.
> utils_package: incorrect parameter for apt-get used to assume "yes"

- virttest/utils_misc.py
As original value for selinux boolean for local and remote
configuration is used in both setup and in clean up it is better
to initialize from __init__
> utils_misc: initialize original value of selinux in init

- virttest/libvirt_xml/devices/interface.py
coalesce is newly added tag, format like below:
``` 
<interface>
...
<coalesce>
<rx>
<frames max='32'/>
</rx>
</coalesce>
...
</interface>
```
This commit is to add new dict xml 'coalesce' to manipulate
coalesce operatation.
Usage:
InterfaceObj.coalesce = {'max':coalesce_value}
> libvirt_xml/devices/interface.py: Use Dict for coalesce support

- shared/cfg/base.cfg
- virttest/env_process.py.orig
Each tests for migration have to perform the presetups before migration
and clean up after test completes, so it is better to handle it in pre/post
process to make more efficient and to reduce redundancy in test code.
> env_process: handle migration presetups in pre/post process

- avocado_vt/loader.py
- virttest/standalone_test.py
The guest name should be independent from machine type. It is not
necessary to list machine type for --vt-list-guests. The machine
type is not like arch, it actually does not matter whether it is
included in the guest name. However, it has to be filtered by
machine.cfg, so remove the suffix after the parser finish its work.
id: 1542862
> VirtTestLoader: Remove machine type for guest_listing and arch_listing

- virttest/vt_console.py
Temporarily introduces some methods to the `ConsoleSession` class
to workaround console-session issues caused by the incorrect usages.
> vt_console: Workaround console-session issues

- selftests/unit/test_installer.py
- selftests/unit/test_utils_misc.py
- virttest/bootstrap.py
- virttest/cartesian_config.py
- virttest/element_tree.py
- virttest/libvirt_storage.py
- virttest/remote_commander/remote_master.py
- virttest/staging/backports/__init__.py
- virttest/staging/backports/simplejson/ordered_dict.py
Python 3 remove iteratable.next() function,and need use
built-in method next() to replace them
> Python 3: Replace iteratable.next() with built-in next()

- virttest/libvirt_vm.py
- virttest/utils_selinux.py
configuring selinux in ubuntu cause unnecessary test errors/fails, it is
better not to configure selinux by default for ubuntu and use selinux_force
param to force it if required.
> selinux: avoid using selinux on ubuntu by default

- virttest/data_dir.py
In ubuntu, apparmor deny libvirt operations from /tmp/* and /var/tmp/*
and causes the tests to error/fail, suggested path is to use
/var/lib/libvirt/images which is open by default.
> data_dir: handle get_tmp_dir for Ubuntu to avoid apparmor denial

- virttest/nfs.py
When mount dir not existing, the error is in cmd's stderr, which is
not captured by current code.
> Fix nfs mount dir check code

- virttest/staging/backports/collections/namedtuple.py
- virttest/staging/backports/simplejson/encoder.py
- virttest/unittest_utils/mock.py
> Python 3: Converts basestring to six.string_types

- virttest/qemu_vm.py
- virttest/utils_misc.py
- virttest/utils_net.py
Set verbose to False to avoid too many lines
of output in debug.log
id: 1555175
> system_output: set verbose to False in some functions

- virttest/virsh.py
We use the vm name "avocado-vt-vm1" with "-"
> Fix the regex incompleteness

- virttest/libvirt_xml/network_xml.py
Using pf as forward device, format like below:
```
<forward ...>
<pf dev='eth0'/>
</forward>
```
Signed-off-by: yafu <yafu@redhat.com>
> Modify parent_path of 'pf' tag to '/forward'

- virttest/ip_sniffing.py
Under concurrency conditions, a `KeyError` would be raised since
the given `HWADDR` (key) record might have been already dropped
in the context of other thread.
We can fix this issue by checking if the given record is in cache
firstly, so that to ensure we will not drop a non-existent record.
ID: 1556771
> ip_sniffing: Fix the issue of dropping cache

- virttest/element_tree.py
- virttest/ppm_utils.py
1. module string could not support replace in Python3
2. lambda could not support tuple in Python3
> Python 3: Fix 2 unsupported issues

- avocado_vt/test.py
The https://github.com/avocado-framework/avocado/commit/d5076fac4891ed886095a27bc884815700224e3c broke Avocado-vt execution, this commit should improve the situation but requires: ~https://github.com/avocado-framework/avocado/pull/2534~ https://github.com/avocado-framework/avocado/pull/2537 to work properly (otherwise it fails earlier in the code-path).
> avocado_vt: Adjust to recent changes in Avocado and little env_save fix

- virttest/qemu_devices/qdevices.py
> Python 3 : fix avoado-vt list issue due to implicit relative import

- virttest/utils_net.py
arping package 2.19-1 doesn't support -f option to quite on first
reply, instead provides -C only wait for count replies, handle it
if help provides support for -C, also the way of output differs
so use appropriate regex.
> utils_net: arping fails with invalid option -f for different package

- virttest/env_process.py
It's possible to use 2 different "vt_types" within a single job, but
"env_process" does not cope with that (it used to be impossible) and
simply proceeds with vm object of different class, when available in
env. This patch adds "isinstance(vm, expected_class)" check that makes
sure we use the right object and refreshes it otherwise.
@clebergnu @apahim this blocks me from using mux-suite (as I'm combining libvirt and qemu executions), would you please take a look at this?
> env_process: Refresh "vm" on "vt_type" change

- shared/deps/serial/VirtIoChannel_guest_send_receive.py
> Python 3: exceptions must derive from BaseException

- virttest/syslog_server.py
I'd prefer adapt the code to python 3 conventions, thus
`import SocketServer as socketserver`
> Python 3: fix SocketServer to socketserver

- virttest/utils_params.py
As IterableUserDict is not supported in Python3, Params inherits
UserDict from collections, whereas it inherits IterableUserDict
from UserDict in Python2.
Due it's different parent class, `get` method need to be override
to catch ParamNotFound error riased by `__getitem__` called by
`get` in Python3.
> Python3: Overriding get() method in Params

- virttest/utils_params.py
> hotfix: super() cannot be used with an old-style class
