- virttest/qemu_storage.py
- virttest/staging/service.py
- virttest/utils_misc.py
- virttest/utils_selinux.py
process.run return bytes instead of text in general case,
need enforcedly call stdout_text if text value needed
> python 3 : fix process.run return bytes instead of text ,but call string interfaces issue

- virttest/utils_net.py
This patch is to fix below error:
ERROR|   File "/root/code-python3/avocado-vt/virttest/env_process.py", line 133, in preprocess_vm
ERROR|     vm = env.create_vm(vm_type, target, name, params, test.bindir)
ERROR|   File "/root/code-python3/avocado-vt/virttest/utils_env.py", line 165, in create_vm
ERROR|     vm = vm_class(name, params, bindir, self.get("address_cache"))
ERROR|   File "/root/code-python3/avocado-vt/virttest/libvirt_vm.py", line 201, in __init__
ERROR|     super(VM, self).__init__(name, params)
ERROR|   File "/root/code-python3/avocado-vt/virttest/virt_vm.py", line 533, in __init__
ERROR|     self.instance)
ERROR|   File "/root/code-python3/avocado-vt/virttest/utils_net.py", line 2931, in __init__
ERROR|     ParamsNet.__init__(self, params, vm_name)
ERROR|   File …
> Python 3: Fix TypeError: list indices must be integers

- virttest/utils_misc.py
- virttest/utils_test/__init__.py
add API update_boot_option_ubuntu() to handle boot configuration as grubby
doesn't work for ubuntu
> utils_test/__init__: update boot configuration for ubuntu

- virttest/libvirt_vm.py
API to get the uptime of vm instance, this would be helpful
in migration testcases where asserting the vm uptime before
and after migration validates whether vm went down/restart
during migration
> libvirt_vm: get uptime of the vm instance

- virttest/libvirt_xml/devices/disk.py
- virttest/utils_test/libvirt.py
alias attribute can be added into disk manually since libvirt
3.9.0
> add alias attribute into disk xml

- virttest/qemu_devices/qcontainer.py
Transfer 'max_ports' to int type when using it
ID: 1563531
> virttest/qemu_devices/qcontainer.py: Transfer 'max_ports' to int type

- virttest/utils_params.py
1. Make Params.get() return string
2. Fix setdefault() raise keyerror in python3 when key is not in dict
without setdefault part fix, below similar 'KeyError' will report.
340 2018-04-02 13:45:00,623 stacktrace       L0047 ERROR|   File "/root/code-python3/p3-ve/lib64/python3.4/collections/__init__.py", line 913, in __getitem__
341 2018-04-02 13:45:00,623 stacktrace       L0047 ERROR|     raise KeyError(key)
342 2018-04-02 13:45:00,623 stacktrace       L0047 ERROR| KeyError: 'queues'
369 2018-04-02 13:45:00,625 stacktrace       L0047 ERROR|   File "/root/code-python3/avocado-vt/virttest/utils_net.py", line 2686, in __init__
370 2018-04-02 13:45:00,625 stacktrace       L0047 ERROR|     nic_params = self.__set_default_params__(nic_name, nic_params)
371 2018-04-02 13:45:00,625 stacktrace …
> Python 3: default to use string and fix Python3 setdefault keyerror

- virttest/qemu_monitor.py
When trigger crash by keyboard, it need to press right ctr key down.
id: 1542783
> qemu_monitor.py: Add press_down_key function for pvpanic case

- virttest/env_process.py
process.system_output() return bytes instead of string on python 3
therefore need to decode() before call any string interfaces
> python 3 : fix bytes call string interface issue

- virttest/test_setup.py
Introduced function to fetch the controller type for SR-IOV Mellanox Adapter PFs.
Depending on the controller type, the output returned can be "Infiniband"/"Ethernet".
> Introduced function to fetch the controller type for SR-IOV Mellanox Adapter PFs.

- shared/cfg/guest-os/Linux/SLES/12.3.s390x.cfg
- shared/unattended/SLES-12.xml
Unfortunately s390x can't boot from "btrfs" partition so adding s390x
variant means changing the default to "xfs", which should work on all
archs.
> shared: Add SLES.12.3.s390x variant

- avocado_vt/test.py
previously use hasattr(stacktrace, "str_unpickable_object") to condition judgement,
but actually can not dertermin whether env.data is really picklale or not
so in python3,it will raise ValueError when calling stacktrace.str_unpickable_object()
> Python 3 : fix pickle issue in __safe_env_savet

- virttest/libvirt_xml/base.py
- virttest/qemu_storage.py
- virttest/staging/service.py
- virttest/utils_libguestfs.py
- virttest/utils_selinux.py
- virttest/utils_v2v.py
- virttest/virsh.py
- virttest/virt_admin.py
,which make it behaves consistently on python 2 and 3
> python 3 force stdout or stderror to be text instead of bytes

- virttest/utils_test/libvirt.py
We will have more and more test scripts designed for multiple arches
with different machine types. One arch can only support several special
machine types. So this is to determine if the case for special machine
type can run on the host.
> utils_test.libvirt: add function to check skip

- virttest/utils_test/__init__.py
- virttest/utils_test/libvirt.py
This change is due to avocado #2543, with which test.tmpdir can't
be public to any user anymore. Since libvirt testing sometimes use
non-creating user to access, so change to use
virttest.data_dir.get_tmp_dir(), which is designed for public user
dedicatedly
> Python 3: Replace test.tmpdir with virttest

- virttest/utils_test/libvirt.py
> utils_test.libvirt: Fix the wrong alias for s390x

- virttest/libvirt_xml/vm_xml.py
When operate topology, we can't use one new CPUXML with topology tag
to update existing cpu element, otherwise other tags in cpu element
will be erased.
> vm_xml: Don't operate non-topology tags when handle topology element

- virttest/compat_52lts.py
- virttest/qemu_vm.py
Improve the default encoding and allow ignoring errors when necessary. (related to pr: https://github.com/avocado-framework/avocado-vt/pull/1515 )
> Lenient encoding

- virttest/element_tree.py
It's to fix the Attribute Error issue when with python3, and
get compatible with python2 at the same time
> Python 3: Minor fix for expat parser

- virttest/element_tree.py
- virttest/ppm_utils.py
- virttest/remote_build.py
- virttest/staging/backports/simplejson/tool.py
- virttest/virsh.py
- virttest/xml_utils.py
Change file open mode without "b" to get it compatible both
py2 and py3. The old way openning file with "rb" & "wb" return bytes
instead of string in Python3, and this will broke tp-libvirt testing
as tp-libvirt use string in most cases.
> Python 3: Force open file with text instead of  "bytes" to make python 2 and 3 compatible

- virttest/utils_env.py
This issue is to fix following issue with Python3, as “Pickling” 
converts a object into a byte stream instead of text
Unable to save environment: write() argument must be str, not bytes
({'version': 1, 'address_cache': {}, 'vm__avocado-vt-vm1':
<virttest.libvirt_vm.VM object at 0x7fa58f432a90>})
> Python 3: Fixup issue unable to save environment

- virttest/utils_test/__init__.py
New gnu tar (1.30 ish) objects to --exclude being passed after the
directory, e.g.
tar -cvzf /dev/null /tmp --exclude=frob
....
tar: The following options were used after any non-optional arguments in archive create or update mode.  These options are positional and affect only arguments that follow them.  Please, rearrange them properly.
tar: --exclude ‘frob’ has no effect
tar: Exiting with failure status due to previous errors
unfortunately we do that in a few places.
Swing the options around to always put the directory at the end.
Signed-off-by: Dr. David Alan Gilbert <dgilbert@redhat.com>
> tar: Swing options around to suit new tar

- virttest/build_helper.py
Line 344 referenced `self.destination_dir`, but init function defined it as `self.destination`. Correct to `self.destination`
base_dest = os.path.dirname(self.destination_dir)
AttributeError: 'RemoteTarHelper' object has no attribute 'destination_dir'
Id: 1572069
> build_helper: Fix AttributeError of RemoteTarHelper.destination_dir

- virttest/remote_commander/messenger.py
- virttest/remote_commander/remote_runner.py
According to https://www.python.org/dev/peps/pep-0008/#imports
> Implicit relative imports should never be used and have been removed in Python 3.
Implicit relative imports have thus been removed here:
https://github.com/avocado-framework/avocado-vt/commit/bc37aa1f2fb6d53253b3a9429f10de13b419ac3e
This causes problems with `vm.commander()`, which copies `"remote_runner.py", "remote_interface.py", "messenger.py"` files to guest vm. There `remote_runner.py` is executed by `remote.remote_commander()` (command `ssh -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=password -p $port $user@$host $path/remote_runner.py agent_base64`). On vm there is no `virttest` package (neither any other package), so import of copied modules fails.
I tested …
> remote: Proper importing on remote host.

- virttest/utils_test/libvirt.py
Disk xml has rawio and sgio attributes, add them.
> Add sgio and rawio attr for disk xml in create_disk_xml method

- virttest/virsh.py
Make necessary change for python 3 base64 usage for libvirt secret
operation.
> Python3: correct base64 encoding usage

- virttest/qemu_vm.py
There are 2 little fixes related to "boot_savevm.default_savevm" test. See the details in commit messages.
> Fix behavior related to "boot_savevm.default_savevm" test

- virttest/qemu_vm.py
After migration the incoming guest might still be in "inmigration" state
for certain period, especially when external command (like gzip_exec) is
used. Let's allow up-to 60s period when we wait for the right status.
This fixes random issues with migrate.with_reboot.exec.gzip_exec test
that after the fe823b6f87b2ebedd692ca480ceb9693439d816e qemu commit
started failing reporting "inmigration" state (which is expected).
> virttest.qemu_vm: Wait for resume after migration

- shared/cfg/base.cfg
- shared/cfg/machines.cfg
- virttest/qemu_devices/qdevices.py
1. Remove pci-bridge from q35 default command line, per qemu bz 1363768 closed as WONTFIX
2. Use qemu-xchi as q35 default usb controller, and plug it into pcie-root-port instead of pcie.0 direct, per qemu bz 1568500 and 1568503
id: 1572437, 1572436
> q35: Update default configurations

- virttest/utils_test/libvirt.py
This is to provide functions for setting up or recovering the libvirtd
configurations on both source and target hosts using specified
parameters.
> utils_test.libvirt: Add libvirtd config customized

- scripts/github/stale_pulls.py
- scripts/regression.py
- scripts/scan_results.py
- selftests/unit/test_utils_net.py
- shared/scripts/ksm_overcommit_guest.py
- shared/scripts/virtio_console_guest.py
- virttest/env_process.py
- virttest/iscsi.py
- virttest/libvirt_vm.py
- virttest/lvm.py
- virttest/postprocess_iozone.py
- virttest/ppm_utils.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_monitor.py
- virttest/qemu_virtio_port.py
- virttest/qemu_vm.py
- virttest/remote.py
- virttest/remote_commander/remote_master.py
- virttest/rss_client.py
- virttest/staging/utils_memory.py
- virttest/storage.py
- virttest/test_setup.py
- virttest/tests/unattended_install.py
- virttest/utils_misc.py
- virttest/utils_numeric.py
- virttest/utils_test/__init__.py
- virttest/utils_test/libvirt.py
- virttest/virt_vm.py
`from __future__ import division` was added into all modules that
use the division operator, so that the / operator to behave the
same in Python 2 as it does in Python 3.
Changed / to //, if the operator should be changed to //.
> Python 3: division fixer

- shared/cfg/base.cfg
- virttest/env_process.py
This patch introduces a new param 'kill_vm_libvirt' to undefine
a libvirt vm during test postprocess given that param is set.
This would be helpful incase of cleaning the env properly for
next test with right set of params(create_vm_libvirt) we can
create a newer vm based on given params for next test.
> Undefine libvirt vm using param during postprocess

- shared/cfg/base.cfg
- virttest/env_process.py
- virttest/storage.py
This patch enables the libvirt vm start in preprocess
without explicit need of `import` test to called
provided `create_vm_libvirt` params is enabled by test.
This feature helps us incase of multi vm boot scenarios
where as framework already gives us support to create/clone images,
just an additional step of create vm is required incase of
libvirt which is available incase of qemu already,
here we are safely assuming import test considering
we have working guest images present.
Signed-off-by: Mallesh Koti <mallesh@linux.vnet.ibm.com>
> Enable libvirt vm start in preprocess

- shared/cfg/guest-os/Linux.cfg
- virttest/utils_test/__init__.py
Reframe VMStress, to remove the autotest dependency, only support stress test, exclude iozone and unixbench part, which should be implemented independently.
id: 1552382
> utils_test: Refactor VMStress to support stress tests and remove autotest dependency

- virttest/qemu_vm.py
There are multiple options for virtio pci device, need use different values for testing. Add a common function to control them.
id: 1542301
> virttest.qemu_vm:Add a common function to control options for virtio pci device

- virttest/qemu_monitor.py
There was a bug when `self.info("block-jobs")` returns `[]`:
Although the `query_block_job` should return `{}`,
it returns `[]` on Python 2.
In later condition check, `if []`is equivalent to `if {}`,
so some cases passed.
However on Python 3, it returns `<fiter object>`, `if <fiter object>`
is qeuivalent to `if True`, which leads to case failures.
> Python 3: fixed a bug related to filter

- virttest/ppm_utils.py
Fix the following decode issue of ppm_utils.
| VM 'avocado-vt-vm1' produced an invalid screendump
| 'utf-8' codec can't decode byte 0xaa in position 6166: invalid start byte
> Python 3: Fix a decode issue of ppm_utils

- virttest/utils_stress.py
This patch introduces a class to generate
different stress events to guest like devices hotplug,
suspend etc, this can further be expanded with other
events and will help incase of multi vm stress tests
> Method to generate stress events to guest

- shared/cfg/base.cfg
- shared/cfg/guest-os/Linux.cfg
Having stress args in base.cfg helps to configure and instrument the
stress args from each testcase granularity, currently it is in Linux.cfg
which overrides the subtests.cfg.
> base.cfg: move stress args from Linux.cfg to base.cfg

- virttest/tests/unattended_install.py
Install balloon/rng/serial/pvpanic/input drivers during guest installation
ID:1566815
> unattended_install: Load balloon/rng/serial/pvpanic/input drivers

- avocado_vt/test.py
- shared/cfg/base.cfg
This patch introduces a param `env_cleanup`, if set
will clear the env from environment, which is needed
while `create_vm_libvirt` and `kill_vm_libvirt` is enbled.
> Add param to cleanup env

- virttest/qemu_vm.py
> hotfix: change iter.next() to next(iter)

- virttest/tests/unattended_install.py
Add a new feature to support configuring extra repos for kickstart
configuration file.
One who wants to configure extra repos is required to:
1. add the content "KVM_TEST_REPOS" into the commands field of
kickstart configuration
2. set the param "kickstart_extra_repos" for the test,
for example:
kickstart_extra_repos = <url1> <url2> ...
And finally, the dummy content will be replaced by:
repo --name=extra_repo1 --baseurl=<url1> ...
repo --name=extra_repo2 --baseurl=<url2> ...
...
ID: 1579082
> unattended_install: To add feature for kickstart cfg

- virttest/tests/unattended_install.py
If unattended file is not a kickstart file, dest_fname would be used
but not declared. So add this patch to fix it.
Signed-off-by: Zheng Xiang <xiang.zheng@linaro.org>
> unattended_install: does nothing if not .ks file

- virttest/qemu_vm.py
Hit error when `qid` is not None:
File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-61.0-py2.7.egg/virttest/qemu_vm.py", line 503, in add_chardev
chardev.set_param("id", devid, dynamic=dynamic)
UnboundLocalError: local variable 'devid' referenced before assignment
id:1581633
> qemu_vm.add_chardev: Correct reference error

- virttest/qemu_installer.py
Add qemu binary entry to support qemu
installer test for powerpc.
> Add qemu binary entry for powerpc

- virttest/utils_package.py
Error get from test:
ShellStatusError: Could not get exit status of command: 'yum install -y omping' (output: u'Loaded plugins: product-id, search-disabled-repos, subscription-manager\nThis system is not registered with an entitlement server. You can use subscription-manager to register.\nResolving Dependencies\n--&gt; Running transaction check\n---&gt; Package omping.x86_64 0:0.0.4-6.el7 will be installed\n--&gt; Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package       Arch          Version              Repository               Size\n================================================================================\nInstalling:\n omping        x86_64        0.0.4-6.el7 …
> Add interval for package install to avoid no exit status issues

- avocado_vt/test.py
- shared/cfg/base.cfg
- virttest/env_process.py
- virttest/test_setup.py
libvirtd debug logs can be enabled by default, tar compress and archieve 
it only on libvirt tests fail or error and it would be deleted on any other
case. This would help not miss the log for debugging or one time occurence
issues. Still user can override it by setting 'enable_libvirtd_debug_log'
param as "no"
> Enable libvirtd debug logs by default for libvirt tests

- virttest/storage.py
- virttest/tests/unattended_install.py
cloning of VM fails if test expects vm image to be available in
nfs share location, so check for vm image bootstrapped in data
directory and copy it.
> storage: copy guest image from data dir to nfs share before cloning

- shared/cfg/guest-os/Linux/Fedora/27.cfg
- shared/cfg/guest-os/Linux/Fedora/28.cfg
I noticed a typo and broken urls for unattended_install.url on Fedora.27 (sorry for that, I shuffled it several times and the last optimization broke it). Also I added Fedora.28. I noticed some odd warnings, but the installation process worked well on x86_64 and the installation began on other arches using TCG as well.
> Add Fedora.28 and fix Fedora.27

- avocado_vt/test.py
At this point the Avocado-vt timeout overrides the Avocado one, which
doesn't look right to me as Avocado timeout is usually generic 14400
value. This PR reorders the timeout initialization so the priorities
are:
1. Avocado timeout (varianter)
2. Avocado-vt timeout (test_timeout)
3. Class default (inherited from Avocado and is None)
> avocado_vt: Allow setting timeout from Avocado params

- virttest/qemu_monitor.py
- virttest/qemu_vm.py
- virttest/virt_vm.py
This supercedes my (2 year old) pull request for postcopy; I've cleaned it up a bit and made sure I've got implementations on more hmp/qmp pairs.
I've kept with the use of exceptions to spot QEMUs that can't do postcopy; it's the easiest way to keep it clean, and also QEMUs errors aren't that clear in the case we need to test, so it's best to keep the code together with teh capabilities code rather than spread the complication around.
I'm using this with my tp changes at: https://github.com/dagrh/tp-qemu/tree/postcopy
> Postcopy testing

- virttest/libvirt_vm.py
Modified to rstrip instead of strip as we need
to keep leading `,` and we need kernel params
to be given in quotes as virt-install cmdline
complains.
> Minor fixes for custom boot params

- shared/cfg/guest-os/Linux/CentOS/7.5.cfg
- shared/cfg/guest-os/Linux/CentOS/7.5/ppc64le.cfg
Add config file to support CentOS 7.5 ppc64le
guest.
> Add guest config file for CentOS 7.5 ppc64le

- virttest/utils_net.py
Avocado process.stdout_text will convert stdout string to unicode,
it has to be converted to string for struct.pack() on Python 2.
In avocado/utils/process.py:
```python
@property
def stdout_text(self):
if hasattr(self.stdout, 'decode'):
return self.stdout.decode(self.encoding)
```
it converts stdout from str to unicode, whereas struct.pack() on Python 2 takes string not unicode.
```
11:43:28 ERROR| Traceback (most recent call last):
11:43:28 ERROR|   File "/usr/lib/python2.7/site-packages/virttest/error_context.py", line 135, in new_fn
11:43:28 ERROR|     return fn(*args, **kwargs)
11:43:28 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/create_macvtap_device.py", line 48, in run
11:43:28 ERROR|     ifname = …
```
> utils_net: fixed a struct bug

- requirements-travis.txt
- requirements.txt
On python3, aexpect always could not get vm's ip address with 1.4.0 and
below version
> Python 3: Update aexpect

- virttest/utils_misc.py
"".join(data) raise "TypeError: sequence item 0:
expected str instance, bytes found"
> utils_misc: Fixup join bytes list in python3

- virttest/remote.py
- virttest/virt_vm.py
This customizes quoting (e.g. shell-escaping) for list of
strings/string and thus enables multiple file transfer.
> remote: Reenable  multiple files transfer

- virttest/utils_test/__init__.py
Currently independent of what users give as download type,
default download_type was been assigned as `tarball`. Incase of
git tree clone, this would fail. This fixes this issue
> Fix the download type for git

- requirements-travis.txt
- requirements.txt
- virttest/qemu_vm.py
The aexpect-1.5.1 has been released so we have a working py3k compatible version. Let's bring back the dependent patches so we can benefit from them.
The fact that py3 aexpect was released means we should not need the: https://github.com/avocado-framework/avocado-vt/pull/1611
> Use aexpect-1.5.1

- virttest/utils_misc.py
openssl in new platform remove private key read permission for other users,
but qemu need access it in TLS enable spice
Fix it by granting read permission to other users
> Fix private key access deny issue in spice graphics

- virttest/qemu_devices/qdevices.py
Current `elif` will never be stepped into, since it is all covered by the first `if` condition.
id: 1589693
> CharDevice.get_supported_options: fix the elif logic error

- setup.py
This prevents manual errors like forgetting to list new packages
when they are introduced.
Currently, this change is equivalent to adding the following packages:
* virttest.staging.backports.collections
* virttest.staging.backports.simplejson
* virttest.utils_windows
Reference: https://github.com/avocado-framework/avocado-vt/pull/1627
> setup.py: use find_packages() instead of manually listing them

- virttest/env_process.py
- virttest/test_setup.py
As the libvirtd is enabled by default to capture debug logs for
all the tests but archive it only for fail/error, it is better to
enable the log level to `info` so as to debug and get close to the
issue as well not polluting the archiving space.
Also back up of the libvirtd config should be done before enabling
and restarting the libvirtd is the right thing to do.
Suggested-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
> env_process: default to log libvirtd info

- selftests/unit/test_qemu_qtree.py
- shared/deps/run_autotest/boottool.py
- virttest/libvirt_xml/domcapability_xml.py
- virttest/libvirt_xml/network_xml.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_devices/utils.py
- virttest/qemu_monitor.py
- virttest/qemu_vm.py
- virttest/staging/backports/simplejson/encoder.py
- virttest/staging/utils_cgroup.py
- virttest/utils_misc.py
- virttest/utils_net.py
- virttest/utils_test/qemu/__init__.py
- virttest/utils_test/qemu/migration.py
More and more we start using "astring.to_text" which frequently produces
"unicode" on python2. The problem is that "unicode" is not instance of
"str", therefor "isinstance(foo, str)" results to false.
Let's address all places where "isinstance(.*, str)" is used by using
"six.string_types" which works well for py2 and py3.
> Use "six.string_types" to check for string

- shared/cfg/base.cfg
- shared/deps/uperf/iperf.xml
- shared/deps/uperf/netperf.xml
- shared/deps/uperf/packet_stream.xml
- virttest/utils_test/__init__.py
1. uperf profiles [netperf,iperf, packetstream] added to avocado-vt deps folder:
Users can add their customized profiles for uperf stress here.
2. Cleaup uperf profile at end of test as part of utils_test/__init__.py
> Add profile cleaup and uperf dependencies

- virttest/utils_test/__init__.py
Currently check_cmd would be assigned with stress_type, which will not hold
good all the time. Example, when we run netperf : stress_type would be netperf
but the actual command running on host would be netstress. This commit fixes
this by assigning check_cmd with actual stress command instead of stress_type.
> Fix stress check command

- shared/cfg/machines.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
1. qcontainer: fix default bus_length of pcie-root-port to 1
2. qdevices.QPCIEBus: define get_free_root_port() for hotplug
3. Add extra root port when boot up vm
4. qemu_vm: add an unified hotplug and unplug, supporting q35
id: 1532521
> Q35: Boot up with extra root port, and hotplug to empty root port instead of pcie.0

- virttest/utils_test/__init__.py
This is minor change in utils_test/__init__.py. Instead of
lists now we use single dict for parsing and replacing
key-value pairs in client stress profile
> Use dict param in prepare_profile

- virttest/libvirt_vm.py
- virttest/utils_misc.py
There are systems with numa nodes where as only memory is present.
e.x. Power9 OpenPower systems with Volta GPU will show GPU memory
as numa node memory with node numbers > 249 where these nodes need
not be used for guest numa pinning etc.,
So lets handle such environments by supplying only
online nodes with both cpu and memory present.
This patch adds a method to get nodes with cpu and
calculates the nodes with both cpu and memory.
> Consider only online nodes with cpu and memory for guest numa

- virttest/libvirt_xml/network_xml.py
Add **dargs to pass non default key-word arguments, such
as readonly.
> network_xml: Update net_create to add **dargs

- virttest/utils_test/libvirt.py
This is to check if specified content exists in the qemu command line.
> utils_test.libvirt: Add check qemu command line func

- shared/cfg/guest-os/Linux/Debian/9.4.0.aarch64.cfg
- shared/downloads/debian-9.4.0-aarch64.ini
- shared/unattended/Debian-9.4.0.arm64.preseed
This patch adds Debian 9.4.0 guest config files for aarch64.
Unattended installation by cdrom passed successfully with this
patch on aarch64 machine.
Signed-off-by: Zheng Xiang <xiang.zheng@linaro.org>
> shared: add Debian-9.4.0 guest for aarch64

- shared/cfg/guest-hw.cfg
- virttest/utils_misc.py
1. Provide API to get the path of qemu-nbd binary for use in tests
2. No need to check the image for case rhe_qemu_iotests
ID: 1582035
> utils_misc: Add support for case rh_qemu_iotests

- virttest/qemu_devices/qcontainer.py
for result from hmp help command, lines starting with tab and parenthesis should not be included in the resulting commands list.
> qcontainer.py: modify regex pattern to exclude tab-starting lines

- virttest/virsh.py
Allow pass "allow_output_check" to process.run as needs of
redirect stdout and stderr into one
> virsh: Update command func

- virttest/utils_misc.py
- virttest/virt_vm.py
reuse get_distro() for vm to retrieve for remote host that can
be used in tests and framework to decide based on distribution.
> utils_misc: extend get_distro to retrieve for remote host

- shared/cfg/base.cfg
- virttest/env_process.py
check for the param that enables sosreport and archive it during the
postprocess of the test.
> env_process: archive sosreport of host/guest/remote host if enabled

- selftests/unit/unittest_data/testcfg.huge/guest-os.cfg
- shared/cfg/guest-os/Linux.cfg
qemu-kvm: -no-kvm-pit-reinjection: warning: deprecated, replaced by
-global kvm-pit.lost_tick_policy=discard
> Fix deprecated param

- virttest/remote.py
commit 0289a17fc53 disabled recursive copy by default caused the
backward compatibility issue.
Suggested-by: Radek Duda <rduda@redhat.com>
> remote: have default recursive scp for backward compatibility

- virttest/qemu_qtree.py
Ovmf add up 2 specific drive without device attached, which will fail check_disk_params since they are not managed in params 'images'.
So skip these 2 drive checking in check_disk_params
ID: 1399929
> qemu_qtree: handle ovmf additional drives in check_disk_params

- docs/source/Experimental.rst
- docs/source/index.rst
- shared/cfg/guest-hw.cfg
- shared/cfg/guest-os/Linux/Fedora/28.cfg
- shared/cfg/machines.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
Hello guys,
yet another interesting architecture is getting more and more attention, let's include it in Avocado-vt to help them testing their bits.
Currently riscv64 support is still very basic. It require `-kernel` to boot and there is no `DVD` to install it from, but despite that we can already run several tests.
> Add support for riscv64

- shared/unattended/Fedora-25.ks
- shared/unattended/JeOS-25.ks
- shared/unattended/RHEL-7-devel.ks
- shared/unattended/RHEL-7-series.ks
The ECHO command is there to workaround issue where /proc/consoles fails
to list the right devices. Anyway as pointed in:
https://bugzilla.redhat.com/show_bug.cgi?id=1351968#c7
it lists the right "major:minor", only the name is wrong. Let's switch
to using "major:minor" until this issue is resolved. (tested on x86,
ppc64le and s390x)
> shared: Fix Fedora/RHEL unattended file ECHO command

- shared/cfg/base.cfg
`libvirtd_debug_level` param overrides from base.cfg to DEBUG level,
let's have the default to INFO level to avoid polluting the archive
space in test debug directory.
Reported-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
> base.cfg: set libvirtd debug log to INFO by default

- virttest/qemu_vm.py
migration parameter have to be configured in source and target VMs before
starting the migration, use monitor API migrate_set_parameter in migrate()
to adopt it from tests.
> qemu_vm: enable migrate() to configure migrate_parameter before migration

- shared/cfg/guest-hw.cfg
- shared/cfg/guest-os/Windows/Win10/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2008/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2012/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2016/x86_64.cfg
- shared/cfg/guest-os/Windows/Win7/x86_64.cfg
- shared/cfg/guest-os/Windows/Win8/x86_64.cfg
- virttest/tests/unattended_install.py
1. Remove params "use_ovmf_autounattend" and also the logic
to get "unattended_file" for ovmf.
2. Define "unattended_file" for ovmf in guest-os.
3. Fix "unattended_file" name mismatch problem for Win2016 guest.
id: 1602780
> guest-os: Define "unattended_file" for ovmf in guest-os

- Makefile
If Avocado is installed in non-standart way (e.g. in virtual
environment), `make link` command fails for two reasons:
1. It does not create symlinks of avocado-vt config files.
2. Sometimes (e.g. while in virtual evironment) setuptools `--user`
is not available.
One could simply define AVOCADO_DIRNAME env variable before `make link`.
> Makefile:  Support arbitrary Avocado location

- shared/cfg/base.cfg
- virttest/qemu_vm.py
Since VM management tool (e.g. libvirt) represents the primary vga
device by using the '-device' expression, it is better to have the
same behaviour for vt tests, so now the command line will be:
> -device VGA_DRIVER,...
Also, add a new param `vga_use_legacy_expression` to let user be
able to fallback using the legacy expression.
ID: 1598410
> qemu_vm: Use '-device' expression for primary vga

- virttest/qemu_vm.py
For python3, `map()` should be replaced by `list(map())`, however here
`devices.insert()` can handle list by itself, not necessary to have map(),
so simply drop it.
id: 1608168
> qemu_vm.add_pci_controllers: Drop unecessary map usage to adapt python3

- Makefile
Python3 systems only often don't contain /bin/python, nor /bin/pip binaries. Let's adjust our Makefile to cope with that.
> Makefile: Few adjustments related to python3 systems

- shared/scripts/virtio_console_guest.py
- virttest/utils_test/__init__.py
- virttest/utils_test/qemu/__init__.py
`filter` and `map` on Python3 returns an object, without iteration
the call back function will not be executed.
id: 1599978
> Python3: fix filter and map related bug

- virttest/utils_package.py
Add object type for session in utils_packages.
After that, while install package by avocado, it will not get type match error.
Signed-off-by: juteman <qiulzhan@redhat.com>
> utils_packages:add object type for session

- virttest/qemu_devices/qcontainer.py
It didn't have any effect if specifying
the cache mode for empty drives.
ID: 1578616
> qcontainer: Drop cache option for empty drives

- virttest/guest_agent.py
base64.b64encode() needs a byte input, while self.cmd() needs args
content being string type, so encode first for b64encode() and
then decode for self.cmd()
id: 1610713
> Python3: guest_agent: Correct password type conversion issue

- virttest/data_dir.py
The 6a78795ddb63a7c39262188893a5b2223edf46dd commit uses apparmor
friendly location for TMPDIR, but on some systems this location might
not be available for certain users. Let's fall-back to default and rely
on users modifying "TMP" environmental value in case
"/var/lib/libvirt/images" is not writable.
Fixes: https://github.com/avocado-framework/avocado-vt/issues/1681
> virttest: Avoid using non-existing TMPDIR on Ubuntu

- virttest/utils_numeric.py
add function 'format_size_human_readable' to format a
number of bytesize to a human readable filesize.
> utils_numeric: add function to format readable size

- virttest/env_process.py
During preprocess/postprocess, when destroy a dead vm,
_cleanup is called, but some of vm's properties are
not initialised.
So it will casue attriute error when calling _cleanup.
This patch checks if vm is alive before invoking vm.destroy.
id: 1611920
> env_process: invoke vm.destroy when vm is alive

- virttest/qemu_vm.py
Arbitrarily raising the number of vnc ports. 1000 guests running simultaneously is a bit harder to achieve than 200.
> qemu_vm: Increase range of vnc ports used

- virttest/utils_test/__init__.py
If it is git/wget file based clone/download proceed, the tool can be
compressed (gzip, XZ etc.,) or might not compressed in file based
download, so handle it appropriately using archive in avocado.utils.
Also allow to use already downloaded tool as fallback or raise if
configuration is not appropriate
> utils_test: extract XZ compressed stress tool

- virttest/libvirt_vm.py
Add support for qemu commandline options to virt-install which
will allow users to add directly qemu commandline options to
libvirt guest xml which helps to test new feature from qemu.
> Add support for virt-install qemu-commandline option

- virttest/utils_test/__init__.py
currently the stress type (stress or stress-ng or etc.,) is common across
all the VMs in multi vm environment. But to have different stress type
for different VM we do not have support. This patch enables it and the params
have to be suffixed with _VMNAME.
Example if we have VM1 name as virt-tests-vm1 and VM2 name as virt-tests-vm2
then the stress params should be like,
stress_args_virt-tests-vm1 = "--vm 2 --io 2 --cpu 2"
stress_args_virt-tests-vm2 = "-io 4 --cpu 3"
> utils_test: support different stress type on different VM

- virttest/virsh.py
domxml-to-native options --domain or --xml have to be provided for
converting existing domain or its xml into native guest configuration
format.
> virsh: domxml-to-native supports xml name or domain name/UUID

- virttest/env_process.py
- virttest/utils_env.py
Python 2's default protocol is 0, whereas Python3.x is 3 or 4
depending on the x.
For VirNet's attribute, if its value is empty string or None,
it will be preserved when protocol is 0 or 1, the rest protocol are not.
So use protocol 0 on both Python3 and 2 to make it compatiable.
Revert "env_process: invoke vm.destroy when vm is alive"
This reverts commit d363a0b.
id: 1611920
> utils_env: set protocol to 0 for pickle.dump

- virttest/libvirt_xml/vm_xml.py
Move 'try-except' into loop to prevent exceptions from breaking
the loop while traversing a list of disks.
> vm_xml: refine logic of check_disk_type

- virttest/remote.py
Since the default LoginGraceTime is 2m in sshd_config file, we need
to provide login_timeout more than 2m, and some designed case like
nic_bonding needs more ssh lantency. enlarge login_timeout to 300s
id: 1283511
> remote: Enlarge login_timeout to 300s

- virttest/storage.py
Right now, in multivm tests user given images for guests
are not entertined rather it overrides to default image name
suffixed with vm name, with this fix users are free provide
their own image name for respective guests in multi vm scenario
This will help us to run multi vm tests with different guest
images.
> Fixup: Don't override user given image for multivm scenario

- virttest/qemu_vm.py
Since aexpect 1.5.1, we have to explicitly pass fd to the destination
qemu process during migration.
> qemu_vm: Fix the bug of passing fd in migration

- shared/scripts/virtio_console_guest.py
1. Use buffering=1 for os.fdopen:
python3.6 does not accept unbuffered text I/O for os.fdopen(), so
use buffering=1 instead
2. Encode text for os.write():
python 3.6 requires a bytes-like object instead of str for write()
id: 1611136
> virtio_console_guest: Fix python3 related issues

- shared/scripts/virtio_console_guest.py
This used to be used by removed "check_zero_sym" test, which used wrong
assumption that this symlink must always exists, but it doesn't have to
be there when other virtio device is present. Let's just rely only on
the "_get_port_status" test which makes sure the number of symlinks
correspondent to number of devices.
Depends on: https://github.com/autotest/tp-qemu/pull/1476
Fixes: https://github.com/avocado-framework/avocado-vt/issues/1736
> shared: Remove check_zero_sym method from virtio_console_guest

- virttest/qemu_devices/qcontainer.py
Current implementation will never take the parameter 'bus',
since the 'if' condition of prepare_hotplug is wrongly indented.
id: 1623789
> qcontainer: fix logic error in simple_hotplug

- virttest/utils_conn.py
From libvirt 3.2.0, the default sasl change from
digest-md5 to gssapi. Although the digest-md5 mechanism
is now considered insecure and should not be used.
In response to manual request, we update framework and scripts
for double sasl machanisms.
> remote_access: Update cases for multiple sasl mechanism

- virttest/libvirt_xml/devices/vsock.py
Add xml for vsock device, such as:
<vsock model='virtio'>
<cid auto='no' address='3'/>
</vsock>
> Add xml for vsock device

- virttest/libvirt_vm.py
- virttest/virt_vm.py
move API to get the uptime of vm instance to virt_vm, this would be
helpful in testcases to assert the vm uptime whether vm went
down/restart during and after test.
without this API caused regression with commit 76c2f8f in tp-qemu
Reported-by: qizhu <qizhu@redhat.com>
> virt_vm: move uptime() of the vm instance from libvirt_vm

- virttest/guest_agent.py
guest_agent: Update shutdown()
Currently, shutdown() returns "{}" or no response after sending the shutdown command,
remove success_resp=False option to raise error message,and remove useless
"return True" and ignore VAgentProtocolErro at the same time.
ID: 1468530, 1476648
Signed-off-by: Xiangchun Fu xfu@redhat.com
> qemu_guest_agent: Update shutdown()

- virttest/staging/utils_memory.py
make use of getpagesize() to use ShellSession object for guest
or remote host.
> utils_memory: make use of getpagesize() for guest

- virttest/env_process.py
- virttest/ppm_utils.py
id: 1544632
1. add function add_timestamp to add timestamp to the bottom of image.
2. using 'add_timestamp' in _take_screendump to enable timestamp of screendump.
>  ppm_utils: add 'add_timestamp' to append timestamp bar to image

- virttest/utils_disk.py
The cmp argument is not supported in 3.x, and a key function
is needed.
In Python 2.7 and Python 3.2 and later we can use a function
'cmp_to_key' to convert a comparison function to a key function.
ID: 1633083
> Fix sort error in Python 3

- shared/cfg/guest-os/Linux.cfg
- shared/cfg/guest-os/Windows.cfg
Since we will drop using ntpdate to get local time in rhel8,
so drop ntp variant as well.
ID: 1629672
> Drop ntp variant use.

- shared/cfg/guest-os/Windows/Win10/i386.cfg
- shared/cfg/guest-os/Windows/Win7/i386.cfg
- shared/cfg/guest-os/Windows/Win8/i386.cfg
Only 2G memory are usable in windows 32bit guests under q35
ID: 1633567
> guest os cfg: Modify windows 32 bit max memory under q35

- avocado_vt/test.py
- shared/cfg/base.cfg
commit 26fdd19 cleanup the libvirtd log if case is not fail
or error, but sometimes it is expected to keep the plain
libvirtd.log in all cases. So make this new param to support it
> Add flag to cleanup libvirtd debug log

- virttest/test_setup.py
This is to make use of two sets of variables which is remote_* and
server_* as they are used in different scenarios. So this is to satisfy
different requirements of usages.
> test_setup: reuse params for remote host info

- virttest/utils_misc.py
if multiple process are with same process name, then a unique
match string in process's cmdline can be used to identify process
instead of process name.
> utils_misc: use pgrep in get_pid() to retrieve pid of process

- virttest/utils_test/__init__.py
When calling `session.cmd()` after called `session.sendline()`,
sometimes the output would be messed up and the test would fail by:
ShellStatusError: Could not get exit status of command: ...
so replace `sendline()` to `cmd()` to fix the issue.
ID: 1637375
> run_autotest: Fix the error of getting command exit status

- virttest/libvirt_xml/devices/controller.py
Implement controller like this:
```
<controller type='pci' index='3' model='pcie-expander-bus'>
<model name='pxb-pcie'/>
<target busNr='254'>
<node>1</node>
</target>
...
</controller>
```
> Add '<node>' tag under the '<forward>' tag

- virttest/nfs.py
nfs-utils package does not provide /usr/lib/systemd/system/nfs.service
any more. So /usr/lib/systemd/system/nfs-server.service is our choice.
> nfs.py: use nfs-server instead of nfs

- virttest/storage.py
> Fix issue: the args "cmp" is rejected in function sorted() on python3

- virttest/libvirt_xml/devices/filterref.py
- virttest/libvirt_xml/devices/interface.py
- virttest/libvirt_xml/devices/librarian.py
- virttest/libvirt_xml/nwfilter_binding.py
This PR is to fix commit d7f91f1, that raised ValueError when assigning value to filterref as
code below:
```
vmxml = vm_xml.VMXML.new_from_dumpxml(vm_name)
iface_xml = vmxml.get_devices('interface')[0]
vmxml.del_device(iface_xml)
iface_xml.source = {'bridge': br_name}
iface_xml.filterref = iface_xml.new_filterref(name=nwfilter)
logging.debug("new interface xml is: %s" % iface_xml)
vmxml.add_device(iface_xml)
vmxml.sync()
File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/libvirt_xml/accessors.py", line 29, in type_check
% (name, expected, is_a_name))
ValueError: Instance of Filterref value is not any of [<class 'interface.Filterref'>], it is a <class 'interface.Filterref'>
```
> Fix filterref ValueError

- shared/cfg/base.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
Example:
```
<configuration>
inputs = mouse1 keyboard1
input_dev_type_mouse1 = mouse
input_dev_type_keyboard1 = keyboard
input_dev_bus_type = virtio
<qemu command line>
-device virtio-mouse-pci,id=input_mouse1,bus=pci.0,addr=0x6 \
-device virtio-keyboard-pci,id=input_keyboard1,bus=pci.0,addr=0x7
```
ID: 1456174
> Support virtio input devices for qemu_vm

- virttest/qemu_monitor.py
Python3 won't call __getinitargs__, instead it uses __reduce__. Let's
use this as backward compatible way to initialize monitor class on both
py2 and py3.
This fixes issue where after test execution Avocado raises tracebacks
like:
Exception ignored in: <bound method Monitor.__del__ of <virttest.qemu_monitor.QMPMonitor object at 0xffffa2425160>>
File "/usr/local/lib/python3.6/site-packages/virttest/qemu_monitor.py", line 227, in __del__
self._close_sock()
File "/usr/local/lib/python3.6/site-packages/virttest/qemu_monitor.py", line 272, in _close_sock
self._socket.shutdown(socket.SHUT_RDWR)
AttributeError: 'QMPMonitor' object has no attribute '_socket'
Exception ignored in: <bound method Monitor.__del__ of <virttest.qemu_monitor.QMPMonitor object at …
> virttest.qemu_monitor: Allow unpickling monitor on py3

- avocado_vt/loader.py
When using "mux-suite-loader" and running "avocado" without
"--vt-extra-params" the "self.vt_extra_params" might not be set at all.
Let's use "getattr" to be able to set the vt-extra-params from
mux-suite-loader.
> avocado_vt: Avoid crash when "--vt-extra-params" not set

- virttest/qemu_devices/qcontainer.py
The purpose of `force_create_image` is to start fresh, usually on
unattended_install tests. So far the AAVMF_VARS was only created once,
but the old state of this file might spoil the results. Let's re-create
it also when `force_create_image` is enabled on the main `image1` image.
> virttest.qemu_devices: Refresh AAVMF_VARS on force_create_image

- virttest/libvirt_xml/vm_xml.py
bootmenu_timeout missing to define in VMOSXML
> Add bootmenu_timeout in VMOSXML

- virttest/utils_v2v.py
For v2v '-o rhv' output, v2v write data to NFS server directly,
so 40min is usually enough, but in some special testing hosts,
if the hosts are plugged in with a telphone line, the transmission
speed will be very slow, 40min may still timeout.
Now v2v implements rhv-upload feature, it copies the data to an
imageio (HTTPS) endpoint, and it usually spends more time. 40 mins
is not enough now.
I tested the value in some different hosts, the time vairies from
20mins to 90min. And developors also said 2 hours is a safe value.
So set the timeout value to 5200s.
> Update v2v cmd running timeout value to 5200

- virttest/utils_misc.py
There is advice to utilize at least 3072 bits to RSA keys.
See [Red Hat documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-hardening_tls_configuration).
> utils_misc: TLS - increase RSA key bit length to 3072 for SPICE connection

- virttest/kernel_interface.py
we have to set or get the values of proc filesystem to configure test
environment in host, remote host or in VM so this patch introduces
getter/setter methods for it.
Example:
>>> obj = ProcFS("/proc/sys/vm/nr_hugepages")
>>> obj.proc_fs_value # To get the value
>>> obj.proc_fs_value = 1 # To set the value
>>> obj2 = SysFS("/sys/kernel/mm/transparent_hugepage/enabled")
>>> obj2.sys_fs_value # To get the value
>>> obj2.sys_fs_value = "madvise" # To set the value
Suggested-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
> kernel_interface: implement set/get APIs for proc/sys filesystem

- virttest/env_process.py
providing entire test dict param for creating remote session using
remote_session() causes conflict, use appropriate dict with remote
machine's credentials.
> env_process: use appropriate param for creating remote session

- virttest/libvirt_vm.py
- virttest/utils_test/libvirt.py
This API can be used to query all the machine types supported by hypervisor
using CapabilityXML() in host or remote host which can be used from tests
and framework.
> utils_test/libvirt: add API `get_machine_types()` to query all machine types

- virttest/utils_misc.py
`NumaInfo()` and `NumaNode()` uses numctl --hardware in their methods,
API breaks if numactl package is not available/installed.
> utils_misc: check for numactl package

- shared/cfg/base.cfg
- virttest/base_installer.py
- virttest/build_helper.py
- virttest/installer.py
- virttest/libvirt_installer.py
The patch implements the build capability for avocado-vt for libvirt sources
from the git repository. The implemention is to get libvirt git repo and make
binaries and build rpms and install as part of the build test.
Signed-off-by: Shivaprasad G Bhat <sbhat@linux.vnet.ibm.com>
> Added support Libvirt package build test

- virttest/qemu_storage.py
In case the qemu-img command fails it's absolutely essential to log the
whole results object in order to have the details about the failure
available.
> virttest.qemu_storage: Log results in case of failure

- shared/cfg/guest-os/Windows/Win2019.cfg
- shared/cfg/guest-os/Windows/Win2019/x86_64.cfg
- shared/unattended/win2019-autounattend.xml
- shared/unattended/win2019-autounattend_ovmf.xml
1. Add win2019 guest-os config file;
2. Add unattended files for win2019.
ID: 1651482
> Add support for windows server 2019

- avocado_vt/test.py
- virttest/env_process.py
id: 1647313
1. always create new screendump no matter VM screen
pauses or not.
2. fix error raising issue.
> env_process: fix screendump timestamp issue

- shared/cfg/guest-os/Linux/Fedora/27.cfg
- shared/cfg/guest-os/Linux/Fedora/28.cfg
- shared/cfg/guest-os/Linux/RHEL/7.5/s390x.cfg
- shared/cfg/guest-os/Linux/RHEL/7.devel/s390x.cfg
- shared/cfg/machines.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
First 3 commits are about VGA support on s390/arm and then there are several fixes to make arm work properly.
Because Avocado does not support adding mouse (it only supports adding usb devices, ...) I solved it by always including mouse in machine definition when VGA is enabled. It's not 100% clean, but it should work for now.
Note: For virtio-gpu-ccw you need at least updated F28, the virtio-gpu-pci should be less picky, but I only got black screen for now (I plan to try it again with later builds, but the machine definition should be fine).
> Add support for VGA on s390/arm and fix some arm workarounds

- virttest/utils_net.py
There is no iteritems method for dict in python3 any more.
> utils_net: Correct dict iteritems in python3

- virttest/test_setup.py
This is to correct the parameter reading method. This is to read
'remote_*' value as default if 'server_*' value is not provided.
> test_setup: Fix wrong parameter value

- shared/cfg/base.cfg
- virttest/env_process.py
- virttest/utils_iptables.py
During guest boot up, dhcp hand shakes happens between guest and
dnsmasq of host via virtual bridge (virbr0) and this is blocked by
firewalld causing failure of guest boot. This patch permits firewalld
to allow dhcp using firewall-cmd as dhcp using raw sockets which is not
going through iptables.
> env_process: firewall blocks dhcp hand shakes for guest

- virttest/utils_net.py
Call ovs_br_exists when ovs init failed, we will meet following error:
2018-01-19 17:08:22,842 stacktrace       L0042 ERROR| Reproduced
traceback from:
/var/tmp/libvirt-ci/runtest/avocado-vt/avocado/avocado/core/test.py:596
2018-01-19 17:08:22,842 stacktrace       L0045 ERROR| Traceback (most
recent call last):
2018-01-19 17:08:22,842 stacktrace       L0045 ERROR|   File
"/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/avocado_vt/test.py",
line 270, in runTest
2018-01-19 17:08:22,842 stacktrace       L0045 ERROR|     raise
self.__status  # pylint: disable=E0702
2018-01-19 17:08:22,842 stacktrace       L0045 ERROR| AttributeError:
'NoneType' object has no attribute 'list_br'
Add ovs None check can help skip this error
> utils_net: Fix issue NoneType object has no attribute list_br

- virttest/libvirt_xml/pool_xml.py
Add 'add_source' manipulation to PoolXML, to fulfil testing scenarios for multiple sources.
> libvirt_storage: add function 'add_source'

- virttest/libvirt_xml/network_xml.py
libvirt_xml/network_xml.py: the netmask attribute is not accepted in
ipv6 ipxml, but it is default in the original file. Add a ipv6 option to
make it complie with ipv6 format.
> Modify the ipxml to compline with ipv4/ipv6 format

- virttest/libvirt_vm.py
When ignore_status=True, test will still be blocked if some
exceptions such as ShellProcessTerminatedError, ShellStatusError
raised. So change the code not to raise exceptions when
ignore_status=True, but just log an error.
> install_package(): Don't raise exception when ignore_status is True

- virttest/qemu_vm.py
Wait for connecting socket server completely by sleeping 1 second.
ID: 1654102
> qemu_vm: Wait for IO channels setting up completely

- virttest/openvswitch.py
1. Change str to int as in python3 str can not compare with int
2. Drop super.init(). Since the parent classes do not define init, so
it calles object.init(), while python3 does not allow pass parameters
to object.init(), it will prompt error: "TypeError: object.init()
takes no parameters". It is unnecessary to call object.init() even
for python2, So drop it.
> [python3]openvswitch: fix errors on python3

- virttest/utils_windows/drive.py
Moved from utils_misc.py.
Define new functions to complete the windows disk extend and shrink.
For disk shrink, need to query maximum shrunk value, then to do shrink.
Define rescan_windows_disk() due to many process need to run these steps.
id: 1411207 1390485
Signed-off-by: Peixiu Hou phou@redhat.com
> utils_windows/drive: Add extend_partition_windows() and shrink_partition_windows()

- virttest/env_process.py
Check for failures in host before test start and
report, so to avoid false test failures after test.
Fixes: https://github.com/avocado-framework/avocado-vt/issues/1808
> Check for failures in host before test start

- shared/cfg/base.cfg
- virttest/env_process.py
The recently introduced firewalld_service actually changes the setting
to work well on Ubuntu.18.10, but in reality it's a bug as firewalld
should not prevent that out of the box. Let's rename it to reflect the
fact of being a workaround and only enable it on that particular host
version (search for nftables firewalld libvirt to get more details).
> virttest: Rename the firewalld_service and disable it by default

- shared/cfg/guest-os/Windows.cfg
Qemu option '-rtc-td-hack' is for early version. Before, it is
deprecated, and recommend use '-rtc driftfix=slew' instead.
Since QEMU-3.1 (fdaf2d5885209634bf9d9f643cec5323efb4525c), it
is removed completely.
id:  1652815
> guest-os: Replace '-rtc-td-hack' with 'driftfix=slew'

- virttest/test_setup.py
Python will check the dict default value before checking the 'get' key.
So it will cause KeyError when the key in default value does not exist,
even though the 'get' key has a value if the way with array is used.
> test_setup: Fix dict keyerror

- virttest/qemu_vm.py
- virttest/utils_misc.py
First commit reuses Avocado implementations of some proces related `virttest.utils_misc`, bringing some fixes and improvements to Avocado-vt's utils and the second commit fixes the issue where forcefully killed qemu process stays alive even when we declared it dead.
This function is only used when qemu refuses to go down. Then when older Avocado is used it adds 10s wait after sending the kill signal. With latest Avocado it really makes sure to wait for all pids to go down.
Note thanks to this PR I noticed the https://github.com/avocado-framework/avocado/pull/2945 is buggy and https://github.com/avocado-framework/avocado/pull/2954 fix is required in order for it to work properly.
> Make sure all qemu processes are destroyed on forceful kill

- virttest/storage.py
When the image already exists qemu-img attempts to get write-lock even
to create it, which fails in case any VM is still using it. Deleting it
first results in the VM using deleted image (until it dies) while
qemu-img happily creating new image in the desired location.
This fixes a real issue where VM from previous test is still running
(either we fail to kill it or keep_between_tests is enabled) and qcow2
image is used with recent-enough qemu and results in:
qemu-img: .../rhel7devel-64.qcow2: Failed to get "write" lock
Is another process using the image?
> virttest.qemu_storage: Remove image on filesystem if exists

- virttest/guest_agent.py
Time duration to wait for response of fsfreeze-freeze cmd is too short.
ID: 1650050
> guest-agent: extend timout for fsfreeze-freeze cmd

- virttest/env_process.py
- virttest/utils_test/libvirt.py
Sometimes 'server_*' parameters may be missing, so we need use "remote_*"
as default.
> libvirt: Fix server_ip missing

- virttest/qemu_storage.py
Updated error msg according to `man qemu-img`:
exit code  1   Check not completed because of internal errors
exit code  2   Check completed, image is corrupted
id: 1654564
> updated qemu-img check error msg

- shared/cfg/base.cfg
- virttest/env_process.py
Guest dmesg log will benefit the analysis of guest dmesg
So just enable it output to console.
> Enable output guest dmesg log

- virttest/qemu_storage.py
1. it supports to get the target_fmt's benchmark sizes by provide a
size as an argument.
2. it can measure a image according to the target_fmt.
id: 1650490
> qemu_storage: added a measure method

- virttest/utils_test/libvirt.py
If no disk type is given, type='None' will be used which will result
vm define failure obviously. Set the default disk type to file if no
vm disk type is specified.
> Give a default value for disk type in set_vm_disk()

- virttest/utils_netperf.py
Sometimes netperf can't guess the correct platform to compile, so
force specify one to compile.
error info: "configure: error: cannot guess build type; you must specify one"
ID: 1663945
> utils_netperf: Specify a platform type to compile netperf

- virttest/utils_test/libvirt.py
Vm name may change after migration if --dname is used. So we also
need to add vm name to vm_ip_dict after migration, or ping_vm()
will fail after migraiton.
> Add vm name to vm_ip_dict in ping_vm() after migration

- virttest/env_process.py
Previously guest_dmesg_log_file=None will bring the value to next loop,
therefore it cause unsupported operand type error
> Fix unsupported operand type for += between 'NoneType' and 'str'

- virttest/utils_misc.py
let `get_qemu_binary()` checks possible qemu binary name
instead of proceeding with `kvm`.
> utils_misc: check for all acceptable qemu binary name

- shared/cfg/guest-os/Linux/Ubuntu/18.10.ppc64le.cfg
- shared/unattended/Ubuntu-18.10-ppc64le.preseed
- virttest/tests/unattended_install.py
- unattended_install: add Ubuntu1810 url variant and its preseed file 
support guest installation of Ubuntu1810 with url method and
unattended file using preseed file.
- unattended_install: allow preseed to be served from builtin http server 
similar to kickstart file, preseed file can also be served to kernel
param during installation by `url=http://localhost:8000/ubuntu.preseed`,
include preseed file to be served from builtin http server.
> unattended_install: support url unattended guest installation for Ubuntu1810 using preseed file

- virttest/utils_netperf.py
Sometimes netperf needs to specify build type (non-x86) during
compilation, add a dict to  correspond to them, otherwise
setting build type equals machine architecture.
ID: 1663945
> Add a dict to correspond to the architecture and netperf build type

- docs/source/DownloadableImages.rst
- docs/source/InstallWinVirtio.rst
This ISO is used for windows testing, it makes sense to add information
where to download it to our docs.
> docs: Add note where to download virtio-win drivers  ISO

- virttest/utils_misc.py
All of those functions are already available since 2014 in
avocado.utils, let's re-use them (even 36 contains them) to share their
improvements and fixes.
This is especially important as I traced down random issue while running migrate jobs to be related to us only checking for localhost+ipv4+tcp port usage while qemu binds to all local interfaces+ipv4+ipv6+tcp which fails in case previous qemu command (or other process) holds this port already, but our find_free_port does not see it. This should be fixed by https://github.com/avocado-framework/avocado/pull/2937 and with this commit here it'd be automatically used once avocado is updated.
> virttest.utils_misc: Use avocado.utils for port functions

- virttest/utils_test/qemu/__init__.py
msinfo32 has some performance issues, so rework windows driver status check function with wmic command and rework device irq check with devcon.exe tool.
ID：1598291
> rework windows driver status check function with wmic command and rework device irq check with devcon.exe tool

- backends/libvirt/cfg/tests.cfg
Here machine_type reset to empty, and override the correct value defined
in machines.cfg, the machine_type value benefit to get correct runtime
guest machine type.
> Enable machine_type get correct value from runtime

- virttest/libvirt_xml/devices/serial.py
Add 'alias' element for 'Serial' device
Signed-off-by: Jing Yan <jiyan@redhat.com>
> Add 'alias' element for 'Serial' device

- virttest/utils_test/qemu/__init__.py
The arguments of logging.warn call on setup_runlevel() are incorrect
formatted, resulting in error:
"TypeError: not enough arguments for format string"
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
> virttest.utils_test: fix logging.warn on setup_runlevel()

- virttest/libvirt_vm.py
When create_serial_console after migration, vm name should be updated
first in case --dname is specified for migration.
> Update vm name first when create_serial_console after migration

- virttest/tests/unattended_install.py
Make image_dir always be created before being used.
ID: 1667362
> unattended_install: To create image_dir before being used

- virttest/utils_netperf.py
The fix includes two parts:
1) Don't print verbose message of tar
2) Redirect the output of configure and make to /dev/null
This fix sloves the "Could not get exit status of command" problem
when compling netperf package.
> Don't print output when compling the netperf package

- virttest/tests/unattended_install.py
An issue was introduced by https://github.com/avocado-framework/avocado-vt/pull/1927 which cause windows guests failed to be installed successfully.
```
ERROR: [Errno 2] No such file or directory: ''
```
That because windows guests do not have a valid `kernel` set, so let's revert the previous approach and use the first one I sent.
Signed-off-by: Xu Han xuhan@redhat.com
ID: 1668237
> unattended_install.nfs: To create image_dir before being used

- virttest/utils_net.py
Sometimes there are not only directories in `/sys/class/net`. For example, when we `modprobe bonding`, a file named `bonding_masters` will be created in this directory. Make it get the interface directory correctly.
ID: 1638680
> utils_net: Fix `get_structure` doesn't get the interface dir correctly

- virttest/libvirt_vm.py
For quite a while the "machine_type" can optionally include avocado-vt
machine type, which is used for example on arm to use either mmio or pci
devices. This was not implemented in libvirt provider and was hidden
until 7d37e0a07e5e803b7a64490032baf2063feab72c which actually enabled
machine_type selection there. Since then all arm jobs are being skipped
because it's machine_type is "arm64-pci:virt".
Let's adjust the "machine_type" assessment to reflect the optional
values.
> virttest.libvirt_vm: Fix machine_type assessment

- virttest/qemu_devices/qcontainer.py
We use "live" qemu instance to query for supported QMP/human-monitor
commands, but the machine is not given any image. On most architectures
this only results to busy loop and unnecessary utilization for a short
period of time, but other architectures (like s390x) actually finishes
as soon as it finds no bootable image, which sometimes is before it
reports the commands. Let's use the '-S' to start in stopped state.
> virttests.qemu_devices: Stop VM to query for hmp/qmp commands

- virttest/utils_hotplug.py
Hotplug xml will have node tag by default, due to which the test
fails to hotplug on non numa systems. Patch will not add node tag
for non numa systems.
Signed-off-by: Hariharan T.S <hari@linux.vnet.ibm.com>
> Ignore numa node for non-numa systems

- shared/cfg/machines.cfg
- virttest/qemu_devices/qcontainer.py
I made two changes:
- change machine's bus type to pcie
- remove virtio-mmio-bus. 
While virt machine type on aarch64 always creates some virtio-mmio buses for connecting on-board devices, I don't think they are useful in tests on 'arm64-pci' configuration. So I remove it. Please correct me if I'm wrong.
I verified the patch with a few tests and it worked fine in my experiments.
> qcontainer: fix arm64-pci machine bus type

- docs/source/Experimental.rst
- docs/source/RunningInEmulationTCG.rst
- docs/source/index.rst
Running emulation especially on different architectures is fairly simple
with Avocado-vt, but not many people use it. It is increasingly
necessary especially with people from other architectures contributing
arch-dependent patches to Avocado-vt so let's provide a guide for people
to simplify cross-platform testing.
> docs: Add documentation on how to use TCG with Avocado-vt

- virttest/libvirt_vm.py
- virttest/utils_misc.py
- virttest/virt_vm.py
In migration tests, verify_dmesg can be used to check the guest
after migration where connect uri would be changed. API should
ensure to hold the `vm.connect_uri` in the test flow when it is
used multiple times, this fix resume the original connect_uri
once verifying dmesg.
utils_misc: let verify_dmesg() return bool if `ignore_result=True`
If ignore_result=True, let verify_dmesg() return bool, True if no
errors/crash and False otherwise which would help proceed the test
based on the return value.
> virt_vm: make sure libvirt connect uri doesn't break the test

- virttest/qemu_monitor.py
The qmp monitor log is re-used by all vms of the same name similarly to
serial-console logs. This is important mainly for migration jobs, where
multiple instances are re-created and therefor the log file get's
re-created. The append mode makes sure we keep all the records.
You can see the difference eg. when using `migrate.default.tcp.default`. Without this patch the `qmpmonitor1-avocado-vt-vm1.log` contains only the qmp logs of the last dst vm while with this patch it contains all of them.
> virttest.qemu_monitor: Use append mode for qmp monitor log

- virttest/utils_v2v.py
This v2v_timeout argument is used to limit v2v cmd running too long.
But it always cause v2v process be killed unexpected. You can check
below script running log[1].
In the log, v2v cmd starts at 14:39 and be killed at 16:09, and v2v
convertion is almost done(94.37/100%) but it's killed unexpected.
We have to debug those failed scripts every time, it waste our energy.
Now let's extend the timeout value and let CI to break the job when
the job really timeout.
1)https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/v2v/view/RHEL-8.0/job/v2v-RHEL-8.0-runtest-x86_64-acceptance-libvirt/65/testReport/rhel/convert_vm_to_libvirt/esx_vm_5_5_linux_latest6_arch_i386
> Extend v2v cmd running time

- virttest/utils_test/libvirt.py
'none' is default for disk cache. This PR is to give a choice to not add
'cache' to disk drive for some tests with special purpose.
> utils_test.libvirt: support to disable disk cache

- virttest/libvirt_vm.py
qemu commandline can be multiple strings with spaces
so let's wrap it with quotes.
> Fixup: Wrap qemu commandline within quotes

- virttest/ppm_utils.py
- virttest/step_editor.py
We encounter invalid bytes opening a steps file in character mode
so this fixes our issue but is not python 2 compatible.
Any contribution on how to preserve py2 compatibility is of course welcome.
> Handle bytes rather than strings in the ppm utils

- virttest/env_process.py
Json read of the version info file fails sometimes when we
have version string with spaces, and causes below failure,
net.sf.json.JSONException: Unquotted string 'u'3.1.50 (v2.8.0-rc0-17028-g3e78ecb378-dirty)''
let's type cast to string to avoid such cases.
> Fixup: type cast version info values to string

- virttest/qemu_vm.py
Nic hotplugging does not share simple_hotplug usage, here directly
get free root port for QPCIEBus and add it as option 'bus' to the
hotplug command
id: 1658131
> qemu_vm: add pcie support for hotplug_nic

- shared/cfg/guest-hw.cfg
Since base.cfg defined usb1 as ich9-usb-ehci1 controller by default,
while usb2 defined another ich9-usb-ehci1 controller install_ehci,
usbc_by_variables() allocate a fixed address '1d.7' for ich9-usb-ehci1
which causes the address conflit when there are 2 ehci controller.
Considering:
1. There should be only 1 echi controller exists
2. If keep drive format 'usb2' by replace 'usbs += ' with 'usbs =', it
will remove all the other type usb controllers which is not expeceted
3. We usally don't test usb2 as a drive format. Instead of introducing
sepecial conditional processing in current code, we prefer to removing
this variants
id: 1676764
> guest-hw: Remove variants usb2 from drive format

- shared/cfg/base.cfg
- virttest/arch.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
1. The cmd line: -device vhost-vsock-pci,id=vhost-vsock0,guest-cid=3
2. guest-cid is between '3' and '0xffffffff - 1'(unsigned 32-bit
integer. 0-2 and 0xffffffff are reserved)
3. It is a virtio device so should be a pcie device
id: 1665845
> qemu_vm: add vsock device

- virttest/tests/unattended_install.py
Force to replace the drive letter which loaded the
virtio driver by the specified letter.
ID: 1628043
> unattended_install: Replace virtio driver disk letter

- virttest/qemu_storage.py
'check_image' will backup image only if these two conditions are met:
1. check_image pass('img_check_failed' is null)
2. 'backup_image = yes'
In such conditions, image will be backed up during postprocess too.
so, remove the 'backup_image' step in 'check_image'.
id: 1683557
> qemu_storage: remove duplicate 'backup_image' step in 'check_image'

- shared/cfg/base.cfg
- virttest/env_process.py
- virttest/storage.py
Using a `save_image_{image_tag}_on_error` param to save any specified
image under JOB-{job_id}-TEST-{case_num}-{image_name} naming convention.
If use `save_image_on_error = yes`, it will save all the images in
the `params["images"]`, image created outside `params["images"]`
will not be saved.
You can choose which image to save, by adding an image tag.
`save_image_{image_tag}_on_error`, eg: `save_image_image1_on_error`.
Refactor backup image for code reuse and efficiency.
id: 1543282
> Add a backup error image function if the test case is not pass

- virttest/utils_test/libvirt.py
Once there some blank space before the output of domiflist, the match
will fail.
> Fix the issue in get_interface_details

- virttest/utils_time.py
1. python2 don't support "re.A"
2. only for python3, "re.A" is used for ASCII-only matching instead of full Unicode matching. We need to match non-ASCII letters here if it have (such as Chinese character)
id: 1677189
> utils_time: remove "re.A" which is not supported by python2

- virttest/qemu_vm.py
- virttest/utils_vsock.py
This is for same steps when hot plugging vsock devices, instead of
limiting it inside qemu command generation phase
id: 1671211
> utils_vsock: Abstract vsock related functions

- virttest/qemu_vm.py
Now we have many migration statuses other than `*active`, so we
could not make the judgment of a finished migration by verifying
the migration status is not `*active`. Hence, we should let it
return `True` only if the current status is in certain ones which
are `none`, `completed`, `failed` and `cancelled`.
ID: 1679860
> qemu_vm: Correct the check in `VM.mig_finished()`

- virttest/qemu_devices/qdevices.py
The former method has trouble to check Dimms with similar id, e.g.
"dimm-mem1" and "dimm-mem11", causing verify failure. Fix it by
checking the id in the dict other than string.
ID: 1688108
> qdevices: update verify_hotplug and verify_unplug for Dimm

- virttest/test_setup.py
The first commit adds "drop_caches" before allocating hugepages, which is pretty useful on lowish-mem systems. The other 2 commits are just little fixes.
> virttest.test_setup: Drop caches before allocating hugepages and some fixes

- shared/cfg/guest-os/Linux/RHEL.cfg
id: 1671630 
set mem lower bound as 2G for installation cases excluding RHEL5 and
RHEL6 guests, so tests with mem less than 2G will be canceled due to
inefficient mem.
tests affected:
"unattended_install"
"check_block_size.4096_512"
"check_block_size.512_512"
"svirt_install"
"with_installation"
> set mem lower bound for installation excluding RHEL5&6 guests

- avocado_vt/test.py
- virttest/error_event.py
id: 1219379
This patch introduces a global error message queue to replace previous
VirtTest.background_errors. This assists some asynchronous tasks that
have no reference to VirtTest object to error the test. This mechanism
is only for internal use inside avocado-vt.
> virttest.error_event: a global error event bus

- shared/cfg/guest-os/Linux/RHEL/8.cfg
- shared/cfg/guest-os/Linux/RHEL/8/8.devel.cfg
- shared/unattended/RHEL-8-devel.ks
This patch adds RHEL.8 variant for following aritectures: x86_64,
ppc64le, aarch64 and s390x. It contains RHEL-8 kickstart file as
well.
Signed-off-by: Radek Duda rduda@redhat.com
> shared: Add RHEL.8 variant

- virttest/utils_net.py
id: 1688577
In some cases, we need to get all the interfaces in a dedicated
bridge. Add a param 'br' to list_iface.
Signed-off-by: Xiyue Wang <xiywang@redhat.com>
> utils_net: add bridge name as a param for list_iface func

- requirements-travis.txt
The updated inspektor contains fixes for the extra lines printed in the
output and the hardcoded pylint versions should avoid new types of fixes
we are not yet ready for (using the same versions as Avocado)
> requirements-travis: Use updated inspektor

- shared/cfg/base.cfg
- virttest/libvirt_vm.py
Add cputune param support for virt-install, which would
help us to define guest cputune configuration during guest
install/import itself.
> Add cputune support for virt-install

- virttest/utils_stress.py
_*Commit 1:*_
**Fixup: validate stress events param before split**
stress events param string is split to convert as list and
when stress events are given as empty string, it does create
list entry with empty string and leads to thread exception, like
below
[stderr]   File "..../virttest/utils_stress.py", line 165, in vm_stress_events
[stderr]   File "..../virttest/utils_stress.py", line 165, in vm_stress_events
[stderr]   File "..../virttest/utils_stress.py", line 190, in host_stress_event
[stderr]     raise NotImplementedError
[stderr]     raise NotImplementedError
[stderr]     raise NotImplementedError
[stderr] NotImplementedError
[stderr] NotImplementedError
[stderr] NotImplementedError
and let's fix it by validating the stress events param before split.
_*Commit 2:*_
**Introduce …
> Fixup: utils_stress

- virttest/utils_test/libvirt.py
it's common to take a string as an expected error message. So here
allow this kind of usage
Signed-off-by: Jin Li <jil@redhat.com>
> allow libvirt.check_result to take a string as expected error message

- virttest/arch.py
- virttest/utils_net.py
A little of testcases need to modify promiscuous mode or mtu size on
the interface, I think they should be supported by Interface(), so add 
them.
> utils_net: Add methods to get/set promisc mode and mtu size

- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
1.  qemu_vm: add parent_bus for vsock pci device
It will not have bus automatically, so no address being issued,
therefor will hit error when add extra pcie-root-port for pcie bus
2.  qdevices: add missed comma in pcie_devices list
Miss a ',' after "vhost-vsock-pci", which will lead all components
after it be treated as pcie device, be plugged into pcie.0 directly
id: 1694901
> vsock: Correct parent bus issue

- virttest/remote.py
- virttest/utils_v2v.py
1) Handle interactive operation with VMware Vcenter to lauch 'Bash'
2) Autoset vddk_libdir and vddk_thumbprint if not set by user
3) Use user's value of vddk_libdir and vddk_thumbprint if set
4) Autoclean mount records after v2v command finishes
> Support -it vddk for virt-v2v

- virttest/utils_test/__init__.py
Packet loss ratio may not be an integer, modify the return format of
`get_loss_ratio()` to handle it.
ID: 1696100
> utils_test: fix the return format of `get_loss_ratio()`

- virttest/ceph.py
Ceph.py: need to create /ceph dir before creating ceph.conf in it
Signed-off-by: meinaLi <meili@redhat.com>
> Ceph.py: need to create /ceph dir before creating ceph.conf in it

- virttest/utils_hotplug.py
On newer version of libvirt, there is no ':' in vcpupin output
anymore, but old versions keep this separator.
> utils_hotplug:Update separator when parsing output of vcpupin

- virttest/env_process.py
LINE 1050 is repeated since base_dir is assigned in LINE 778.
> env_process.preprocess: remove repeated base_dir definition

- virttest/virt_vm.py
In some cases the file is open just fine but the serial console
prints no output. Not being able to find kernel panic or other
messages in an empty output should be equivalent to good output
or otherwise this will spawn lots of warnings throughout the run.
For instance, a recent check for these warnings for our runs got:
grep -r "Unable to read serial" * |wc -l
-> 9774
Empty output is not the same as no output.
> Log warning for unreadable serial console in case of IOError

- virttest/utils_misc.py
If not required, a empty dict could be passed. So set the default
value to be a empty dict for easier usage.
> Give a default value for get_qemu_version

- virttest/qemu_devices/qcontainer.py
the header string should be "Buses of" instead of "Devices of".
> DevContainer.str_bus_long: wrong header string

- shared/cfg/guest-os/Linux/SLES.cfg
SLES.11 doesn't support virtio1.0, make it use legacy mode.
id: 1704547
> SLES: Make SLES.11 use legacy virtio

- shared/cfg/base.cfg
- virttest/qemu_vm.py
- virttest/virt_vm.py
id: 1219379
1. virt_vm.VMUnexpectedExitError to represent vm's unexpected exit
status error.
2. qemu_vm.qemu_proc_term_handler, will be used as callback function
to aexpect.Tail to monitor QEMU non-zero exit.
3. new param "monitor_exit_status", with value either "on" or "off",
"on" to enable pushing an instance of `VMExitStatusError` to global
error event bus.
> monitor qemu process non-zero exit

- virttest/utils_misc.py
- virttest/virt_vm.py
In migration scenarios, VM will be in target host and APIs try
to access them to get uptime, sosreport, cpu count etc., for which
framework should use `wait_for_serial_login()` with virsh uri to
target host, else tests/framework errors with `Login timeout expired`
as it tries to connect to VM in local host where it wouldn't be
running/available. This patch refactor the code using decorator to
abstract handling session/uri for libvirt tests.
> virt_vm: use decorator to handle session/uri for libvirt tests

- shared/unattended/RHEL-7-devel.ks
- shared/unattended/RHEL-7-series.ks
- shared/unattended/RHEL-8-devel.ks
Installation fails to start by prompting for text/graphical
input during unattended install test, use text mode in kickstart
file for the test for proceed.
> RHEL.ks: use text mode in kickstart for unattended install

- virttest/utils_stress.py
Emulator pin does not depend on vcpu number, and it
has to be assigned once per Guest VM, let's fix it.
> Fixup: Emulatorpin does not need to iterate for vcpus

- shared/cfg/base.cfg
- virttest/tests/unattended_install.py
`reboot` parameter in kickstart file supposed to restart the VM on
successful post installation without prompt, but instead VM shutsoff
and test fails. This bug is reported, but for our test to proceed
have a workaround with the param set `kickstart_reboot_bug = "yes"`
Bug-id: RH1663430
> unattended_install: `reboot` parameter in kickstart file doesn't work

- backends/v2v/cfg/convert_source.cfg
- virttest/remote.py
- virttest/utils_v2v.py
Support convertion vmware guest by esx:// with vddk
Example:
virt-v2v -ic esx://root@xxx/?no_verify=1 -it vddk xxx
> Support VMX uri with vddk

- virttest/utils_test/__init__.py
This patch introduces config params to make further tunable
the guest background avocado-misc tests, inorder to control
it from testcase rather than just defaulting.
Recently started seeing the reinstall of avocado framework crashes
while test invoke, to be rootcasued though but we should be able
to workaround by disabling reinstall.
This will help us address if any such workarounds and issues.
> Make avocado guest background test tuneable from testcase

- virttest/virt_vm.py
Let's use serial login for dmesg check during postprocess
if set by user.
> Fixup: Use serial login for dmesg check if set by user

- virttest/utils_netperf.py
We might miss the catching of netserver processes, that because we only
do a one-shot check immediately after the process being launched. Now
let's make the check not too harsh.
ID: 1296804
> utils_netperf: Wait a few seconds for running up netserver

- virttest/qemu_vm.py
To find port sequentially is in order to know of the number
of running guests on the host, so it could help us to debug some issues,
such as checking whether the environment of the host was pure, there are not
others non-automation guests were running at that time if the host was released.
ID: 1712230
> qemu_vm: Find port sequentially

- virttest/utils_net.py
Test can cause timeout `process.getoutput()` for `arping_cmd` and
framework tries to kill it with signal.SIGKILL and switches on
TestWarn. Instead wait till the `arping_cmd` completes to finish
the test gracefully.
Issue-Id: https://github.com/avocado-framework/avocado-vt/issues/2089
Reported-by: Yanan Fu <yfu@redhat.com>
Suggested-by: Yanan Fu <yfu@redhat.com>
> utils_net: `arping_cmd` can timeout causing TestWarn

- virttest/utils_test/libvirt.py
`create_macvtap_vmxml()` creates xml object for macvtap interface
which is used to perform attach/detach operation to VM.
> utils_test/libvirt: add API to create macvtap xml for VM

- virttest/qemu_vm.py
Currently we require full-match on s390x machine type, but it is
possible to use different machine types requiring the same hacks (eg.
s390-ccw-virtio-2.6). Let's use startwith.
> virttest.qemu_vm: Support VGA on non-default s390x machine_type

- virttest/env_process.py
- virttest/nfs.py
- virttest/utils_test/libvirt.py
Ubuntu doesn't support firewalld, so avoid using firewall-cmd and
configure/install firewalld to prevent test/framework to break
in ubuntu
> Avoid configure firewalld in ubuntu

- virttest/qemu_devices/qcontainer.py
Some test suites are using android-x86 machines for testing functionality related to Android devices.
More details on the issue can be found here:
https://bugs.launchpad.net/qemu/+bug/1778350?comments=all
> Add a fix for android (x86) devices on recent (2.10+) qemu

- virttest/libvirt_vm.py
Fixes below issue.
ERROR|     cpus = vcpus // numa_nodes
ERROR| TypeError: unsupported operand type(s) for //: 'str' and 'int'
> Fixup: unsupported operand type for vcpus

- virttest/libvirt_xml/vm_xml.py
From libvirt, state of `nested-hv` attribute need to be set 'on' to
launch qemu commandline with `cap-nested-hv=on` for VM (L1) to use kvm_hv
in L0 and to support nested virtualized VM (L2) on it.
> libvirt_xml/vm_xml: `nested-hv` feature xml attribute for pseries VM

- virttest/virsh.py
The option '--post-copy' should be specified to migrate-getspeed command
for a postcopy migration. This is a new option from libvirt 5.0.1.
> virsh: add extra option to migrate_getspeed

- virttest/utils_stress.py
Let's allow different combinations of stress events and parameters
for each VM incase of multiple VMs with different configurations,
instead of processing the params globally, let's handle it inside
VM threads so that we can allow them.
> Handle different combinations of stress events and parameters per VM

- virttest/libvirt_xml/vm_xml.py
Add boolean param allow_dup for add_device function in vm_xml.py,
since there are cases need test multi devices, some are same or
similar. And default value set to False, will not affect existing calls in
other files.
> vm_xml.py: add param to support allow dup

- virttest/openvswitch.py
- virttest/qemu_vm.py
- virttest/utils_net.py
The current method sometimes cannot delete all ports of guest
accurately. Such as openvswitch backend, ovs takes some time to process
ports to be deleted. So we should not check the port status via 'ip
link'(get_net_if), we need to check if it exists in the bridge to decide
whether to delete it.
ID: 1701815
> qemu_vm: Delete all guest ports correctly when destroying guest

- virttest/utils_misc.py
- virttest/utils_test/__init__.py
add support to run `avocado-vt` inside guest that can be used to
bringup nested guests from tests.
> utils_test: Nested virtualization support for Avocado-VT

- virttest/libvirt_vm.py
Add numa distance support for virt-install
so that numa distance can be configured duing
installtion/starting of guest.
> Add numa distance support for virt-install

- virttest/utils_netperf.py
resource release should be called explicitly instead of relying on the
garbage collection of python interpreter's implementation.
> virttest.utils_netperf: remove __del__

- virttest/tests/unattended_install.py
Some OSes (JeOS) don't have unattended file associated and attempt to
open "None" crashes. Let's not apply the workaround in such case.
While on it also correctly open/close the unattended_file via with.
> unattended_install: Avoid crash on missing unattended file

- virttest/utils_disk.py
For virtual_disks tests, there is a function to check if the disk
partition in vm works well in individual .py files. It's a common
function and should be moved to avocado-vt. So add it to utils_disk.
> utils_disk: Add a method to check basic disk function in guest

- virttest/env_process.py
vm.verify_dmesg() method in postprocess was catching only
test fail exception and rest it slipped through the postprocess
try block, resulting in tests not executing rest of postprocess
steps like cleaning up the VMs in environment, leaving further
tests to fail, this patch address it by adding vm.verify_dmesg()
under try block that covers all exceptions.
> Fixup: Avoid skipping postprocess due to failure in verify_dmesg

- avocado_vt/loader.py
Recently Avocado dropped the deprecated DEFAULT/AVAILABLE/ALL variables,
let's add the compatibility bits to Avocado-vt to allow running with
old-ish Avocado as well as with master.
Fixes: https://github.com/avocado-framework/avocado/issues/3163
> avocado_vt: Get loader mode from DiscoverMode

- virttest/utils_time.py
For serial session, there may be other logs except for cmd output.
bug id: 1694040
> utils_time: modify timezone_pattern

- virttest/storage.py
The "minimum_disk_free" will always be a float, which doesn't allow such
optimization. Let's avoid it at all as it is not critical, nor executed
frequently (and does not work...)
> virttest.storage: Avoid using bitshift on float

- virttest/libvirt_version.py
- virttest/utils_misc.py
There is no /usr/share/libvirt/cpu_map.xml file existing on RHEL8，
but instead of this file with /usr/share/libvirt/cpu_map directory.
If a test which calls the get_model_features() is runned on RHEL8,
an FileNotFoundError will be thrown resulting in making this test
failed.
Signed-off-by: Yanghang Liu <yanghliu@redhat.com>
>   Fix the FileNotFoundError of get_model_features()

- virttest/libvirt_xml/vm_xml.py
In some scenarios, we would hit below issue due to vmcpu_xml
is not initialized in proper place, this patch tries to fix it.
UnboundLocalError: local variable 'vmcpu_xml' referenced before assignment
Reported-by: Junxiang Li <junli@redhat.com>
> Fixup: Improper initialization of vmcpu_xml

- virttest/qemu_vm.py
> qemu_vm: Deprecate option vectors for single queue

- virttest/qemu_vm.py
'state' is not always None when initialize class VM, especially
when the test case is in non-first place of the test run. The list
will be superimposed in one loop since the parameter 'state' will
record it and reuse previous list. So need to empty it before
fill it again
> qemu_vm.py: Empty self.virtio_ports before fill it

- virttest/utils_misc.py
Since the partition index is uncertain, such as GPT label that
will add a reserved partition automatically or some partitions
are existed, so get its index after creating a partition.
> utils_misc: Update the codes of format_windows_disk

- virttest/libvirt_version.py
It is needed by some cross migration tests or other tests which have
different libvirt version on multiple hosts.
> Enhance libvirt_version.py to check libvirt version on remote

- virttest/utils_misc.py
- virttest/utils_windows/drive.py
Sometimes, the cdrom is identified delay in guest,
that caused get the cdrom drive letter will fail sometimes.
Add get cdrom drive letter function to wait_for function,
that will try getting letter cycle in 240 secs.
If getted, return the value. if not, return None.
id: 1685924
> drive/utils_misc: Update get drive id in wait_for function

- virttest/iscsi.py
When a user gives wrong image_size value, test continues and
fails in future point with misleading error.
This patch would rectify this issue and notify user with right error.
> Error out on invalid image size value

- virttest/kernel_interface.py
Sys and proc interface can return value that may not be
type casted to int type, so return as string on receiving
`ValueError`.
> kernel_interface: handle invalid literal for int()

- virttest/utils_test/__init__.py
provide option to install extra packages inside guest and
use quotes to handle if multiple params are passed in the
avocado commandline.
> utils_test: option to install packages for avocado inside VM

- virttest/nfs.py
- virttest/utils_misc.py
nfs: add support to configure nfs on remote host/VM
perform nfs configurations in remote machines and mount it
in test machines with `setup_remote_nfs` set, this patch
adds support to it.
utils_misc: refactor safe_rmdir() to support remote host/vm
add safe_rmdir() to handle remote session to make use of it by virttest/nfs
package to perform setup_remote_nfs to configure nfs on remote host/guest
and mount it in test machines. add check_isdir() to verify whether a path
is directory or not in remote/VM.
> nfs: add support to configure nfs on remote host/VM

- virttest/utils_misc.py
Add support for three cpu models: Icelake-Server, Icelake-Client,
and Cascadelake-Server.
ID: 1727212
> utils_misc: add support for three cpu models

- virttest/utils_iptables.py
Perform operations to add/remove/get direct rule using firewall-cmd.
This is required by some migration cases.
> utils_iptables: support to add/remove/get direct rule

- shared/cfg/base.cfg
- virttest/qemu_vm.py
For some cases, e.g., timer device, -S needs to be removed in
qemu.
bug id: 1694657
> virttest.qemu_vm: add a qemu_stop param for -S

- virttest/guest_agent.py
Add function of guest-get-fsinfo and guet-get-osinfo.
ID: 1557247
> virttest.guest_agent: Add function of guest-get fsinfo and osinfo

- virttest/env_process.py
- virttest/staging/service.py
- virttest/utils_iptables.py
perform operations to start/stop/restart/status of services in remote
machines/VMs with new class if session is not provided it fall back to
Factory() in localhost, remove Firewalld() from utils_iptables as
this Service() can be used instead.
> staging.service: Add `class Service()` to handle services in remote

- virttest/libvirt_xml/devices/librarian.py
- virttest/libvirt_xml/devices/tpm.py
tpm.py is used to create tpm device xml, for testing tpm function
in tp-libvirt. Also modify librarian.py to permit use.
> tpm.py: For create tpm dev xml

- virttest/qemu_monitor.py
Some cases boot vm for not only one time but with same 'vm.name',
if we use 'log_file = "%s-%s.log" % (name, vm.name)", two different
processes will use same file name to save monitor log, and the log
for the first one will be overwritten by the second one.
So, add pid to the log file name to save all of the log.
id: 1685134
> qemu_monitor: add pid of vm to the monitor log file name

- virttest/nfs.py
It is safe to have ssh_auto_recover as False, during env cleanup
of multiple setups in remote host, with default as True may cleanup
ssh obj and cause forthcoming remote cleanup to error out.
> nfs: set ssh_auto_recover as False by default in nfs cleanup

- virttest/utils_misc.py
It is suggested in class ConnectionBase() not to make auto_recover
to be True,
```
We suggest *not* to pass auto_recover=True to __init__(),
and call conn_recover() manually when you don't need this
connection any more.
```
so let's adopt it and clean it up in proper way.
Reported-by: Junxiang Li <junli@redhat.com>
> utils_misc: default the auto_recover to be False in cleanup()

- selftests/unit/test_utils_params.py
- virttest/utils_params.py
This includes custom key checking, list and dictionary parameter
retrieval, advanced object parameter manipulation, etc.
The only additional change other than pure copying from our downstream
code was done in order to adapt to object method access rather than module
function one:
index 40b21f63..b61e5864 100644
@@ -139,21 +139,21 @@ class Params(IterableUserDict):
:returns: empty dict if if the key is not in the parameters, a dict
or an ordered dictionary if the item order is important
:rtype: {str: str}
This uses :py:meth:`get_list` to convert the list entries to dict.
"""
if need_order:
result = OrderedDict()
else:
result = dict()
-        for entry in get_list(self, key, default, delimiter):
+        for entry in self.get_list(key, default, delimiter):
index = entry.find('=')
if index …
> Add various parameter manipulation functionality to the param utils

- avocado_vt/options.py
- avocado_vt/plugins/vt.py
Certain variants are filtered early in tests.cfg that can only be
executed via vt-config. Let's add an "expert" mode where this file is
not parsed and only minimal set of filters is applied.
Note some backend require additional variables and filters, so this
option should only be used after careful evaluation. On the other hand
it allows to perform hugepages, gluster, OVMF or other kinds of
variants usually available only in vt-config world.
> avocado_vt: Allow to run variants filtered by tests.cfg

- virttest/utils_test/__init__.py
Let's validate the session object before attempt
to close it to avoid below issue
```
File "/root/smfci/tests/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/avocado_guest.py", line 35, in run
ignore_result=False)
File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/virttest/utils_test/__init__.py", line 942, in __init__
if not self.env_check():
File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-70.0-py2.7.egg/virttest/utils_test/__init__.py", line 871, in manage_session
self.session.close()
AttributeError: 'NoneType' object has no attribute 'close'
```
> Fixup: Validate session before close

- virttest/env_process.py
It is meaningless to backup image when test fail, so restrict it
id: 1683557
> env_process: backup image in postprocess only if test pass

- shared/deps/finish/finish.bat
- virttest/tests/unattended_install.py
Sometimes, we would install windows updates for our guests, and these
updates may require a reboot to accomplish themselves.
In order to achieve this requirement, add an optional step to perform
the operation (by setting the string `-AccomplishWinUpdates` as the
third argument of `finish.bat`.)
ID: 1601309
> finish.bat: Add optional step to accomplish windows updates

- selftests/unit/test_utils_params.py
- virttest/utils_params.py
We allow the user more flexibility when it comes to white spaces
and overall Cartesian configuration formatting.
> Increase the flexibility of parameter type converting methods

- shared/cfg/base.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
Fix issue: https://github.com/avocado-framework/avocado-vt/commit/9c82ef693d6a7d5f7835b04d76505f945731fd11#commitcomment-34427735
> qemu_vm: Name serial by index if there is prefix defined

- virttest/qemu_monitor.py
- virttest/qemu_vm.py
In order to support various qemu versions, let's always try using "x-"
or non "x-" variant of the migration capability.
> virttest.qemu_monitor: Automatic fallback to "x-" mig capability

- selftests/unit/unittest_data/testcfg.huge/base.cfg
- selftests/unit/unittest_data/testcfg.huge/subtests.cfg
- shared/cfg/base.cfg
- virttest/qemu_vm.py
1. Use 'query-cpus-fast' instead of 'query-cpus' for new qemu build (
beginning with 2.12.0)
2. qemu_vm: Add a method `get_vcpus_info()` to get vcpus info
3. Deprecate 'vcpu_thread_pattern'
ID: 1731777
> get_vcpu_pids: Modify method of getting vcpus info from monitor

- shared/cfg/guest-hw.cfg
Enable hugepage param in respective hugepages
config section so that it get's honored by filter
while using `only hugepages` for libvirt tests.
> set hugepage param in respective config section

- virttest/utils_test/__init__.py
The value of 'timeout' in RemoteVMManager.setup_ssh_auth is not
used. Fix the hard-code issue and update the default value to 20s
which works for many cases for now.
> utils_test: timeout was hardcoded

- virttest/env_process.py
- virttest/staging/utils_memory.py
- virttest/test_setup.py
1. Add a function to get total surplus hugepages.
2. Add a param to set number of overcommit hugepages, and we can test it in the future.
3. Handle existing surplus hugepages, make `self.target_hugepages` correct.
4. Tracking existing huge page before and after testing
ID: 1701853
> test_setup and env_process: Track and handle host surplus hugepage

- shared/cfg/base.cfg
- virttest/env_process.py
During multivm tests, there might be scenarios where we
need to reset/tweak few parameters on master  disk image
before we start using that to clone disks for usage with vms.
This commit introduces params "sysprep_required" &
"sysprep_options", using which users can provide required customization
to prepare master disk image, like "truncating machine-id" or any other
tweaks supported by virt-sysprep tool, followed by cloning process.
Usecase example: Recent distros not only depend on the unique mac
address to determine IP but also the machine-id. If the cloned images
have same machine-id, then all cloned guests end up getting same IP.
Using this commit user can reset machine-id in the master disk image so that
multivms using cloned disks would get unique ip addresses later.
Signed-off-by: …
>  Add sysprep option before cloning master image

- virttest/env_process.py
- virttest/libvirt_vm.py
- virttest/storage.py
- virttest/tests/unattended_install.py
changing the param during runtime affects the test from different
places, avoid changing the param `image_name` for vm.create() to
use nfs mounted path. Instead make use of `images_base_dir` param
to provide nfs mounted path as base path for VM to be created.
Also remove copying VM image from data_dir to nfs mounted path
from multiple places and call it from vm.create() in libvirt_vm
to avoid redundant code and simpicity.
> env_process: avoid changing the param `image_name` for nfs

- virttest/env_process.py
- virttest/storage.py
In MultiVM environment, every VM can have different master image
to support different OS distributions and this patch provide option
for it.
Param `master_image_name_<VM name>` can be used to clone VM specific
master image and param `image_name_<VM name>` can be used to provide
name of the cloned image for VM to use.
> storage: allow VM specific master image to be cloned

- shared/cfg/guest-os/Linux/Fedora/28.cfg
- shared/cfg/guest-os/Linux/RHEL.cfg
- shared/cfg/guest-os/Linux/RHEL/8.cfg
- virttest/tests/unattended_install.py
Most distribution generate some ".log" files during installation that
are essential to debug installation failures. Let's attempt to get them
from the most common locations and attach them in
test.outputdir/vm.name. It only works on running VM as those location
are not usually stored on the destination disk.
Currently the list is based on Fedora/RHEL (/tmp/*.log) and few other
locations were added to cover the most common locations. Feel free to
add other locations, it should simply ignore missing locations (or other
failures while obtaining the files)
> unattended_install: Attempt to log useful files in case of failure

- virttest/utils_test/libvirt.py
This method performs a way to check log file on local and remote.
> libvirt: add check_logfile to check if log file contains specific string

- virttest/libvirt_remote.py
This is required by migration cases.
Need to update libvirt related configuration files on remote.
> Add libvirt_remote.py to manage libvirt on remote

- virttest/test_setup.py
In different kernel, the network interface will be unpredictable
changed, wen can use shell command to get the network interface
name
id:1692233
> test_setup: support shell command for param "physical_nic"

- virttest/utils_conn.py
It reports 'id_rsa already exists' error while generating key pairs.
Update to check the key on client host before run ssh-keygen to make
sure it checked correct host.
> minor fix for id_rsa already exists issue

- virttest/utils_net.py
In different kernel, the network interface will be unpredictable
changed, wen can use shell command to get the network interface
name for param netdst_nic
id: 1692276
> utils_net: support shell command for param netdst_nic

- virttest/qemu_capabilities.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_monitor.py
- virttest/qemu_vm.py
qdevices: New classes to support blockdev options
1. New a class QBlockdevNode to represent the "-blockdev" qemu object.
2. New classes to represent the type of format blockdev node.
2.1 QBlockdevFormatNode represents the format blockdev node.
2.2 QBlockdevFormatQcow2 represents the format qcow2 blockdev node.
2.3 QBlockdevFormatRaw represents the format raw blockdev node.
2.4 QBlockdevFormatLuks represents the format lusk blockdev node.
3. New classes to represent the type of protocol blockdev node.
3.1 QBlockdevProtocol represents the protocol blockdev node.
3.2 QBlockdevProtocolFile represents the protocol file blockdev node.
3.3 QBlockdevProtocolNullCo represents the protocol null-co blockdev
node.
3.4 QBlockdevProtocolHostDevice represents the protocol host_device
blockdev node.
3.5 …
> blockdev: Support blockdev

- virttest/utils_hotplug.py
1. Adding missing checking point, not only for config, but also live
2. When not current vcpu in xml, set it to max
It also related to https://github.com/autotest/tp-libvirt/pull/1345
> Fix vcpu issues after refactor from tp-libvirt

- avocado_vt/loader.py
- avocado_vt/options.py
- avocado_vt/plugins/vt_bootstrap.py
- avocado_vt/plugins/vt_joblock.py
Avocado with nrunner uses dict instead of argparse.Namespace object for
args. Let's "downgrade" the dict to argparce.Namespace as a hotfix,
before all places are tackled and we could switch to the dict-like
access.
This is a hotfix that should be easier to review than the original https://github.com/avocado-framework/avocado-vt/pull/2194 but it should not replace the need for the proper fix (update vs. downgrade)
> avocado_vt: Add compatibility with nrunner Avocado

- virttest/utils_misc.py
Add labletype parameter for format_windows_disk() to support
formatting disk with specified lable type.
id: 1566836
> utils_misc: add labletype parameter for format_windows_disk()

- virttest/env_process.py
from commit 281e7990, vm_params is used for cloning image to
support multiple images on multiple vms, but clone_image()
updates image_name_* in vm_params but not in global params.
This fix gives backward compatibility to use vm clone with
or without vm specific `master_image_name` and `image_name`.
Reported-by: Srikanth Aithal <sraithal@linux.vnet.ibm.com>
> env_process: update params image_name keys with vm_params

- virttest/openvswitch.py
- virttest/qemu_vm.py
- virttest/utils_net.py
The current code can delete the ovs port correctly, but for linux bridge
backend, qemu will delete all guest ports after it quit, so sometimes
_cleanup() will delete a port which has been deleted.
ID: 1701815
> Fix delete port problem on linux bridge backend

- virttest/qemu_monitor.py
input_send_key_event() is used to send keys on keyboard from qemu monitor.
input_send_btn_event() is used to send button on mouse from qemu monitor.
id: 1735508
> virttest: Add input_send_key/btn_event funcs in qemu_monitor.py

- virttest/qemu_devices/qcontainer.py
The newly introduced cache_map 7a685934dda4d0de05e3aec31ea330384d5eb816 only works with valid values or None, but
these params are often specified in cart config and might result in
empty string instead of None. Even we set it to "" on line 2018 in
cdroms_define_by_params in case of aio == threads.
Instead of fixing our value let's treat any empty string the same as
None as users might want to get the default from cart config.
> virttest.qemu_devices: Allow cache='' in images definition

- virttest/storage.py
Currently after backup/restore of any image would leave .backup file behind.
This would have been done to reuse backup when next time there is a call for
backup function, but there can be scenarios where user would like to remove
backup once original image is restored.
This commit introduces an option to allow users to remove backup images
by providing a flag.
> Introduce option to remove backup files

- virttest/utils_v2v.py
The problem is 5 times tring for getting driver info, but only did once and then script exit.
2019-07-14 01:56:00,248 utils_v2v        L0777 DEBUG| 5 times remaining for getting driver info
2019-07-14 01:56:00,248 client           L1126 DEBUG| Sending command: DRIVERQUERY /SI
2019-07-14 01:57:00,309 utils_v2v        L0781 ERROR| Timeout expired while waiting for shell command to complete: 'DRIVERQUERY /SI'    (output: '')
2019-07-14 01:57:00,309 client           L1126 DEBUG| Sending command: cls
2019-07-14 01:58:00,689 ovirt            L0319 INFO | Shutdown VM esx6.7-win10-x86_64LhT
Fix:
Move the self.session.cmd('cls') to into try..except clause, because when it
also raise an exception, the uncaught exception will break the while loop.
> Fix trying failed problem in get_driver_info

- virttest/qemu_vm.py
- virttest/utils_net.py
1. automatically specify bus and addr for hot plugged nic device
2. drop the default vector because it is meaningless
3. vectors are added only when there are multiqueue during hotplug
ID: 1512424 1736784
> Specify bus/addr and fix vector issue during hotplug nic device

- shared/cfg/base.cfg
- virttest/env_process.py
Sometimes libvirt refuses to undefine VM properly even
`kill_vm_libvirt` is set due to issue in managed-save etc.,
So, let's use user defined param, `kill_vm_libvirt_opions`
to give additional undefine params, it is bydefault set to
clear if any managed state file, but it can be customized many
other usecases, like remove storage, clear snanpshot metadata.
> Make sure postprocess cleans up libvirt VM properly

- virttest/utils_net.py
Got a wrong mac addr `52:54:00:be:e1` by invoking `BaseVM.add_nic`,
that is because there is `0x00` in the high order octets of the addr
and the `_int_to_int_list` method would give a wrong result to that.
Making this patch to fix the issue.
Fix: https://github.com/avocado-framework/avocado-vt/issues/2209
> utils_net: Fix the mac generator issue

- virttest/env_process.py
commit 501b0e78 introduced option to use virt-sysprep in order to customize
the master image before cloning for multivm usecase. This was essential for
addressing usecases where cloned disk images had same keys [ex. machine-id], which
led to duplicate IPv4 address issues. But virt-sysprep can be used to do more
customization as well. So there is a need to backup master image and restore it
back at end of test case, so the further testcases which do not require those
customization can use restored original disk image.
> Backup and restore master image used for sysprep

- virttest/libvirt_xml/vm_xml.py
Guests with nvram will fail with "ERROR: Failed to undefine " since
the --nvram flag is only added for the aarch platform. Instead, add the
--nvram for any guest with nvram.
Signed-off-by: John Allen john.allen@amd.com
> libvirt_xml/vm_xml: Add --nvram flag for guests with nvram

- virttest/env_process.py
- virttest/utils_test/__init__.py
This patch enables existing tests to be run on nested VMs to
multilevels, is supports N * N * N VMs where multiple guests
can be brought up and nested with multilevel and multiple VMs
on every level. The params can be set to the granularity of any
particular VM on any level.
The point here is to dynamically calculate and distribute memory to
higher level VMs based on the available memory in current level
VM/host. It is not neccesary but it is required for VMs to run
test seamlessly on positive scenarios, still negative scenarios
can be tested by overriding the param to perform this distribution.
We handle the test across all the VMs at all the Levels in linear
way as parallelism from here will not have control on the test
flow but configuring different testcases on different VMs at any …
> env_process: add nested virtualization support to run tests in nested VMs

- virttest/qemu_vm.py
During "make_create_command" the VM object is re-created with the new
params, which might affect the "self._caps" value, therefor we have to
use the new VM's _caps in this function.
This fixes a real issue where first test uses >2.12 qemu and second test
uses <2.12 qemu. In this case _caps are inherited from previous params,
therefor it attempts to use -blockdev.
> virttest.qemu_vm: Get _caps of the updated VM

- shared/cfg/base.cfg
- virttest/env_process.py
This patch enables the gcov code coverage report
generation as part of test postprocess if suitable
params are enabled and prerequisite as mentioned in
base.cfg are satisfied.
This would be helpful in case of code debugging and new
test scenarios development.
> Generate gcov code coverage report for qemu in postprocess

- virttest/utils_selinux.py
Currently there are only methods to get and set the context of the
given file. There are usecases to check for specific labels in the
context of the file. This commit introduces new method to do the same.
> New api to read and check specific label in context of the given file

- virttest/utils_net.py
Update to return valid value for this funtion
id:1743446
> utils_net.py: fix return command prompt in "get_netkvm_param_value"

- shared/cfg/base.cfg
- virttest/env_process.py
Add support for user defined vm information for both
qemu and libvirt tests from vm monitor during the test
in regular intervals, this comes handy while debugging.
> Add support for user defined vm info collection

- shared/cfg/base.cfg
- virttest/libvirt_vm.py
- virttest/utils_net.py
Let's add support for virt-queues during guest boot
in virt-install commandline, queues and net_driver
params to be set accordingly in-order to use this support.
> virttest.libvirt_vm: Add support for virtqueues while guest boot

- avocado_vt/test.py
Avocado recently made the file_handler attribute private, and
Avocado-VT use of that attribute is just a duplicate of what
Avocado.Test already does.
This should keep compatibility with latest Avocado and remove
duplication.
Reference: https://github.com/avocado-framework/avocado/pull/3279
> Drop use of file_handler attribute

- virttest/qemu_devices/qcontainer.py
`simple_hotplug()` insert the device at first before hotplugging it, will remove it if it  doesn't support hot plugging.
ID: 1645981
> Automatically specify bus and address when hotplugging a pci device

- virttest/remote.py
It tried to remove items in mutable type and definded it's index
as range in 'for' loop. It caused issue like 'list index out of
range' if the matched line was not the last one. So correct it
in this PR.
> RemoteFile: correct the logic for remove()

- virttest/qemu_vm.py
Fix formatting issue in hotplug_nic and hotunplug_nic, otherwise they
will hot plug/unplug with incorrect `device_id` and `netdev_id`.
> qemu_vm: Make commands of hotplug_nic and hotunlug_nic more accurate

- virttest/ppm_utils.py
`debug.log` would be polluted by `PIL`:
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 1216
Let's fix it.
> Prevent PIL's logs pollution

- virttest/env_process.py
This lazy initialization is motivated by the fact that on some
container based testing scenarios, we don't want to even touch the
service manager utility code, which breaks when trying to determine if
this "system" is SysV or systemd based (and is neither).
---
Changes from v1 (#2202):
* Added one missing location in postprocess (spotted by @luckyh )
> Only initiate libvirtd installation helper when really needed [v2]

- virttest/env_process.py
Let's log the qemu-dst-version when the user specified different qemu
binaries (different paths).
> virttest.env_process: Log qemu-dst-version when set

- virttest/env_process.py
Reverts avocado-framework/avocado-vt#2262
As comment point out, all function test in CI will be blocked by this commit, so for urgent issue, just revert it
> Revert "virttest.env_process: Log qemu-dst-version when set"

- .cirrus.yml
- contrib/containers/ci/README
- contrib/containers/ci/centos-7.docker
- contrib/containers/ci/fedora-30.docker
- contrib/containers/ci/rhel-8.docker
- setup.py
This adds an initial set of Avocado + Avocado-VT basic set of
checks on:
- latest Fedora (30)
- CentOS 7
- RHEL 8
Because Avocado-VT should work with Avocado's LTS and non-LTS version,
this uses the latest LTS release and Avocado's latest master.
The RHEL 8 checks are simpler, and only involve checking the presence
of the Avocado-VT plugins, instead of doing the full bootstrap, list
and dry-run, because of package limitations.  This could be improved
in the future with some moking of the required packages and binaries.
---
Changes from v3 (#2221):
* Removed the step that install pip deps from requirements.txt (so we rely on setup.py)
* Added matrix item for empty AVOCADO_SRC settings (relying on pip or setup.py for having Avocado installed)
* …
> CI: add smoke checks based on containers and Cirrus CI [v4]

- Makefile.include
- requirements.txt
There are some issues with pip installation. First the "--root" doesn't work as expected on py3 and the "pip install" puts shared files into the incorrect location on py2.
---
Resending https://github.com/avocado-framework/avocado-vt/pull/2203 to make it go through the new CI checks.
> HOTFIX: Makefile: Fix "make install" after the pip changes

- virttest/utils_misc.py
1. The default value of timeout is None which makes it raise exception,
so update to '60'.
2. update the command output to 'stdout'
> utils_misc: Fix cmd_status_output() for command failing on remote

- shared/cfg/guest-os/Windows.cfg
Add "!virtual_nic" to Windows.cfg, It should not use
"autostress = no" for virtual_nic.cfg
id:1749260
> Fix background test start failed on 32bit windows guests issue

- virttest/utils_test/__init__.py
On py2 this will result in insignificant memory overhead (the list will
be very small) and on py3 it will actually work.
Fixes https://github.com/avocado-framework/avocado-vt/issues/2232
> virttest.utils_test: Replace "iteritems" with "items"

- virttest/utils_test/__init__.py
fix to adopt python3 as it doesn't support iteritems() instead
use items().
File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'iteritems'
> utils_test: python3 doesn't support iteritems()

- virttest/env_process.py
Let's log the qemu-dst-version when the user specified different qemu
binaries (different paths).
Changes:
* Added check for qemu presence to avoid issues from https://github.com/avocado-framework/avocado-vt/pull/2262
> virttest.env_process: Log qemu-dst-version when set [v2]

- avocado_vt/test.py
- virt.py
Some test suites would prefer to place their tests outside of and
not relative to the default folder with virtual tests.
> Allow for absolute paths to additional virtual tests

- virttest/utils_net.py
When running tests with windows guest, the following message would
flood the main log stream.
Retry verifying IP address (0.000007 secs)
However, it isn't helpful since it only tells user what it will do
rather than give the detail of errors. Let's remove it then.
> utils_net: Remove unhelpful log message

- docs/source/CartesianConfig.rst
This adds a paragraph and a minimal example about using the "join"
and "suffix" keyworlds as well as a note on overwriting parameters.
> Add some minimal documentation on heterogeneous Cartesian variants

- shared/unattended/Fedora-25.ks
This kickstart is still being used by F28, but was removed in
595befd.
> shared.unattended: Bring back Fedora-25.ks

- virttest/qemu_vm.py
ncat works appropriately with internet protocol version specified
for migration to succeed, otherwise connection get refused.
13:50:33 INFO | Migrating to "exec:nc localhost 4444"
13:50:33 DEBUG| (monitor avocado-vt-vm1.qmpmonitor1) Sending command 'migrate'
13:50:33 DEBUG| Send command: {'execute': 'migrate', 'arguments': {'uri': 'exec:nc localhost 4444', 'blk': False, 'inc': False}, 'id': 'ZQGotJkl'}
13:50:33 INFO | [qemu output] close: Bad file descriptor
13:50:33 INFO | [qemu output] Ncat: Connection reset by peer.
13:50:33 INFO | [qemu output] qemu-system-ppc64: Unable to write to command: Broken pipe
> qemu_vm: include internet protocol version in migration incoming uri

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
- virttest/utils_qemu.py
Currently, the capabilities of qemu is stored in `VM` and it would
result in some issue, for example, the inconsistency of this
attribute between `VM` and `DevContainer`.
To resolve the issue, as Lukáš suggested we can store the capabilities
only in `DevContainer` and make it to be a public attribute, hence,
it can be used by any context which needs that, and its lifetime will
be managed easily.
CC: Lukáš Doktor <ldoktor@redhat.com>
> Refactor qemu capabilities related code

- virttest/utils_net.py
Quite often I see a failure related to port removal, when the port is
already removed (either doulbe-removal, or "ip link delete ..."). Let's
be a bit more lenient and only fail the "del_port" when the port is
still present in the bridge (as that is the purpose of this method)
> virttest.utils_net: Avoid failing test when port already removed

- virttest/qemu_devices/qcontainer.py
The vms in our runs are constantly reset using release 72.0 and the
reason is mismatched env configuration within the same vm. The
mismatched params come from no real configuration change but from
a different `qemu_capabilities.Capabilities` instance which is not
relevant to such use cases.
> Add the new Qemu capabilities key to the qcontainer comparison ignorable ones

- virttest/gluster.py
- virttest/utils_misc.py
- virttest/utils_net.py
- virttest/utils_test/libvirt.py
This adds some functions to manage the glusterfs backend disk
1. Add functions to mount/umount/check status of glusterfs
2. Add functions to create/remove/check symlink
3. Move setup_or_cleanup_gluster from libvirt.py to gluster.py
and move get_host_ipv4_addr to utils_net due to cyclic import
This PR is required by migration cases which need to migrate
with gluster backend disk.
> Add funcs for gluster backend disk oprations

- virttest/libvirt_xml/pool_xml.py
The initiator element in source fileld is mainly used for iscsi-direct pool
Signed-off-by: MeinaLi <meili@redhat.com>
> Pool_xml: add initiator iqn name in source element

- shared/cfg/base.cfg
- virttest/qemu_capabilities.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
- virttest/virt_vm.py
1. Add smp 'dies=*' option support
2. Optimize missing parameter calculation
Reference to: [vl.c: Add -smp, dies=* command line support and update doc](https://git.qemu.org/?p=qemu.git;a=commitdiff;h=1b45842203540943b1e22fc30764456c035d8637)
Reference to: [compute missing values, prefer sockets over cores over threads](https://github.com/qemu/qemu/blob/f3b8f18ebf344ab359e8f79f6ed777e740dae77c/hw/i386/pc.c#L1561-L1586)
> Add smp 'dies' option support and optimize parameter calculation

- virttest/qemu_storage.py
support the specification of source cache mode for image conversion.
> virttest.qemu_storage.QemuImg.convert: support source cache mode

- virttest/utils_time.py
In some distribution, grep binary is not placed
under /usr/bin path, rather in /bin path, so let's
find out the grep binary path and use it rather.
> Fixup: remove hard coded grep binary path

- virttest/qemu_vm.py
commit d384d23f7 modified cpu_str_to_list method to
import from wrong module, let's fix it.
> Hotfix: Fixup: module 'virttest.cpu' has no attribute 'cpu_str_to_list'

- virttest/libvirt_xml/vm_xml.py
This is required by cpu cases.
> Add pmu for cpu features

- virttest/utils_config.py
Looks like platform.dist() is removed from python3.8 so the below error
```
Failed to load plugin from module "avocado_vt.plugins.vt": AttributeError("module 'platform' has no attribute 'dist'") :
File "/usr/local/lib/python3.8/site-packages/avocado_framework-72.0-py3.8.egg/avocado/core/extension_manager.py", line 62, in __init__
plugin = ep.load()
File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
return self.resolve()
File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/local/lib/python3.8/site-packages/avocado_framework_plugins_vt-72.0-py3.8.egg/avocado_vt/plugins/vt.py", line 39, in <module>
from ..loader import VirtTestLoader
File …
```
> Fixup: AttributeError("module 'platform' has no attribute 'dist'")

- shared/cfg/guest-os/Linux/RHEL.cfg
With multiple console outputs Anaconda runs usually on the later and on
some archs not even there. Let's modify our "console=" lines to make it
always produce the output to serial console, which is captured in nice
format.
The only cons is that on ppc64 some messages will go only to serial
console and not to VGA output. This only affects some kernel messages
and not the graphical installation itself.
Note: We are already using this on Fedora and RHEL8 and it works better
than the previous implementation with output to tty0.
> shared: Force anaconda output to serial console

- virttest/utils_v2v.py
'-ic' is optional in '-i vmx' mode.
> Remove '-ic' option if '-i vmx' is specified in v2v

- avocado_vt/plugins/vt.py
Raising EnvironmentError won't be handled by avocado/core/extension_manager.py anymore since https://github.com/avocado-framework/avocado/commit/c2e30ab980520ab025673a0e60f07de1f32dfa94
Consequence is that if there's no previous avocado installation (/var/lib/avocado)
vt-bootstrap will always fail the first time with
"FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/avocado/data/avocado-vt/test-providers.d/downloads'"
Raising ImportError instead of EnvironmentError to maintain existing
behavior.
> Fix vt-bootstrap

- virttest/utils_v2v.py
ValueError: cannot process flags argument with a compiled pattern
> Fix cannot process flags argument with a compiled pattern

- virttest/qemu_vm.py
Previously we relied on a freshly-produced clone of the src vm to
cleanup the source vm on "finally" stage. This is not enough, because
the source vm (self) contains processes (nc attached to consoles). Let's
explicitly cleanup the source vm (self) just before replacing ourselves
with the destination (clone) vm to make sure all those processes are
cleared. To be super-safe let's keep the updated clone for the "finally"
postprocess.
Without this patch I'm getting about 2 extra aexpect (nc) processes per
ping_pong migration, with this patch it cleans everything properly.
> virttest.qemu_vm: Properly cleanup src vm on migration

- docs/source/cartesian/CartesianConfigReference-KVM-migration_mode.rst
- docs/source/cartesian/CartesianConfigReference-KVM-redirs.rst
- virttest/libvirt_vm.py
- virttest/qemu_vm.py
- virttest/utils_test/qemu/migration.py
The ports 590x are used for VNC (-vnc :0 => 5900) but the port of the
currently processed VM is not yet taken so find_free_port has no chance
on judging whether the port 5900 can be taken. This can happen with any
port depending on the current -vnc index so let's just limit the
available range to 5899 to completely avoid such clashes.
> qemu_vm: Avoid vnc ports clash on migration

- virttest/guest_agent.py
Add guest-get-memory-block-info,guest-get-memory-blocks and
guest-set-memory-blocks functions.
ID: 1754370
> virttest.guest_agent: Add function related to memory block

- virttest/qemu_vm.py
In different kernel, the network interface will be unpredictable
changed, use shell command to get the network interface  name for
param "device_name" in SRIOV tests
id: 1772359
> qemu_vm: support shell command for params "device_name"

- virttest/qemu_storage.py
id:1774452
Support qemu-img rebase option `-T` to specify cache mode used with
source files.
> qemu_storage.QemuImg.rebase: support source cache mode

- virttest/utils_v2v.py
Update v2v_timeout to v2v_cmd_timeout to avoid confusion with v2v
image import timeout value. And set the time to 5 hours since v2v
need a long time to run when convertion from local file by rhv
upload.
> Update v2v_timeout name to avoid confusion with v2v image import timeout

- virttest/env_process.py
Fix following UnboundLocalError.
File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
self.run()
File "/usr/lib64/python2.7/threading.py", line 765, in run
self.__target(*self.__args, **self.__kwargs)
File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/env_process.py", line 1922, in _store_vm_info
stored_log = store_vm_info(vm, vr_filename, cmd, vmtype=vmtype)
File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/env_process.py", line 1864, in store_vm_info
log_filename = "%s_%s" % (log_filename, timestamp)
UnboundLocalError: local variable 'timestamp' referenced before assignment
> Fix local variable 'timestamp' referenced before assignment

- virttest/qemu_vm.py
QEMU 4.1 introduced new usage of mlock, the cmd line has changed
from '-realtime mlock=...' to '-overcommit mem-lock=...'. Update
qemu cli to be compatible with QEMU 4.1 and before.
ID: 1750235
> qemu_vm: Update mlock qemu cli

- virttest/utils_v2v.py
'--mac' can match two options in v2v help. Update the patten to
only match '--mac <mac'.
--mac <mac:network|bridge:out>      Map NIC to network or bridge
--machine-readable[=format]         Make output machine readable
> Fix --mac option checking error

- virttest/utils_libguestfs.py
'-format' parameter must appear before '-a' parameter in
virt-format command, move '-a' parameter to the end of the
command.
ID:1776058
> fix parameter order issue in virt_format function

- virttest/utils_test/libvirt.py
libvirt.py: refactor the "check_vm_state".
The function "check_vm_state" is generic for non-migration scenario's as well.
Placing it out of the MigrationTest class, would be useful to refer in other tests.
> libvirt.py: refactor the "check_vm_state".

- shared/cfg/guest-hw.cfg
- virttest/ceph.py
- virttest/iscsi.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_storage.py
- virttest/qemu_vm.py
- virttest/storage.py
1. Support QEMU to access iSCSI resources directly by url:
iscsi://portal/target/lun
2. Support QEMU to access ceph resources directly by uri:
rbd:{pool-name}/{image-name}
3. Support vm installation on directly accessed iscsi/ceph image
ID: 1775502,1775506,1775508,1775509
> Add iscsi and ceph backends support

- virttest/env_process.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
- virttest/utils_qemu.py
- virttest/virt_vm.py
- qdevices:
1. Add class 'QCPUDevice' to support define a vcpu device, it supports all cpu properties
2. Add class 'QCPUBus' to manage all vcpu, include fixed vcpu and vcpu device
- qcontainer:
1. Add a method 'vcpu_device_define_by_params' to define vcpu device using params
- utils_qemu:
1. Add few functions to perform query operations via qemu
- base.cfg：
1. Specify cpu_model of pseries as host
- env_process:
1. Define vcpu_driver if not set
- qemu_vm:
1. Support add vcpu devices when create qemu command
2. Add a method to get all vcpu devices that support hot plug/unplug
> Add vcpu device support [V2]

- shared/cfg/base.cfg
- virttest/qemu_vm.py
Remove the default values of boot options to add ability to
test each option separately.
ID: 1752360
> boot_options_default: remove default values of boot options

- virttest/qemu_monitor.py
The set_migrate_parameter also needs to take the
disable_auto_x_evaluation argument as it accepts it on QMP.
> virttest: Add disable_auto_x_evaluation to human monitor

- shared/cfg/guest-os/Linux/Fedora/28.cfg
- shared/cfg/guest-os/Linux/RHEL.cfg
- shared/cfg/guest-os/Linux/RHEL/8.cfg
Some versions (RHEL8, Fedora>28) don't enable network unless it is
explicitly enabled by ip=... or via dependency (inst.repo=...). Let's
enable it via ip=dhcp.
> shared: Force-enable nic on Fedora/RHEL install

- virttest/env_process.py
- virttest/utils_qemu.py
If the category is wrong, `find_supported_devices` will raise KeyError.
Captured it and return an empty list directly since the match was not
successful.
Bugzilla ID: 1781036
> hotfix: capture and return empty list if category is wrong

- virttest/utils_qemu.py
The output type of some qemu help information may be different in
different distributions, some are `stdout`, some are `stderr`. Add
allow_output_check='combined' to check them together.
Bugzilla ID: 1781036
> utils_qemu: set allow_output_check='combined' in has_device_category

- virttest/utils_misc.py
utils_misc.py: Fixed the syntax error for the function "get_interface_from_pci_id"
> utils_misc.py: Fixed the syntax error for the function "get_interface_from_pci_id"

- virttest/libvirt_vm.py
- virttest/storage.py
framework picks wrong path from `image_base_dir` or `data_dir` path
for nfs tests causing VM to boot/test with wrong disk path. Instead
use `nfs_mount_dir` for VM to use appropriate image for NFS based
tests.
Fixes: commit 0b463201 and 782cc76a
> libvirt_vm: use `nfs_mount_dir` as base_dir for NFS tests

- virttest/unittests/test_utils_test__init__.py
- virttest/utils_test/__init__.py
On s390x running zipl command is required after updating boot loader entries
(with grubby), see https://bugzilla.redhat.com/show_bug.cgi?id=1764306#c2
In other words, running grubby and then rebooting without zipl won't change
cmdline.
1. update_boot_option:
a. Added new parameter guest_arch_name: zipl has to be run only on s390x
guests. Has default value for backwards compatibility.
b. __run_cmd_handle_error: extracted cmd line handling into private
method to avoid duplication.
2. virttest/unittests:
a. Created new package for unit tests because virttest/tests contains
higher level test cases.
3. test_utils_test__init__.py:
a. Added unit tests for 1.a./b.
b. try: import unittest.mock...: In order to run the unit tests with 2.x
'mock' has to be installed from pip, import will be …
> Update boot loader entry on s390x

- backends/v2v/cfg/tests-shared.cfg
- virttest/utils_v2v.py
1) Reform v2v_setup_ssh_key_cleanup to be more general
2) Reform the resource cleanup function for setup_ssh_key
3) Disable store_vm_info for v2v to avoid annoying exception reports
during running.
> Reform setup_ssh_key function for v2v

- virttest/libvirt_xml/devices/rng.py
- virttest/libvirt_xml/devices/vsock.py
1. libvirt_xml.devices.vsock: Address requires type_name when initialize
2. libvirt_xml.devices.rng: Add address attribute for rng xml
> libvirt_xml.devices: Complement address attribute for vsock and rng

- virttest/cpu.py
It used to match 'max_conf' even vm restarted.
Fixup this issue in this PR.
> Fix to check correct value for 'max' in check_vcpu_domstats

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
- virttest/vt_iothread.py
support iothread allocation schemes:
1. predefined
```
iothreads = iothread0 iothread1 iothread2
image_iothread_image1 = iothread1
```
2. round robin
```
iothread_scheme = roundrobin
iothreads = iothread0 iothread1 iothread2 iothread3
image_iothread = auto
```
will allocate four iothread objects and use them in a round robin way.
3. one-to-one
```
iothread_scheme = oto
image_iothread = auto
```
will always create new iothread object for each requesting device.
> Enhance iothread support

- shared/cfg/guest-hw.cfg
qcow2 was supported by ceph since qemu 4.1.0
> qcow2 was supported by ceph since qemu 4.1.0

- backends/v2v/cfg/convert_source.cfg
ESX6.7 and ESX6.5 use vddk-6.7, ESX6.0 and ESX5.5 use vddk-6.5.
So move setting vddk_libdir_src from tp-libvirt to avocado-vt
to avoide duplicate codes
> Move vddk lib source settings to convert_srouce.cfg

- docs/source/CartesianConfig.rst
- selftests/unit/test_cartesian_config.py
- virttest/cartesian_config.py
Introduce the new operator `~=` to support variable lazy assignment,
which means a variable will be set only if it has not been defined
in previous frames during configuration parsing. For example, by
given the following configuration, the value of the variable `foo`
should be `"bar"`,
foo ~= bar
whereas, by given the following configuration, the value of the
variable `foo` would still be `"bar"`.
foo = bar
foo ~= foo
This might be useful for generating configuration under uncertain
conditions. For instance, we can set `smp` by using the value of
`vcpu_maxcpus` in the case of `smp` is not being set, otherwise,
let `smp` be what it was.
> cartesian_config: Introduce the new operator '~='

- avocado_vt/conf.d/vt.conf
- avocado_vt/loader.py
- avocado_vt/options.py
- avocado_vt/test.py
- virttest/data_dir.py
- virttest/env_process.py
Adding optional vm persistence throughout tests/jobs is an old behavior in virt-test that seems to be missing in avocado-vt but is highly appreciated when it comes to improved performance due to no vm rebooting as well as setup reuse through qcow2 vm snapshots. The only way this can be possible is if the vms are not immediately destroyed and the environment/sockets/address_pool cleaned up, all in turn requiring a persistent temporary location that is not regenerated for each job. This branch is doing exactly this, keeping the cleaner (but less efficient) default behavior while making such new behavior optional.
> Optional vm persistence

- virttest/libvirt_xml/vm_xml.py
- virttest/unittests/libvirt_xml/test_vm_xml.py
1. del_seclabel:
a. The function originally deleted all seclabels.
b. Added new parameter maintaining legacy behavior.
c. New parameter let's restrict the set of seclables
to be removed (see docstring).
2. virttest/unittests:
a. Created new package for unit tests and subpackage to have
consistent paths in unittests.
3. test_vm_xml.py:
a. Added test cases to cover previous/default and new behavior.
> Restrict set of seclabels to be removed

- shared/cfg/guest-hw.cfg
Change to use lazy assignment for variable image_boot to support
modifying its value in case level.
ID: 1781445
> image_boot: use lazy assignment for image_boot

- virttest/qemu_vm.py
After migration, the dst guest might in "inmigration" state for certain
period, especially with "exec:gzip". But resume vm in "inmigrate" can't
work, so wait up to 120s to wait for the right status.
id: 1791785
> qemu_vm: Avoid resume vm in "inmigrate" status

- virttest/libvirt_xml/vm_xml.py
It's required by iothread cases.
> VMCPUTuneXML:Add iothreadscheds, iothread_period and iothread_quota

- virttest/virsh.py
It's required by iothread cases.
> Virsh: Add iothreadset()

- backends/v2v/cfg/tests-shared.cfg
- virttest/utils_v2v.py
1) For local virsh connection, it may does' have session_id attribute,
we need to check that.
2) Add '--no-pager' option for journal command, if not, the command may
be timeout because of wating for user interaction.
3) Add 'lshw' for checking pci devices, because not every guest has 'lspci'
command.
4) store_vm_info is defined in base.cfg, we need to reset its value after
base.cfg.
5) Move subtests.cfg to the line after 'include convert_destination.cfg'
in tests-shared.cfg.
> Fix closing local virsh connection problems in V2V

- virttest/utils_disk.py
Add a parameter "quick_format" for the function
create_filesystem_windows to enable or disable quick format,
since some windows scenario need to disable quick format.
id:17838962
> utils_disk.py: add "quick_format" for create_filesystem_windows

- virttest/libvirt_vm.py
In order for the kernel console parameter to be set correctly on s390x
the guest architecture must be passed on. Details s. https://github.com/avocado-framework/avocado-vt/pull/2312
Signed-off-by: Sebastian Mitterle smitterl@redhat.com
> Add set_kernel_console support for s390x

- virttest/ceph.py
- virttest/storage.py
Given a keyring string, avocado-vt should support authentication for both qemu and rbd commands.
Supported the following rbd commands with keyring option
rbd rm xxx --keyring keyring_file
rbd ls xxx --keyring keyring_file
rbd create xxx --keyring keyring_file
ID: 1802376
> Supported rbd command with keyring file

- virttest/libvirt_xml/vm_xml.py
Return address of type ccw. On s390x (and only there) both disk_bus scsi
and virtio will have ccw type address. Therefore, first check address
type instead of target bus.
> Get address of type ccw

- virttest/libvirt_xml/devices/tpm.py
Add encryption secret configuration support in tpm device xml.
> tpm.py: Add encryption support

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
The  #2387 broke arm64-pci because the multifunction rootport was not defined for it's machine type. This PR fixes the definition and also adds some fixes in related code. I tested this on arm as well as i440fx and q35.
> Fix ARM pcie-topology

- virttest/cpu.py
Add timeout to retry until vcpu hotplug check fails, as
time to complete hotplug event increases with number of
vcpus increases and the check can be wrong, so let's confirm
it for retrying until a timeout.
> Add timeout to retry until vcpu hotplug check fails

- virttest/env_process.py
There is a typo in `preprocess` and that would cause incorrect vm
registrations between tests, let's fix it.
ID: 1798405
> Fix the env vms issue

- virttest/utils_test/libvirt.py
New usage type 'vtpm' is involved from libvirt-5.6, for vtpm
encryption. Add this option in create_secret() function.
> libvirt.py: secret new usage type 'vtpm'

- virttest/tests/unattended_install.py
Provide vm specific parameters before performing any unattended vm setup
This change makes sure we are running vm-restricted configuration during unattended installation and should have no effect on any tests avoiding regex matching through ``?=`` or ``join`` operators in the Cartesian configs. It is however needed if some Cartesian parameters end up with a vm suffix like ``_vm1`` due to any preinstallation preprocessing.
> Unattended install params

- virttest/qemu_monitor.py
The constructor assumes more functionality than the one provided
by dummy vms which avoid recursion when the monitor is unpickled.
> Fix monitor creation for unpickled vms

- virttest/utils_disk.py
- virttest/utils_test/libvirt.py
1. `utils_disk.get_scsi_info`: new function to get required information
for `//hostdev/source/address`
2. `utils_test.libvirt.create_hostdev_xml`:
a. handle usb/pci as before
b. add logic for scsi
c. don't modify name of parameter `pci_id`: it has already been overloaded
to be used with usb, so explicitly mention which information parameter
can hold but don't change name for backwards compatibility in case
function called with named parameters
> Add scsi hostdev helper functions

- .cirrus.yml
- contrib/containers/ci/centos-8.1.docker
The CentOS based image doesn't need the fake binaries, and the less
fake the testing the better.
> Cirrus CI: replace UBI8 for CentOS 8.1 based image

- virttest/qemu_vm.py
legacy pci device in Q35 type vm should be plug into pcie-pci-bridge and not pci.0
ID: 1808960, 1809396
> fix hotplug legacy pci device into wrong bus issue

- virttest/qemu_devices/qcontainer.py
Defaults the blockdev format node to RAW type since will raise
UnboundLocalError while the imgfmt is None.
ID: 1797975
> qcontainer: Defaults the blockdev format node to RAW type

- virttest/qemu_vm.py
Move adding usb devices logic at the earlier stage in
make_create_command() before adding images to support
plugging usb-storage under usb-hub automatically.
ID: 1802010
> usb_device: move adding usb devices logic forward

- virttest/utils_misc.py
We apologize for the inconvenience, we should have put the network module
in deprecation, but we ended up forgetting about it. I made this change and hopefully
will fix the problem.
Signed-off-by: Beraldo Leal <bleal@redhat.com>
> virttests: fixed avocado.utils.network import

- virttest/virt_vm.py
As you can see below, There are millions of error logs were printed in job.log. so the job.log
is very large which makes jenkins out-of-memory.
2020-02-23 23:28:41,427 virt_vm          L1188 DEBUG| Attempting to log into 'esx6.7-rhel8.1-x86_64WY0' (timeout 480s)
2020-02-23 23:29:21,840 ip_sniffing      L0053 DEBUG| Updated HWADDR (00:50:56:ac:06:41)<->(192.168.122.150) IP pair into address cache
2020-02-23 23:29:22,067 virt_vm          L0919 DEBUG| Found/Verified IP 192.168.122.150 for VM esx6.7-rhel8.1-x86_64WY0 NIC 0
2020-02-23 23:30:43,083 ip_sniffing      L0068 DEBUG| Dropped the address cache of HWADDR (00:50:56:ac:06:41)
2020-02-23 23:30:43,086 virt_vm          L1373 DEBUG| Attempting to log into 'esx6.7-rhel8.1-x86_64WY0' via serial console (timeout 10s)
2020-02-23 23:30:43,087 …
> Fix keep printing error logs when Client process terminated unexpectedly

- shared/cfg/guest-os/Linux/RHEL.cfg
- shared/cfg/guest-os/Linux/RHEL/7.6.cfg
- shared/cfg/guest-os/Linux/RHEL/7.6/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.7.cfg
- shared/cfg/guest-os/Linux/RHEL/7.7/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/8.cfg
- shared/cfg/guest-os/Windows.cfg
- shared/cfg/guest-os/Windows/Win10/i386.cfg
- shared/cfg/guest-os/Windows/Win10/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2012/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2016/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2019/x86_64.cfg
- shared/cfg/guest-os/Windows/Win8/i386.cfg
- shared/cfg/guest-os/Windows/Win8/x86_64.cfg
There are two scenarios in check_block_size:
one is related to the unattended installation,like as
512_512,4096_512,4096_4096 under ovmf. The other is
booting os directly. we need to specify the cases range
in configuratoin files to adapt different scenario.
ID:1810946,1766078,1804025
> classify installation cases for check_block_size

- virttest/storage.py
id: 1816048
for a raw device with `image_name = /dev/autotest/lv0`, current
implementation will remove the file path as releasing it. Let's simply
skip the removal and leave the decision to the user.
> storage.file_remove: skip removal of raw device

- shared/cfg/base.cfg
- virttest/gluster.py
1. base.cfg:
a. new parameter `gluster_managed_by_test` to determine if the test should manage
the gluster server or if a static instance managed e.g. manually is to be used.
2. gluster.py:
a. Have `setup_or_cleanup_gluster` set up or clean up gluster server
instance only if parameter `gluster_managed_by_test` is `yes`;
this is default and legacy behavior.
The function returns local IP or gluster_server_ip to maintain legacy
behavior.
b. Suppress pylint E1121 in order to maintain original signature
c. Support the following use cases (gluster decides if to use local or remote
gluster server by value of "gluster_server_ip", s. virttest/gluster.py):
|UC#|Use gluster|Gluster location|Manage setup/cleanup|
|1  |Yes        |local           |Yes                 |
|2  |Yes        |remote …
> Restrict gluster usage by tests

- virttest/qemu_devices/qcontainer.py
For some scenarios that the driver file is empty, so
check whether the file is not None then get the options 
of file.
ID: 1787113, 1804030
> qcontainer: Fix ValueError “Wrong filename None”

- virttest/libvirt_xml/devices/memballoon.py
This is to add 'address' element to Memballoon object and make it configurable.
> Add address to memballoon

- virttest/utils_test/libvirt.py
Creating secret remotely is required by migration test.
> Update create_secret to create secret on remote

- shared/cfg/base.cfg
- virttest/qemu_vm.py
- virttest/virt_vm.py
This brings back the first commit from https://github.com/avocado-framework/avocado-vt/pull/2081 that was removed before merging, because after couple of months I have many failed cases because of missed events.
The second commit adds a fix to the QMP check when it happens during init when `vm.monitor` is `None`, which also pop-ups pretty frequently in my testing.
@luckyh please re-consider your NACK of the first commit as I am hitting it regularly.
Update: Added 2 commits that are fixing "missing MAC" and "directory not empty" issues I am also regularly hitting and finally got to debug. It's also caused by partially initialized VM during reboot.
> Couple fixes to "reboot" when used together with migration

- virttest/storage.py
1. In the raw device restore process, remove the procedure to dd to an
intermediate .part file.
2. In methods `save_image` and `backup_image`, the source should be the
raw device path, which is `image_filename`.
> storage.QemuImg: fix raw device backup and save

- virttest/libvirt_xml/devices/interface.py
- virttest/utils_test/libvirt.py
Add teaming element to Interface class.
And update libvirt.modify_vm_iface accordingly.
> Update to support teaming for interface

- shared/cfg/base.cfg
- virttest/libvirt_vm.py
- virttest/qemu_vm.py
The "-compat" option was introduced recently in qemu to let users
configure the behavior on the use of deprecated interfaces. See:
Configurable policy for handling deprecated interfaces
email for more details. Let's add this interface to both qemu_vm and
libvirt_vm to allow developing tests or simply running tests with custom
policy (the example in base.cfg makes the qemu crash when deprecated
interface is used).
* Note in order to test this you need to apply the `Configurable policy for handling deprecated interfaces` patch to qemu (for example by `git fetch origin 'patchew/20200303163505.32041-1-armbru@redhat.com'` on the `https://github.com/patchew-project/qemu` git repo).
* I don't remember (and wasn't able to easily find) how to check whether given qemu command is available in …
> Add support for "-compat"

- virttest/utils_test/qemu/__init__.py
This is also available, and only used, in the migration.py file
in the same directory.
> Remove duplicate and identical version of get_nic_vendor function

- virttest/virt_vm.py
Every failed login attempt in will log non-ERROR messages.
This clutters up the job.log and as a consequence Jenkins runs
out of memory, s. https://github.com/avocado-framework/avocado-vt/commit/b2ded91de9ab08fd76aa1544ddae6c3be8904ae5
Add a sleep in order to reduce number of attempts like in
`wait_for_serial_login` https://github.com/avocado-framework/avocado-vt/blob/a75febd923b8d6c8e6720bef12ecd9874ff7fe00/virttest/virt_vm.py#L1391
Signed-off-by: Lukas Doktor <ldoktor@redhat.com>
> Reduce login attempts on error

- virttest/utils_conn.py
Fix the error:
UnboundLocalError: local variable 'pattern_to_repl' referenced before assignment
> Fix variable reference issue

- virttest/utils_test/__init__.py
Adds error if not found any pip packages.
Apart from the list packages that should be upgraded, we should care if pip
was upgrading too. Because if it not, the exit code doesn't show errors during
upgrade or install packages.
Signed-off-by: Oksana Vohchana <ovoshcha@redhat.com>
> virttest.utils_test: Upgrade pip package

- virttest/test_setup.py
This is to add a parameter to use customized kernel hugepage file instead of a default one.
> Enable customized kernel hugepage file

- shared/cfg/base.cfg
- virttest/libvirtd_decorator.py
- virttest/utils_libvirtd.py
This is part of effort to address libvirtd split issue after libvirt version >= 5.6.0
As such, libvirtd will be replaced by split daemons,e.g virtqemud, virtnetworkd,etc
For automation scripts, the code need to be kept compatible whether libvirt version >= 5.6.0 or not
Therefore, some decorators are introduced, and those decorators apply on libvird operations functions
such start, stop,restart,etc. And the final purpose is to keep libvird function work as before if libvirt
version is < 5.6.0, but do nothing after libvirt >= 5.6.0
> Add libvirtd decorator to address libvirtd split issue

- shared/cfg/guest-os/Linux/Fedora/28.cfg
- shared/cfg/guest-os/Linux/Fedora/31.cfg
- shared/downloads/fedora-31-x86_64.ini
- shared/unattended/Fedora-25.ks
This is needed by Fedora 31 and later test.
Fedora-25.ks won't work any more as root login is disable by default from Fedora 31 on
> Add config files for Fedora 31

- virttest/utils_test/libvirt.py
If there is no interface in vm, it will raise exception.
> libvirt: Fix indexerror in modify_vm_iface

- virttest/qemu_vm.py
The total number of logical CPUs -smp [cpus],sockets/cores/threads[,maxcpus]
describe CPU topology.
But from 3.1 version requires '-smp X,maxcpus=Y' option, thus allow hotplug vcpu
Signed-off-by: Oksana Vohchana <ovoshcha@redhat.com>
> Update CPUs topology

- .cirrus.yml
Given that there's bootstrap specific code for different
virtualization types.  So far, this does it for only one OS (Fedora
30) which seems to be enough.
> Cirrus CI: also perform a libvirt based bootstrap/list

- virttest/test_setup.py
On my z/VM only available zone is DMA. The current code
restricted info to DMA32 and Normal zones.
On s390x, follow ppc64le and don't restrict zones for chunk_info.
> Don't restrict mem zones on s390x

- virttest/virsh.py
This command is used to set the threshold for block-threshold event for a given block device or it's backing chain element.
> Add virsh domblkthreshold command

- virttest/ovirt.py
The execution should be interrupted if ovirtsdk4 is not found.
If not, the guests cannot be cleaned up on rhv server.
Although it will not block convertion to other targets, but
the benefit is less than the disadvantage.
> Block execution if ovirtsdk4 is not found

- virttest/env_process.py
- virttest/unittests/test_utils_kernel_module.py
- virttest/utils_kernel_module.py
Handle cases where kvm module is loaded without hugepage support
1. Add class to help reload and restore Linux kernel module configuration.
KernelModuleHandler will only reload if current module configuration
doesn't contain some of the requested parameter settings. It will only
restore backed up configuration if it changed the current module configuration.
2. Hook activating hugepages with config into env_process
a. Introduce variable `kvm_module_force_load` to force loading the module always. Don't
force by default.
b. Introduce variable `kvm_module_parameters` to define custom module parameters on load.
c. Use convenience method `reload` to delegate decision if to load to new python module.
d. Sample log output
i. where reload is not necessary
```bash
2020-02-20 14:44:31,300 …
```
> Add stateless kernel module handler for kvm hugepage support

- shared/cfg/guest-os/Windows.cfg
- virttest/utils_test/qemu/__init__.py
For win8.1+ guests, enable "kernel syncronization delay fuzzing";
For win8.1- guests, use standard setting since "kernel syncronization delay fuzzing" is not supported on them.
ID: 1827536
Signed-off-by: lijin <lijin@redhat.com>
> Enable "kernel syncronization delay fuzzing" flag in verifer for win8.1+ guests

- shared/cfg/guest-os/Linux/RHEL.cfg
Installation options set for case blockdev_snapshot_install
id:1831968
> Shared.RHEL:blockdev_snapshot_install installation options set

- virttest/utils_misc.py
Add a function to get absolute path for pci devices.
It's required by sriov migration test.
> Add get_pci_path into utils_misc

- virttest/utils_test/libvirt.py
The function of create/add controller was changed in 7bfccd89.
So need to set controller index when generate xml.
> Set default controller index in set_vm_disk

- shared/cfg/base.cfg
- shared/cfg/machines.cfg
- virttest/qemu_devices/qcontainer.py
In addition to some common properties, nvdimm device has some unique
properties. pseries already supports this device since qemu-5.0, but it
needs to set the "uuid" property for this dimm device on the qemu
command line.
1. qcontainer: Set nvdimm's uuid if required
2. qcontainer: Supports add other properties with "dimm_extra_params"
3. Introduce of new params in the cfg
ID: 1829139
> Support more properties for dimm devices

- virttest/env_process.py
Fix 'VM' object has no attribute 'devices' for libvirt type
during cleaning up daemons.
> env_process: Fix 'VM' object has no attribute 'devices'

- virttest/virsh.py
The detach_device_alias works asynchronously. It return results
immediately before device are really detached from VM. The new argument
wait_remove_event can make it works synchronously, implementing event
command and waiting for device_removed event. The event_timeout set the
timeout of event command.
Signed-off-by: Han Han <hhan@redhat.com>
> virsh.py: New agruments of detach_device_alias for device_removed event

- virttest/env_process.py
The following failure could be emitted during `Postprocess`:
RuntimeError: Failures occurred while postprocess:
Postprocess: 'NoneType' object has no attribute 'cleanup_daemons'
it is introduced by commit 0148461, and because a qemu VM instance are
being `postprocess` without called `create` at its lifetime.
> Hotfix for the RuntimeError during Postprocess

- virttest/migration.py
The function which will be executed during migration may not have
any parameter.
> fix MigrationTest.do_migration to be able to run function without params

- virttest/libvirt_vm.py
In order to allow for setting guest agent state without
re-installing package, extract method safely.
Legacy behavior is left unchanged.
> Extract guest agent state

- virttest/utils_v2v.py
SLES15SP1 guest which is installed minimal OS doesn't support
'lspci' and 'lshw' command, so add command 'hwinfo' to
check the pci devices of guest.
Signed-off-by: mxie91 <mxie@redhat.com>
> Add another command to check pci devices of linux guest

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
With machine type pc, the parant bus is pci.
With machine type q35, the parent bus is pci-bridge.
id: 1818721
> Add correct parent bus for 'pci-serial' device

- virttest/utils_misc.py
Some methods might raise, e.g. if a device is not ready yet.
Add new function like `wait_for` but ignoring errors.
Add pylint exception because in this specific case we want to handle all errors and exceptions.
> Allow for errors while waiting

- virttest/utils_net.py
When 'force_ipv4' is True, ping will only use ipv4 address as source
> Add 'force_ipv4' to function ping

- virttest/utils_test/libvirt.py
Commands run in vm session don't return process.CmdResult.
In order to increase code reusability of `check_result` add
proxy function to support session typical results.
> Add proxy function to delegate to check_result

- virttest/utils_test/libvirt.py
The original assertion is not correct, we must compare search result
with 'None' to confirm if there is already a panic device in vm xml.
> Fix the issue of duplicated adding panic device

- virttest/migration.py
Sometimes we execute migrate-postcopy command before migration really starts, so we get below error:
"error: internal error: unable to execute QEMU command 'migrate-start-postcopy': Enable postcopy
with migrate_set_capability before the start of migration".
So this is to stabilize the script.
> Stabilize postcopy migration

- virttest/utils_test/libvirt_domjobinfo.py
It was introduced in tp-libvirt migrate_options_shared.py.
Now, a new migration script needs it, so move it
to utils_test.
> Move check_domjobinfo function to utils_test.libvirt

- virttest/cpu.py
1. Commit d384d23 missed some cpu models added in commit a1678102,
add them back
2. Add EPYC-Rome cpu model
ID: 1838492
> cpu: add more cpu models support

- virttest/env_process.py
For two newly installed machines in migration, authenticity confirmation dialog popup
during calling virsh.hostname(uri=dest_uri),
And this leads to migration breakout
> Fix authenticity confirmation dialog popup issue

- virttest/cpu.py
According to bz 1661030, MPX support was removed from 8.0 machine
types. In order to get suitable cpu modle when run test with either
bare mental or VM, do not check this flag anymore
id: 1841486
> cpu: do not check cpu flag 'mpx' when determine cpu model

- virttest/utils_netperf.py
Add params to support latest netperf version.
ID:1833873
> utils_netperf: Add params to support latest netperf version

- virttest/utils_test/__init__.py
when there are mutiple nics in guest and second one or third on is
public, there will be a error "ipv4 DHCP lease", force restart
network in such case.
id: 1837801
> virttest.utils_test: restart network in funtion update_boot_option

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
Small tweak to the merged https://github.com/avocado-framework/avocado-vt/pull/2566 to incorporate https://github.com/avocado-framework/avocado-vt/pull/2497
There are more than just pci-serial devices, but names of all of them
starts with "pci*". Let's treat them the same way by using startswith.
> Plug all pci-* serial devices into pci bus

- shared/cfg/guest-hw.cfg
- virttest/gluster.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_storage.py
- virttest/storage.py
1. Access storage by 'qemu-kvm -drive'
gluster[+tcp]://1.2.3.4[:24007]/testvol/dir/a.img
gluster[+tcp]://[1:2:3:4:5:6:7:8][:24007]/testvol/dir/a.img
gluster+unix:///testvol/dir/a.img?socket=/var/run/glusterd.sock
2. Access storage by 'qemu-kvm -blockdev'
driver=gluster,volume=..,path=..,server.0.type=inet,
server.0.host=..,server.0.port=..,server.1.type=...
ID: 1789278
> Support gluster storage backend

- virttest/utils_sriov.py
The previous command does not work when the OS is newly installed.
> utils_sriov: Update connection creation command

- virttest/utils_v2v.py
A spell error caused undefine vaiant was used in cmd_run
> Fix wrong spell issue in cmd_run function of v2v

- virttest/utils_test/__init__.py
Add a helper function to parse testlist
for avocado guest tests, commit bb8c86acc
removed the parsing of testlist by run_avocado_bg()
method and expects user to pass by value,
due to which tests using it in mutiple places
silently skipping test run, lets have helper
function added to parse the testlist, still
the tests using run_avocado_bg() needs a change
and this API will help avoid code duplication
on muliple places.
> Add a helper function to parse testlist

- virttest/qemu_devices/qcontainer.py
ID: 1837184, 1837188
Signed-off-by: Xianwang <xianwang@redhat.com>
> qcontainer: slof support scsi id from 0 to 63 and lun id from 0 to 31 on vscsi adaptor

- virttest/qemu_storage.py
Just a few cleanups and optmizations on the `decode_to_text()` and `avocado.utils.process` usage on that module.
> virttest.qemu_storage: drop unused decode_to_text() and default to process.run()

- virttest/qemu_devices/qcontainer.py
The alllocated iothread object will be passed in the self.allocate_iothread
again in the second iteration which will raise ValueError("Not support
request specific iothread") when applying multiple scsi hbas. Change the
variable to differentitate the params "image_iothread" and the allocated
iothread object.
ID: 1844337
> qcontainer: Fix fail to allocate iothread for mulitple scsi hbas

- virttest/utils_test/__init__.py
That patch provides a fix in two places.
In case to install the dependencies we get the status of the last package.
The package was installed not with pip but need to update it.
Signed-off-by: Oksana Vohchana <ovoshcha@redhat.com>
> virttest.utils_test: Improvement to pip installation

- virttest/utils_test/__init__.py
run_avocado method does not take arguments but
passed while calling from run_avocado_bg,
let's fix it.
Without this fix we will see below error
```
File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-79.0-py3.6.egg/virttest/utils_test/__init__.py", line 1991, in join
raise self.exception
File "/usr/local/lib/python3.6/site-packages/avocado_framework_plugin_vt-79.0-py3.6.egg/virttest/utils_test/__init__.py", line 1974, in launch
func(*params, **kwargs)
TypeError: manage_session() takes 1 positional argument but 223 were given
```
> Fixup: run_avocado method does not take arguments

- requirements-travis.txt
- requirements.txt
- setup.py
Pinning 0.7.19 as the version for selftests (because 0.7.20 won't run
on Python 2 / EL 7), and updating to that minimum version for
installation purposes (just to keep more consistency between what's
used to test and what's used to run it).
> Requirements: update netaddr versions

- README.rst
- docs/source/GetStartedGuide.rst
- virttest/bootstrap.py
1. Avocado doc has been restructured: fix broken links
2. Give more priority to pip installation:
a. It's the primary installation method for Avocado (s. doc
https://avocado-framework.readthedocs.io/en/latest/guides/user/chapters/installing.html
"Avocado is primarily written in Python, so a standard Python installation is possible
and often preferable. You can also install from your distro repository, if available."
etc.)
b. Pip installation is available on more environments.
c. Whoever wants to develop/debug test cases is better off with pip installation.
3. Recommend to use the same installation method for both plugin and main program:
a. Mixing both methods can lead to issues due to version incompatibility and command
availability.
4. Add python-devel as dependency: I got installation …
> Update Getting Started

- virttest/utils_package.py
On slow systems, e.g. network, commands can time out.
1. Add global constant for default parameter
2. Make sure all command executions have a configurable timeout
> Add timeout constant

- virttest/qemu_devices/qcontainer.py
cache-size is a qcow2 option, it cannot be given to any
blockdev node but qcow2 nodes.
ID: 1849670
> correct blockdev command lines for parameter cache-size

- avocado_vt/loader.py
Avocado has renamed "args" to "config" in 84ae9a5d61.  lets keep
making the old name available for compatibility with new and old
releases.
> Loader: avocado compatibility hotfix

- virttest/ovirt.py
- virttest/utils_v2v.py
1) When vm.start fails, the vm should be deleted and image should
be removed from export domain.
2) When timeout is -1, wait forever until the VM is imported to
data domain successfully.
> Fix VM cleanup issue when vm.start fails

- avocado_vt/plugins/vt.py
- avocado_vt/plugins/vt_bootstrap.py
- avocado_vt/plugins/vt_joblock.py
- avocado_vt/plugins/vt_list.py
The current import logic looks for the plugin interfaces on a location
that was valid before the 69.0 LTS release.  Now, all current releases
have the interfaces at the same location, so this logic is not needed
anymore.
> Plugin: drop attempt to use pre 69.0 LTS interfaces

- avocado_vt/loader.py
- avocado_vt/options.py
- avocado_vt/plugins/vt_bootstrap.py
- virttest/bootstrap.py
- virttest/compat.py
- virttest/standalone_test.py
Which is part of the "Job API enabler" work, while keeping
compatibility with previous Avocado version that supply an
argparse.Namespace instance.
Reference: https://github.com/avocado-framework/avocado/pull/3248
> Add support for job configuration as a dictionary

- virttest/virsh.py
Involved by commit d9acd3a3a19ff11e8a9987379379d3f332b3d1d0
> Fix the stdout error as compat_52lts removed

- virttest/virsh.py
Before
```
JOB ID     : ffedfb827f8b266c79044a116c693a4fd13b76b4
JOB LOG    : /root/avocado/job-results/job-2020-06-30T22.42-ffedfb8/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.memtune.positive_test.normal_1: ERROR: invalid literal for int() with base 10: 'unlimited\\nsoft_limit' (28.08 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 29.42 s
```
After
```
JOB ID     : b1a52663c3045d473939321501b0e301164f1ac3
JOB LOG    : /root/avocado/job-results/job-2020-06-30T22.58-b1a5266/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.memtune.positive_test.normal_1: PASS (26.84 s)
JOB TIME   : …
```
> Fix the error to decode the cmd result

- virttest/ceph.py
On commit d9acd3a3a1 there was a mass change in favor of direct usage
of avocado.utils.process, instead of the now removed 52lts
compatibility code.  A few of those changes resulted in mistakes, such
as the issue reported by Yongxue Hong with `process.system_output()`
instead of `process.run()`.
Besides that one change, this defaults to using `process.run()`, and
while at it, fixes a bug that was using the result of
`process.system()` (the process return code) instead of the actual
output produced by the process.
Reported-by: Yongxue Hong <yhong@redhat.com>
---
Reported at #2611 by @YongxueHong
> virttest/ceph.py: fix avocado.utils.process usage

- virttest/libvirt_xml/base.py
- virttest/qemu_storage.py
- virttest/remote.py
- virttest/utils_libguestfs.py
- virttest/utils_selinux.py
- virttest/utils_v2v.py
- virttest/virsh.py
- virttest/virt_admin.py
During lts removal,below command lines were removed in some python files:
ret.stdout = results_stdout_52lts(ret)
ret.stderr = results_stderr_52lts(ret)
During testing, finding that leads to some unanticipated results, for example virsh.cmd_result can not
return correct value.
As one solution, those similar command logic are added back.
> Fix some issues introduced by pr2611_lts_removal

- virttest/cpu.py
The replacements of removing 52lts bring in this error. According
to context, it should be exit_status, not stdout_text.
> Fix error of replacing exit_status with stdout

- shared/cfg/guest-hw.cfg
- virttest/nbd.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_monitor.py
- virttest/qemu_storage.py
- virttest/qemu_vm.py
- virttest/storage.py
- virttest/utils_misc.py
Add nbd storage backend support
1. Access nbd storage by uri:
nbd://server
nbd://server:port
nbd://server/export
nbd://server:port/export
nbd://?socket=/path/sock
nbd:///export?socket=/path/sock
2. Access nbd storage by blockdev
driver=nbd,server.type=inet,server.host=xxx,server.port=xxx
driver=nbd,server.type=unix,server.path=xxx
driver=nbd,server.type=inet,server.host=xxx,server.port=xxx,tls-creds=xxx
ID: 1825932
> Support NBD storage backend

- virttest/utils_v2v.py
Because VMCheck can be instantiated before import_vm_to_ovirt function,
the ovirt vm instance may still be NULL. It should be updated before
cleanup.
> Update ovirt vm instance before cleaning up

- virttest/virsh.py
Add the existing virsh command to the virsh API.
> Add hypervisor-cpu-baseline command

- virttest/qemu_monitor.py
> Do not force use int type for 'fd' in qmp command

- avocado_vt/plugins/vt_joblock.py
Which got converted from a list into its own class, which contains
a property with the actual list of tests.
Reference: https://github.com/avocado-framework/avocado/pull/3980
> Make JobLock plugin compatible with latest Avocado's test suite

- virttest/utils_test/libvirt.py
Extend the search content type to list and str. Originally only str is supported.
> Enhance the pattern search

- virttest/utils_conn.py
Wrong /etc/hosts config lead to follow error:
authentication failed: Failed to start SASL negotiation: -1 (SASL(-1):
generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code
may provide more information (Server libvirt/****@REDHAT.COM
not found in Kerberos database))
> Fix wrong config in tls connection

- virttest/utils_test/__init__.py
session.sendline will send the command line and ignore its return,
sometimes this will prevent the pattern check of next command, use
"session.cmd" instead of it. Also, update the parent sendline with
"process.run".
ID: 1854114
> VMStress: Replace session.sendline to session.cmd

- virttest/ovirt.py
- virttest/utils_v2v.py
1) Fix not found update_instance issue
2) Fix incorrect waiting vm startup timeout issue
2020-07-03 06:20:44,055 ovirt            L0208 INFO | VM Auto-esx6.7-rhel7.5-sr04Nl status is <Down>
2020-07-03 06:20:44,056 ovirt            L0235 INFO | Starting VM Auto-esx6.7-rhel7.5-sr04Nl
2020-07-03 06:21:50,110 utils_v2v        L1320 ERROR| Start Auto-esx6.7-rhel7.5-sr04Nl failed: Timeout expired when waiting for VM to START, actual state is: up
2020-07-03 06:21:50,202 ovirt            L0335 INFO | Delete VM Auto-esx6.7-rhel7.5-sr04Nl
> Fix update_instance and vm start timeout issue

- avocado_vt/test.py
It raises an exception if there is no libvirtd.log for some
reasons. Fixup this issue in this PR.
> Fixup an error while archiving libvirtd debug logs

- virttest/libvirt_xml/devices/disk.py
Allow for supported attribute //disk/boot@loadparm.
> Add loadparm attribute to disk xml

- virttest/libvirtd_decorator.py
The way the current check for the libvirt version is done, at the
module level, means that the code will called even if Avocado-VT
is never used or the check is never needed.  For instance, running
an Avocado job with a simple "passtest.py" results in:
$ ./examples/jobs/passjob_html.py
WARNING:root:libvirtd -V
WARNING:root:libvirt version value by libvirtd or virtqemud command: ['libvirtd (libvirt) 5.6.0']
JOB ID     : 1d7dfcb1e047acee1abc8cf656cb91f9f7463bd1
JOB LOG    : /home/cleber/avocado/job-results/job-2020-07-06T09.57-1d7dfcb/job.log
(1/1) examples/tests/passtest.py:PassTest.test: PASS (0.00 s)
JOB HTML   : /home/cleber/avocado/job-results/job-2020-07-06T09.57-1d7dfcb/results.html
With this change, it …
> libvirt check: delay the actual check until/if needed

- virttest/libvirt_xml/vm_xml.py
Define a static constructor method to create a
VMCPUXML intance valid for cpu-compare.
> Add method to construct cpu xml from domcapabilities

- virttest/utils_conn.py
Otherwise the error message will be: Certificate check failed
Certificate [session] owner does not match the hostname
> Now more information is needed when the certificates generated

- virttest/qemu_vm.py
The some attributes from block device info are json format
if the image format is luks.
e.g:
{"execute": "query-block", "id": "KXntTIed"}
{"return": [{..., "inserted": {..., "filename": "json:{"driver":
"luks", "file": {"driver": "file", "filename": "/virtio-scsi.luks"},
"key-secret": "image_encrypt"}", ..., "file": "json:{"driver": "luks",
"file": {"driver": "file", "filename": "/virtio-scsi.luks"},
"key-secret": "image_encrypt"}",...}], "id": "KXntTIed"}
so filter out them into dictionary.
ID: 1853800
> qemu_vm: Support json format of luks in get_block_old

- shared/cfg/base.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
1. This is a global parameter for pcie-root-port except slot 0
2. This parameter work with 'pcie_extra_root_port' too
id: 1856690
> Support add extra params for pcie-root-port

- virttest/qemu_devices/qcontainer.py
On commit 91fe444, there was a mistake that raised AttributeError:
'NoneType' object has no attribute 'startswith' in the scenario where
the filename was None.
ID: 1860277
> qcontainer: Fix AttributeError: 'NoneType' object has no attribute

- virttest/staging/service.py
- virttest/utils_conn.py
- virttest/utils_libvirtd.py
Since libvirt 5.6.0, there are 3 genres of running libvirtd
daemons - traditional, monolith, modular daemons. This PR updates
Libvirtd() to handle all of these 3 types and adds DaemonSocket()
to manage tls/tcp sockets.
> Add a class for libvirtd/virtdproxy tls and tcp

- virttest/env_process.py
- virttest/test_setup.py
In split daemon environment, it needs to modify polkit related
settings in virtqemud.conf.
depends on https://github.com/avocado-framework/avocado-vt/pull/2646
> Fix polkit configuration issue in split daemon job

- virttest/libvirt_storage.py
Strip the binary_path to avoid following error which return incorrect
result.
debug output:
ERROR: Command '/usr/bin/qemu-img\n -h' failed.\n
> Fix check_qemu_image_lock_support problem

- virttest/libvirt_xml/checkpoint_xml.py
Uplayer product will frequently use 'checkpoint-dumpxml' and
'checkpoint-create --redefine' to redefine checkpoint, so we'll
need to test this. Add this function for convenience.
> Add a fucntion to save the xml from checkpoint-dumpxml

- virttest/utils_libvirtd.py
It was introduced by 447804fc, 'not' was deleted by mistake.
> Fixup Libvirtd.restart()

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_storage.py
- virttest/storage.py
Add support for qcow2 external data file.
New parameters:
`enable_data_file`: works when `image_format` is qcow2, will create
external data file(`root_dir/images/{image}.data_file` or specified by
`image_data_file_path`).
`image_data_file_path`: optional, used to specify the path to external
data file.
`image_data_file_raw`: if the data file is kept as a raw file.
id: 1828649
> Support qcow2 external data file

- requirements.txt
Limit the pthon version of "netaddr>=0.7.19" to 3, otherwise installing
requirements.txt via python2 will fail.
log:
```
$ pip2 install -r ./requirements.txt 
Double requirement given: netaddr>=0.7.19 (from -r ./requirements.txt (line 5)) (already in netaddr<=0.7.19 (from -r ./requirements.txt (line 4)), name='netaddr')
```
> Requirements: Fix netaddr version conflict on python2

- shared/cfg/base.cfg
- virttest/libvirt_vm.py
this patchs adds support to add TPM device
to libvirt guest xml via virt-install using
user params.
> Add TPM device support to virt-install cmdline

- backends/libvirt/cfg/tests-shared.cfg
- backends/qemu/cfg/tests-shared.cfg
- virttest/bootstrap.py
Rename host-os.cfg to host.cfg to better fit further additions to it.
Add vendor variant to host config inorder to refine tests to be choosen.
For example, there is a test specific to Power9 HW, and
we do not need to run on Power8 HW provided, this will help
in those cases, test uses filter like `only HostCpuFamily.power9`
and similarly for intel, broadwell family file like
`only HostCpuFamily.broadwell` etc.
Today we do such checks inside the test and skip, which is
unnecessary and takes additional test run time, with this change
we do skip the test before even it starts, to be presice the test
will not be even selected to run in those environment.
Usage examples in test configs:
only HostCpuFamily.power9
only HostCpuFamily.power8
no HostCpuFamily.power8
only HostCpuFamily.power9.2.1 => …
> Add vendor variant to host-os config

- virttest/migration.py
It usually takes more time in testing. To avoid this error,
extend it to 240s.
> Extend timeout for verifying IP address of migrated VM

- virttest/utils_misc.py
The content of /sys/devices/system/node/node*/meminfo may have space
after the last '\n', and will cause AttributeError.
e.g.
>>> file = '/sys/devices/system/node/node1/meminfo'
>>> data = os.popen('cat %s' %file).read()
>>> data.split('\n')[-1]
''
>>> data.strip().split('\n')[-1]
'Node 1 HugePages_Surp:      0'
id: 1862866
> NumaInfo: Fix 'NoneType' object has no attribute 'groups' error

- virttest/utils_v2v.py
When exception occurs in _v2v_pre_cmd, the code goes to finnaly and will
report 'target_obj' referenced before assignment. This error cannot reflect
the root cause.
This patch fixes the error information.
> Improve error report when exception happens before Target initialization

- .cirrus.yml
Turns out that the "-e" option is not a requirement for installations
from GIT.  The side effect of having that flag, is that a "python
setup.py develop" ended up being called, which did not create the
necessary directories and caused the failures in the comments:
```
```
Without '-e', a common installation occurs, and that failure is no
longer present.
Reference: https://github.com/avocado-framework/avocado/issues/3462
> Cirrus CI: drop editable requirements from GIT based installs

- virttest/utils_test/libvirt.py
Existing codes only support busNr for target. Now we need to extend it to support more items,
like hotplug, chassNr and so on.
> Extend contr target

- virttest/qemu_devices/qcontainer.py
For most OS, it is the default path of EDK2 (default path for
aarch64: /usr/share/edk2/aarch64/QEMU_EFI-pflash.raw).
Signed-off-by: Chen Qun <kuhn.chenqun@huawei.com>
> qcontainer: change EFI pflash path for different OS in aarch64

- virttest/env_process.py
- virttest/test_setup.py
- virttest/utils_conn.py
- virttest/utils_libvirtd.py
There is a new method to check if modular daemon is enabled on
local and remote, so update accordingly.
> Adjust to the modular daemon environment checking change

- virttest/bootstrap.py
Some of the cpu utils are not implemented yet for certain cpu
arch yet due to which we would encounter below error,
during the vt-bootstrap
```
create_host_os_cfg(options)
File ".../virttest/bootstrap.py", line 355, in create_host_os_cfg
family = cpu.get_family() if hasattr(cpu, 'get_family') else None
File ".../avocado/avocado/utils/cpu.py", line 188, in get_family
raise NotImplementedError
NotImplementedError
```
Let's handle the same, additionaly populate the vendor
information in the config only if available.
Reported-by: Yanan Fu <yfu@redhat.com>
> Fixup: Handle cpu util failures on non implemented arch

- virttest/utils_config.py
> Fix get_conf_obj() to create config obj on non-modular daemon

- virttest/libvirt_xml/vm_xml.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2652
Currently, only //disk/boot@order can be set.
Add a method to allow also for //disk/boot@loadparm.
> Add method to handle all boot attributes

- virttest/utils_nbd.py
The function build_server_key has been modified to avoid the error msg
"Certificate check failed Certificate [session] owner does not match
the hostname". Updated the argument here.
Signed-off-by: iccaszhulili <lizhu@redhat.com>
> Add the server's ip info when the certificates generated

- .cirrus.yml
- avocado_vt/loader.py
- avocado_vt/options.py
- avocado_vt/plugins/vt.py
- avocado_vt/plugins/vt_bootstrap.py
- avocado_vt/plugins/vt_init.py
- avocado_vt/plugins/vt_joblock.py
- avocado_vt/plugins/vt_list.py
- setup.py
- virttest/bootstrap.py
- virttest/compat.py
- virttest/data_dir.py
- virttest/standalone_test.py
The primary goal of this PR is to support the new Avocado settings implementation, which is in itself, very different from the current one.  All of Avocado itself has been ported to the new API, but the `avocado.core.settings` module has not yet been removed and replaced by the new because Avocado-VT is missing compatibility.  See:
https://github.com/avocado-framework/avocado/pull/3944
This PR brings the best support I could come up with for the different Avocado versions, including the one with Avocado PR 3944 merged.  This is why there's a commit called `[REMOVE ME]: Test with avocado new settings implementation`, which adds a Cirrus CI task that checks Avocado-VT compatibility with the proposed changes in Avocado.
This needs to be thoroughly tested, just as some of the previous mass …
> Avocado compatibility: support for thew new settings [v2]

- virttest/libvirt_vm.py
Sometimes vm fails to start, but there is no detailed error message printed out.
> Add debug info

- virttest/virsh.py
> Minorfix: Make a copy for globals to avoid RuntimeError

- virttest/utils_test/libvirt.py
Signed-off-by: Han Han <hhan@redhat.com>
> virttest: Delete scsi disk before scsi_debug mod unload

- virttest/arch.py
- virttest/env_process.py
- virttest/unittests/test_utils_kernel_module.py
- virttest/utils_kernel_module.py
1. arch.get_kvm_module_list: Update kvm module list for powerpc and s390
2. Add support to handle the kvm_probe module.
3. Improve "reload_module" and "restore" methods which provided by
utils_kernel_module, now they will unload the module and those used by
this one.
ID: 1836116, 1836123
> env_process: Handle the kvm_probe module together

- virttest/utils_conn.py
This is to fix an incorrect replacement in commit 30c34c8e8.
With old implemention, the libvirtd daemon can not be started because of
the incorrect configuration in /etc/libvirt/qemu.conf like below:
chardev_tls_x509_cert_dir=\\"/etc/pki/libvirt-chardev\\"
> Fix an issue for TLS

- virttest/utils_misc.py
Starting with Avocado version 81.0, the "avocado.core.status" module
is being renamed to "avocado.core.teststatus", given that the "status"
namespace is being kindly requested to hold a much larger module
structure.
> Conditionally import Avocado's test status constants

- avocado_vt/conf.d/vt.conf
- avocado_vt/conf.d/vt_joblock.conf
With the new Avocado settings module, configuration file content takes
precedence over builtin defaults.  With this new model, the current
configuration files are breaking Avocado-VT when used with the latest
Avocado.
By commenting them out, we leave them as examples only, and users can
uncomment and enable only their specific configurations.  Fortunately,
Avocado-VT doesn't *need* the settings on the configuration files even
when running with Avocado 69.x LTS.
This should fix the Cirrus CI checks with the latest Avocado.
> Configuration files: provide them as example only

- virttest/utils_conn.py
- virttest/utils_nbd.py
Also update build_CA() and build_server_key() to wrap ca_cakey_path
into credential_dict.
When access local libvirtd from remote host via tls protocol, we
will need to create server cert on local host and client cert on
remote host, and reuse the CA cert created for tls access from
local to remote previously.
> Update TLSConnection client_setup() to reuse previous CA cert

- virttest/libvirt_xml/network_xml.py
- virttest/utils_test/libvirt.py
- Add dict-attr 'port' to network xml
- Update function create_net_xml() to support 'port'
- Fix error that net_name being overwritten by params['net_name'].
Before fix, if we provide a name by setting var 'net_name' but not
set on params['net_name'], the var will be overwritten to 'default'
> Add port to network xml

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
The base image directory parameter was ignored in some cases of image
creation where it should override the default path for this.
> Reuse the unified image directory upon vm image creation

- virttest/openvswitch.py
This issue is from #2611, CmdResult.stdout is a raw stdout (bytes), and
"list_br" needs to return a string list.
ID: 1871741
> openvswitch: fix "list_br" returns byte-like issue

- virttest/utils_libvirtd.py
Extract logic from tp-libvirt commit 7a213bd18c49ccd6f135a7aac131036543337a78 (https://github.com/autotest/tp-libvirt/pull/2513)
into new function in avocado-vt for reuse.
By removing the autostarted file behavior of daemon at reboot can be simulated
regarding storage autostart behavior.
> Add new function for autostart handling

- virttest/remote.py
- virttest/utils_logfile.py
This is to remove remote.py's dependant on utils_misc.
The exsiting dependancy is only for some utilities of log file.
Put the log file utilities into a new module to make it standalone.
Existing remote.py is too messed up, so we need to lessen the dependancy
as much as we can do.
> Remove the dependancy on utils_misc

- virttest/kernel_interface.py
1. kernel_interface: Avoid repeated calls to 'fs_value'
2. kernel_interface: check fs existing or not with correct target
id: 1871870
> kernel_interface: check fs existing or not with correct target

- virttest/libvirt_xml/devices/memory.py
'uuid' is a sub-element under <memory> tag
> Add 'uuid' to memory device

- shared/cfg/base.cfg
- virttest/qemu_monitor.py
- virttest/qemu_vm.py
1. qemu_monitor: get supported hmp cmds from qmp monitor when it is needed
2. qemu_monitor: Make 'set_link' only accept on/off from now on
3. qemu_vm: Support boot vm with '--preconfig'
1. Use 'qemu_preconfig' to determin if boot vm with "--preconfig"
2. In migration scenario, '--preconfig' with dest is meanningless,
remove it.
3. Skip some steps that are meanningless under 'preconfig' status
4. "query-cpu-fast" that be used to generate "vm.vcpu_threads" is
not permitted under preconfig status, so generate this property
only when it was called.
4. qemu_monitor: Add exit_preconfig method
id: 1871156
> Support boot vm with '--preconfig'

- virttest/utils_libvirt/libvirt_network.py
It's required by some migration cases for now.
> Add a func to create or delete network on local/remote

- avocado_vt/plugins/vt_joblock.py
With the resolver/nrunner implementation, there won't be the
traditional "test factories" in the test suites, but Tasks.
This attempts to fetch the class from the test factory, and ignores if
it fails, which would happen if a Task is there instead.
This leniency isn't a problem because the joblock plugin should only
enforce a lock if a VT (VirtTest) test in within the test suite, which
won't happen at this point as there's no resolver for VT tests.
Fixes: https://github.com/avocado-framework/avocado/issues/4102
> VT Joblock plugin: be lenient with test suites containing Tasks

- virttest/env_process.py
get_family() method is not yet implemented for certain cpu archs like
amd, arm in avocado cpu utils so while using in the generic code path
like in below libraries hit unwanted error, So let's handle it.
```
Reproduced traceback from: /usr/lib/python3.8/site-packages/avocado_vt/test.py:442
File "/usr/lib/python3.8/site-packages/virttest/error_context.py", line 135, in new_fn
return fn(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/virttest/env_process.py", line 932, in preprocess
cpu_family = cpu_utils.get_family() if hasattr(cpu_utils, 'get_family') else cpu_utils.get_cpu_arch()
File "/usr/lib/python3.8/site-packages/avocado/utils/cpu.py", line 188, in get_family
raise NotImplementedError
NotImplementedError
```
Reported-by: Plamen Dimitrov …
> Fixup: Handle cpu utils failure on AMD and ARM cpu archs

- virttest/utils_hotplug.py
To support creating a mem device xml with specific uuid
> Add param 'uuid' to function create_mem_xml

- virttest/migration.py
Before, vm connect_uri was reset to 'qemu:///system' in ping_vm()
unexpectedly when parameter uri is passed to ping_vm(). We should
backup the original value and restore it after ping is done.
> migration: backup and restore vm connect_uri in ping_vm()

- virttest/utils_libvirt/libvirt_config.py
In some cases, it needs to remove remote_mode key from the
libvirt.conf if modular daemon is enabled.
> Add a function to remove config key for modular daemon env

- virttest/utils_disk.py
Generate some random data to a vm's disk, without mkfs, etc. This
is mainly used for incremental_backup function for now.
> Add method to generate some random data to vm disk

- virttest/bootstrap.py
- virttest/env_process.py
Some routines would request the information of host cpu family for
branch selection, so we need to suppress all the exceptions to ensure
that the whole procedure won't be interrupted.
Reported-by: Qinghua Cheng <qcheng@redhat.com>
ID: 1878675
> Handle the failures when getting host cpu family

- virttest/utils_test/libvirt.py
To start vm correctly, we need to change ownership to 'qemu:qemu'
if the source file is located in no_root_squash NFS.
> Update set_vm_disk to change the ownership of the file on nfs

- virttest/libvirt_cgroup.py
Previously the io.bfq.weight file has something like "100",
but now it could be "default 100". So we need to get the number
correctly.
> Get correct value from io.bfq.weight file

- virttest/env_process.py
cpu_family could be 'None' according to function get_family(), and
'NoneType' is not iterable. Therefore check whether it's None or not
before string comparing.
> env_process:check value of cpu_family in case it's None

- virttest/utils_net.py
The output of cmd "which <cmd>" includes a trailing "\n", which
leads to the failure of cmd "arping/ip".
> utils_net: Strip the output of cmd "which arping"

- virttest/utils_conn.py
It reports an error - module 'aexpect.remote' has no attribute
'RemoteFile' when creating TLSConnection or TCPConnection.
> utils_conn: Fix no attribute 'RemoteFile' issue

- virttest/staging/utils_cgroup.py
Gather all types of cpu times instead of only one type, so that
user can decide which one to use.
id: 1875683
> utils_cgroup: update 'get_load_per_cpu' to get all types of cpu times

- virttest/utils_misc.py
- virttest/utils_v2v.py
If a server has bad network connection with NFS storage, v2v may
starts nbdkit timeout. This patch checks parts of files' md5sum in
vddklib and compare it with local vddklib, re-copy to local if they
are different. When cases use different vddklib versions, it checks
the local vddklib version and only copy it when the new vddklib does
not exist on local server.
All new vddklib are copied to local server in name 'vddklib_x'. The
'latest' is a link to currently using vddklib.
The directories look like:
/var/tmp/vddklib_dir/latest -> /var/tmp/vddk_libdir/vddklib_1
/var/tmp/vddklib_dir/vddklib_1
/var/tmp/vddklib_dir/vddklib_2
...
> v2v: copy vddklib from NFS to local

- virttest/utils_test/libvirt.py
By allow one more parameter:image_owner_group, it allow change image ownership before vm start
This is necessary in certain situations
> Extend set_vm_disk with one more parameter:image_owner_group

- virttest/staging/utils_cgroup.py
This is a issue introduced by commit:
0099798c8be9b073e59475a21ac05c31ec15ccec
id: 1875683
> utils_cgroup: hotfix for missing one list of elements

- requirements.txt
Somehow,current aexpect version leads to bootstrap error,
and upgrade to 1.6.0 afterwards, the issue can be fixed
> Upgrade aexpect version request to 1.6.0+

- virttest/bootstrap.py
We use "diff" to visualize differences between config files.
> virttest.bootstrap: Add "diff" to list of required programs

- shared/cfg/machines.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
machines.cfg:
1. Introduce aavmf params to configure aarch64's pflashs from cfg
qemu_vm.py
1. Migrate pflash handler from qemu_vm.py to qcontainer.py
qcontainer.py:
1. Add a method to handle pflash firmware
2. Handle pflash only on supported machine types
3. Split pflash command from 1 to 2 if using `-blockdev`
ID: 1883407
> Enhance EFI boot process at q35 chip and aarch64 platform

- virttest/utils_test/libvirt.py
It reports 'aexpect.remote' modula has no attribute 'run_remote_cmd'.
> Fix no attribute 'run_remote_cmd' issue

- setup.py
The latest release, aexpect 1.6.1, contains Python 2
incompatibilities.  Let's pin it to 1.6.0 or earlier on those
circumstances.
> setup.py: use older and compatible aexpect on Python 2

- virttest/utils_test/__init__.py
By default, guest tests use python2 and pip2 as default. The tests failed
when trying to install avocado plugins it installs a different version
that not satisfy by avocado. We can't remove python2 support,
but we can change a priority to use python3/pip3
Signed-off-by: Oksana Vohchana <ovoshcha@redhat.com>
> Change priority to use python3 and pip3

- virttest/utils_test/libvirt.py
Assign '{}' to  'nat_attrs' as default value to avoid eval()
taking 'None' as input param.
> Fix up:Update default value of 'nat_attrs' of create_net_xml()

- virttest/data_dir.py
Testprovider download dir should be under 'virttest'
> Fix error #2808 brought in: testprovider download dir path changed

- requirements.txt
On centos 7.1, it use python 2.7 and need relatively lower aexpect version
> Fix centos 7.1 cirrus failure issue due to aexpect

- virttest/utils_libvirt/libvirt_pcicontr.py
This is to add an utility function to help obtain the maximum controller indexes of
given guest xml. The user can specifiy how many indexes they want.
> Add util func for controller

- virttest/qemu_devices/qcontainer.py
format node: set read-only = false
protocol node: set auto-read-only = true, discard = unmap
ID: 1882628
> Sync blockdev options with libvirt

- avocado_vt/plugins/vt_init.py
When running with Avocado 82.0, is_registering_settings_required()
returns True, settings will be registered, default value of mem is ''.
Setting of mem in 'base.cfg' or other config files from test provider
will not take effect if 'mem' is registered as empty string, changing
to 'None' could fix it.
> Change default value of 'mem' from empty string to 'None'

- virttest/libvirt_xml/backup_xml.py
BZ1829829 introduced two new attributes - 'backupmode' and
'incremental', for backup xml's disk element. This patch is to
support them.
> Add new attribute support for backup xml

- virttest/utils_backup.py
These 2 attributes are to make sure newly attached disk can be
backuped with existing disk who already has checkpoints.
> Add ability to set backup disk's 'backupmode' and 'incremental'

- .travis.yml
Remove allow_failures for python 3+, and add more disable lint items to allow travis test pass
> Add multiple python version with python 3.6 afterwards in travis ci

- virttest/utils_backup.py
- virttest/utils_config.py
Libvirt-6.6.0-1.el8 starts to support TLS authentication for pull mode
incremntal backup, we need to support dumping the data from TLS
enabled NBD export to local image.
> Support to dump data from NBD export with TLS in backup function

- virttest/utils_config.py
- virttest/utils_test/libvirt.py
There are 8 sub daemons instead of a libvirtd when modular daemons
are enabled. In previous code, it changed 'libvirtd' to 'virtqemud'
for modular daemons env which fixed some problems. But for now, we
still need to support other daemons. So it is extended to all
modular daemons.
> Update customize_libvirt_config for modular daemons

- virttest/utils_net.py
If the openvswitch service is not running on the host, we should
start it before testing.
> utils_net: Update to start openvswitch if needed

- virttest/libvirt_xml/vm_xml.py
- virttest/utils_libvirt/libvirt_keywrap.py
1. Add helper class to handle commands for working with protected keys.
2. Add keywrap element to XML to control keywrap configuration.
> Add protected key support

- MANIFEST.in
With commit ba63274, virttest/passfd.c is not being packaged.  Let's
add it to the manifest file.
> Add virttest/passfd.c back to packages

- virttest/qemu_devices/qcontainer.py
Currently, the `pflash_vars_path` is in relative path under `pwd`, which
is not correct. Move it to absolute path of "data_dir.DATA_DIR/images".
Also, force "backing_chain = no".
ID: 1899392, 1900486
> qcontainer: fix pflash_vars file in relative path

- virttest/libvirt_xml/devices/hostdev.py
- virttest/unittests/test_utils_zcrypt.py
- virttest/utils_zcrypt.py
1. utils_zcrypt: add s390x crypto device helpers
CryptoDeviceInfoXXX:
Add classes to store crypto device info on s390x systems
obtained from 'lszcrypt' for later passthrough setup.
load_vfio_ap:
Add method to assure passthrough driver is available.
APMaskHelper/MatrixDevice:
Add classes to control device availability and the matrix device
to be attached to the guest (details s. kernel doc).
2. libvirt_xml/devices/hostdev: add support for uuid address
Add support for `<address uuid="..."/>`.
Add support for `<hostdev model="..."/>`.
> virttest: add s390x crypto device support

- virttest/utils_v2v.py
Don't use '/var/tmp' to store vddklib to avoid accidentally file corruption.
> v2v: update vddklib path

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
- virttest/shared/cfg/base.cfg
Let some of the qemu opitons to be configurable, in order to support kata style vm template.
ID: 1902565
> Support kata style vm template

- virttest/utils_backup.py
When create a checkpoint along with a backup, a bitmap will be
added in qcow2 file. This function is to get all bitmap names
from a qcow2 image.
> Add a method to get image's bitmap names for backup feature

- virttest/utils_disk.py
Add a timeout parameter for getting multiple
disks in windows.
ID: 1699204
> utils_disk: Add a timeout parameter

- virttest/env_process.py
- virttest/shared/cfg/base.cfg
- virttest/utils_test/__init__.py
Introduce a new param to configure the kernel command line
Introduce kernel_extra_params_serial_login to configure the kernel command line in env_process, sometimes the guest does not have a serial session available. The issue is from #2564
ID: 1899377
> env_process: Introduce a new param to configure the kernel command line

- avocado_vt/loader.py
- avocado_vt/plugins/vt.py
- avocado_vt/plugins/vt_init.py
- avocado_vt/plugins/vt_list.py
- virttest/compat.py
Right now when we want to run tests through avocado Job API the avocado-vt is
not loaded, because a lot of avocado-vt settings is initialized through CLI
plugin. This commit moves the initialization to the Init plugin and leaves CLI
plugin just for necessary command line setup
Signed-off-by: Jan Richter jarichte@redhat.com
---
Changes form v1:
- put style fixes to the separated commits
- usage of `virttest.compat`
> Initialization with Job API [v2]
