avocado-framework/avocado-vt

- virttest/qemu_virtio_port.py
- virttest/qemu_vm.py
> qemu_virtio_port: Support tcp/udp socket backend

- virttest/test_setup.py
> Minorfix: Fixup the polkit user error

- virttest/libvirt_xml/vm_xml.py
Also update del_controller func
> Add get_controllers func

- virttest/utils_disk.py
For commits utils_disk: Add disk resize related functions:
1. Add get_partition_attrs_linux() to get a disk
partition's attributes in linux geust.
2. Add get_mpoint_fstype_linux() to get a disk
partition's file system type and mountpoint.
3. Add resize_filesystem_linux() to resize a partition's
filesystem in linux guest.
4. Add resize_partition_linux() to resize a disk
partition's size in linux guest.
5. add get_disk_size_windows() to get a disk size in windows guest.
6. add get_disk_size_linux() to get a disk size in linux guest.
7. add get_disk_size() to get a disk size in guest.
id:1664992
> utils_disk: Add disk resize related functions 

- virttest/utils_test/__init__.py
print nothing if install stress application from local
> fix logical error in download_stress function

- virttest/utils_test/__init__.py
> fix tmp_dir not exists issue

- shared/cfg/guest-hw.cfg
- virttest/qemu_vm.py
- virttest/test_setup.py
> guest-hw: Add suffix for rng param to avoid name conflict

- virttest/env_process.py
Perform updating kernel params inside preprocess_vm() and cleanup
in postprocess_vm() by doing so,
* vm specific kernel params can be provided for multivm cases
* `start_vm` check and creating/starting vm is taken care
for libvirt and qemu test.
* re-iteration of vm objects and re-checks can be avoided
Reported-by: Yongxue Hong <yhong@redhat.com>
Suggested-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
> env_process: refactor updating kernel params during pre/postprocess

- virttest/utils_net.py
- virttest/utils_windows/virtio_win.py
1 Add netkvmco.dll copy path in virtio_win.py
2 Add set/get netkvm params in utils_net.py
id:1566941
> Add set/get netkvm params function for netkvm driver in windows

- shared/deps/serial/VirtIoChannel_guest_send_receive.py
- shared/deps/serial/serial_host_send_receive.py
- shared/deps/serial/windows_support.py
- virttest/utils_test/__init__.py
Make it running on py2 and Linux first, will fix py3 and Windows issue later separately
id: 1724987, 1734208, 1734210
> run_virtio_serial_file_transfer: make serial data transfter script work

- virttest/env_process.py
> Correct the version matching regex

- virttest/qemu_vm.py
> fix TypeError when create serial device

- shared/cfg/base.cfg
- virttest/gluster.py
- virttest/utils_misc.py
- virttest/utils_test/libvirt.py
1. Add session part
2. update the existing gluster related func with gluster-server infomation
> Update for outside gluster server

- shared/deps/serial/serial_host_send_receive.py
> serial_host_send_receive: Support pty backend

- virttest/test_setup.py
SysFS() API introduced in utils_misc is generic for host/guest/remote host
and reduces the file operations, adopt it for refactoring.
> test_setup: refactor TransparentHugepageConfig() to adopt SysFS() API

- shared/cfg/guest-os/Linux/RHEL/7.7.cfg
- shared/cfg/guest-os/Linux/RHEL/7.7/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.7/ppc64le.cfg
- shared/cfg/guest-os/Linux/RHEL/7.7/x86_64.cfg
> guest-os: Add RHEL7.7 guest os configuration

- virttest/libvirt_vm.py
> Log error when fails to create serial console

- virttest/utils_test/libvirt.py
> Add new function update_vm_disk_driver_cache()

- virttest/utils_virtio_port.py
> utils_virtio_port: Align to new chardev definition rules

- virttest/qemu_devices/qcontainer.py
> qcontainer: Fix aio unset error

- virttest/qemu_devices/qdevices.py
> qdevices.CharDevice: correct verify_hotplug/unplug pattern

- virttest/qemu_vm.py
1. QEMU represents the primary watchdog device by using the
'-device' expression, so change the command line to:
> -device $watchdog_device
And, drop the old usage "-watchdog $watchdog_device_type"
2. Some type watchdog device occupies a slot, but without parent
bus, StrDev doesn't consume pci slot in auto code which will cause
the subsequent device get non-free slot. Add "parent_bus" to solve
this problem
3. when test hotplug pci device then migrate, the pluged device will
be added to the params, dst qemu will create commands using new
params. If the pluged device be created before wantchdog, it will
cause the device's slot don't match with src qemu, so move watchdog
to the font.
id: 1748742
> qemu_vm: Specify parent bus when add watchdog device

- shared/cfg/guest-hw.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_storage.py
- virttest/storage.py
This aims to provide support new image format luks and luks encryption
for qcow2 image. Currently, only limited functions are included:
1. image creation(snapshot)
2. vm creation
3. image check
Usage:
1. luks
"""
image_secret = redhat
image_format = luks
"""
2. luks-encrypted qcow2
"""
image_format = qcow2
encryption = luks
image_secret = redhat
"""
> luks support

- virttest/utils_v2v.py
Reference: https://itsfoss.com/check-uefi-or-bios/
> Update way of checking UEFI for linux guest

- virttest/utils_test/libvirt.py
Need detailed result to report proper error message in test script.
> Update connect_libvirtd to return detailed result

- virttest/env_process.py
These hooks can then be used by custom code for additional stages
during environment setup and cleanup when the vms are on and/or off.
> Add vm pre- and post-processing hooks for on/off vm stages

- .cirrus.yml
- contrib/containers/ci/rhel-8.docker
Add some description that might speed-up the future reviews and expand the RHEL CI coverage by mocking the required deps.
> Cirrus: Follow-up after initial implementation

- virttest/utils_conn.py
From libvirt 5.6, need to start below sockets, *before* libvirtd
itself is started to enable tls/tcp connection.
1. systemctl start libvirtd-tls.socket
2. systemctl start libvirtd-tcp.socket
Again, for recovery, stop sockets because they are inactive 
by default.
> utils_conn: update to start socket before libvirtd started

- virttest/qemu_storage.py
1. add image resize support for luks.
2. support preallocation mode in resize.
> virttest.qemu_storage.QemuImg.resize: support luks

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
Add ringbuf chardev parameters to hotplug
id:1588424
> qdevices:Get chardev hotplug requried args of ringbuf

- virttest/utils_hotplug.py
> Add alias for memory xml

- virttest/qemu_storage.py
1. refactor `QemuImg.convert`
1.1. add support to convert from/to luks or luks-encrypted qcow2 images.
1.2. return params of convert image params to instead of the source
image tag.
1.3. two parameter changes:
i. `cluster_size` to `image_cluster_size`.
ii. `compat` to `qcow2_compatible`.
1.4. deprecate previous way to specify commit target image, and add new
parameter `convert_target` to specify which image object defined by
params is the convert target image.
EXAMPLE:
```
images = "image1 image2"
image_name_image1 = example
image_format_image1 = qcow2
convert_target_image1 = image2
image_name_image2 = demo
image_format_image2 = luks
image_secret_image2 = aloha
```
The reasonale behind this is to support luks as convert target, the
final command line should include the secret object from …
> virttest.qemu_storage.QemuImg.convert: support luks

- virttest/qemu_storage.py
1. add support of luks in method commit.
2. add `base` to specify base image to commit to.
3. add `drop` to support drop image after commit.
> qemu_storage.QemuImg.commit: support luks

- virttest/utils_test/libvirt.py
This PR updates set_vm_disk() and create_controller_xml() in
utils_test/libvirt to set model for disk and controller.
There are 2 ways to make virtio device work with legacy guest drivers.
1. Update 'model virtio-transitional' in disk
2. Update model for controller
This is required by legacy guest migration case for now.
> Update set_vm_disk and create_controller_xml to make disks work with model

- virttest/libvirt_xml/devices/disk.py
- virttest/libvirt_xml/devices/input.py
> Add model for input/disk device

- virttest/libvirt_xml/vm_xml.py
vm_xml: add firmware attribute in os tag
> vm_xml: add firmware attribute in os tag

- virttest/qemu_storage.py
1. add support of luks in rebase, which will cover:
1.1. rebase to a luks image
1.2. rebase a luks-inside-qcow2 image
> qemu_storage.QemuImg.rebase: support luks

- virttest/utils_test/libvirt.py
Need to cleanup disks before attach in some cases, so add an entry
to remove all disks before testing.
> Minorfix: Update to able to remove disks

- virttest/utils_test/libvirt.py
- virttest/virsh.py
Add iscsi-direct pool to valid pool type
> Add iscsi-direct pool to valid pool type

- virttest/utils_test/libvirt.py
Add a function to delete the filterref in interface class.
> Add del_filter in interface class

- virttest/utils_config.py
> Add 'vnc_tls_x509_secret_uuid' parameter in qemu.conf

- shared/cfg/guest-os/Linux/RHEL.cfg
- shared/cfg/guest-os/Linux/RHEL/7.6.cfg
- shared/cfg/guest-os/Linux/RHEL/7.6/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.7.cfg
- shared/cfg/guest-os/Linux/RHEL/7.7/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.devel.cfg
- shared/cfg/guest-os/Linux/RHEL/7.devel/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/8.cfg
- shared/cfg/guest-os/Linux/RHEL/8/8.devel.cfg
- shared/cfg/guest-os/Windows.cfg
- shared/cfg/guest-os/Windows/Win10/i386.cfg
- shared/cfg/guest-os/Windows/Win10/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2012/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2016/x86_64.cfg
- shared/cfg/guest-os/Windows/Win2019/x86_64.cfg
- shared/cfg/guest-os/Windows/Win8/i386.cfg
- shared/cfg/guest-os/Windows/Win8/x86_64.cfg
…ation
ID : 1743608
Signed-off-by: Qing Wang <qinwang@redhat.com>
> Enable physical and logical block size 4096 on ovmf installation

- virttest/libvirt_xml/devices/interface.py
interface.py: add ip element as user type interface can set ip address
in the interface section.
> Add ip element to support user type interface customer ip setting

- virttest/qemu_devices/qcontainer.py
Add support of luks for `-blockdev`.
> blockdev: support luks

- virttest/utils_net.py
Once there some blank space before the output of domiflist, the match
will fail.
> Add functions to get guest's nameserver and gateway

- virttest/utils_v2v.py
1) Add support for detecting availability of v2v options
2) Support manually set --mac option in cfg files.
Ex.
iface_macs = xx:xx:xx:xx:xx:xx:bridge:br0
or
iface_macs = xx:xx:xx:xx:xx:xx:bridge:br0;xx:xx:xx:xx:xx:xx:bridge:br1
3) Automatically set --mac option if available.
4) Rollback to -b/-n option if --mac is not available.
> Add --mac option support for v2v

- virttest/utils_conn.py
Feature changes from libvirt 5.6, so update accordingly.
1. tcp_port changes to 'ListenStream' in
/usr/lib/systemd/system/libvirtd-tcp.socket
2. tls_port changes to 'ListenStream' in
/usr/lib/systemd/system/libvirtd-tls.socket
3. unix_sock_dir configuration changes to 'ListenStream' in
/usr/lib/systemd/system/libvirtd.socket
4. unix_sock_rw_perms changes to 'SocketMode' in
/usr/lib/systemd/system/libvirtd.socket
> utils_conn: update configuration for TCP/TLS/UNIX connection

- virttest/qemu_vm.py
ID:1702654
rearrange code in 'make_create_command' to first initialize VM vcpu,
then to create block devices. This aims to support the optimal iothread
scheme that:
iothread_count = min(device, vcpu, pcpu)
> virttest.qemu_vm.VM.make_create_command: rearrange code

- virttest/utils_v2v.py
> Fix using wrong vmx disk path in NFS for v2v

- virttest/utils_v2v.py
Add support checking logs when it has multiple lines
> Improve v2v log checking function

- virttest/qemu_monitor.py
Query mice status in guest.
id: 1724061, 1724060
> qemu_monitor: Add query_mice function

- virttest/utils_v2v.py
The name of a guest in esx, the nfs path of esx guest files and the
name of vmx file may be different
For '-i vmx', It always needs to mount the nfs storage to local host,
so we can get the real vmx file name. But for '-i vmx -it ssh', NFS
storage don't have to be mounted, it's not worth mounting it and only
for getting the correct vmx file name. Luckily we can infer more than
95% guest's name by it's nfs disk path. And if the inference is wrong,
V2V will report an error. If v2v runs successfully, it can be sure
the name is correct.
If some corner guests cannot run successfully, you can set the correct
nfs source as in '-i vmx' for those corver scenarios.
> Fix vmx filename in '-i vmx' for v2v

- virttest/remote.py
- virttest/utils_v2v.py
1. Fix hanging up in v2v ssh connection
2. Fix cannot find function get_disk_source in vm_xml
> Fix ssh connection problem and wrong call get_disk_source issue

- virttest/libvirt_xml/devices/graphics.py
> Add copypaste attribute for graphics

- shared/scripts/virtio_console_guest.py
For 'is_console': yes, vtermno will start from '1..', which was
previously starting from '0'. 
ID:1770165
> virtio_console_guest:fix wrong way to store hvc with fixed kernel

- virttest/libvirt_xml/devices/graphics.py
> Add filetransfer attribute and update copypaste for graphics

- virttest/libvirt_xml/devices/graphics.py
> Add streaming attribute for graphics

- virttest/qemu_storage.py
id: 1777186
add new method `compare_to` to offer luks format compare operation.
> qemu_storage.QemuImg: add new compare method

- virttest/qemu_vm.py
suport 'mq=off' option test.
ID: 1585582
Signed-off-by: yanglei-rh <leiyang@redhat.com>
> qemu_vm: support 'mq=off' option

- virttest/utils_v2v.py
> Skip get mac address in some input_mode of v2v

- virttest/libvirt_xml/vm_xml.py
> Add memtune and cachetune xml in vm_xml

- virttest/utils_conn.py
For libvirtd >= 5.6, libvirtd.service may not stop directly and
can kick up by libvirtd.socket. And libvirtd*socket restart operation
needs libvirtd.service is in stop stats. To make it stop immediately,
update to stop libvirtd.socket before libvirtd.service.
BTW, in some case, close_session raise exception in clean up block
and recovery part will be skipped in previous code, fix it also.
> Fixup libvirtd*socket restart timeout issue 

- virttest/libvirt_xml/vm_xml.py
Need to add some vendor_id related cases.
> Add cpu vendor_id attribute

- virttest/utils_v2v.py
Add a new parameter 'skip_virsh_pre_conn' to control pre-connection
to source hypervisor.
By default, 'skip_virsh_pre_conn' is None, it means v2v will do pre-
connection to source hypervisor. In some testing envrionment, like
gating, It doesn't have source hypervisor to connect, you need to
set 'skip_virsh_pre_conn' to 'yes' to skip the connection.
> Add a switch to control virsh pre conn to source hypervisor

- virttest/utils_test/libvirt.py
> Add func add_panic_device

- virttest/qemu_storage.py
> qemu_storage: Support host device in function filename_to_file_opts

- virttest/utils_v2v.py
1) Rename get_vm_xorg to vm_xorg_search, use 'grep' instead of
'cat' to decrease unnecessary log printing
2) Add vm_journal_search for journal log checking
3) Add vm_general_search for general cmd output checking
> Add three functions for contents searching in VM

- virttest/utils_hotplug.py
- virttest/virt_vm.py
> Add mem_discard in create_mem_xml function

- shared/cfg/guest-hw.cfg
> rng_builtin: add support for virtio-rng new backend 'rng-builtin'

- virttest/utils_v2v.py
> Update xen uri for v2v

- virttest/qemu_devices/qdevices.py
> Supported secret object hotplug by qmp

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
> update device topology for Q35 machine

- virttest/qemu_devices/qcontainer.py
ID: 1755682
Signed-off-by: nanliu <nanliu@redhat.com>
> virtio_serial: Add virtio_serial extra params handle

- virttest/qemu_devices/qcontainer.py
> qcontainer: fix 'bus_params' referenced before assignment

- virttest/test_setup.py
1. Check if dnsmasq package exists before _start_dhcp_server
2. Use a better method to check ovs bridge
- If the bridge name contains digits, the bridge info is similar to the following:
```bash
$ ovs-vsctl show
65fbb3f9-b98f-4009-8c20-8eb725ba3d2a
Bridge ovsI
Port ovsI
Interface ovsI
type: internal
Bridge "ovs0"
Port "ovs0"
Interface "ovs0"
type: internal
ovs_version: "2.11.0"
```
- So `re.match` could not match it
https://github.com/avocado-framework/avocado-vt/blob/9acbffa1bd200be205c5cff771c0a1b3e277a80a/virttest/test_setup.py#L1005-L1012
- This will block the call to the cleanup method
https://github.com/avocado-framework/avocado-vt/blob/9acbffa1bd200be205c5cff771c0a1b3e277a80a/virttest/test_setup.py#L981-L984
ID: 1783859
> test_setup: Enhance code of create private bridge

- virttest/qemu_devices/qdevices.py
last function port address is hex device address (e,g.'0x1.0x7').
but original code check it with string '*.7' and caused bug#1800461.
Fixed bug by check if the slot can allocate a free function address.
ID: 1800461
> fix bug in get free pcie root port device

- shared/cfg/base.cfg
- virttest/qemu_monitor.py
- virttest/qemu_vm.py
ID: 1746246
please refer to test result of the patch: [autotest/tp-qemu #2060](https://github.com/autotest/tp-qemu/pull/2060)
> virtio_serial:support qmp monitor with tcp_socket chardev backend

- virttest/utils_v2v.py
> Enhance run_cmd function for v2v

- virttest/qemu_devices/qcontainer.py
ID: 1792851
Signed-off-by: Micky Yun Chan <michan@redhat.com>
> support 'to' option for chardev device with tcp_socket backend

- virttest/utils_stress.py
Update wrong import and usage of cpu utils
> Fixup: update wrong import and usage of cpu utils

- virttest/qemu_vm.py
Some test need use specified chardev_path and serial_name for
testing, make it accept these definiation.
If it is not defined, use the default value that generated by
the test framework.
id: 1786555
> virtio_serial: accept specified chardev_path and serial_name

- virttest/qemu_vm.py
regression of 4c707a7e42e85db587bacc2ccc7fddfef8c72b29
It changed qemu_monitor but missed to update hmp monitor
id: 1804530
> qemu_vm: Fix connect hmp monitor failed issue

- avocado-plugins-vt.spec
- setup.py
This fixes some missed variable changes and compatibility renaming details
> Spec file fixes

- virttest/utils_v2v.py
> Add two functions for version comparison

- virttest/utils_nbd.py
VM can directly consume multiple images exported by qemu-nbd
> add nbd server utils to support and wrap qemu-nbd command to export image

- virttest/guest_agent.py
The interface of class 'Monitor' have changed, update the param
name to make it more readable
id: 1806375
> guest_agent: update the param name as the meaning have changed

- virttest/graphical_console.py
- virttest/ppm_utils.py
Include mouse button down/up/press func,
mouse scroll up/down func,
and mouse move func.
id: 1724060, 1724061
> graphical_console: Add mouse related functions

- virttest/qemu_devices/qcontainer.py
id: 1786552
Signed-off-by: Micky Yun Chan <michan@redhat.com>
> Create named pipe for chardev backend pipe

- virttest/qemu_storage.py
1. Add "--output" option to the check_image.
2. Return the result of check_image.
ID: 1786420
Signed-off-by: Tingting Mao <timao@redhat.com>
> qemu_storage: Update the function of check_image

- virttest/qemu_devices/qdevices.py
> add function to test device is a virtio pcie device

- virttest/qemu_vm.py
Add iommu support for all virtio devices
ID: 1783824
> Add iommu support for all virtio devices

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_storage.py
- virttest/storage.py
1. Supported multiple remote images secret access
2. Enhanced create/info/convert with multiple images secret access
ID: 1778550 1778552
> Supported multiple remote images secret acess

- shared/cfg/guest-os/Windows/Win2012/x86_64.cfg
Add the filter "with_installation" to Win2012 cfg.
ID: 1731616
> guest-os: Add new filter to Win2012 cfg

- shared/cfg/guest-os/Linux/RHEL/8.cfg
- shared/unattended/Fedora-25.ks
- shared/unattended/RHEL-7-devel.ks
- shared/unattended/RHEL-8-devel.ks
Couple of fixes to RHEL8 kickstart/config and some unification with Fedora/RHEL7.
> shared: Fix RHEL8 os_variant

- virttest/tests/unattended_install.py
In case the test fails let's also attempt to log /var/log/messages and
"journalctl" outputs.
> tests.unattended_install: Attach messages and journalctl output

- virttest/utils_v2v.py
1) Make v2v_cmd more flexible, uses can now only generate command and
re-edit it, and run it later.
2) Support --no-copy arguments
> Improve function v2v_cmd and add support for --no-copy

- shared/scripts/virtio_console_guest.py
- virttest/qemu_virtio_port.py
ID: 1798383
Signed-off-by: Micky Yun Chan <michan@redhat.com>
> virtio_console_guest: Install module six if missing

- virttest/openvswitch.py
- virttest/utils_net.py
- virttest/utils_test/libvirt.py
> Add support for vhostuser+dpdk testing

- virttest/virsh.py
There are more options for blkdeviotune than before. So this is to
add those into this function.
> Add more params for blkdeviotune

- virttest/utils_test/libvirt.py
This function is to create tpm dev.
> libvirt: add function to create tpm device

- virttest/libvirt_xml/devices/disk.py
Slice is newly introduced attribute for disk
> Add slice attribute into disk xml

- virttest/utils_test/libvirt.py
> Add slice support in create_disk_xml

- virttest/guest_agent.py
Get host name, timezone and users info via qga command
ID: 1809416
> guest_agent: Add function of get basic info of vm

- shared/scripts/ksm_overcommit_guest.py
Signed-off-by: Han Han <hhan@redhat.com>
> Remove blank space before left parenthesis

- virttest/utils_conn.py
From libvirt 5.6.0, migration with tls and tcp needs to start
libvirtd-tls.socket and libvirtd-tcp.socket on target host. But
before that, we need stop libvirtd and must not start libvirtd
after xx.socket is started.
> Fix tcp tls for socket

- virttest/libvirt_xml/devices/disk.py
Add new method to create backingStore.
And add 'file' in backingStore new_source and fix xml.
> Add new_backingstore for disk

- virttest/utils_test/libvirt.py
Add on create_local_disk to create luks local file
Signed-off-by: jgao <jgao@localhost.localdomain>
> Add on create_local_disk to create luks local file

- virttest/test_setup.py
After libvirt-5.6.0, more polkit rules are needed to be setup.
Like,
if (action.id == "org.libvirt.api.network.read" &&
subject.user == "test1") {
if (action.lookup("connect_driver") == 'network') {
return polkit.Result.YES;
} else {
return polkit.Result.NO;
}
}
if (action.id == "org.libvirt.api.network-port.create" &&
subject.user == "test1") {
if (action.lookup("connect_driver") == 'network') {
return polkit.Result.YES;
} else {
return polkit.Result.NO;
}
}
...
> Fix polkit policy

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
Support snapshot on blockdev mode.
ID: 1740006
> Support snapshot on blockdev mode

- virttest/utils_test/libvirt.py
> Add nat/route support in create virtual network xml

- virttest/utils_config.py
- virttest/utils_split_daemons.py
New daemons are introduced due to libvirtd split feature
> Add split daemon and config class

- virttest/utils_test/qemu/__init__.py
> Update unplug_memory function to enable unplug memdev without dimm

- virttest/utils_test/libvirt.py
Some functions are used in several migration python files, so
move them to MigrationTest.
> Move some migration functions to libvirt.MigrationTest

- virttest/qemu_devices/qdevices.py
> qdevice: add 'pmem' option for memory backend

- virttest/libvirt_xml/devices/filesystem.py
> Add attributes for filesystem device

- virttest/step_editor.py
This is the minimum needed for Python 3 compatibility and update
of the GTK API from 2 to 3 is the minimal needed for the GObject
introspection compatibility layer.
> Update pygtk requirement to GTK3 compatibility layer

- virttest/utils_test/libvirt.py
1. Add 'forward_pf' in create_net_xml
2. Update function pci_lable_from_address to support generating
pci id
> libvirt: update to get pci_id from address and add forward_pf support

- virttest/utils_gdb.py
> [python3] Fix for getattr type return to Enum

- shared/cfg/guest-os/Linux/RHEL/7.8.cfg
- shared/cfg/guest-os/Linux/RHEL/7.8/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.8/ppc64le.cfg
- shared/cfg/guest-os/Linux/RHEL/7.8/x86_64.cfg
> guest-os: Add RHEL.7.8 guest os

- virttest/utils_misc.py
Fix new qemu-kvm version have no rhev issues
> Fix new qemu-kvm version have no rhev issues

- shared/cfg/guest-os/Linux/RHEL.cfg
Installation options setting for case "blockdev_commit_install"
id:1828140
> shared.RHEL:"blockdev_commit_install" installation options setting

- virttest/utils_test/libvirt.py
This is to enable the capabilities of configuring more parameters when creating a controller.
And it is also to support to only modify an exsiting vm xml object instead of a guest's xml.
> libvirt: split to controller create and add func

- virttest/guest_agent.py
Get virtio device of windows guest.
ID: 1824430 
> guest_agent: Add function of get virtio device of vm

- virttest/env_process.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
> Support virtio-fs filesystem

- virttest/utils_pyvmomi.py
- virttest/utils_v2v.py
> Add a new utils_pyvmomi module for vmware pyvmomi

- virttest/guest_agent.py
Take guest-fsfreeze-freeze-list and guest-fsfreeze-freeze to one
function.
ID: 1817348
> guest_agent: Add function of guest-fsfreeze-freeze-list

- virttest/utils_sriov.py
It's required by sriov migration test for now.
> Add sriov related functions

- virttest/migration.py
Some cases require different signals.
> migration: prameterize signal for do_cancel

- backends/v2v/cfg/convert_source.cfg
Signed-off-by: mxie91 <mxie@redhat.com>
> Add new source 'esx7.0' for v2v testeing

- virttest/libvirt_xml/devices/filesystem.py
> Add attribute 'xattr' for filesystem device

- virttest/libvirt_xml/vm_xml.py
> Add access_mode setting in vmxml.set_memoryBacking_tag()

- virttest/utils_test/libvirt_device_utils.py
> Add function to create filesystem device

- virttest/libvirt_xml/vm_xml.py
For new feature, add monitor sub class in memorytune class
> Add monitor sub class in memorytune class

- virttest/utils_test/libvirt.py
> Add function to check the output of any cmds

- virttest/libvirt_xml/vm_xml.py
> Add numa node setting in function vm_xml.set_vm_vcpus()

- virttest/qemu_devices/qcontainer.py
> Support to add multiple virtio-serial-pci

- virttest/libvirt_xml/vm_xml.py
> Fix 'no_numa_cell' UnboundLocalError issue

- virttest/libvirt_xml/vm_xml.py
> PPC memory size should align to 256M

- virttest/utils_test/libvirt.py
Modify create_disk_xml function to support create image with slice
Signed-off-by: jgao <jgao@localhost.localdomain>
> Modify create_disk_xml function to support create image with slice

- avocado_vt/test.py
For python3 the `libvirtd_debug_file` is always removed.
The reason is that there is a change in behavior which seems to
be intended for python3 as by https://bugs.python.org/issue35790:
In the `finally` block `sys.exc_info()` does not return the last
exception but the last unhandled exception (which is `(None, None,
None)` if only a single `exception.TestError` was raised, for example).
Store the `exc_info` in case of error and test that info which works for both
python2 and python3.
> Fix libvirtd_log_cleanup for python3

- virttest/bootstrap.py
- virttest/libvirt_xml/network_xml.py
- virttest/propcan.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_virtio_port.py
- virttest/utils_conn.py
- virttest/virsh.py
Reference for this change:
https://bugs.python.org/issue34850
> Use correct comparison between str/int and python literals

- virttest/test_setup.py
> test_setup: correct setbr_cmd

- virttest/utils_v2v.py
> Add service query support for windows guest

- virttest/qemu_devices/qdevices.py
> qdevices: Add align option for memory object

- virttest/storage.py
> Use dict method instead of Params method

- virttest/utils_test/libvirt.py
This breakage was introduced by commit id:f42f691dcb29455ebb233b896fb5b0ffa9c81d04
> Fix create slice xml breakage with slice_in_source given

- virttest/virsh.py
Backup and checkpoint related cmds involved from this fix.
> Add virsh cmds for incremental backup

- virttest/libvirt_xml/checkpoint_xml.py
> Add checkpoint xml to support backup function

- virttest/qemu_qtree.py
The value of key "file" is json format from qmp commmand "query-block"
if the backend image format is luks, so need to pick up the "filename"
as the "image_name".
ID: 1838887
> qemu_qtree: Support json format in generate_params for lusk format

- virttest/migration.py
It's usaually set to "yes" or "no", so update the value.
> Update status_error in migration.check_result

- virttest/utils_conn.py
> Fix libvirtd-tcp socket restart failed issue

- virttest/qemu_capabilities.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_monitor.py
- virttest/qemu_vm.py
Support migration with "-incoming defer".
ID: 1766663
> Support migration with "-incoming defer"

- virttest/utils_test/libvirt.py
Add support for nwfilter with parameters in the modify_vm_iface().
> Add support for nwfilter with parameters

- virttest/libvirt_xml/devices/disk.py
Add auth support in source element of backingstore element
> Add auth support in source element of backingstore element

- virttest/ceph.py
cephfs mount and umount intends to be used for cephfs cases
> Add cephfs mount and umount utils

- virttest/utils_conn.py
> Fix authentication failed issue

- virttest/utils_v2v.py
> Don't create duplicate VM session in a same VMCheck instance

- virttest/utils_conn.py
> Add support for traditional mode test

- shared/cfg/guest-hw.cfg
- virttest/nvme.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_storage.py
- virttest/qemu_vm.py
- virttest/storage.py
Support nvme storage backend.
ID: 1847232
> Support nvme storage backend

- virttest/utils_conn.py
> Fix TLS connection setup issue

- virttest/utils_conn.py
> Add a parameter for tls connection

- virttest/utils_secret.py
Pull up some distributed secret related functions into this file as common utils
> Add secret utils python file

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/utils_test/qemu/__init__.py
> Update Memory.__attributes__ to separate options for different backend

- virttest/qemu_storage.py
> Fix hardcode of force_share in check_image calling

- virttest/libvirt_xml/backup_xml.py
> Add xml support for domain backup

- virttest/libvirt_version.py
If there was an issue while connecting to virsh client, it would
be failed to get libvirtd version.
> Update to check libvirt version by 'libvirtd' or 'virtqemud' command

- virttest/utils_misc.py
> utils_misc: remove line-feed for function get_full_pci_id

- virttest/utils_conn.py
> Recover local libvirtd if tls server_setup_local is True

- virttest/qemu_devices/qcontainer.py
When the bootable image has a backing file, the current code could not
boot up the guest with the correct AAVMF_VARS.fd, this may lead to
the risk that guest will not start.
ID: 1854032
> qcontainer: Correct AAVMF_VARS if image has backing file

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
> qdevice: Add option prealloc-threads for memory-backend-file

- virttest/test_setup.py
> Update LibvirtdDebugLog to enable debuging log for virt* daemons

- backends/v2v/cfg/convert_destination.cfg
> v2v: Add dest_null for '-o null'

- shared/cfg/guest-hw.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_storage.py
- virttest/qemu_vm.py
- virttest/storage.py
- virttest/storage_ssh.py
> support ssh storage backend

- virttest/utils_config.py
- virttest/utils_test/libvirt.py
Some of cases need special settings, so update accordingly.
> Update customize_libvirt_config to set configurations for more daemons

- virttest/qemu_vm.py
> add boot option splash-time to boot command line

- virttest/libvirt_xml/devices/interface.py
Define vlan as a class in the interface xml.
> Add vlan into the interface xml definition

- virttest/virsh.py
Signed-off-by: iccaszhulili <lizhu@redhat.com>
> Add guestinfo cmd

- virttest/utils_split_daemons.py
> Add a method to check if modular daemon is enabled

- virttest/qemu_devices/qdevices.py
> Plug 'vfio-pci' into pcie-root-port instead of pcie.0

- virttest/cpu.py
> cpu: update intel cpu model types

- shared/cfg/guest-hw.cfg
- virttest/curl.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_storage.py
- virttest/qemu_vm.py
- virttest/storage.py
> Support curl stroage backend

- virttest/cpu.py
For global usage in some cpu test cases
id: 1856240
> virttest/cpu.py: Extract variants cpu_types and cpu_types_re

- virttest/libvirt_xml/devices/interface.py
- virttest/utils_test/libvirt.py
- Add d dict type attr of Interface
- Update function modify_vm_iface() to support newly added attr
> Add attr 'port' to Interface class

- backends/v2v/cfg/convert_destination.cfg
- virttest/utils_v2v.py
1) Move all construction of output options to target specific functions
2) Add new targets dest_json and dest_local
3) Rename some variant's name
> v2v: improve construction of output options

- virttest/virsh.py
> Add missing parameters for 'blkiotune' virsh cmd

- virttest/qemu_devices/qcontainer.py
1. hostbus and hostaddr
2. hostbus and hostport
3. venderid and productid
ID: 1847777, 1847778
> usb_host: add usb-host device specific parameters support

- shared/cfg/guest-hw.cfg
- virttest/nbd.py
> Export a qcow2 persistent bitmap with qemu-nbd

- virttest/qemu_vm.py
> qemu_vm: support add maxmem without slots

- virttest/utils_libvirt/libvirt_config.py
Some of cases need to delete some settings in configuration file
on local or remote.
> Add a method to remove setting in configuration

- virttest/utils_split_daemons.py
It prints too much output when checking if it's modular daemon
environment, so update to check it when the function is first
called.
> Check the modular daemon environment only the first time you use it

- virttest/utils_test/libvirt.py
> Extend check_qemu_cmd_line to fit for checking in remote machine

- shared/cfg/base.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
> Support tpm devices

- virttest/utils_test/libvirt.py
Add one operation to del_mac_address for interface xml
> Add one operation to del_mac_address for interface xml

- shared/cfg/base.cfg
- virttest/qemu_vm.py
> qemu_vm: Add device intel-iommu before any virtio devices

- virttest/utils_test/libvirt.py
test result is under preparing.
> Wrap config type into customize libvirt config

- virttest/qemu_vm.py
> qemu_vm.py: Enable multi-threads support for cpu model EPYC

- virttest/utils_libvirtd.py
It needs to update command from 'LIBVIRTD' to a specific cmd if
the modular daemon is enabled.
> Update LibvirtdSession for modular daemon env

- virttest/qemu_monitor.py
id: 1859024
Reference:https://www.qemu.org/docs/master/qemu-qmp-ref.html#index-set_002dnuma_002dnode
> qemu_monitor: add 'set_numa_node' method

- shared/cfg/base.cfg
- virttest/qemu_vm.py
> qemu_vm: Add '-numa cpu' to qemu command line

- virttest/utils_misc.py
> NumaInfo: add online_nodes_cpus to collect cpus for every node

- virttest/test_setup.py
> test_setup: remove line-feed for self.physical_nic

- virttest/utils_v2v.py
Sometime a case may requires multiple pkgs are at special versions.
This new function can help you specify those pkgs and their versions
in cases cfg files.
> Add a new function for multiple pkg version checking

- virttest/qemu_monitor.py
- virttest/qemu_vm.py
qemu_monitor:
1. Add 2 qapi methods "netdev_add" and "netdev_del"
2. Migrate QMPMonitor.set_link from self.send_args_cmd to self.cmd
qemu_vm:
1. Refactor to use simple_hot(un)plug to plug/unplug network frontend device
2. Use monitor.netdev_add and monitor_netdev_del to plug/unplug network backend device
ID: 1860240
References: https://github.com/qemu/qemu/tree/master/qapi
> qemu_vm: Refactor some network methods which called by hot(un)plug_nic

- shared/cfg/base.cfg
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_monitor.py
- virttest/qemu_vm.py
> Add throttle support on blockdev

- virttest/utils_misc.py
- virttest/utils_v2v.py
1. Add a new function asterisk_passwd in utils_misc.py
2. Remove logging output in utls_v2v.check_exit_status to
avoid duplicate logs.
3. Add a new function interactive_run in utils_v2v.py to
handle interative v2v command execution
4. Move function 'cmd_remove_option' to utils_v2v.py
> v2v: Support interative command execution

- virttest/libvirt_vm.py
Add support for adding custom bios in virt-install
commandline
> Add support for adding custom bios in virt-install

- virttest/arch.py
- virttest/cpu.py
- virttest/env_process.py
- virttest/utils_stress.py
Cpu library is getting refactored through this
PR https://github.com/avocado-framework/avocado/pull/3350,
This PR modified respective test code to reflect the same.
> Adopt Avocado cpu library changes

- virttest/utils_v2v.py
- virttest/virt_admin.py
> Fix more literal comparisons detected via python 3.8 warnings

- virttest/libvirt_xml/accessors.py
- virttest/libvirt_xml/vm_xml.py
- XMLElementList doesn't use to support a list of xml objects which
have child elements, this commit will fix it.
- numa_cell under 'cpu' tag of libvirt xml is now updated according
to libvirt.org. It used to be one-line xml element without child-elements,
it now could have child elements, therefore an update of marshal function
is necessary.
> XMLElementList:support list of xml elements with child elements

- virttest/cpu.py
- virttest/env_process.py
- virttest/utils_stress.py
Handle failures for avocado 69lts version.
> Fixup: handle failures for avocado 69lts

- virttest/utils_disk.py
New API to get the drive letters of the specified disk in windows
guest.
ID: 1876750
> utils_disk: New API to get windows drive letters of specified disk

- virttest/libvirt_xml/vm_xml.py
Usage of numa_cell is changed now.
> Fix outdated usage of numa_cell

- shared/cfg/base.cfg
- virttest/qemu_vm.py
> qemu_vm: support for adding '-numa dist' to qemu command line

- virttest/qemu_devices/qcontainer.py
qemu-kvm can handle '-cpu help' and '-device help' before 'no default
machine', so "self.__workaround_machine_type" does not currently work
effect. Dry run a qemu instance and check the exit status to determine
whether to add "-machine none".
Reference: https://patchwork.kernel.org/patch/11437515
ID: 1874317
> qcontainer: Update workaround machine type from "virt" to "none"

- virttest/remote.py
- virttest/utils_disk.py
This function is to check if the disks are working well in remote
VM, for example, after migration.
> utils_disk: Add function to check disks of remote vm

- virttest/qemu_vm.py
> qemu_vm: fix no attribute 'DeviceHotplugError' error

- virttest/utils_libvirtd.py
1. Create a daemon service object via Libvirtd class with
deamon's name
2. Update hardcode 'libvirtd'
> Update LibvirtdSession for modular deamon env

- virttest/utils_backup.py
Libvirt's incremental backup related supporting methods added in this file.
> Add utils for domain backup function

- virttest/libvirt_xml/pool_xml.py
- virttest/utils_test/libvirt.py
reduce the loop times when setting up nfs server
Singed-off-by: ljmen <lmen@redhat.com>
> update script for source_protocol_ver

- virttest/utils_libvirt/libvirt_cpu.py
- virttest/utils_libvirt/libvirt_vmxml.py
Add_cpu_settings is to add some specific elements/attributes in VMXML.
Set_vm_attrs is to set or update the attributes in VMXML
> Add functions to add or set the elements or attrs in VMXML

- virttest/utils_net.py
In some cases, it needs to reobtain IP address after adding port,
so add a new function to create/delete ovs bridge via tmux command
on local and remote host.
> Add a functiton to create or remove ovs bridge

- virttest/utils_libvirt/libvirt_nwfilter.py
> Add one method to clean up existed nwfilter binding list

- virttest/qemu_devices/qcontainer.py
Add usb ohci  for power
ID:1888208
Signed-off-by: MiriramDeng <mdeng@redhat.com>
> ohci:add usb ohci for power

- shared/cfg/guest-hw.cfg
- virttest/ceph.py
- virttest/qemu_storage.py
- virttest/storage.py
ceph backends: add namespace support for rbd image
Sign-off-by: Zixi Chen <zixchen@redhat.com>
ID: 1881278
> ceph backends: add namespace support for rbd image

- virttest/remote.py
The value of timeout was set to 'None' and verbose was directly
added to ssh command line in previous code, so fixup it in this PR.
> remote: Fix incorrect timeout issue and ssh cmd error

- virttest/qemu_storage.py
1. measure the size required by a new created image
2. measure the size required by a new converted image
ID: 1883249, 1883250
> virttest.qemu_storage: add luks format support to measure function

- virttest/qemu_vm.py
1. Delete 'add_virtio_option' since it will execute qemu each time it is
called.
2. Get supported properties to decide whether to add options.
ID: 1879359
> qemu_vm: Refactor code to add virtio options

- virttest/tests/unattended_install.py
Install viofs driver during guest installation
ID: 1878041
> unattended_install: Load viofs driver

- virttest/utils_config.py
This is new attribute introduced in qemuconfig
> Add nbd_tls_x509_secret_uuid into qemuconfig

- virttest/libvirt_xml/network_xml.py
- virttest/utils_test/libvirt.py
'nat' tag is child of 'forward' tag.
> network_xml:add 'nat_attrs' to NetworkXMLBase

- contrib/containers/ci/centos-8.1.docker
Reference: https://github.com/avocado-framework/avocado-vt/pull/2519
> Add diff package to Centos 8.1 CI container image

- virttest/utils_conn.py
Private key need to be encrypted by input password somehow
> Add_one parameter into build_client_key to extend encrypt client key

- .travis.yml
- selftests/unit/test_propcan.py
- virttest/graphical_console.py
- virttest/qemu_storage.py
- virttest/staging/lv_utils.py
- virttest/utils_test/qemu/migration.py
Fixed: E0611, E0633, E1135, E1136, E1137
> Patch set of lint fixes

- virttest/utils_nbd.py
Somehow,clien key need to be encrypted,so add password and secret parameters to enable it
> Extend nbd utils to allow encrypted key

- virttest/virsh.py
As per https://bugzilla.redhat.com/show_bug.cgi?id=1826636,
virsh secret-set-value will throw error if pass secret value by --base64 option
Read the secret from a file is right choice.
> Update virsh secret set value with file option

- virttest/migration.py
- virttest/migration_template.py
- virttest/shared/cfg/base.cfg
This module is used for cross feature testing with migration.
With this module, testing migration with specified feature can
be implemented easily. Before, when a specified feature is
automated, migration part is always left behind because of its
complexity. Now with this module, when we automate a specified
feature, we can implement the migration part by inheriting the
MigrationTemplate and copy&&paste the code related to specified
feature here.
> Add migration_template.py, also update base.cfg

- virttest/migration_template.py
Commit b2c1f4e is not the final version of pr#2709(actually I forgot
to push the latest update before it was merged) and it introdocued
travis-ci failure.
> Fixup for commit b2c1f4e

- virttest/remote.py
> Fix argument passing in wait_for_ssh_login_to_migrate

- virttest/ovirt.py
> ovirt: Auto query ovirt server version information

- virttest/libvirt_xml/vm_xml.py
Add sysinfo attribute to vm xml
> Add sysinfo attribute to vm xml

- virttest/virt_admin.py
As under the split daemon mode, the server name and
config file changed
> Added two functions to deal with split daemon mode

- virttest/utils_qemu.py
It is unreliable to grab the "cpu-max" through the error message of
qemu, modify the method to use the return value of qmp.
ID: 1901796
> utils_qemu: Get "cpu-max" with QMP return value

- virttest/utils_libvirt/libvirt_keywrap.py
1. All methods were run on host. Pass guest session to assure
commands are run in guest if session is present.
2. The utils_misc.cmd_status_output function tries to decode
protected key token as utf-8 which can cause an error. Define a local
version just passing the stdout as is.
> Fix ProtectedKeyHelper

- virttest/utils_test/libvirt.py
Some cases need to attach a disk with encryption source.
> Support source encryption for create_disk_xml()

- virttest/lvm.py
> lvm: Add emulated_image_size for EmulatedLVM

- virttest/utils_time.py
Adding a timeout parameter for logging in with host load
ID: 1903945
> utils_time: Add a timeout parameter

- virttest/utils_test/libvirt.py
Add driver_packed in create_disk_xml
> Add driver_packed in create_disk_xml

- virttest/qemu_devices/qcontainer.py
There will be some nested json string in the image info of luks, so we
cannot get the correct image filename. In order to eliminate the impact
of snapshot and filename, tweak the method of generating flash_vars.
ID: 1903624
> qcontainer: Tweak the method of generating flash_vars in pflash_handler

- virttest/libvirt_xml/devices/input.py
- virttest/libvirt_xml/devices/video.py
Add driver_packed attribute to input and video devices
> Add driver_packed attribute to input and video devices

- virttest/libvirt_xml/devices/memballoon.py
- virttest/libvirt_xml/devices/rng.py
Add driver attribute to rng and memballoon devices
> Add driver attribute to rng and memballoon devices

- virttest/utils_disk.py
1.Support the function "get_linux_disks" in RHEL6 guest,  since command lsblk does not support them in RHEL6.
2. For function create_partition_linux, add a step to check if the partition is created completely and return the kanme of partition created.
3. For function create_partition_windows, return the index of partition created.
4. For function create_partition, return the kanme of partition created in linux, the index of  partition in windows.
5. Add a mechanism to check the partition is deleted completely.
ID: 1699169, 1719589, 1748158, 1776109
> utils_disk: Tweak creating and deleting partition

- virttest/qemu_storage.py
1. add parameter -r to convert method
2. add parameter -r to commit method
ID: 1909738
> virttest.qemu_storage: add support for rate limit

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
- virttest/shared/cfg/base.cfg
> qemu_vm: Add numa hmat_lb and hmat_caches

- virttest/utils_disk.py
On s390x, vdb are attached to the channel subsystem.
Set the commands accordingly to 'css0'.
> [utils_disk] make sysfs paths s390x compatible

- virttest/env_process.py
This is on par with the image preprocessing which already does it.
> Allow custom paths for postprocessed images

- virttest/utils_conn.py
Some cases need to create a special server.info with specific ip
address.
> Add server_info_ip to create server.info with specific ip addr

- virttest/utils_test/libvirt.py
Update --source-iqn to --source-initiator in iscsi-direct pool
> Update --source-iqn to --source-initiator in iscsi-direct pool

- virttest/libvirt_xml/vm_xml.py
- virttest/utils_libvirt/libvirt_numa.py
Add InterconnectsXML and CellDistancesXML. Update CellCacheXML properties
to have better usabilites.
> Add or update xml configuration for interconnects and cell distances

- virttest/guest_agent.py
Add command 'guest-get-disk' for checking disks info.
ID: 1906654
> guest_agent: Add new command 'guest-get-disks' for checking disks info

- virttest/lvm.py
ID:1914104
Signed-off-by: Leidong Wang <leidwang@redhat.com>
> lvm: Add extra options for creating logical volume 

- virttest/libvirt_xml/vm_xml.py
After define failed, we would more like to get detailed reason from
error message than the content of vm's xml. Xml content is too long
for error message, it could be printed as log.
> No longer raise error with xml content if define has failed

- virttest/libvirt_vm.py
add nvram option automatically in vm.undefine if needed
Signed-off-by: Liu Yiding <liuyd.fnst@cn.fujitsu.com>
> Set nvram option for machine contains nvram

- virttest/utils_libvirt/libvirt_embedded_qemu.py
> Add class and functions for embedded qemu driver

- virttest/tests/unattended_install.py
Add parameters for kickstart script
ID: 1890839
> unattended.py: Add new parameters for kickstart script

- virttest/kernel_interface.py
- virttest/libvirt_xml/vm_xml.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_monitor.py
- virttest/qemu_storage.py
- virttest/remote.py
- virttest/remote_commander/remote_interface.py
- virttest/staging/service.py
- virttest/storage.py
- virttest/test_setup.py
- virttest/utils_iptables.py
- virttest/utils_libvirt/libvirt_keywrap.py
- virttest/utils_misc.py
- virttest/utils_selinux.py
- virttest/utils_split_daemons.py
- virttest/utils_test/libvirt_domjobinfo.py
- virttest/utils_test/qemu/migration.py
- virttest/utils_windows/drive.py
Signed-off-by: Han Han <hhan@redhat.com>
> virttest: Fix inspekt checking failures

- virttest/libvirt_xml/vm_xml.py
- virttest/utils_libvirt/libvirt_cpu.py
> To fix the CellDistanceXML slots and numa cell setting

- virttest/utils_backup.py
Sometimes a failed case will leave unremoved checkpoints, and this
will block followed cases. So we need a method to clean all
checkpoints.
> Add method to clean all checkpoints for a vm

- virttest/qemu_devices/qcontainer.py
Update failed_pattern since error message changed.
ID: 1917404
> qcontainer: update failed_pattern of workaround machine type

- virttest/libvirt_xml/network_xml.py
Add the support for lease setting for ip/dhcp/range and
ip/dhcp/hosts.
> Enable the network xml to set with dhcp lease info

- MAINTAINERS
Changing email address for Satheesh Rajendran
Signed-off-by: Satheesh Rajendran <sathnaga86@gmail.com>
> Changing email address

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
Update virtiofsd daemon parameter to improve performance
ID: 1917638
> qdevices: modify the virtiofsd daemon '-d' as an optional parameter

- virttest/utils_test/libvirt.py
Some cases need to modify remote VM's iface.
> Update modify_vm_iface to get remote vm's iface xml

- virttest/qemu_vm.py
> qemu_vm: Correct numa_nodeid missing issue

- virttest/guest_agent.py
guest_agent: Hotfix case "gagent_ssh_public_key_injection"
ID: 1919092
> guest_agent: Hotfix case "gagent_ssh_public_key_injection"

- virttest/ip_sniffing.py
From tshark 3.0.0, the field name - bootp [1] is no longer supported
and users should use dhcp [2] instead.
tshark: Some fields aren't valid:
bootp.option.dhcp
bootp.ip.your
...
(Process terminated with status 1)
Updating the module accordingly.
References:
[1] https://www.wireshark.org/docs/dfref/b/bootp.html
[2] https://www.wireshark.org/docs/dfref/d/dhcp.html
ID: 1917682
> ip_sniffing: Support tshark (wireshark) 3.x

- virttest/qemu_devices/qcontainer.py
> qcontainer:add throttle support for cdrom device

- virttest/utils_backup.py
Incremental backup is not enabled by libvirt. We need to edit vm's
xml to enable it. This is a workaround before bz1799015 fixed.
> Add method to enable vm's capability of incremental backup

- virttest/migration.py
Add MigrationTest.set_migratepostcopy() to switch to postcopy
during migration.
> Add a method to set the migration postcopy

- virttest/utils_libvirt/libvirt_disk.py
This is a wrapper method to create disk on local/remote.
> Add a function to create disk on local or remote

- virttest/nbd.py
- virttest/qemu_monitor.py
> Block export support

- virttest/libvirt_xml/vm_xml.py
> Add kvm poll-control to vm features xml

- virttest/qemu_devices/qdevices.py
> qdevices: Add support for memory-backend-memfd

- virttest/libvirt_xml/vm_xml.py
Add two new arguments and one reverse argument to anti-select the
disks.
This could solve following problem:
When disk device has 'scsi' bus and a cdrom device has 'sata' bus,
the target dev will have same value. so the previous disks[dev] will
be covered by the cdrom value.
See following example:
<disk type='file' device='disk'>
<source file='[esx6.7-matrix] xxx/xxx-xxx.vmdk'/>
<target dev='sda' bus='scsi'/>
<address type='drive' controller='0' bus='0' target='0' unit='0'/>
</disk>
<disk type='file' device='cdrom'>
<target dev='sda' bus='sata'/>
<address type='drive' controller='0' bus='0' target='0' unit='0'/>
</disk>
> vm_xml: make get_disk_all more flexible when selecting disks

- virttest/libvirt_xml/devices/disk.py
This is newly introduced xml element,something like:
<driver name='qemu' type='qcow2'>
<metadata_cache>
<max_size unit='bytes'>10</max_size>
</metadata_cache>
</driver>
> Add metadata_cache xml support

- virttest/virsh.py
this exend change-media to allow certain time waiting for event,
in some test cases, it help to avoid timeout issue
> Add wait_change_event into change-media command

- virttest/utils_test/libvirt.py
> Add logging info after log check passed

- virttest/libvirt_xml/vm_xml.py
This is only to add the support for global_period and global_quota for
schedinfo command.
> Add global param for schedinfo

- virttest/utils_test/libvirt.py
> Add refresh step after pool create to make vol available

- virttest/cpu.py
> cpu.py:add new model EPYC-Milan and delete old model

- virttest/utils_libvirt/libvirt_pcicontr.py
This is to fix the error:
`NameError: name 'vmxml' is not defined&#10;`
> Fix a typo

- virttest/libvirt_xml/devices/hostdev.py
For iscsi device hostdev, Initiator can be wrapped into hostdev source tag as one element
> Add Initiator element support in hostdev

- virttest/qemu_storage.py
1. add parameter --target-is-zero to convert
2. add parameter -B to convert
ID: 1942220, 1942222, 1942223, 1942225, 1942226, 1942227
> virttest.qemu_storage: add support for new parameters of convert

- virttest/qemu_vm.py
> qemu_vm: Add support for balloon option free-page-reporting

- virttest/utils_conn.py
It takes more time to install and uninstall qemu-kvm.pp on some
machines.
> utils_conn: Extend timeout for qemu-kvm.pp installation

- virttest/utils_libvirt/libvirt_network.py
Some of migration cases need to check the established connection
on destination host.
` (1/7) type_specific.io-github-autotest-libvirt.virsh.migrate_storage.migrateuri.default.ipv4.copy_storage_all: PASS (156.52 s)`
> libvirt_migration: Add a function to check established connection

- virttest/utils_net.py
Get inside-vm info of certain interface with given mac address
Add a new module libvirt_interface
> Add function to get iface info inside vm

- virttest/utils_test/libvirt.py
```
JOB ID     : dd52e9e386c235827b0ff429eadcd546ca4051c0
JOB LOG    : /root/avocado/job-results/job-2021-03-24T03.19-dd52e9e/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.ceph.hot_plug.without_auth.disk_attach.attach_device: PASS (66.51 s)
JOB TIME   : 67.71 s
JOB ID     : 23af5080a2cdbcf7c849843a4fef0ef6716db79e
JOB LOG    : /root/avocado/job-results/job-2021-03-24T07.50-23af508/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_bridge.default.shared_physical_network: PASS (133.00 s)
JOB TIME   : 134.59 s
```
> Make wait for writing file finish as common func

- virttest/libvirt_version.py
Automation of a new feature always needs comparing libvirt version
to check if it's supported in the installed libvirt version, so
implement a common function in libvirt_misc.
> Add a function to check if the feature is supported

- virttest/utils_v2v.py
Add support for running v2v command in unpriviliged user.
> v2v: support unpriviliged user run v2v command

- virttest/qemu_storage.py
> virttest.qemu_storage: add support for luks key management

- virttest/utils_misc.py
> utils_misc: fix issue of invalid literal for int()

- virttest/libvirt_cgroup.py
Since libvirt-7.0.0-5.el8 (commit fbb27c3a5e), libvirt creates
a nested dir 'libvirt' in each machine slice dir.
All params will be set under this dir. But blkio.bfq.weight and
cpu.shares will be set in the machince slice root dir. We need to
treat them specially.
> Update cgroup file path to align with libvirt change

- virttest/shared/scripts/pmsocat/pmsocat36.py
It reports DeprecationWarning: "@coroutine" decorator is deprecated
since Python 3.8, use "async def" instead. So update the code
accordingly. For details please check
https://docs.python.org/3/reference/compound_stmts.html#async-def
> pmsocat: Replace @coroutine with 'async def'

- virttest/migration.py
1. Merge check_result with do_migraion
2. Add a method to clear up vm on a local host and remote host
Test results:
https://github.com/autotest/tp-libvirt/pull/3404#issue-602656760
> migration: Update to check result after migraion and add a func to clean vm

- virttest/utils_test/qemu/__init__.py
Currently, the function setup_win_driver_verifier() only support one driver file verify,
We also need to support multi driver files verify.
ID: 1919753
> Adjust setup_win_driver_verifier to support multi driver files verify

- virttest/virsh.py
By defining function with this decorator, it allows virsh commands
to wait for certain events to show up before returning. Exception
will be raised if timeout and event is not found.
----
Test log:
```
Sending "event avocado-vt-vm1 --all --loop" to virsh shell
Running virsh command: change-media avocado-vt-vm1 hdc  --update --live /tmp/avocado_rzvye8ng/change_media_new.iso 
Running '/bin/virsh change-media avocado-vt-vm1 hdc  --update --live /tmp/avocado_rzvye8ng/change_media_new.iso '
[stdout] Successfully updated media.
Command '/bin/virsh change-media avocado-vt-vm1 hdc  --update --live /tmp/avocado_rzvye8ng/change_media_new.iso ' finished with 0 after 0.03598618507385254s
status: 0
stdout: Successfully updated media.
stderr: 
Welcome to …
```
> Add EventTracker to enable virsh commands to wait for events

- virttest/utils_test/libvirt.py
> Update modify_vm_iface() to support coalesce

- virttest/utils_libvirt/libvirt_ceph_utils.py
Enable add ceph backend disk into VM
> Add ceph setup utility module

- virttest/openvswitch.py
e.g. ovs-vsctl add-port ovsbr0 vhost-client-1  -- set Interface vhost-client-1 type=dpdkvhostuserclient  options:vhost-server-path=/var/lib/libvirt/qemu/vhost-client-1
> Add more parameter for add-port commands

- virttest/utils_libvirt/libvirt_pcicontr.py
So cases failed due to error "No more available PCI slots".
As a matter of convenience, Introduce an API to reset the number of
guest's PCI directly.
BTW. Different platforms may require additional configuration, I just
tested it on aarch64 guest.
> libvirt_pcicontr: Introduce reset_pci_num api

- virttest/utils_disk.py
This function is to get the first disk on the host or guest, especially
to detect the disk is 'vda' or 'sda'.
> Add func to get first disk

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
> qemu_vm: Replace password with password-secret for spice

- virttest/libvirt_cgroup.py
Although cfq is out of date, we still need make existing cases can
work with cfq to avoid regression.
```
Before fix:
(1/1) type_specific.io-github-autotest-libvirt.virsh.blkiotune.positive.set_blkio_parameter.running_guest.change_weight.options.live.minimum_boundary: ERROR: [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/machine.slice/machine-qemu\\x2d1\\x2davocado\\x2dvt\\x2dvm1.scope/blkio.bfq.weight' (65.36 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 69.20 s
```
> Support cfq scheduler

- virttest/utils_sys.py
Allow users to check whether dmesg output contains certain pattern.
> Add function check_dmesg_output

- .cirrus.yml
- .travis.yml
Couple of Python 2 cleanups on Travis and Cirrus CI.
Part of #2963
> Python 2 CI cleanups

- virttest/utils_test/libvirt.py
> Add extra file to avoid "Failed to open file" error

- virttest/utils_net.py
To check if the multiqueue setting is effective, run "ethtool -l" on
the vm. And set it by "ethtool -L". Add these 2 functions to check and
set the multiqueue in the vm.
> Add the multiqueue check and set functions

- virttest/migration.py
Add a function to set the migration speed for precopy and postcopy.
This is usually used to decrease the speed in order to give the
opportunity to run other functions during migration process.
> migration: control migration speed

- virttest/migration.py
There are several enhancements:
- Support to run multiple functions during migration. In the past,
we only support to run a single function.
- Support to control when the function should be run, before vm is
paused or after.
- Support to run a function triggered by a given event
- Support to return the function execution results
- Support to check system disk as default for migrated vm
> migration: Support multiple functions

- virttest/utils_net.py
Add 2 functions to create/delete linux bridge on the host. And it will
also add or delete a physical interface to the bridge. Using the tmux to
execute the ip commands to avoid the broken of the host network.
> Add 2 functions to create/delete linux bridge

- virttest/utils_libvirt/libvirt_network.py
1. Enable to run command on local host
2. Enable to return the port when needed
> Check port on local

- virttest/migration_template.py
> migrate_template: Support more migration options

- virttest/virsh.py
> Add set-user-sshkeys and get-user-sshkeys cmd to virsh.py

- virttest/utils_sys.py
This function could be replaced with another function of master
branch of avocado. Add a todo here as a reminder.
> Add todo info for function check_dmesg_output

- virttest/utils_libvirt/libvirt_disk.py
Those two APIs can be more of common utils
> Add memoryBacking and check_in_vm into libvirt_disk.py

- virttest/ssh_key.py
Now it only support to create ssh key for current user.
> ssh_keys: support to create ssh keys for other users on client host

- virttest/qemu_vm.py
1. add parameter failover=on for virtio-net-pci device.
2. add parameter failover_pair_id for vfio-pci device.
3. qemu command line example:
-device vfio-pci,host=04:0a.0,failover_pair_id=net0\
-device virtio-net-pci,mac=22:2b:62:bb:a9:82,failover=on,id=net0\
-netdev tap,vhost=on \
4. config exmaple:
nics = 'nic1 nic2
pci_assignable_nic1 = vf
pci_assignable_nic2 = no
failover_nic2 = on
device_id_nic2 = net0
failover_pair_id_nic1 = net0
device_driver = vfio-pci
vf_filter_re = "Virtual Function"
pf_filter_re = 82599
device_name_nic1 = eth0
netdst_nic2 = private
physical_nic2 = eth0
mac_nic2= 22:2b:62:bb:a9:82
mac_nic1= 22:2b:62:bb:a9:82
nic_model_nic2 = virtio
vhost_nic2 = vhost=on
id: 1960158
> Support vfio-vf failover

- virttest/libvirt_cgroup.py
> Add 1 function for cgroup2

- virttest/env_process.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
> Add machine type option memory-backend

- virttest/utils_test/libvirt.py
The restart libvirt flag(parameter) added to customize_libvirt_config
since the restart of the libvirt after applying config changes is not
always needed/intended. Parameter remains true for existing tests,
but can be changed to false for future tests that do not need/require
the libvirt service restarted.
Signed-off-by: Kamil Varga <kvarga@redhat.com>
> New flag added to customize_libvirt_config to support some tests

- virttest/qemu_vm.py
> qemu_vm: Fix QMPCmdError

- virttest/utils_net.py
Add openvswitch2.15 as the package name varies on different version.
> Add openvswitch2.15 as the package name varies

- virttest/utils_conn.py
- virttest/utils_test/libvirt.py
Second password for additional verification methods(SASL) added to
libvirt.py, new parameter added to unixconnection, so it can be used
for communication and setup on remote host.
Used for a new test, results availble at: https://github.com/autotest/tp-libvirt/pull/3425
Signed-off-by: Kamil Varga <kvarga@redhat.com>
> Added support for remote unix connection to libvirt.

- virttest/utils_libvirt/libvirt_disk.py
This is to create a same virtual size empty disk image on remote
host as the first disk of the vm on local host. This is common
used for storage migration test.
> libvirt_disk: create remote disk

- virttest/utils_conn.py
Before this PR, we always scp all required files like cakey, cacert,
severkey ... to the TLS server host and client host which are normal
way for TLS connection setup. But sometimes we need partial setup.
So this PR is to enable the capability to allow the user to define
which files will be scped to the TLS server/client host.
> Customize tls setup

- virttest/qemu_devices/qdevices.py
> qdevice: Add new attributes for class Memory and Dimm

- virttest/libvirt_xml/devices/memballoon.py
Add alias tag to memballoon device.
> Update xml of memballoon device

- virttest/utils_libvirt/libvirt_nwfilter.py
Sometime user need nwfilter list from system
> Add get_nwfilter_list as common util

- virttest/libvirt_xml/vm_xml.py
Add more elements supported in cputune.
> More support cputune

- virttest/utils_test/libvirt.py
> Update function update_memballoon_xml to support alias

- virttest/libvirt_xml/nodedev_xml.py
Some tests need to get the driver name.
> nodedev_xml: Add driver_name

- virttest/virt_vm.py
> virt_vm: Enable the logging of session for VM

- virttest/utils_sriov.py
This PR adds a function to get pf infomation on the host.
```
<module 'virttest.utils_sriov' from '/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/utils_sriov.py'>
>>> res=utils_sriov.get_pf_info()
>>> res
{'3b:00.0': {'driver': 'ixgbe', 'pci_id': '0000:3b:00.0', 'iface': 'ens1f0', 'status': 'up'}, '3b:00.1': {'driver': 'ixgbe', 'pci_id': '0000:3b:00.1', 'iface': 'ens1f1', 'status': 'down'}}
```
> sriov: Add a function to get PFs' info

- avocado_vt/plugins/vt_runner.py
This commit adds the usage for avocado messaging methods to the vt
nrunner. It will help with maintaining of future changes in nrunner
messaging system.
> Messaging helper methods in vt runner

- virttest/libvirt_xml/devices/disk.py
- virttest/utils_net.py
> Workaround pylint errors

- virttest/libvirt_xml/vm_xml.py
Add a new attribute 'migratable' in cpu setting.
Add a new function for cpu feature.
> Support new attribute in cpu

- virttest/utils_test/libvirt.py
Add "del_target" and "del_alias" into the modify_vm_iface().
> Add 2 more method into modify_vm_iface()

- virttest/utils_libvirt/libvirt_network.py
Add a function to modify network xml.
> Add modify network xml function

- virttest/qemu_vm.py
> qemu_vm: Add support for option 'cpu-pm'

- virttest/utils_libvirt/libvirt_vmxml.py
> libvirt_vmxml: add func to check dumpxml

- virttest/qemu_vm.py
> qemu_vm: add 'aer' option for virtio device

- virttest/libvirt_xml/vol_xml.py
Add clusterSize element to volume xml
> Add clusterSize element to volume xml

- virttest/utils_libvirt/libvirt_network.py
Ensure the default network exists and in the expected status.
> Add one function to ensure default network exists

- virttest/utils_sriov.py
This PR adds:
1. a function to get iface by the given pci
2. a function to get non-administrative mac of VF
3. a function to get pci by the given iface
Test result:
https://github.com/autotest/tp-libvirt/pull/3677#issue-701153582
> utils_sriov: Add functions to get iface and vf's non-admin mac

- virttest/lvsbs.py
Change column_names from None type to list
> Fix I1101 issue in virttest/lvsbs.py

- virttest/utils_libvirt/libvirt_disk.py
In quite a lot cases, there are requirements to fill sth in VM first
before execute further actions
> Add fill_sth_in_vm as common API in libvirt_disk.py

- virttest/libvirt_xml/vm_xml.py
> Add idmap, sysinfo bios classes to vm_xml

- virttest/libvirt_xml/base.py
- virttest/libvirt_xml/vm_xml.py
The function allows us to setup attributes of an xml object with
a dict-like param.
> Add function to setup attrs of an xml object

- virttest/utils_net.py
Move the tc rule check into avocado-vt to share with other tests.
> Move the tc rule check into avocado-vt

- virttest/utils_test/libvirt.py
Log info of content being found.
> check_qemu_cmd_line: Add more log to the function

- virttest/utils_misc.py
> utils_misc: ignore field deprecated when getting machine type

- virttest/libvirt_xml/vm_xml.py
Add firmware element to VMOSXML
> Add firmware element to VMOSXML

- .github/workflows/ci.yml
- Makefile
- requirements-travis.txt
- selftests/signedoff-check.sh
- spell.ignore
- virttest/libvirt_xml/base.py
- virttest/utils_libvirt/libvirt_embedded_qemu.py
Third commit from splitting PR https://github.com/avocado-framework/avocado-vt/pull/3173
* ` Makefile`: update check target to include the spellchecker
* CI
*  Add job to build package (egg)
* Check signed-off-by to make sure new commits are signed by the author.
* Add spellchecker together with its requirements on pyenchant to `requirements-travis.txt`
After the update, the CI will look like this https://github.com/ana/avocado-vt/actions/runs/1115976569
> Updates to CI

- Makefile
- setup.py
This is part of a split of PR https://github.com/avocado-framework/avocado-vt/pull/3173
> Fix default target in Makefile and add custom command clean to setup.py

- virttest/virsh.py
> Add virsh cmd domdirtyrate-calc to virsh

- spell.ignore
- virttest/libvirt_xml/backup_xml.py
- virttest/passfd.c
- virttest/passfd.py
- virttest/remote_commander/remote_runner.py
- virttest/staging/utils_koji.py
- virttest/test_setup.py
- virttest/tests/unattended_install.py
- virttest/utils_libguestfs.py
- virttest/utils_libvirt/libvirt_vfio.py
- virttest/utils_test/__init__.py
- virttest/utils_test/libvirt.py
- virttest/utils_v2v.py
- virttest/utils_version.py
- virttest/virsh.py
Upstream changed her name and email and would like to update it. 
Reference: https://github.com/NightTsarina/python-passfd/commit/e800b4d8abfc04fd1087ce7c91a466c325368fab
> virttest/passfd: Update upstream's name and email.

- spell.ignore
> Add 'TestCancel' to spell.ignore

- virttest/utils_libvirt/libvirt_nested.py
Depend on https://github.com/avocado-framework/avocado-vt/pull/3127
> Support nest virt on host

- avocado_vt/plugins/vt_runner.py
The test statuses on the vt-runner was limited only to the `PASS` and
`ERROR`, this will add usage of other statuses as `FAIL`, `SKIP`, `WARN`
`INTERRUPTED` and `CANCEL`
Reference: #3107
> Vt-runner test statuses fix

- virttest/unittests/libvirt_xml/device_xml/test_memory_xml.py
Test setting all attributes of a memory device
> Add unittest of memory device

- virttest/qemu_vm.py
Update backend_options params for cfg add configuration method
id:1996925
> qemu_vm:update backend_options params

- virttest/utils_disk.py
- virttest/utils_libvirt/libvirt_disk.py
This is to provide a new utitily function which is very basic and
can be invoked by many other utitily functions.
> utils_disk: new added parts

- virttest/utils_test/libvirt_device_utils.py
> Add creating xml for externally launched virtiofsd

- spell.ignore
- virttest/qemu_vm.py
Add a device vmcoreinfo in avocado-vt.
ID: 1992917
> Add a vmcoreinfo support on avocado-vt

- avocado_vt/plugins/vt_runner.py
This will add the `fail_reason` and `exit_code` attributes to the
`FinishedMessage` inside vt-runner. Thanks to that, the user will have
more details about test status.
Reference: #3107
> More details for test status in avocado vt-runner

- virttest/libvirt_xml/base.py
- virttest/libvirt_xml/devices/controller.py
- virttest/libvirt_xml/devices/interface.py
- virttest/unittests/libvirt_xml/device_xml/test_controller_xml.py
- virttest/unittests/libvirt_xml/device_xml/test_interface_xml.py
- virttest/unittests/libvirt_xml/device_xml/test_memory_xml.py
Along with unittest of controller and interface xml objects
> Add function to fetch attrs of an xml object

- avocado_vt/test.py
- avocado_vt/utils.py
This is part of a discussion with @richtja about cleaning up and possibly unifying the VirtTest class.  Extended testing from reviewers is very welcome!
> Virt test cleanups

- virttest/qemu_vm.py
> qemu_vm: Add designation of nic driver model for different platforms

- virttest/virsh.py
> virsh: Remove redundant code

- virttest/iscsi.py
Using lun_attrs to define attributes of fileio lun
ID:2007146
> Add setting attribute for fileio

- virttest/virsh.py
Fix the issue that it can not get detach event.
> Fix the issue that can not get event

- avocado_vt/plugins/vt_runner.py
This is the restructuring of avocado vt-runner. This change brings the
reusage of vt legacy code in vt nrunner. Thanks to that, there won't be
any compatibility issues which were reported in #3221, and  also it will
be easier to save all the vt log files into the test-result directory
which fix issue #3213.
Reference: #3213, #3221
> VT-runner with test.VirtTest class

- virttest/libvirt_xml/devices/interface.py
> Add attribute 'acpi' to interface

- avocado_vt/plugins/vt_runner.py
Signed-off-by: Beraldo Leal <bleal@redhat.com>
> fixes CI issue with E0702

- virttest/utils_libvirtd.py
> Set default service_name for modular daemon mode

- virttest/shared/cfg/guest-os/Windows/Win11/x86_64.cfg
Signed-off-by: Leidong Wang <leidwang@redhat.com>
ID:2013927
> Update Win11 configuration file

- virttest/qemu_monitor.py
Add support for blockdev-reopen
id:2012761
> qemu_monitor:add support for blockdev-reopen

- virttest/utils_stress.py
> Add the function to install stressapptest cmd

- virttest/libvirt_version.py
> libvirt_version: Fix a typo in is_libvirt_feature_supported

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/shared/cfg/base.cfg
Add Block Filter copy-on-read
id:2014969
> qemu_devices:add support for copy-on-read filter

- virttest/utils_misc.py
> Add a function to kill service on source/destination host

- virttest/guest_agent.py
change the crypt parameter to '-6' from '-crypt'.
ID: 2012876
Signed-off-by: demeng <demeng@redhat.com>
> guest_agent.py: change the crypt method of 'openssl'

- virttest/qemu_devices/qdevices.py
> Set vhost-user-fs-pci device's bus to pcie root port

- virttest/qemu_devices/qdevices.py
qdevices: Add --terminate option for swtpm command
Signed-off-by: qcheng <qcheng@redhat.com>
ID: 2028018
> qdevices: Add --terminate option for swtpm command

- virttest/libvirt_xml/devices/serial.py
> Add log file in serial device xml

- virttest/virsh.py
Add libvirt's allocpages command.
> virsh: add allocpages command

- virttest/virsh.py
> virsh: Fix can't get event info in some env

- requirements-travis.txt
> update inspektor to latest version

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/utils_qemu.py
- virttest/utils_test/qemu/__init__.py
> qdevices: Support getting device attributes dynamically

- virttest/utils_v2v.py
When both src and dst don't have the file in checklist, the previous
code treated the md5 compare is False. This logic is wrong. The result
is same vddklib will be copied from NFS to local server.
This patch fixes the issue.
> v2v: fix copying duplicate vddklib from nfs issue

- virttest/gluster.py
Replace get_tmp_dir() with get_data_dir().
> Fix gluster brick path

- virttest/utils_conn.py
Check path if exists on client.
> utils_conn: Update for check path

- virttest/libvirt_xml/devices/watchdog.py
> Fix watchdog modprobe return error

- virttest/virsh.py
> Change the detach-interface get event timeout

- virttest/shared/scripts/dd.py
> Changed "mkdir" to "makedirs"

- virttest/utils_v2v.py
> v2v: add arbitray username for vpx connection

- virttest/shared/scripts/rh_perf_log_guestinfo_script.sh
> rh_perf_log_guestinfo_script.sh: add "ethtool -l" in guest

- virttest/nbd.py
- virttest/qemu_storage.py
- virttest/shared/cfg/base.cfg
Signed-off-by: Tingting Mao <timao@redhat.com>
ID: 2018122
> qemu_storage: add bitmap sub command

- virttest/qemu_devices/qdevices.py
Add daemon alive check in start_daemon()
ID:2052864
> qdevices: Add daemon alive check in start_daemon()

- virttest/libvirt_xml/devices/tpm.py
Add active_pcr_banks element to tpm device construction.
> tpm.py: add active_pcr_banks element

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/utils_qemu.py
- virttest/utils_test/qemu/__init__.py
Add new attributes for memory and dimm devices.
ID: 2054732
> Add new attributes for memory and dimm devices.

- virttest/env_process.py
env_process: removes message function from test exception
No message function for Exception class with python3
ID: 2034135
> env_process: removes message function from Exception class

- virttest/utils_libvirt/libvirt_embedded_qemu.py
> libvirt_embedded_qemu: use cancel instead error

- virttest/test_setup.py
> test_setup: fix backup virtqemud.conf file

- virttest/utils_libvirt/libvirt_secret.py
write new function create_secret in libvirt_secret.py
this func is implemented by translating keys in params to new ones,we'd better directly pass a dict with secret settingsSo we use setup_attr to rewrite function
> implement new function create_secret in libvirt_secret.py

- virttest/utils_vdpa.py
Test results: https://github.com/autotest/tp-libvirt/pull/4127#issuecomment-1078658590
> vdpa: Enhance VDPAOvsTest to support max queues

- virttest/utils_v2v.py
> v2v: add a new function to set LIBGEUSTFS_BACKEND

- virttest/libvirt_xml/devices/memory.py
Test results: https://github.com/autotest/tp-libvirt/pull/4115#issue-1174801445
> memory: Add block, requested and current to Target

- virttest/utils_conn.py
In modular daemon environment, 'virsh -c qemu+unix:///system' will
connect to virtqemud directly. So need config virtqemud.conf.
> utils_conn: Update for UNIX connection

- virttest/qemu_vm.py
Signed-off-by: Leidong Wang <leidwang@redhat.com>
> Add option to force setting socket value

- virttest/shared/cfg/guest-os/Windows/Win10/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win11/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win2012/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win2016/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win2019/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win2022/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win8/x86_64.cfg
Remove the default md5sum value as it will change frequently.
id: 2056338
> Remove md5sum value for windows iso

- spell.ignore
- virttest/libvirt_xml/devices/memory.py
> memory: add pmem alignsize to nvdimm

- virttest/virsh.py
When we use` def  start_get_event` , The output of session can't be gotten immediately,  Wait for a while to avoid this situation.   Move  the waiting code to `def start_get_event` so that we can cover the ` def  start_get_event`  and ` wait_event`
**Test result**: 
Some cases related @EventTracker.wait_event
[root@hpe-xl220agen8v2-02 ~]# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockcopy_options.positive_test.extended_l2_on.not_encrypt_disk --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy_options.positive_test.extended_l2_on.not_encrypt_disk: STARTED
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy_options.positive_test.extended_l2_on.not …
> virsh.py: move confirm event started to start event function

- virttest/utils_test/libvirt.py
This is to give an oppotunity for the user to decide if an exception
or a boolean value is needed when checking fails.
> libvirt: add new param

- virttest/utils_libvirt/libvirt_numa.py
Some formats of numa nodeset are provided in provider cases, but
those formats require the host numa nodes continouse. The truth is
host numa nodes have big differences among available numa hosts.
The host numa nodes might be not continuous, so certain format is
not support, like 'x-y'. In this case, we have to use 'x,y' instead.
> libvirt_numa: handle numa nodeset utils

- virttest/test_setup.py
Allocating Hugepages requires a number of contiguous memory.
Sometimes we can't get the required number of hugepages because of memory
fragmentation, although there is enough free memory.
write 1 to /proc/sys/vm/compact_memory, all zones are compacted such that
free memory is available in contiguous.
Before
```
(091/162) Host_RHEL.m8.u6.v0.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.boot_vm_in_hugepage.512M.arm64-pci:  ERROR: Cannot set the kernel hugepage setting to the target value of 16 hugepages. (4.03 s)
```
After
```
(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.aarch64.io-github-autotest-qemu.boot_vm_in_hugepage.512M.arm64-pci: PASS (645.75 s) …
```
> test_setup: compact memory before allocate hugepages

- virttest/utils_netperf.py
* correct the package remove command
* explicitly close sessions to avoid issues
> Fix the issues of utils_netperf

- virttest/libvirt_xml/vm_xml.py
> vm_xml:Update memoryBacking xml with new attribute

- virttest/utils_conn.py
Signed-off-by: Lili Zhu <lizhu@redhat.com>
> Add parameter tcp_min_ssf to TCPConnection

- virttest/migration.py
- virttest/migration_template.py
Add a param to check guest state on source host.
> migration: Add a new param

- virttest/utils_libvirt/libvirt_vmxml.py
Need to add function to create device when not get device
From https://github.com/autotest/tp-libvirt/pull/4219
> libvirt_vmxml.py:Add function to create deivice if not get expected device

- virttest/migration.py
> migration: Add --nvram option for vm.undefine

- virttest/env_process.py
- virttest/shared/cfg/base.cfg
> Set libvirtd log filter to align with log level by default

- virttest/backends/v2v/cfg/convert_destination.cfg
- virttest/utils_v2v.py
> v2v: add new output target 'qemu'

- selftests/unit/test_cartesian_config.py
- virttest/cartesian_config.py
> Add del operator support for join/suffix enhanced dictionaries

- virttest/unittests/libvirt_xml/device_xml/test_memory_xml.py
Add more test cases with different xml settings
> Update xml unittest of memory device

- virttest/qemu_storage.py
Signed-off-by: Tingting Mao <timao@redhat.com>
ID: 2103037
> qemu_storage: add repair option for image check function

- virttest/libvirt_cgroup.py
'sys/fs/cgroup/cpuset/machine.slice/cpuset.cpus' file could be created
when the vm is started for the first time. This is to make sure the file
exist in the test environment.
> libvirt_cgroup: fix cpusest.cpus missing

- virttest/libvirt_xml/network_xml.py
- virttest/utils_test/libvirt.py
> Update vf_list of NetworkXML

- virttest/utils_libvirt/libvirt_network.py
Add a checkpoint to check network connection service.
> libvirt_network: Add a checkpoint

- virttest/libvirt_xml/devices/filesystem.py
- virttest/utils_test/libvirt_device_utils.py
Signed-off-by: Lili Zhu <lizhu@redhat.com>
> Add the element thread_pool to filesystem device

- virttest/unittests/libvirt_xml/device_xml/test_interface_xml.py
> Update unittest of interface xml test

- virttest/utils_linux_modules.py
It is based on avocado/utils/linux_modules.py. I did some changes to
make it better supports guest seesion.
> virttest: Add utils_linux_modules.py

- virttest/qemu_vm.py
> Support setting backend for machine mem

- virttest/libvirt_xml/devices/graphics.py
> Update old definition of Graphics XML Class

- virttest/libvirt_xml/vm_xml.py
> vm_xml:Update old definition of VMHugepagesXML

- spell.ignore
- virttest/utils_libvirt/libvirt_bios.py
Remove some items for efi to avoid conflicted configuration with test case
> libvirt_bios: remove for efi

- virttest/utils_libvirt/libvirt_pcicontr.py
This function is to help return a list of free pcie-root-port controllers' indexes
> libvirt_pcicontr: add func to find freed root ports

- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
> Fix the EMPTY_STRING issue

- virttest/utils_libvirt/libvirt_disk.py
add qemu-img rebase and do commit with virsh opt
Note:
fedora_35 AVOCADO_SRC: SETUP:setup.py develop --user VT_TYPE:qemu error not related my code ,
Please help review and ignore this error
> add support for blockcommit relative path case

- virttest/utils_libvirt/libvirt_network.py
Update to setup a network via setup_attrs().
Test results: https://github.com/autotest/tp-libvirt/pull/4445#issue-1347604307
> libvirt_network: Update to create network via setup_attrs()

- spell.ignore
- virttest/utils_libvirt/libvirt_memory.py
> Add a function to get memlock hard limit

- virttest/utils_libvirt/libvirt_disk.py
Need source file before create snap with --reuse-external  option
Note:
`fedora_35 AVOCADO_SRC: SETUP:setup.py develop --user VT_TYPE:qemu `error not related my code ,Please help review
> add source file for create_reuse_snap function

- virttest/libvirt_xml/backup_xml.py
- virttest/utils_backup.py
> Update old implementation of BackupXML

- virttest/utils_libvirt/libvirt_network.py
Use different command to check port and service.
> Update for service check

- virttest/virsh.py
def start_get_event needs to update event_cmd as param
> virsh.py:set event cmd as variable in start_get_event func

- virttest/utils_npiv.py
Sometimes after 'nodedev-destroy' or 'nodedev-create' the mpath
devices not synced with scsi luns.
And this may produce device not found or device not unique issues.
This fix is to make sure the multipath devices synced with scsi
luns.
> Restart multipathd to make sure mpath devs synced

- virttest/libvirt_xml/devices/channel.py
- virttest/libvirt_xml/devices/character.py
- virttest/libvirt_xml/devices/console.py
- virttest/libvirt_xml/devices/serial.py
- virttest/utils_test/libvirt.py
To support source as nested xml.
> Update xml classes of Serial, Console and Channel

- virttest/utils_libvirt/libvirt_vmxml.py
> create_vm_device_by_type:Add support of serial devices

- virttest/test_setup.py
Introducing a new param `vt_ulimit_memlock`.
ID:2133389
> test_setup:Introducing a new param 'vt_ulimit_memlock'

- virttest/utils_test/libvirt.py
> libvirt:Update modify_vm_iface to support deleting bandwidth

- virttest/libvirt_xml/vm_xml.py
> Add ioapic to vmxml features

- virttest/migration.py
> Update to check vm disk on source or destination

- virttest/utils_v2v.py
Add the new parameter to control the shell option in process.run function.
> v2v: add shell parameter to v2v_cmd function

- virttest/libvirt_xml/devices/iommu.py
Test results: https://github.com/autotest/tp-libvirt/pull/4604#issue-1424917860
> iommu: Add 'alias' and 'address'

- virttest/libvirt_vm.py
- virttest/virt_vm.py
Add vm start error status into the class for later usage
> virt_vm: new param for VMStartError

- virttest/shared/cfg/guest-os/Windows/Win10/i386.cfg
- virttest/shared/cfg/guest-os/Windows/Win10/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win11/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win2008/i386.cfg
- virttest/shared/cfg/guest-os/Windows/Win2008/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win2012/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win2016/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win2019/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win2022/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win7/i386.cfg
- virttest/shared/cfg/guest-os/Windows/Win7/x86_64.cfg
- virttest/shared/cfg/guest-os/Windows/Win8/i386.cfg
- virttest/shared/cfg/guest-os/Windows/Win8/x86_64.cfg
> windows: add win virtio driver supports to related cfgs

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_devices/utils.py
- virttest/qemu_vm.py
- virttest/shared/cfg/base.cfg
> qemu_vm: modify/optimize the code to create qemu command in json style

- virttest/libvirt_xml/vm_xml.py
- Remove nvram_template
- Add nvram_attrs and nvram_source
> Update xml class of os/nvram of VMXML

- spell.ignore
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
- virttest/shared/cfg/base.cfg
Includes virtio-mem device support and also
for virtio-mem option/attributes
ID: 2121669
> Includes virtio-mem device support

- virttest/qemu_vm.py
- virttest/shared/cfg/guest-hw.cfg
- virttest/utils_vdpa.py
- virttest/virt_vm.py
Add support for vDPA test environment.
ID:2035984
> Add support for vDPA test environment

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
> qdevices: change value in "cache-size" to integer

- spell.ignore
- virttest/virsh.py
> virsh:Add command domifaddr

- virttest/libvirt_vm.py
> migration: Fix OSError

- virttest/libvirt_xml/vm_xml.py
Signed-off-by: Lili Zhu <lizhu@redhat.com>
> Add the dirty-ring of vm features

- spell.ignore
- virttest/qemu_devices/qdevices.py
- virttest/qemu_monitor.py
- virttest/qemu_vm.py
- virttest/shared/cfg/base.cfg
ID: 2135575
Signed-off-by: Zixi Chen <zixchen@redhat.com>
> Add sgx vt support

- virttest/backends/v2v/cfg/convert_source.cfg
Signed-off-by: vwu-vera <vwu@redhat.com>
> v2v:add ESXi8.0 conf info in vt

- virttest/utils_net.py
Sometimes the address on the interface device is required, so a new option is provided.
> utils_net: enable not remove address

- virttest/migration.py
- virttest/utils_libvirt/libvirt_monitor.py
- virttest/utils_libvirt/libvirt_network.py
- virttest/utils_libvirt/libvirt_service.py
- virttest/utils_misc.py
- virttest/virsh.py
1. Add functions to setup/cleanup firewall rule.
2. Add a parameter for domjobabort().
3. Update kill_service() to kill_or_control_service().
4. Add need_sleep_time parameter.
> Add functions to set firewall rule

- virttest/utils_config.py
> utils_config: add sched_core support

- virttest/qemu_devices/qdevices.py
Add a new param discard_granularity for a virtio disk
id: 2137732
> virttest: Add a new param discard granularity for a disk

- virttest/utils_libvirt/libvirt_disk.py
> Add one simple method to check whether disk partition in vm can be normally used

- spell.ignore
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
> qemu_vm: create qemu command in json style phase II

- virttest/utils_libvirt/libvirt_service.py
To Verify whether certain service is started, start it if not.
> libvirt_service:Add function ensure_service_started

- virttest/utils_libvirt/libvirt_memory.py
1. Add a function to compare memlock
2. Add a function to normalize mem size
Signed-off-by: Yingshun Cui <yicui@yicui.nay.csb>
Test results:
https://github.com/autotest/tp-libvirt/pull/4702#issue-1526662137
> Add supports for memory related tests

- virttest/utils_test/qemu/__init__.py
Includes support for virtio_mem device hotplug
ID: 2127829
> virtio_mem: includes virtio_mem device hotplug

- virttest/libvirt_xml/devices/input.py
> add alias var for input class

- virttest/cpu.py
Architectures might not have NUMA, e.g. s390x. Add variable to skip numa check when checking vcpus, default to True to maintain existing behavior.
Also, add logs to determine more easily which checks failed if the global result is a failure.
> virttest/cpu: add switch to turn off numa check

- virttest/libvirt_xml/vm_xml.py
> vm_xml:Update old implementation of Timer

- virttest/libvirt_xml/devices/disk.py
The old marshal_to/marshal_from functions are customized, update them to support setup_attrs/fetch_attrs
Test result:
```
(1/3) type_specific.io-github-autotest-libvirt.svirt_attach_disk.positive_test.default_vol.disk_seclabel.disk_label_svirt_image_s0.sec_relabel_yes.sec_type_static: PASS (28.32 s)
(2/3) type_specific.io-github-autotest-libvirt.svirt_attach_disk.positive_test.disk_pool.disk_seclabel.enable_namespace.disk_label_svirt_image_s0.sec_relabel_yes.sec_type_static: PASS (55.47 s)
(3/3) type_specific.io-github-autotest-libvirt.svirt_attach_disk.positive_test.disk_pool.disk_seclabel.disable_namespace.disk_label_svirt_image_s0.sec_relabel_yes.sec_type_static: PASS (73.60 s)
```
> disk:Update old marshal functions

- spell.ignore
- virttest/qemu_devices/qdevices.py
qdevices: creating support some types of -object
fix some types represented of object option in json style
> qdevices: creating support some types of -object

- spell.ignore
- virttest/backends/v2v/cfg/convert_destination.cfg
- virttest/utils_v2v.py
> v2v: add '-o kubevirt' support

- virttest/qemu_devices/qdevices.py
> qdevices: change requested-size type in json for -device

- avocado_vt/plugins/vt_runner.py
In avocado #5586 we added missing tributes for result plugins. This is a fix for avocado-vt runner.
Reference: https://github.com/avocado-framework/avocado/pull/5586
> Add missing attributes to the test status

- requirements-travis.txt
- virttest/remote.py
- virttest/utils_v2v.py
Reference
- https://github.com/avocado-framework/aexpect/commit/5fe4e339ffd8b079b87746247cdc0eb98a09dc54
> Typo fix to match aexpect

- virttest/qemu_monitor.py
We raise a specialized exception for monitor errors in a manner similar to the one for QMP monitors.
This fixes issue #3583.
> Raise an error if any errors are detected in monitor command's output

- spell.ignore
- virttest/libvirt_xml/vm_xml.py
1. There are more and more hyperv features as time goes by. So it is good to use standable class to contain all hyperv feeatures.
2. Add more supported hyperv features in the class
> vm_xml: Add new feature in hyperv

- virttest/libvirt_xml/domcapability_xml.py
Add hyperv attributes and features support in domcapabilities XML.
> domcapability_xml: add hyperv feature support

- virttest/qemu_devices/qdevices.py
> qdevices: change type of pmem and label-size

- virttest/qemu_storage.py
- virttest/shared/cfg/base.cfg
Add extent_size_hint to _parse_options()
id:2176783
> qemu_storage:add extent_size_hint support

- virttest/guest_agent.py
Add a new guest agent command 'guest-get-diskstats' to get guest disk statistics
ID:2166559
Signed-off-by: demeng demeng@redhat.com
> guest_agent.py: Add new command 'guest-get-diskstats'

- selftests/unit/test_iscsi.py
- virttest/iscsi.py
Remove the functions of setting target acls, set  initiator name of iscsiadm and restarting iscsid.
> Remove unused iscsi functions

- virttest/qemu_devices/qdevices.py
> qdevices: change "discard-data" type from string to boolean

- spell.ignore
- virttest/qemu_devices/qdevices.py
> qdevice: change acpi-index type

- virttest/libvirt_xml/snapshot_xml.py
Add support for new parameter in snapshot xml class
> snapshot_xml: add new attribute

- virttest/utils_net.py
To support getting interface info of given interface
> utils_net:Update function get_linux_iface_info

- virttest/utils_logfile.py
need a function to check key message count
related pr  https://github.com/autotest/tp-libvirt/pull/4825/ 
```
/usr/bin/python /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 chardev..file_append
(1/3) type_specific.io-github-autotest-libvirt.chardev.file_append.serial.append_on: PASS (112.97 s)
(2/3) type_specific.io-github-autotest-libvirt.chardev.file_append.serial.append_off: PASS (130.14 s)
(3/3) type_specific.io-github-autotest-libvirt.chardev.file_append.serial.append_default: PASS (129.61 s)
```
> add def get_match_count

- virttest/utils_libvirt/libvirt_unprivileged.py
Or session cannot get status of command sent to it.
> libvirt_unprivileged:Set default status_check_cmd of vm session

- spell.ignore
- virttest/vt_utils/cpu.py
Signed-off-by: Houqi (Nick) Zuo [hzuo@redhat.com](mailto:hzuo@redhat.com)
> vt_utils/cpu.py: Add a new utility for the CPU

- virttest/qemu_devices/qcontainer.py
By default, EDK2 provides firmware files in raw format, but fedora recently supported qcow2 format, and QEMU can native use it.
Reference: https://src.fedoraproject.org/rpms/edk2/c/3cf8c78157b21905db34f926f94a15ced66f52de?branch=rawhide
ID: 2196404
> qcontainer: Support pflash firmware files in qcow2 format

- virttest/utils_test/libvirt.py
This is to enable to verify some messages do not exist in the qemu command line.
> libvirt: enable not found in qemu line

- virttest/virsh.py
Add a function to support virsh domhostname.
> virsh: Support domhostname

- virttest/env_process.py
Need to set different values in some cases.
> env_process: Make 'local_boolean_value' configurable

- virttest/vt_utils/sys_time.py
Here's a new time module including the functions about time.
> vt_utils/sys_time.py: Add a new utility for the time

- virttest/qemu_vm.py
ID: 2214521
Signed-off-by: Jin Liu jinl@redhat.com
> Fix parent_bus for virtio-gpu device

- virttest/qemu_capabilities.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_vm.py
* qcontainer: refactor the routine of `machine_by_params`
* qdevices: introduce `QMachine` and apply it to virttest
> Enhance the creation of qemu machine dev

- virttest/utils_libvirt/libvirt_monitor.py
To fix following error:
ERROR: eval() arg 1 must be a string, bytes or code object
> Fix a parameter error

- virttest/utils_test/libvirt.py
verify_virsh_console function always auto close session
For https://github.com/autotest/tp-libvirt/pull/4990  and https://github.com/autotest/tp-libvirt/pull/4963
> seperate virsh console login function

- virttest/libvirt_xml/pool_xml.py
- virttest/utils_test/libvirt.py
> pool_xml: enable fetch_attrs usage

- virttest/virsh.py
> virsh: enable page size unit definition

- virttest/libvirt_xml/capability_xml.py
Two enhancements:
- Enable the <pages> under <cpu> could be achieved by Getter/Setter
<capabilities>
<host>
<cpu>
...
<pages unit='KiB' size='4'/>
<pages unit='KiB' size='2048'/>
<pages unit='KiB' size='1048576'/>
- Enable <pages> under <cell> could be used by fetch_attrs
<capabilities>
<host>
<cpu>
...
<topology>
<cells num='1'>
<cell id='0'>
<memory unit='KiB'>7757548</memory>
<pages unit='KiB' size='4'>1939387</pages>
<pages unit='KiB' size='2048'>0</pages>
<pages unit='KiB' size='1048576'>0</pages>
> capability_xml: add pages element

- virttest/libvirt_xml/vm_xml.py
Add os acpi element for VMOSXML
> vm_xml.py: add os acpi element for VMOSXML

- virttest/qemu_monitor.py
Add qmp cmd about sev platform, capabilities, launch measurement
and attestation report.
> Add sev qmp support

- virttest/test_setup/__init__.py
Sometimes less pages are allocated, but it is acceptable, so no need to raise an error
> test_setup: add new param

- virttest/libvirt_xml/vm_xml.py
Add selable element to os nvram source part
> vm_xml.py: add seclable element to os nvram source part

- selftests/unit/test_setup_networking.py
- virttest/env_process.py
- virttest/test_setup/networking.py
Writing the code to setup/cleanup a bridge into a `Setuper` subclass. Then, registering it in the `setup_manager` from `virttest.env_process`, instead of calling the old set/cleanup code.
ID: 2228738
> env_process: Refactor BridgeConfig into a Setuper

- virttest/libvirt_xml/devices/memballoon.py
For https://github.com/autotest/tp-libvirt/pull/5196
> add support for memballon autodeflate

- virttest/utils_libvirt/libvirt_memory.py
for https://github.com/autotest/tp-libvirt/pull/5061
> add support for qemu process memlock limit value

- virttest/libvirt_xml/devices/memballoon.py
add support for memballoon freepage report attribute 
> add support for memballoon freepage report attribute

- virttest/utils_libvirtd.py
Sometimes the service cannot be starting after we updated config file
> add uncheck service active in restart func

- virttest/libvirt_xml/vm_xml.py
- Add properties
- Remove outdated implementation
> vm_xml:Update VMSysinfoXML class

- virttest/utils_kernel_module.py
1. `unload_module` should also unload the module's holders
2. Some modules don't have parameters, so they will not have `parameters` directory
ID: 1401
> utils_kernel_module.py: unload_module method improvement

- virttest/qemu_vm.py
qemu_vm.py:  add "-global ICH9-LPC.noreboot=off" cmd to guest cli
ID: 1462
> Add itco watchdog to qemu_vm

- virttest/test_setup/__init__.py
> test_setup: fix incorrect format

- virttest/utils_libvirt/libvirt_network.py
Test result in https://github.com/autotest/tp-libvirt/pull/5237.
> Add a function to check listen address

- virttest/utils_libvirt/libvirt_disk.py
Use "/" mount information to identify a disk and return its name.
> utils_libvirt/libvirt_disk: add function to get disk not on /

- scripts/perf.conf
- scripts/regression.py
> regression.py: Fix the error in running regression.py

- virttest/libvirt_xml/devices/disk.py
From function point, it is already supported, just update related parameter description
> Add discard_granularity attribute in blockio section

- virttest/utils_net.py
In case of VM sessions, the command with pipes created a return value with additional characters ("<#...") so that the command was repeated in the output.
Instead of using bash pipes with grep and awk run plain 'ip route' in bash and do the filtering in Python code.
> utils_net: move ip route filter for default to Python code

- virttest/utils_test/qemu/__init__.py
unplug_memory: include virtio-mem unplug support
Following the same approach implemented in virtio-mem
hotplug; includes the support for virtio-mem device
unplug.
ID: 1939
> unplug_memory: include virtio-mem unplug support

- virttest/ssh_key.py
Add key on a new line to avoid authorized_keys file format issue.
> Fix authorized_keys issue

- virttest/utils_libvirt/libvirt_network.py
> Update check_listen_address function

- virttest/shared/cfg/guest-os/Windows/Win2025.cfg
- virttest/shared/cfg/guest-os/Windows/Win2025/x86_64.cfg
- virttest/shared/unattended/win2025-autounattend.xml
- virttest/shared/unattended/win2025-autounattend_ovmf.xml
Microsoft released a new windows server version, add related configuration to support Win2025 in avocado-vt.
ID:1936
> Add Win2025 support

- virttest/utils_sriov.py
Update to return the 1st PF if there is no PF in 'UP' status.
> utils_sriov: Update get_pf_pci()

- virttest/env_process.py
- virttest/test_setup/storage.py
This patch refactors the VM storage setup and cleanup steps out from the pre- and post-process functions on `env_process.py` into a `Setuper` subclass.
ID: 1970
> env_process: Refactor storage setup/cleanup into a Setuper

- virttest/qemu_storage.py
- virttest/shared/cfg/base.cfg
Signed-off-by: Tingting Mao <timao@redhat.com>
ID: 1953
> qemu_storage: add compression_type for create and convert

- virttest/utils_test/qemu/__init__.py
1. Add check crashkernel size method
2. Add crashkenel size calculation in MemoryHotplug check_memory
ID: 1441
Signed-off-by: zhenyzha zhenyzha@redhat.com
> Add check crashkernel size method

- virttest/libvirt_xml/vm_xml.py
For https://github.com/autotest/tp-libvirt/pull/5502
> add genid element for vm xml

- virttest/libvirt_xml/devices/input.py
Add @type for selection of elements by their type.
> libvirt_xml/input: add type attribute

- virttest/qemu_vm.py
Add default values for sandbox options
ID: 2025
> sandbox_opt: add default values for sandbox options

- virttest/shared/cfg/guest-os/Windows/WinNext.cfg
- virttest/shared/cfg/guest-os/Windows/WinNext/x86_64.cfg
- virttest/shared/unattended/win-vnext-autounattend.xml
- virttest/shared/unattended/win-vnext-autounattend_ovmf.xml
Introduce a new varaint WinNext to test Windows desktop vNext edtion.
ID:2103
> WinNext: Introduce a new guest name to test vnext version

- virttest/utils_vdpa.py
Update to support vhost-vdpa blk test.
> utils_vdpa: Add simulated vhost-vdpa blk support

- virttest/qemu_vm.py
> qemu_vm: Fix the issue of iterating a dict

- virttest/virsh.py
check event to confirm attach device successfully
> add support for wait event in attach device function

- virttest/libvirt_xml/devices/disk.py
This is to support the new elements in disk as below:
<driver name='qemu' queues='3'>
<iothreads>
<iothread id='2'>
<queue id='1'/>
</iothread>
<iothread id='3'>
<queue id='0'/>
<queue id='2'/>
</iothread>
</iothreads>
</driver>
> disk: support driver iothreads elements

- virttest/utils_libvirt/libvirt_disk.py
> libvirt_disk: return instead of exception

- virttest/env_process.py
- virttest/test_setup/networking.py
Move the setup step of the firewalld service from the env_process.{pre,post}process into a Setuper subclass. The env_process setup_manager will call the setup/cleanup methods when appropriate.
ID: 2276
> env_process: Refactor firewalld setup/cleanup into a Setuper

- virttest/qemu_devices/qcontainer.py
- virttest/qemu_vm.py
1. Removed kvm-type from -machine options
2. Workaround the firmware setting by bios_path
ID: 2368
> Added Intel TDX support

- virttest/utils_sys.py
Add a new function to get host bridges on a host
> utils_misc: Add a new func for get host_bridge on a host

- virttest/cpu.py
Starting from qemu v9.0.0, the help text of cpu models associated with all the hardware architectures was unified to the pattern below.
$ qemu -cpu '?'
Available CPUs:
<model>   <description>
...
As a result, we have to modify the corresponding parseing function to cater for the change, since the arch names were no longer showed in front of the model names.
This patch is going to introduce a new parser for handling the new pattern of cpu help text, meanwhile keep the old one for supporting legacy qemus.
ID: 2369
> cpu: adapt help text parsing to support modern qemus

- virttest/tests/unattended_install.py
Install viomem driver during guest installation
ID: 1946
Signed-off-by: menli <menli@redhat.com>
> unattended_install: Load viomem driver

- virttest/utils_misc.py
Extend the functions get_pci_vendor_device, bind_device_driver, and unbind_device_driver to support session handling.
id:2285
> utils_misc.py: add session support to PCI device utilities

- virttest/utils_libvirt/libvirt_memory.py
> libvirt_memory: install numactl in vm

- virttest/qemu_vm.py
> Hotunplug original nic without closfd

- virttest/utils_libvirt/libvirt_vmxml.py
- virttest/utils_sys.py
need to add function
For https://github.com/autotest/tp-libvirt/pull/5657
> add function check_guest_machine_type and check_audit_log

- virttest/utils_net.py
1. detect available dhcp clients (dhclient, dhcpcd)
2. configure release command base on detected client
id: 2628
> utils_net.py: add dhcp client detection

- virttest/qemu_capabilities.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_devices/qdevices.py
- virttest/qemu_monitor.py
- qemu_capabilities: introduce BLOCKJOB_BACKING_MASK_PROTOCOL
- qemu_monitor: introduce new argument to block_stream/commit
- qcontainer: eliminate raw format node by default
ID: 2408
> Qemu blockdev raw format elimination

- virttest/test_setup/__init__.py
Add huge page checking after allocation.
Test results using this function:
(1/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.default_page_size: PASS (94.29 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.default_hugepage_size: PASS (103.27 s)
(3/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.1G: PASS (109.94 s)
(4/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.0: PASS (23.74 s)
(5/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.scarce_mem: PASS (25.24 s)
> Add huge page allocation checking

- virttest/utils_zcrypt.py
Since there is extra sestat entry in secure guest in s390, so add processing for it.
> Add crypto device sestat entry in secure guest for S390

- virttest/qemu_devices/qdevices.py
Some options are deprecated since the dedicated virtiofsd package since rhel9, while before virtiofsd belongs to qemu package.
> qdevices: Adapt virtiofsd options

- virttest/nfs.py
When the directory is not exist, process.getoutput may return empty, which will cause the directory creation step to be skipped. So update code.
> Fix no directory issue

- virttest/libvirt_xml/vm_xml.py
Signed-off-by: Julia Graham [jugraham@redhat.com](mailto:jugraham@redhat.com)
Modified set_vm_vcpus() to ensure clusters is not None
> vm_xml: set_vm_vcpus() ensure clusters not None

- virttest/libvirt_xml/devices/tpm.py
Add debug attr for swtpm logging.
> tpm.py: add debug attr for swtpm logging

- virttest/utils_net.py
> utils_net:Fix func get_default_gateway_json

- virttest/utils_net.py
Test result: https://github.com/autotest/tp-libvirt/pull/6000
> get_default_gateway_json:support returning iface name of default gateway

- virttest/utils_net.py
Add ip_options to support removing color option
> utils_net:Add ip_options to function get_net_if

- virttest/utils_net.py
Test result in https://github.com/autotest/tp-libvirt/pull/6189.
> utils_net: Add ip_options to create_ovs_bridge/delete_ovs_bridge

- virttest/utils_misc.py
For https://github.com/autotest/tp-libvirt/pull/6225
> add support for data file properity in get_image_info function

- virttest/nfs.py
this patch fix CI issue which is introduced by https://github.com/avocado-framework/avocado-vt/pull/4048
> FIX CI issue

- virttest/qemu_devices/qdevice_format.py
- virttest/storage.py
- Optimizing and Fixing the error about usb args type for each usb-devices.
ID: 3710
> update qdevice_format.py module

- virttest/virsh.py
virsh net-metadata cmd is new introduced
> add support fo virsh net-metadata cmd

- virttest/nfs.py
Test passed on the jenkins jobs.
> Update mount source for image mode

- virttest/remote.py
Update right parameters for _pull_file, _push_file and _reset_file
ID:4124
> remote:Update right parameters for functions of RemoteFile

- virttest/utils_net.py
Tell them which NIC to use (script picks NIC 0 if we don’t say). This patch uses that number instead of always 0 in the command and logs, and the old code still works fine.
ID: 4042
Signed-off-by: wji <wji@redhat.com>
> netkvm: add nic_index argument to set/get nic params

- virttest/backends/v2v/cfg/convert_source.cfg
VDDK 9.0.0.0 (sic) was released last week add vddk9.0.0 value for nbdkit testing
> add vddk9.0.0 value for nbdkit testing
