virttest/virsh.py
In the previous code, a file is opened in 'a+' mode which causes
a problem when creating several secrets in the file.
=> Update the mode to write for secret_set_value()

.cirrus.yml, avocado_vt/loader.py, avocado_vt/plugins/vt_list_archs.py, avocado_vt/plugins/vt_list_guests.py, setup.py, virttest/standalone_test.py
The current `--vt-list-guests` and `--vt-list-archs` options to `avocado list` depend on the `avocado.core.loader`'s "extra listing" feature, which is not a great thing.
Also, users tend to want to have access to that specific information, and not that and the test list.
This is also a preparation to when the `avocado.core.loader` is removed for good (in place of the resolver).
=> Introduce standalone commands to list guests and archs

virttest/utils_disk.py
Add parameter target_letter as an option to set driver letter
in windows guest.
ID: 1829709
Signed-off-by: Menghuan Li menli@redhat.com
=> utils_disk: Add parameter target_letter to set driver letter

avocado_vt/plugins/vt.py
In the commit f54b602 was introduced a configuration of command line options
compatible with avocado Job API. Unfortunately there missing default value for
`--vt-type` option on avocado versions 80 and lower. This commit fixing this
problem.
=> `--vt-type` default

avocado_vt/test.py, avocado_vt/utils.py, virttest/utils_misc.py
This simplifies the `VirtTest._runTest` method by moving blocks of code into their own utility functions.  The reasons are:
* Maintainability
* I'm working on a runner based on the nrunner architecture, and those blocks of code are also needed in this other implementation too
=> VirtTest refactors

virttest/utils_windows/drive.py
New API get_disk_props_by_serial_number to get disk drive value
of properties by serial number in windows guest.
ID: 1868329
=> drive: New API to get disk drive value of porperties by serial number

avocado_vt/loader.py, avocado_vt/plugins/vt.py, avocado_vt/plugins/vt_init.py
Sometimes, when we use the config file to run avocado, we want to use
short names as test names, so "--vt-short-names-when-config" is
introduced to allow users to switch it.
ID: 1905350 
=> Introduce "--vt-short-names-when-config" to switch test names display

virttest/qemu_monitor.py, virttest/qemu_vm.py
Enable migration capabilities "pause-before-switchover" on source
host and "late-block-activate" destination host before migrating
guest, Then continue migration on source host after the status of
migration is "pre-switchover".
ID: 1881805
=> qemu_vm: Enable pause-before-switchover and late-block-activate

virttest/ovirt.py
When VM has more than one interfaces, the index 0
interface may be unreachable, this patch checks
the IP address before returning.
=> v2v: find reachable IP address automatically

virttest/bootstrap.py
Special chars like '()' cannot be parsed successfully in cfg file.
Replacing special chars with _ could avoid bootstrap failure
=> bootstrap:Replace special chars in cpu_version

virttest/utils_test/__init__.py
'tar' might not be available on some vm. Install it first to make
sure command exists.
=> Install 'tar' before executing commands

PR_Review_And_Contribute_Practices.txt
This is follow-up for issue:#2748
Libvirt Team members summarize some rules or guidelines related to Upstream PR Review/Contribute as per past practices.
After reviewing, it is good to be merged and become common best practices in avocado-vt upstream.
If further feedbacks are available, related guidelines and rules can be constantsly evolved accordingly.
=> Add upstream PR Review/Contribute Practices

virttest/virt_admin.py
This PR adds a function to support server-update-tls command
in the virt-admin session.
=> Add server_update_tls() for virt-admin server_update_tls command

virttest/libvirt_xml/backup_xml.py, virttest/utils_backup.py
With the implementation of libvirt RFE bz1811906, luks encryption
was supported during domain backup process. Now, the SCRATCH
of the pull-mode backup and the TARGET of the push-mode can be
encrypted with LUKS. And the usage is to add a 'encrytion' subelement
under 'scratch' or 'target' elements. This commit is to support it.
=> Add encryption support for domain backup xml

virttest/ovirt.py
The previous ping command doesn't return 0 even the IP
is reachable. Let's use ping function in utils_net.py
to replace the old command.
=> ovirt: fix unexpected return value of ping

virttest/qemu_devices/qcontainer.py
qemu can launch a guest without any images, no need to deal with efi rom
at this time.
ID: 1912175
=> qcontainer: Allow empty image in pflash_handler

virttest/utils_test/libvirt.py
In some cases, observe that disk xml is used before all contents are completely written in
By allowing additional wait until </disk> keyword is at end of xml file
=> Fix disk xml is used before all contents are completly written in

virttest/qemu_capabilities.py, virttest/qemu_devices/qcontainer.py, virttest/qemu_migration.py, virttest/qemu_vm.py, virttest/utils_test/qemu/migration.py
Some migration parameters are deprecated and replaced by other parameters after qemu-5.1.
1."migrate_set_downtime" is deprecated and replaced by "migrate_set_parameter":
2."migrate_set_speed" is deprecated and replaced by "migrate_set_parameter": 
3."migrate_set_cache_size" is deprecated and replaced by "migrate_set_parameter";
ID: 1845429
=> migration: Support for setting migration parameters

virttest/guest_agent.py
Add new command "guest-ssh-add-authorized-keys, 
-remove-, -get-, and reset " for ssh login guest without 
passwd.
ID: 1906644
=> guest_agent: Add new api for ssh-pub-keys operations

virttest/migration.py, virttest/utils_misc.py, virttest/utils_test/__init__.py
threading.Thread.isAlive() has been removed in python 3.9,
and is_alive() has been supported since python 2.6
id: 1916085
=> Replace 'isAlive' with 'is_alive' for threading.Thread

.travis.yml
python 2.7 is deprecated already, so just remove it
Moreover, this also align with avocado project
=> Remove python 2.7 support in travis ci

virttest/libvirt_vm.py
undefine() will do nvram check, remove duplicated check
Fix remove_guest failure
Signed-off-by: Liu Yiding <liuyd.fnst@cn.fujitsu.com>
=> Remove duplicated nvram option check

virttest/utils_test/libvirt.py
Recently the dhcp/range has added a element expiry time, so the
definition change from dict to a class. Update some network
define functions in libvirt.py file accordingly.
=> Update the dhcp/range as the definition changes

virttest/passfd_setup.py
For Python>=3.8, abiflag `m` is no longer added [1] therefore we
have to update the compile option.
Reference:
[1] https://bugs.python.org/issue36844
ID: 1917860
=> passfd: Correct the library name for Python>=3.8

virttest/utils_test/libvirt.py
disk_type is used both for disk definition xml and for create_local_disk function
call. Since commit avocado-vt 18fd732 create_local_disk won't
default to lvm for value `block` anymore. Therefore, any call to attach_disks with disk_type
block is currently failing. Those calls should be fixed to pass `lvm` now to be more specific
as later changes to create_local_disk might add other block disk types besides lvm.
=> [libvirt.attach_disks] set correct disk_type for lvm

virttest/utils_test/libvirt.py
avocado-vt supports 2 arm machine type: arm64-mmio:virt arm64-pci:virt
Signed-off-by: Liu Yiding <liuyd.fnst@cn.fujitsu.com>
=> support arm in check_machine_type_arch

virttest/migration.py
Migration should be started correctly before executing some
command lines. So update it to wait for 3s to avoid some
unexpected problems. For instance, the virsh domjobabort command
sometimes make storage migration timeout if it's executed directly
after the migration.
=> migration: wait for a few seconds to start the migration correctly

virttest/qemu_vm.py
The issue happened on give the wrong key or value
case 1 inexist key:
p_dict = {"filexx": orig_img_name}
device_name = vm.get_block(p_dict)
print(device_name)
case 2 unmatch value:
p_dict = {"file": orig_img_name}
device_name = vm.get_block(p_dict)
print(device_name)
For the case1, it return the fist block
For the case2, it crash on "for block in blocks_info.splitlines()"
due to 'list' object has no attribute 'splitlines'
ID:1920886
=> qemu_vm:fix get_block issue

virttest/qemu_vm.py
Allow iommu related options to be configured via xxx_extra_params,
otherwise qemu_vm will cleanup iommu options properties when
virtio_dev_xxx is empty.
ID: 1925548
=> Do not set iommu related option when virtio_dev_xxx is not defined

virttest/libvirt_vm.py
unattended_install will not use "cdrom_no_kernel_initrd" anywhere, it
should be "cdrom". Otherwise, the virt-install will add the cdrom_cd1 in
"--location" and "--disk".
=> libvirt_vm: Correct the cdrom type in make_create_command

virttest/libvirt_cgroup.py
Libvirt commit ed1ba69f5a starts to use '17592186044415' as max value
for cpu quota, this patch is to treat this value as 'max'.
=> Add new cpu quota max value for cgroup2 test

virttest/shared/deps/rss/Makefile, virttest/shared/deps/rss/setuprss.bat
When PowerShell is invoked from a 32-bit process running on a
64-bit OS some cmdlets are not accessible (e.g. `New-SmbShare`,
`Install-WindowsFeature` and others). With this change rss.exe or
rss64.exe will be installed depending on the detected bitness.
=> Add a 64-bit build configuration for rss

virttest/utils_test/libvirt.py
If volume name is like 'Auto-esx7.0-rhel7.9-special-characters~!@#$%^&*_=+,?><:;|."[]{}()`\-m',
when calling shlex.split, it will raise 'No closing quotation' error.
Reading the following answer, a repr could solve the problem and it works well
on both python2 and python3.
https://stackoverflow.com/questions/18935754/how-to-escape-special-characters-of-a-string-with-single-backslashes
After the fix:
>>> import shlex
>>> v1 = 'Auto-esx7.0-rhel7.9-special-characters~!@#$%^&*_=+,?><:;|."[]{}()`\-m'
>>> shlex.split('virsh dumpxml %s' % repr(v1))
['virsh', 'dumpxml', 'Auto-esx7.0-rhel7.9-special-characters~!@#$%^&*_=+,?><:;|."[]{}()`\\\\-m']
=> fix No closing quotation error when volume has special characters

virttest/libvirt_xml/accessors.py
It fails if trying to assign an XMLElementList if its parent xpath
not exists. This commit will try to create the missing parent xpath.
=> XMLElementList: create parent xpath if not exists

avocado-plugins-vt.spec
Python 2 is no longer included in the CI and slowly falling out of favor,
let's make it optional and make Python 3 the RPM package of choice.
=> Make the python3 RPM the default subpackage and python2 optional

MANIFEST.in
It reports a SyntaxError when installing avocado-vt in python 2.7
env. And it's a script that can only be used in python 3 env, so
exlude it in MANIFEST.in.
=> Exclude pmsocat to install avocado-vt in python 2.7 env

virttest/utils_v2v.py
The source file path may has nested directories. Let's use greedy re expression
for the path.
For example:
<source file='[esx6.0-matrix-backup] esx6.0/esx6.0-win10-x86_64/esx6.0-win10-x86_64.vmdk'/>
=> v2v: fix incorrect vmx file path issue

virttest/backends/v2v/cfg/convert_source.cfg
ESXi5.5 is not supported by v2v anymore
Signed-off-by: mxie91 <mxie@redhat.com>
=> Remove esx5.5 source from v2v jobs

virttest/utils_net.py
The package "dhcp-client" was not installed on some hosts, so the
network connection would be interrupted.
=> utils_net: Install dhcp-client before creating/deleting the ovs bridge

virttest/utils_v2v.py
The process.run in compare_version should ignore_status, or it will
break the testing script execution when the package is not installed.
=> v2v: do not fail in compare_version

virttest/ip_sniffing.py
1) Tshark version string may don't have '(Wireshark)', we should update
the re expression about it.
example version output:
TShark 1.10.14 (Git Rev Unknown from unknown)
TShark (Wireshark) 2.6.2 (v2.6.2)
TShark (Wireshark) 3.4.2 (Git commit a889cf1b1bf9)
2) Update the tshark version command.
=> ip_sniffing: update tshark version re expression

virttest/migration.py
Some of migration cases need to run stress in VM, so add it to
MigrationTest() class.
=> migration: Add run_stress_in_vm method into MigrationTest class

virttest/migration.py
`migrate_options` might not have been set. Return empty string to avoid
tests failing with
"TypeError: argument of type 'NoneType' is not iterable"
=> [virttest/migration] Set default value to avoid TypeError

avocado_vt/plugins/vt_init.py, selftests/.data/vt_test.conf, selftests/__init__.py, selftests/unit/test_vt_init.py
In early stage of avocado run, there is a time when the vt options are
created, but they are not synchronized with values from config files.
This can affect some of the global variables which are set during this
time. This commit ensures the synchronization right after the options
are registered.
Reference: #2912
=> Compatibility with config files in early stages

virttest/qemu_devices/qcontainer.py
1. Correct the image path from DATA_DIR to current_data_dir
2. Keep `pc` machine type can use continue to use OVMF
ID: 1926800
=> pflash_handler: correct the image path in and keep it compatible with pc

virttest/utils_backup.py
Incremental backup function was enabled by default since
libvirt-7.0.0-6.el8, which is tracked by bz1799015.
So update script NOT to edit vm's xml to enable this function.
=> Update the libvirt version which enables incremental backup

virttest/libvirt_xml/devices/disk.py
The methold __eq__ override super class with DriverMetadata,which cause
vm_xml.del_device() throw not define error
=> Fix driverMetadata is not defined error

virttest/qemu_devices/qdevices.py
`aexpect.run_bg` will also run the shell command in the background, so
if swtpm running in the daemon mode, then "run_bg" will return an idle
process and the swtpm process is not controlled.
ID: 1932183
=> qdevices: Remove "--daemon" option on QSwtpmDev

avocado_vt/test.py
In the avocado 86.0 will be removed the test -> job dependency. This
commit will ensure the compatibility of avocado-vt with avocado>=86
Reference:https://github.com/avocado-framework/avocado/pull/4429
=> Future Test class independence on Job class in avocado

avocado_vt/utils.py
Some refactoring made it possible that this variable is never
previously defined leading to:
```
13:00:37 ERROR| Reproduced traceback from: /usr/lib/python3.8/site-packages/avocado/core/test.py:767
13:00:37 ERROR| Traceback (most recent call last):
13:00:37 ERROR|   File "/usr/lib/python3.8/site-packages/avocado_vt/test.py", line 309, in runTest
13:00:37 ERROR|     raise self.__status  # pylint: disable=E0702
13:00:37 ERROR|   File "/usr/lib/python3.8/site-packages/avocado_vt/test.py", line 255, in setUp
13:00:37 ERROR|     self._runTest()
13:00:37 ERROR|   File "/usr/lib/python3.8/site-packages/avocado_vt/test.py", line 361, in _runTest
13:00:37 ERROR|     test_modules = utils.find_test_modules(t_types, subtest_dirs)
13:00:37 ERROR|   File …
```
=> Fix an instance of (conditionally) undefined variable

virttest/utils_conn.py
Some cases need to build server key with an empty ip_address.
=> TLSConnection: Update to set an empty server_info_ip in build_server_key

virttest/cpu.py
For new os there is a line
"Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled"
Which will cause error for get_cpu_info:
"dictionary update sequence element #24 has length 4; 2 is required"
update to compatible this situation
=> Resolve the lscpu have multi ":" in ouput

virttest/utils_libvirt/libvirt_cpu.py
Xmltreefile can not find the cpu mode although it exists in the domain xml,
change to use try except to check if cpu mode exists
=> Fix the xmltreefile can not find the cpu mode issue

selftests/unit/test_cartesian_config.py, virttest/cartesian_config.py
Joint variants need flattening and dropping of indices in order
to detect values that should be substituted if a previous parameter
of the given key exists.
=> Allow value replacement in joint variants

virttest/libvirt_xml/vm_xml.py
'memory_unit' accessor was defined, but not added to slots,
this commit will fix it.
=> Fix 'memory_unit' missing from slots of VMXMLBase

virttest/utils_libvirt/libvirt_pcicontr.py
This is to provide an utility function to get a free slot for a given bus.
This function is useful to select an usable slot when attaching a pci
device to avoid of slot conflict.
=> libvirt_pcicontr: Get free pci slot

avocado_vt/test.py
Specific parameters for avcoad-vt are named as `vt_params` but inside
`VirtTest` those parameters are named as `params_vt`. This might be
confusing because it's still the same data. This PR unifies the
naming.
=> Unification of vt parameters naming

virttest/remote_commander/remote_runner.py
It reports an E1111 error when checking the style.
depends on https://github.com/avocado-framework/avocado-vt/pull/2967
=> remote_runner: Fix E1111 errors

requirements-travis.txt, selftests/unit/test_qemu_devices.py, virttest/element_tree.py, virttest/ip_sniffing.py, virttest/libvirt_xml/devices/disk.py, virttest/libvirt_xml/vm_xml.py, virttest/propcan.py, virttest/qemu_virtio_port.py, virttest/utils_backup.py
Version of pylint is too low and causing errors like:
`module 'isort' has no attribute 'SortImports'` which blocks pylint
check for all modules.
This commit should fix it.
=> Fix: pylint check not working

virttest/libvirt_xml/domcapability_xml.py, virttest/libvirt_xml/vm_xml.py
The method get_additional_feature_list() got the features except
invtsc. But some cases need it for now, so add a parameter to
set whether to get it or not.
=> get_additional_feature_list: Update to get complete features

avocado_vt/test.py
Just a few long overdue compatibility cleanups.
=> VirtTest: remove compatibility with legacy Avocado versions

virttest/qemu_devices/qcontainer.py
Support to boot a guest with virtio-serial-ccw device on s390x host
ID: 1941879
=> qcontainer: Support virtio-serial-ccw on s390x

virttest/qemu_devices/qcontainer.py
When machine_type needs to add parameters, the simplest qemu instance will
report an error. add failed pattern to fix it.
ID: 1942374 
=> qcontainer: fix machine type extra params error

virttest/utils_zcrypt.py
For test tear down, add function to unload the vfio_ap.
=> [utils_zcrypt] add function to unload module

virttest/cpu.py
As there are several lines in the lscpu output for some attribute, directly splitline will get wrong pair info
Reduce the \n+space before splitlines
e.g.
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state u
nknown
before
```
JOB ID     : 0aa182dc4f1f1e30703442d32d57e8d9e94770da
JOB LOG    : /root/avocado/job-results/job-2021-04-01T07.05-0aa182d/job.log
(1/1) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem: ERROR: dictionary update sequence element #28 has length 1; 2 is required (49.79 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 50.51 s
```
after
```
JOB ID     : …
```
=> Fix the cpu info get in guest

virttest/backends/v2v/cfg/convert_destination.cfg
'--nvram' has no harm no mattter whether it's a uefi guest or not.
so place the configuration here for all to_libvirt cases.
=> v2v: add '--nvram' when convertion target is to_libvirt

virttest/utils_test/libvirt.py
According to recsent change, tmp_dir is no longer suitable as nfs
server. Replacing it with data_dir could fix the errors when we
try to mount nfs storage.
=> Update nfs mount path to data_dir instead of tmp_dir

virttest/utils_misc.py, virttest/utils_test/qemu/__init__.py
Get cache memory of guest,including windows and linux os.
ID: 1946456
=> virttest: add function to get cache memory for given OS

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/qemu_vm.py
From qemu6.0, short-form boolean options are deprecated, options
such as "server" or "nowait", correct them to "server=on" and
"wait=off", and also make correction for some -spice options
id: 1945036
=> qemu_vm/qemu_devices: deprecate short-form boolean options

virttest/qemu_devices/qcontainer.py
The network storage image path is in json format,
Instead of img_path. So we need to redefine pflash_vars_path.
ID: 1945507
=> qcontainer.py: Add pflash_handler() support for network-storage

virttest/libvirt_vm.py
Enable config source name and target path when preparing
guest agent
Signed-off-by: Lili Zhu <lizhu@redhat.com>
=> Enable to config other elements in prepare_guest_agent

virttest/libvirt_cgroup.py
Some cases check the result's exist status of virsh command,
so split get_virsh_output_dict() into 2 methods to get the dict
type output from the command object.
BTW, update the values of "quota" related keys to 'max'.
test results:
https://github.com/autotest/tp-libvirt/pull/3437#issue-615842628
=> libvirt_cgroup: Add a method to get output as a dict

virttest/utils_test/libvirt.py
Sometimes it triggers GC when returning xml tmp file path which causes
the following referrence fails. So it should be removed. This PR can
fix the problem by directly returning whole object.
The error is like:
`CmdError: Command '/bin/virsh attach-device avocado-vt-vm1 /tmp/xml_utils_temp_9exbbws7.xml --current' failed.stdout: b'\n'stderr: b"error: Failed to open file '/tmp/xml_utils_temp_9exbbws7.xml': No such file or directory\n"additional_info: None`
=> Remove retuning xml tmp file

virttest/libvirt_xml/vm_xml.py
This function is to provide a common support to remove sub element
in <cpu> configuration.
=> Remove any sub elem in <cpu>

virttest/libvirt_xml/vm_xml.py
To allow get_iface_by_mac() to get coalesce info
=> Add coalesce info to get_iface_by_mac()

virttest/utils_conn.py
There is no /etc/pki/CA dir on the remote host since rhel9,
so update to create one if needed.
_Before fix:_
```
JOB ID     : f69c3224396bc9af5c37066bf56723f756eaae2c
JOB LOG    : /root/avocado/job-results/job-2021-04-06T05.56-f69c322/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.listen_address.with_tls.without_postcopy: ERROR: Failed scp from /tmp/avocado_jxph4ju9/tmpwelayt7y/cacert.pem on AdminHost to /etc/pki/CA/ on 10.73.114.63.\nerror: SCP transfer failed    (status: 1,    output: '\ndebug1: Authentication succeeded (password).\nAuthenticated to 10.73.114.63 ([10.73.114.63]:... (101.76 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | …
```
=> utils_conn: Update to create pki_CA_dir on remote host

requirements-travis.txt
- Update version of pylint to >=2.8.0
- Remove requirements of python 2.7 since travis check on python
2.7 had been removed.
=> Fix error of inspektor in travis check

virttest/shared/cfg/guest-os/Windows.cfg
This check is deprecated starting in Windows 10 Insider Preview
Build 19042 and above.
id: 1944490
=> Deprecate "Kernel synchronization delay fuzzing" flag for win10

virttest/libvirt_xml/vm_xml.py
As the bandwidth setting can be with either 'inbound' or 'outbound',
add one check before the assignment. Same for driver part, as it can
be without driver/host and driver/guest.
=> Update the get_iface_by_mac() to be more robust

virttest/migration.py, virttest/virsh.py
Add virsh.EventTracker.wait_event decorator to check event if needed.
Test result:
https://github.com/autotest/tp-libvirt/pull/3431#issue-614144325
=> Update to check event for some of migration cases

virttest/qemu_devices/qcontainer.py
After multiple resets of vms with the same command line (and thus parameters)
I had to investigate why I keep getting "VM params in env don't match requested"
a lengthy debugging revealed the problem is in 'mig_params` not being found in
the second container dictionary because:
<virttest.qemu_capabilities.Capabilities object at 0x7f95e57af430>
!= <virttest.qemu_capabilities.Capabilities object at 0x7f95e7ed2b80>
The `mig_params` which was modified in some incompatible way somewhere in the
last versions should thus be ignored for the comparison.
=> Drop usage of migration capabilities in qdev container comparisons

virttest/utils_test/libvirt.py
For gluster volume setup, /tmp sometimes causes unexpected error because
tmpfs (/tmp sometimes use) filesystem can not support the function. So
we decide to use other directory instead.
For iscsi block,  dd 10G sometimes will fail due to no enough space on /tmp. 
So it is also changed.
=> do not use /tmp

virttest/utils_misc.py
same with https://github.com/avocado-framework/avocado-vt/pull/2948
```
JOB ID     : 4f0c5bdacca7afac4d9a43a87cafa74e3de3f6e1
JOB LOG    : /root/avocado/job-results/job-2021-05-06T03.08-4f0c5bd/job.log
(1/1) type_specific.io-github-autotest-libvirt.libvirt_cputune.normal_test.wo_cachetune: PASS (7.32 s)
JOB TIME   : 7.85 s
```
=> Resolve the lscpu have multi ":" in ouput in utils_misc

virttest/qemu_devices/qdevices.py
short-form boolean options are deprecated, options such as "server"
or "nowait" use server=on" and "wait=off" now, the qemu command line
was updated with commit ce145bc4a0b231b6a65a58d77e832aeda5a8fda7,
make it work with device hotplug too.
id:1958490
=> qdevices: fix chardev hotplug with wrong parameter value

virttest/migration.py, virttest/utils_disk.py
Add network accessibility and disk I/O checks as common checkpoints.
Disk partition checking does not work in remote vm session.
It reports an error - ERROR: Shell command failed:
"yes|mkfs.ext4 -F '/dev/\x1b[01;31m\x1b[Kvdb\x1b[m\x1b[K1'".
So update to no longer highlight the matching strings for the command
line in _list_disk_partitions().
=> MigrationTest: Enhance post_migration_check to check disk and network

virttest/utils_test/libvirt.py
vhostuser disk is newly introduced backend storage
```
vhostuser disk looks like as below:
<disk type='vhostuser' device='disk' snapshot='no'>
<driver name='qemu' type='raw'/>
<source type='unix' path='/tmp/vhost.sock'/>
<target dev='vdb' bus='virtio'/>
</disk>
```
=> Add vhostuser disk support in libvirt.create_disk_xml

.cirrus.yml, contrib/containers/ci/centos-7.docker
This is a part of https://github.com/avocado-framework/avocado-vt/issues/2963
=> cirrus-ci: Disable Python2 checks

avocado-plugins-vt.spec, setup.py
It's been decided that Python 2 will be dropped.  That doesn't necessarily
mean we'll go through all the code and remove everything that is valid on
Python 2, but that we won't ship or support Avocado-VT running on Python 2.
This removes the conditionals for requirements on Python 2, and removes the
(already optional) building of Python 2 RPMs.
Reference: https://github.com/avocado-framework/avocado-vt/issues/2963
=> Remove installation and package availability based on Python 2

virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py
virtual-network: add virtual-css in qemu_vm to support s390x, add
virtual-css for parent bus in qcontainer to support s390x
ID:1942866
=> Add virtio-net-css to support s390x

virttest/libvirt_xml/devices/audio.py, virttest/libvirt_xml/devices/librarian.py
Unknown/unsupported type 'audio', supported types will thrown if
there is no this attribute added
=> Fix audio device delete failure issue

virttest/utils_backup.py, virttest/virsh.py
There are 3 parts in this commit:
1. Add a new BackupCanceledError exception.
2. Add 'extra' in virsh.domjobinfo to allow it take more params
such as '--complete' when backup job canceled.
3. Add a 'is_backup_canceled' method to check if backup job
just canceled.
=> Add support to check if backup job canceled

virttest/utils_test/libvirt.py
Update create_hostdev_xml function to create a hostdev device
with 'teaming'.
depends on:  https://github.com/avocado-framework/avocado-vt/pull/3052
Test result:
` (1/1) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: PASS (119.34 s)`
=> Update create_hostdev_xml to create hostdev with teaming

virttest/ceph.py
Previously we didn't write a '\n' to the file end, and this will cause
rbd command failure on rhel9.
=> Add new line to ceph.conf file

virttest/libvirt_xml/devices/hostdev.py
Add 'teaming' elememt for hostdev device.
Test result:
` (1/1) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: PASS (119.34 s)`
=> hostdev: Add 'teaming' to Hostdev

virttest/env_process.py, virttest/qemu_monitor.py
This is an addition to the original implementation of vm persistence
that preserves the vm objects, i.e. PR: Optional vm persistence #2105.
=>  Preserve monitor connections for any preserved vms across test runs

virttest/libvirt_xml/accessors.py, virttest/libvirt_xml/devices/disk.py
Multiple snapshot could create backingchain inside diskxml,
BackingStore objects nested under BackingStore objects. This commit
will allow us to get backingStore object from the parent
backingStore object.
Update function element_by_parent by adding arg nested to allow the
function to search for sub-element when nested is True instead of
returning parent element when parent element has the same tag with
target sub-element.
There's also a new function to get an ordered list of backingStores
of a disk object.
=> Support backingstore nested under backingstore

virttest/libvirt_xml/devices/disk.py
The method is to help get backstore list from disk, then
get relative elements from backstore list,such as source file
=> Add one method get_backingstore_list into Disk

avocado-plugins-vt.spec, avocado_vt/discovery.py, avocado_vt/loader.py, avocado_vt/plugins/vt_resolver.py, avocado_vt/plugins/vt_runner.py, avocado_vt/test.py, avocado_vt/utils.py, setup.py
This is an early, and limited, but still functional, implementation of a runner that plugs into Avocado's "nrunner" architecture.
It is based on @clebergnu PoC #2904
If you're interested in trying it out, after bootstrapping Avocado-VT, you should be able to do:
```
$ avocado list --resolver boot 
avocado-vt io-github-autotest-qemu.boot
```
And to run tests:
```
$  avocado run --test-runner=nrunner --nrunner-max-parallel-tasks 1 boot /bin/true /bin/true /bin/true
JOB ID     : f5fcbe85af3398323fe8a482eea30bdfe3fd213a
JOB LOG    : /home/jarichte/avocado/job-results/job-2021-03-19T17.48-f5fcbe8/job.log
(1/4) io-github-autotest-qemu.boot: STARTED
(1/4) io-github-autotest-qemu.boot: PASS (22.31 s)
(2/4) /bin/true: STARTED
(2/4) /bin/true: PASS (0.01 s)
(3/4) /bin/true: STARTED
(3/4) /bin/true: …
```
=> Nrunner support  [v2]

virttest/utils_test/libvirt.py
This is to make the command 'qemu-img convert' optional for netfs.
Because image_convert is True as default, this change will not
impact the existing invoke codes. The reason to change this is
because in most cases there is no need to do the image convert
which increases the migration duration. After this, the user
invokes set_vm_disk() with image_convert='no' to avoid converting
the image.
=> Support image convert disable

virttest/utils_libvirt/libvirt_misc.py
Some virsh commands have output in same or similar format. So this
function is to used as an unified one to run and parse the result
to a dict. For example, the commands are virsh.vcpupin, virsh.emulatorpin,
virsh.iothreadinfo and so on.
=> libvirt_misc: new function to parse result

virttest/migration.py
`migrate_options` might not be set. Use empty string to avoid tests
failing with
"TypeError: argument of type 'NoneType' is not iterable"
=> [virttest/migration] Add default value to avoid TypeError

virttest/utils_sriov.py
This PR adds a function to set VF's mac address.
` (1/1) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: PASS (103.56 s)`
=> utils_sriov: Add a function to set VF's mac

virttest/video_maker.py
`image_size` is correctly initialized as a tuple, which is the type
expected by `PIL.Image.resize()`, but when the size is smaller than
640x480 the tuple is inadvertently replaced by an integer.
Signed-off-by: Samir Aguiar <samir.aguiar@intra2net.com>
=> Fix image resizing before video encoding

virttest/utils_sriov.py
The package 'dhcp-client' is not installed in some cases, so
update to install it and update the dhclient command line to
configure all network interfaces to avoid network disconnection
problem.
Test result:
(1/1) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: PASS (119.34 s)
=> utils_sriov: Install 'dhcp-client' and update to configure all interfaces

virttest/utils_sriov.py
This PR adds a function to get vf's pci id from pf pci id.
Test result:
` (1/1) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: PASS (119.34 s)`
=> utils_sriov: Add a function to get vf's id

virttest/qemu_devices/qcontainer.py
Virtual_block:modify dev_parent bus from virtio-bus to virtual-css bus
since when doing the hotplug action, the pluggable bus is the ccs bus
on s390x
ID:1964477
=> Modify parent bus for virtio-blk-ccw on s390x

virttest/migration_template.py
Due to a mistake in code, virsh_migrate_options will be set to
empty string if --xml/--persistent-xml is not specified. Introduced
by commit ab3c84ba.
=> migration_template: fix an error in migrate options

virttest/unittests/test_utils_zchannels.py, virttest/utils_zchannels.py
Add two new classes to handle subchannel and channel paths using
s390-tools commands lcss, chchp.
=> [utils_zchannel] Define helpers for handling (sub)channel paths on s390x

virttest/shared/cfg/guest-os/Windows/Win2022.cfg, virttest/shared/cfg/guest-os/Windows/Win2022/x86_64.cfg, virttest/shared/unattended/win2022-autounattend.xml, virttest/shared/unattended/win2022-autounattend_ovmf.xml
1. Add guest os config files for win2022;
2. Add answer files(seabios & ovmf) for win2022.
ID: 1966588
=> Add windows server 2022 support

virttest/migration.py
In some cases, we need to pass a MethodType 'func' during
migration.
=> Migration: Support MethodType 'func'

virttest/utils_libvirt/libvirt_vmxml.py
Add support to clear up vm's devices of a given type.
Test result:
```
JOB LOG    : /root/avocado/job-results/job-2021-06-06T21.04-846db45/job.log
(1/1) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_device_with_teaming: PASS (99.11 s)
```
=> libvirt_vmxml: Add a method to remove vm's devices of a given type

virttest/utils_libvirt/libvirt_vfio.py
This PR adds a method to check if the driver is vfio type.
Test result:
` (1/1) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_device_with_teaming: PASS (97.59 s)`
=> Add support to check if the driver is vfio

virttest/utils_sriov.py
This PR adds a method to get the mac address of VF.
`type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_device_with_teaming: PASS (97.59 s)`
=> utils_sriov: Add a method to get vf's mac

virttest/nfs.py
To avoid the problem of NFS sever not working properly,
restarting the nfs-server and rpcbind at the beginning of the
setup().
=> nfs: Update to restart the services

virttest/libvirt_xml/vm_xml.py, virttest/utils_v2v.py
The old vmxml.get_disk_all cannot filter some disks which will make
the code more complcated. Let's create a new function get_disk_count_by_expr
to only count the expected disks.
=> v2v: make getting disk count more flexible

virttest/libvirt_xml/vm_xml.py, virttest/utils_v2v.py
1) When source vm has a cdrom, the process of getting source disks
will fail.
2) Improve the v2v_setup_ssh_key to accept a custom pub key
=> v2v: fix get disks issue and improve v2v_setup_ssh_key

avocado_vt/plugins/vt.py, avocado_vt/plugins/vt_init.py
The action being given to the "--vt-extra-params", by omission, was
"store".  That caused every entry to override the previous one.  What
we really need, to have a list of options, is "append".
While at it, let's change the number of arguments, because it does
not make any sense to have "--vt-extra-params" with zero arguments.
=> Extra Params: restore support for command line --vt-extra-params

.cirrus.yml, avocado_vt/plugins/vt.py, avocado_vt/plugins/vt_init.py, contrib/containers/ci/fedora-34.docker
This greatly improves coverage by actually running a complete boot test, using the KVM support on Cirrus CI.  It's currently only supported for the QEMU backend, because further setup would be necessary for the libvirt backend.
=> CI: add complete boot tests

avocado_vt/plugins/vt_joblock.py
This is a version that is not supported anymore, so that compatibility
should not be here anymore.
=> avocado_vt/plugins/vt_joblock.py: remove compatibility with LTS 36.0

virttest/cpu.py
The output of 'lscpu' on remote host is different from that on
the local host since util-linux-2.37.
=> CPU: Fixup 'lscpu' command's output inconsistent issue

virttest/libvirt_cgroup.py
After libvirt commit 184245f53b 'vircgroup: introduce nested cgroup
to properly work with systemd'. All vm's cgroup params will be in
a 'libvirt' sub-dir in /sys/fs/cgroup/vm.scope/. But 'cpu.shares'
and 'io.bfq.weight' still stay in the vm's root dir (vm.scope dir).
So this patch is to make sure using correct path to read 'cpu.shares'
and 'io.bfq.weight' files.
=> cgroup2: Use correct path to read cpu.shares and io.bfq.weight

avocado_vt/plugins/vt_runner.py
In the newest avocado, after [#4629](https://github.com/avocado-framework/avocado/pull/4629), the nrunner messages have to be sent as bytes. This makes avocado-vt nrunner compatible with those changes.
Reference: #3106
=> Nrunner logging fix

virttest/env_process.py, virttest/qemu_devices/qcontainer.py
Since some customer scenarios need to set the capability
of the shell env before starting the daemon.
So modify virtiofsd daemon and qemu cmd decoupled,
Allow users to set the daemon more flexibly.
ID: 1966468
=> Modify virtiofsd daemon and qemu cmd decouple

virttest/libvirt_xml/devices/tpm.py, virttest/utils_test/libvirt.py
Add new attribute persistent_state for tpm device, supported from
libvirt 7.0.0.
=> tpm dev: new attribute persistent_state

virttest/libvirt_xml/capability_xml.py
Add 'iommu' to CapabilityXML class.
`(1/1) type_specific.io-github-autotest-libvirt.sriov.capabilities.intel_iommu: PASS (3.50 s)`
=> capability_xml: Add 'iommu' to CapabilityXML

virttest/utils_libvirt/libvirt_pcicontr.py
Currently pcie-to-pci-bridge controller can be displayed in the
VM's XML, in which case it reports "Multiple 'pci' controllers".
=> libvirt_pcicontr: Fix reset_pci_num

virttest/tests/unattended_install.py
=> unattended_install:support to use cdrom metadata during installation 

virttest/qemu_monitor.py
"query-cpu-model-expansion" will return all properties with the provided
CPU model, add it in QMPMonitor and then we can query which features are
supported of the specific CPU model.
ID: 1970784, 1970785, 1970786
=> qemu_monitor: Introduce "query_cpu_model_expansion" in QMPMonitor

virttest/utils_v2v.py
The previous code bind '--no-copy' with '-oo rhv-disk-uuid' option,
but in fact, they don't have relations, let's use a variant to control
the rhv-disk-uuid option.
=> v2v: update rhv-disk-uuid setting

virttest/virt_vm.py
Some cases test with vm without nic need a serial session, make
it is available.
id: 1968402
=> virt_vm: allow use a serial connection when remote login failed

virttest/libvirt_xml/devices/librarian.py, virttest/libvirt_xml/devices/nvram.py, virttest/libvirt_xml/devices/redirfilter.py, virttest/libvirt_xml/devices/shmem.py
This is subsequent follow-ups requests from hanhan in PR: https://github.com/avocado-framework/avocado-vt/pull/3056
=> Add nvram, redirfilter and shmem device support

virttest/libvirt_cgroup.py
The default value of cgroup memory is set to PAGE_COUNTER_MAX, which is
LONG_MAX/PAGE_SIZE on 64-bit platform.
When the paltform`s PAGE_SIZE is diferent, the default value of cgroup memory is diferent,
such as 4k and 64k has the different default values:
0x7ffffffffffff000(pagesize=4k)
0x7fffffffffff0000(pagesize= 64k)
Fix tp-libvirt guest_resource_control.control_cgroup..memtune..positive for aarch64
Before
```
[root@hpe-moonshot-02-c21 avocado_vt]# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio guest_resource_control.control_cgroup..memtune..positive
JOB ID     : af784ff734c424bc09fcc310b198b2999f8eefbd
JOB LOG    : /root/avocado/job-results/job-2021-07-13T03.38-af784ff/job.log
(01/12) …
```
=> libvirt_cgroup: Set max_mem_value when PAGE_SIZE is 65536

virttest/utils_sriov.py
This PR adds:
1. a function to get the pci id of pf
2. a function to get the address dict from pci_id
3. a function to get the device name from pci_id
test results: https://github.com/avocado-framework/avocado-vt/pull/3133
=> utils_sriov: Add some functions

virttest/utils_test/libvirt.py
Add hostdev_addr to modify_vm_iface()
` (1/1) type_specific.io-github-autotest-libvirt.sriov.managed.device.hotplug.managed_no: PASS (40.64 s)`
=> libvirt: Add hostdev_addr to modify_vm_iface()

virttest/utils_test/libvirt.py
Add interface managed to modify_vm_iface().
```
>>> iface = interface.Interface('network')
>>> iface.xml=libvirt.modify_vm_iface("avocado-vt-vm1", "get_xml", {'managed': 'yes'})
>>> print(iface)
<?xml version='1.0' encoding='UTF-8'?>
<interface managed="yes" type="network">
<mac address="52:54:00:26:58:7e" />
<source network="default" />
<model type="virtio" />
<address bus="0x01" domain="0x0000" function="0x0" slot="0x00" type="pci" />
</interface>
>>> iface.xml=libvirt.modify_vm_iface("avocado-vt-vm1", "get_xml", {'managed': 'no'})
>>> print(iface)
<?xml version='1.0' encoding='UTF-8'?>
<interface managed="no" type="network">
<mac address="52:54:00:26:58:7e" />
<source network="default" />
<model type="virtio" />
<address …
```
=> libvirt: Add managed to modify_vm_iface()

virttest/utils_test/libvirt.py
Support vf_list in create_net_xml.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.managed.networks.default: PASS (108.88 s)`
=> libvirt: Add vf_list to create_net_xml()

virttest/utils_libvirt/libvirt_keywrap.py
Reading the key with `cat` can lead to issues with aexpects
ShellSession. Use `hexdump` instead.
=> [libvirt_keywrap] use hexdump to read key

virttest/qemu_vm.py
qemu_vm: Add pvpanic device support for aarch64
id: 1979447
=> qemu_vm: Add pvpanic device support for aarch64

virttest/utils_net.py
avoid the error below:
```
Problem: problem with installed package openvswitch2.11-2.11.3-89.el8fdp.x86_64
- package openvswitch2.15-2.15.0-24.el8fdp.x86_64 conflicts with openvswitch2.11 provided by openvswitch2.11-2.11.3-89.el8fdp.x86_64
```
before
```
virtual_network.iface_options.iface_type.type_vhostuser.queue_size_check: PASS (344.19 s)
```
after
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_vhostuser.queue_size_check: PASS (42.14 s)
```
=> Change the order to deal with install conflict time waste

virttest/libvirt_xml/devices/disk.py
Add support for the following libvirt new features:
```
v7.4.0
qemu: Add support for sharing base image of <transient/> disks
Users can use <transient shareBacking='yes'/> to tell the qemu driver
to never open the base image in write mode thus multiple VMs can share
the same image. Note that the disk will be hotplugged during startup.
```
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>
=> Add sharebacking attribute to disk xml

virttest/virsh.py
Before
```
[root@hpe-moonshot-02-c20 ~]# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio \
> managedsave.libvirt_guests.positive_test.parallel_shutdown.shutdown_on_shutdown.ignore_on_boot \
> managedsave.libvirt_guests.negative_test.no_parallel_shutdown \
> virsh.managedsave.functional_test.undefine
JOB ID     : b866299512b1f56d41269122b7957ae526213504
JOB LOG    : /root/avocado/job-results/job-2021-07-22T04.39-b866299/job.log
(1/3) type_specific.io-github-autotest-libvirt.managedsave.libvirt_guests.positive_test.parallel_shutdown.shutdown_on_shutdown.ignore_on_boot: PASS (109.95 s)
(2/3) type_specific.io-github-autotest-libvirt.managedsave.libvirt_guests.negative_test.no_parallel_shutdown: ERROR: Command …
```
=> virsh.py: add undefine "--nvram" option for aarch64

virttest/utils_test/libvirt.py
This is to provide an utility function to update the vm disk's
target attributes.
=> libvirt_disk: update vm disk target

virttest/nfs.py
This reverts commit 3d3f48c78219fa1786df6b2db3d84170df4248b6.
NFS mount bug has been resolved and previous commit has caused
problems for others.
=> Revert "nfs: Update to restart the services"

virttest/utils_test/libvirt.py
When there is no interface device in the vm xml, it will create a new one.
But in previous code, it forget to add it into the vm xml. If the oper is
"update_iface", the function will not work as expected.
=> Fix the issue in modify_vm_iface()

avocado_vt/plugins/vt_resolver.py
There is no need to initialize parser each time when resolver resolving
reference, it is time consumptive operation. This PR initializes
parser inside resolver initialization.
=> Cartesian parser init for resolver

virttest/utils_sriov.py
Some tests require specific pf details, so add a function to get
pf information by the given pci id.
Test results:
https://github.com/autotest/tp-libvirt/pull/3658#issue-694170220
=> utils_sriov: Add a function to get pf info by the given pci id

virttest/utils_misc.py
'avocado.core.exceptions' has no attribute 'TestSetupError', it should
be 'TestSetupFail'.
id: 1986658 
=> utils_misc: fix 'TestSetupError' attribute error

avocado_vt/plugins/vt_resolver.py
The #3126 PR isn't compatible with avocado changes in
https://github.com/avocado-framework/avocado/pull/4746/commits/43286b5fa3083fc0d3fb4381a4a40024d120eb81 this incompatibility of avocado and avocado-vt broke vt resolver. This
commit fixes the problems.
=> VT resolver fix

virttest/libvirt_xml/base.py
When comparing 2 xml objects, we're comparing values of attributes
of all_slots. But we don't always set value to all those attributes,
and trying to get value of an unset attribute would meet
`AttributeError`. Therefore ignore the error.
=> Ignore Error when trying to get an unset attribuite of an xml obj

avocado_vt/conf.d/vt.conf, avocado_vt/plugins/vt_runner.py, docs/source/GetStartedGuide.rst
The avocado plan for near future to change default runner form legacy to
nrunner. It is necessary to prepare avocado-vt for this change. The vt
nrunner doesn't support parallel run, and it is necessary to set
`--nrunner-max-parallel-tasks` to 1 before each run with nrunner. This
might be frustrating when the nrunner becomes the default  avocado
runner. This commit sets  `--nrunner-max-parallel-tasks` to 1 as default
when the avcodo-vt is bootstrapped. So it won’t be necessary to set that
variable each time the avocado-vt is run.
Reference: #3030
=> Default serial run for vt nrunner

virttest/qemu_vm.py
QEMU help info about smp change with QEMU6.1:
1. old:
-smp [cpus=]n[,maxcpus=cpus][,cores=cores][,threads=threads]...
2. new:
-smp [[cpus=]n][,maxcpus=cpus][,sockets=sockets][,dies=dies]...
so update the patter to match maxcpus for all.
id: 1988915
=> qemu_vm: update smp_pattern to match maxcpus

virttest/libvirt_xml/base.py
To compare 2 xml objects when they're not equal.
=> LibvirtXMLBase: override operator ne

virttest/utils_package.py
This is to print the error message when installation fails.
=> utils_package: print error log

virttest/qemu_storage.py
This is a new change in QEMU6.1, refer QEMU commit:
497a30dbb065937d67f6c43af6dd78492e1d6f6d
id: 1989371
=> qemu_storage: require -F with -b backing image

virttest/shared/cfg/guest-os/Linux.cfg, virttest/shared/cfg/guest-os/Windows.cfg
Move the specific parameters of test cases into tp-qemu.
ID: 1987211
=> Remove parameters of file_transfer in Linux.cfg and Windows.cfg

virttest/utils_libvirt/libvirt_keywrap.py
Commit 3bcc957a800ea465db407a783ee4633b453864c6 switched to usage
of `hexdump`. Unfortunately, `hexdump` doesn't set error code
if no token can be read and instead just notifies
"hexdump: /sys/devices/virtual/misc/pkey/protkey/protkey_aes_128: No
such device".
Check for substring in output to handle this as if error code was set.
=> libvirt_keywrap: handle hexdump when token unavailable

virttest/libvirt_xml/network_xml.py, virttest/libvirt_xml/vm_xml.py
For XMLElementList accessor that has subclass, we need marshal_from
function to accept dict as arguments to support function setup_attrs
=> Update marshal_from function to support setup_attrs

virttest/virsh.py
'virsh vcpuinfo' has an option '--pretty'. This PR is to support it.
=> virsh: support vcpuinfo option

virttest/utils_libvirt/libvirt_network.py
Check if the tap device is connected to the bridge, and compare
with the expected state.
=> Check if the tap device is connection state is as expected

virttest/utils_misc.py
Add passout parameter to fix following error:
CmdError: Command '/usr/bin/openssl req -new -x509 -days 1095
-key /etc/pki/libvirt-spice/ca-key.pem -passin pass:none
-out /etc/pki/libvirt-spice/ca-cert.pem -subj
&quot;/C=NC/L=Raleigh/O=Red Hat/CN=virt-test&quot;'
failed.stdout: b''stderr: b'Enter PEM pass phrase: ...
=> Update parameter for openssl command

virttest/libvirt_xml/network_xml.py, virttest/utils_test/libvirt.py
Network can be set as dns disabled or dhcp disabled. Set
<dns enable='no'/> can disable the dns function of the vm. And
delete the dhcp range can disable dhcp for the network.
=> To support a test case about disable dns and dhcp

virttest/env_process.py, virttest/utils_conn.py
SSH pwdless connection needs for some storage migration cases.
Test result:
https://github.com/autotest/tp-libvirt/pull/3716#issue-715788540
=> Enable ssh connection for migration

virttest/libvirt_xml/vm_xml.py
Add new parameter to allow for 'memfd' source type.
Per default, the value is not set.
A sample xml will look like:
```
<memoryBacking>
<source type="memfd" />
<access mode="shared" />
</memoryBacking>
```
=> vm_xml/set_memoryBacking_tag: add memfd support

.cirrus.yml
Avocado 91.0 adds a job check for missing runners, that is, when a
runner is not found, the job is aborted.
While other fixes will be included in Avocado 92.0, this will allow
Cirrus CI jobs to find "avocado-runner-dry-run", and hopefully restore
the passing state of jobs currently failing with:
Avocado job failed: JobError: Could not find runners for runnable(s) of kind(s): dry-run
=> Cirrus CI: workaround for Avocado 91.0

virttest/utils_sriov.py
Add timeout parameter to set_vf().
https://github.com/autotest/tp-libvirt/pull/3754#issue-726530073
=> sriov: Add timeout to set_vf

avocado_vt/plugins/vt_resolver.py
For each test reference we have to parse a new avocado Cartesian
configuration with new `only_filter` related to the reference. This will
fix the problem with resolving multiple vt references.
Reference: #3210
=> Cartesian parser fix in resolver

virttest/utils_libvirt/libvirt_network.py
Add a function to check connection number of a network.
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.connection.macvtap_passthrough: PASS (38.70 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.connection.hostdev: PASS (41.52 s)
```
=> libvirt_network: Add a function to check network connections

virttest/libvirt_xml/vm_xml.py
The policy of some features may be 'disable', so update the policy
when adding a feature.
**Before fix:**
` (1/1) type_specific.io-github-autotest-libvirt.virsh.hypervisor_cpu_compare.cpu_xml.f_domcapa_xml: FAIL: Expect success but got:\n (6.89 s)`
**After the fix:**
`1/1) type_specific.io-github-autotest-libvirt.virsh.hypervisor_cpu_compare.cpu_xml.f_domcapa_xml: PASS (6.42 s)`
=> from_domcapabilities: Update to specify features' policy

avocado_vt/options.py, virttest/env_process.py, virttest/guest_agent.py, virttest/ppm_utils.py, virttest/qemu_monitor.py, virttest/virsh.py, virttest/virt_admin.py
As we discussed at avocado-framework/avocado#4797 and #3169, the
current logger will display a lot of excessive output on the LOG_UI. These
outputs are the same as debug.log, they should only be in logs if we
don't use verbose mode, so this is unexpected behavior. Beraldo Leal
provides a good solution in #3169, the code works for me, so I
borrowed his solution to solve this problem accordingly.
Some VT modules will use "logging.warning" to print messages outside
the class/function, so when import these modules, the logging.RootLogger
will be initialized before the test execution, which will make the
RootLogger is out of control. Use the LOG_UI is a better choice.
Signed-off-by: Beraldo Leal <bleal@redhat.com>
=> Redefine the logger to avoid excessive output at the LOG_UI

virttest/utils_test/libvirt.py
Usually we check the expected error messages in stderr. But some
virsh command also outputs the useful message to stdout when the
exit status is not zero. For example,
```
virsh command: hypervisor-cpu-compare /tmp/log
status: 1
stdout: CPU described in /tmp/log is incompatible with the CPU
provided by hypervisor on the host
stderr:
```
So this is to support to check stdout, too.
=> libvirt: support search stdout on error

virttest/utils_test/libvirt.py
The avocado_data path may don't have correct permission settings for
v2v operation, and the unconfigurable path is inconvenient to use.
It's better to add custom param to make the path configurable.
[stderr] stderr: 'error: Failed to start domain 'esx6.5-win2016-x86_64'
error: internal error: process exited while connecting to monitor: 2021-09-22T08:27:59.579473Z qemu-kvm: -blockdev {"driver":"file","filename":"/root/avocado/data/avocado-vt/v2v_dir_pool/esx6.5-win2016-x86_64-sda","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/root/avocado/data/avocado-vt/v2v_dir_pool/esx6.5-win2016-x86_64-sda': Permission denied
=> Make pool target path adjustable in PoolVolumeTest

virttest/backends/v2v/cfg/convert_destination.cfg
The data_dir.get_data_dir() will have permission issue for v2v
operations. It should always use default libvirt image path for testing.
=> v2v: make images into default image path when converting vm to libvirt

virttest/tests/unattended_install.py
On avocado-vt side, add install fwcfg64 driver support when
unattend install a windows vm.
id: 1992917
=> [unattended_install] Add installing fwcfg64 driver support

virttest/utils_test/libvirt.py
There was no log when patterns are found.Logging found info could
make output more clear.
=> libvirt: Add more log to check_result() when patterns are found

virttest/libvirt_xml/vm_xml.py
xml classes which inherit from VMXML will also inherit VMXML's slots, along with other methods, which will make comparison of 2 xml instances impossible.
=> vm_xml: Update super class from VMXML to base.LibvirtXMLBase

virttest/qemu_monitor.py
Under heavy load, saving large Windows 10 VMs (dozens of GBs) can
lead to timeout errors.
This is similar to what was done in 9e24834.
Signed-off-by: Samir Aguiar <samir.aguiar@intra2net.com>
=> Increase timeout for monitor commands

virttest/libvirt_vm.py, virttest/qemu_vm.py
As discussed in multiple threads in Avocado project, we are using this
new logging approach to avoid touching on the root logger since July.
The next LTS is counting on that and we need to adapt the logging calls
here to use its own namespace.
This is just an test/experiment to see how things will behave here. I'm
choosing this file because is the one with more logging calls.
Signed-off-by: Beraldo Leal <bleal@redhat.com>
=> libvirt_vm: using module name as logger namespace

avocado_vt/test.py
This solves remaining process-isolation issues and background described in 
https://github.com/avocado-framework/avocado-vt/issues/3239
=> Add a possibility to customize VT tests via pre-run hooks

virttest/libvirt_xml/vm_xml.py
Set default xml to EventXML instance to fix the issue of xml missing.
=> Fixup: xml missing from definition of VMPerfXML.EventXML

virttest/utils_test/libvirt.py
Since the su did not work for some special cases, the new terminal
has to be opened and therefore the code was updated to support this.
Signed-off-by: kvarga <kvarga@redhat.com>
=> Updated connect_libvirtd to support su

virttest/env_process.py, virttest/test_setup.py
With split daemon, if we're going to enable polkit access control
with the modular daemons it needs to be enabled on all of them
at once. The original code only enable polkit on qemud.conf. So
fix it.
=> Fix the polkit setup

virttest/libvirt_xml/vm_xml.py
Including CacheTuneXML, MemoryTuneXML and VMCPUTuneXML and their
subclasses.
We support attributes of XMLElementList with subclasses now, the
old usage is outdated.
=> vm_xml: Update old usage of xml classes

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/shared/deps/serial/serial_host_send_receive.py
ID: 1986691
abstract=on|off specifies the use of the abstract
socket namespace, rather than the filesystem. Optional,
defaults to false. tight=on|off sets the socket length
of abstract sockets to their minimum, rather than the
full sun_path length. Optional, defaults to true.
related tp-qemu patch: [tp-qemu/3008](https://github.com/autotest/tp-qemu/pull/3008)
=> qdevices.py: add chardev parameters

virttest/qemu_vm.py
Upstream qemu change with commit 553dc36b38, it tweak
[, maxcpus=cpus] to [, maxcpus=maxcpus] in qemu-options
id: 2013885
=> qemu_vm: change the smp pattern to match maxcpus correctly

docs/source/DownloadableImages.rst
We've found that recently we had to make sure our test images
have `export TERM=dumb` for consoles to suppress control characters
that broke tests.
Add a new section to contain topics that users should keep
in mind when using their own images.
=> doc: Add section about custom images

virttest/qemu_devices/qcontainer.py
There is an issue that multiple vTPM daemoms will use the same tpm
state path and sock patch on both source and destination guest
in the scenario of localhost migration. This will result in datat
conflict. So work around to distinguish though adding the randon
string suffix to the filename to make it unique.
ID: 2018896
=> qcontainer: Rename file of vTPM daemon to be unique

virttest/test_setup.py
The connect driver may be different in some cases, so update to
be able to specify 2 drivers.
Test results: https://github.com/autotest/tp-libvirt/pull/3853#issue-1044268444
=> LibvirtPolkitConfig: Support multiple connect drivers

virttest/utils_split_daemons.py
Even in a modular daemons environment, all virt*d.socket may not
be running, so update to check if the daemons are enabled.
=> is_modular_daemon: update to check if daemons are enabled

virttest/utils_libvirt/libvirt_nested.py
Previous restarting libvirtd daemon method requires to recognize if the
environment is a monolithic vs modular daemons as default. But after
the libvirt packages are installed in L1 guest, those daemons are not
expected to be started automatically. So preovious restarting method
can not work correctly on right daemons. To make the right daemons
start correctly, it is easy to reboot the vm directly or explicitly
restart it by name in certain case which will be more flexible. So
this fix is to remove that part and leave the control to the invoker.
=> libvirt_nested: not control daemon

virttest/utils_split_daemons.py
1.Run the testcase if the daemon mode on the host is the same as the
required daemon mode;
2.Cancle the testcase if the daemon mode on the host is not the same
as the required daemon mode;
=>  Add a function to only run the testcase in the daemon mode on the host

spell.ignore, virttest/utils_sriov.py, virttest/utils_switchdev.py, virttest/utils_vdpa.py
Add support to setup vDPA test environment.
BTW, there is no 'net' dir for the vDPA env, so update to read the
link of the VF in get_vf_pci_id() to get the pci id.
Test results: https://github.com/autotest/tp-libvirt/pull/3838#issue-1035947106
=> vDPA: Add utilities for vDPA test

virttest/utils_conn.py
In modular daemon environment, if the qemu.conf file is changed,
then virtqemud daemon should also be restarted.
=> utils_conn: fix tls if qemu.conf is changed

virttest/qemu_vm.py
=> qemu_vm: avoid adding -mem-path option when numa node is defined

virttest/utils_misc.py
Add a function to check if a test is supported in the installed qemu
version.
=> is_qemu_feature_supported: Support to check if a test is supported

virttest/env_process.py, virttest/test_setup.py, virttest/utils_libvirtd.py, virttest/utils_test/libvirt.py
By default, we only need to operate 'virtqemud' in modular daemons
mode now. So add a new param to determine whether to process all
sub-daemons.
=> Libvirtd: Add all_daemons param

requirements.txt
Since some new tests introduced changes in the aexpect repo, this
commit is about updating the required version to make sure the
tests are running on the latest aexpect version to succed.
Signed-off-by: Kamil Varga <kvarga@redhat.com>
=> Update the version of the aexpect to the latest available

virttest/utils_v2v.py
When doing v2v testing, some workers' tmp directory may not have
enough disk space which will cause convertion failure.
Let's keep same as libvirt's default image path.
=> v2v: update the default os_directory path

virttest/qemu_vm.py
As the bug [1] reported, Python < 3.7 has the issue for pickling
loggers correctly, which resulted in the below VT issue.
Therefore, had the workaround by wrapping the logger to a function
to bypass the issue.
Issue: https://github.com/avocado-framework/avocado-vt/issues/3256
Reference:
[1] https://bugs.python.org/issue30520
=> Bypass the issue of pickling vm data with Python < 3.7

virttest/shared/cfg/guest-hw.cfg
Use lazy assignment for rng required_qemu to avoid overwriting the
configuration in case level.
ID: 1974032
=> rng_required_qemu: use lazy assignment for rng required_qemu

requirements.txt
aexpect 1.6.3 has a problem which blocks the nc client. It was fixed
in 1.6.4. so let's bump it to the new version.
=> Bump the aexpect version to 1.6.4

virttest/libvirt_installer.py, virttest/qemu_devices/qcontainer.py, virttest/utils_qemu.py, virttest/virsh.py
The allow_output_check parameter on the avocado.utils.process.run()
method was meant for use by the "--allow-output-check" feature, but
given it was public API, using it was fair game.
To the best of my knowledge, the parameter is not really needed in
Avocado-VT (it was a nice to have).
Reference: https://github.com/avocado-framework/avocado-vt/issues/3299
=> Workaround for removal of "allow_output_check" parameter

virttest/utils_net.py
For ovs bridge type interface, when we set bandwidth, the unit of
burst value in tc is b, take this situation into account. And correct
the unit conversion(refer to https://bugzilla.redhat.com/show_bug.cgi?id=1510237#c23 
the unit should be 1000. not 1024).
=> Update the unit of tc burst

virttest/utils_net.py
Sometimes there are 2 default gateway on the host, which cause the
get_ip_address_by_interface() to fail with value error. Update it
to pass a single interface name.
=> Fix the get_host_ip_address()

virttest/virsh.py
We did some changes in 4873a25 to fix error "Not found event tray-change after
40 seconds".
Since the error is hard to be reproduced locally and the error breaks a lot
cases in CI. So we merged that draft PR.
After further debug, we noticed that some changes are unnecessary or
inappropriate. Replacing time.sleep with utils_misc.wait_for is much better.
Fix: 4873a25f Debug draft
=> virsh: Remove unnecessary change

virttest/utils_test/qemu/__init__.py
Add wait_time parameter to check momory in guest function, such as after hotplug memory, windows os need several seconds to perceive it.
ID: 1874694
=> virttest.utils_test: Add wait_time parameter for check_memory function

virttest/libvirt_xml/devices/watchdog.py
In order for watchdog to be functional it might be necessary to load
the corresponding kernel module.
Move this function from tp-libvirt watchdog test here to make
it available for more tests.
=> libvirt_xml/devices/watchdog: move try_modprobe function here

virttest/libvirt_xml/vm_xml.py
A PR to add function that support getting dict type cpu feature
**Test result** : /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 vcpu_misc.positive_test.managedsave_restore --vt-connect-uri qemu:///system
JOB ID     : d4757db9f7971041b571fa4e6521cc1b8ca2f0f2
JOB LOG    : /root/avocado/job-results/job-2021-12-20T17.59-d4757db/job.log
(1/1) type_specific.io-github-autotest-libvirt.vcpu_misc.positive_test.managedsave_restore: PASS (5.22 s)
JOB TIME   : 5.63 s
=> vm_xml: Support getting dict type cpu feature

virttest/utils_net.py
After confirmed with developers, the correct unit for burst should
be 1024 not 1000. Update it accordingly, refer to
https://bugzilla.redhat.com/show_bug.cgi?id=1510237#c27
=> The unit of burst should be 1024 not 1000

virttest/backends/virttools/cfg/drivers.cfg, virttest/backends/virttools/cfg/tests-shared.cfg, virttest/backends/virttools/cfg/tests.cfg, virttest/bootstrap.py, virttest/standalone_test.py, virttest/test-providers.d/io-github-autotest-libvirt.ini
Adds a new test type 'virttools' intended to be used for tools offered by the 'virt-manager' repository:
- virt-manager
- virt-clone
- virt-install
- virt-xml
A passing test case for this new type is available in https://github.com/autotest/tp-libvirt/pull/3923
=> backends: add new test type virttools

virttest/cpu.py, virttest/staging/utils_cgroup.py, virttest/utils_package.py
PR alignes avocado-vt with software_manager changes in avocado
See: https://github.com/avocado-framework/avocado/pull/5225
id: 2040126
Signed-off-by: Lukas Kotek <lkotek@redhat.com>
=> software_manager: align avocado-vt with changes in avocado

avocado_vt/plugins/vt_runner.py
After the changes in
https://github.com/avocado-framework/avocado/pull/5179 the avocado
spawners are managing the test output dir. Because of this change,
avocado-vt doesn't have to save results after the test because the
avocado spawner will manage that. This will save the resources and also
make test-results available during the test runtime on avocado
`ProcesSpawner`.
=> `_save_log_dir` removal

avocado-plugins-vt.spec
The May 24, 2021, is not Tuesday, it is Monday. This mistake is causing
warnings in RPM-s builds.
=> Change log date fix

virttest/virsh.py
The event monitor should be started before executing virsh command.
Test result: https://github.com/autotest/tp-libvirt/pull/3991#issue-1101260266
=> virsh: Update detach_interface to use EventTracker.wait_event

.cirrus.yml, setup.py
Hi Avocado-VT developers and maintainers,
This is a PR that needs a bit of special attention from you.  While it looks just like CI level updates, it proposes a decoupling between the development branch of Avocado and Avocado-VT.  This should allow for Avocado to develop new features faster, while still considering compatibility between Avocado and Avocado-VT.
A couple of important points:
1) Every new Avocado development sprint includes a week for stabilization and bug fixes.  If changes are introduced in the latest Avocado development that causes a compatibility issue, there would still be one week to work on bringing back compatibility.
2) The goal continues to be having all Avocado and Avocado-VT regular releases compatible, but that will depend on available resources.  Compromise …
=> Compatibility with Avocado

virttest/utils_misc.py
`set_winutils_letter` fails with an error (see below please) if `None` instead of string containing volume ID is returned by `get_winutils_vol` and then passed as an argument to `replace` function:
```
20:02:22 ERROR|     return cmd.replace(label, get_winutils_vol(session))
20:02:22 ERROR| TypeError: replace() argument 2 must be str, not None
```
PR adds more descriptive error message.
id: 2041500
Signed-off-by: Lukas Kotek <lkotek@redhat.com>
=> utils_misc: add more informative error description to set_winutils_letter

.cirrus.yml, .github/workflows/ci.yml, contrib/containers/ci/fedora-30.docker, contrib/containers/ci/fedora-35.docker, requirements-travis.txt
* Cirrus CI: add dockerfile for Fedora 35
This dockerfile is the source for the pre-built container at https://quay.io/repository/avocado-framework/avocado-vt-ci-fedora-35
Remove old dockerfiles.
* CI: add test on Python 3.10.1
* `requirements-travis.txt`: update and use fixed versions
=> CI updates: cirrus, gha and requirements-travis.txt

virttest/utils_test/libvirt.py
It fails to start virtqemud with a non-existent log directory
in the latest libvirt, so create dirs if need.
=> customize_libvirt_config: Check if log dir exists

virttest/utils_test/libvirt.py
It was introduced by 6275087334d. There's no 'log_outputs' in some
config_type.
```
JOB LOG    : /root/avocado/job-results/job-2022-01-23T20.15-9b8be49/job.log
(1/2) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.stress.vm.iozone_with_set_max_downtime.with_postcopy: PASS (137.93 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.live_migration.native_tls.migrate_x509_no.default_x509_zero.by_shared.p2p_live.without_postcopy: PASS (185.99 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 324.65 s
```
=> customize_libvirt_config: Fix LibvirtConfigUnknownKeyError issue

selftests/unit/test_cartesian_config.py, virttest/cartesian_config.py
Value substitutions of variables with a "-" are now parsed properly.
The scope of the ignored exception has been minimized to KeyError so other possible exceptions are not masked.
ID: 2027950
=> cartesian_config: can't replace variable with names with "-"

virttest/utils_v2v.py
When the version is like "[,virt-v2v-1.43.1-5)", the function
multiple_versions_compare cannot get correct package name.
=> v2v: fix multiple version compare issue

virttest/virsh.py
Add virsh nodedev commands to handle persistent device setup
=> virsh: add new nodedev commands

avocado_vt/plugins/vt_resolver.py
When the user sets `vt.config` config variable by command line,
everything works fine, but when this variable is set by Job API the
`Discoverer` won't discover tests from the `vt.config` and test
references are empty. This commit will fix that.
=> Discoverer with the Job API

virttest/utils_libvirt/libvirt_disk.py
For block disk,  we need to use stype=block in --diskspec to create snapshot, but create_reuse_external_snapshots function didn't include it. So update it.
=> libvirt_disk.py: fix snapshot issue with stype=block

virttest/utils_test/libvirt.py
tray is one of attribute for cdrom device, something like below:
<target dev='sdb' bus='scsi' tray='open'/>
=> Add tray attribute into create_disk_xml

virttest/utils_v2v.py
=> v2v: remove rhv-proxy option if v2v doesn't support it

virttest/env_process.py, virttest/test_setup.py
1. The 'original_config' be used to restore in cleanup() should be the config
before setup, it is incorrect to get a new 'original_config' with a new
TransparentHugePageConfig instance when doing cleanup.
2. Logically, khugepaged_test doesn't belong to setup(), so move it
out. It can be called on demand.
id: 1654144
=> test_setup: restore correct original_config in TransparentHugePageConfig

virttest/libvirt_vm.py
Though highly recommended to be used with the qemu guest agent,
the pm-utils package might not be available or the test scenario
might not want to install it.
Add a parameter to the `prepare_guest_agent` function to allow for
tests to skip the pm-utils installation. This speeds up testing
where pm-utils is not available.
Make installation of pm-utils the default option in order to
keep default behavior as-is and not require any changes from
consuming code.
=> libvirt_vm: allow for skipping pm-utils installation

virttest/virsh.py
The event monitor should be started before executing virsh command.
=> virsh: Update detach_disk to use EventTracker.wait_event

virttest/ceph.py
When client to access the ceph server, the keyring file should be
exist in /etc/ceph/
=> ceph: add func to create keyring

virttest/utils_net.py
Adding additional check when parsing the arp table (reading /proc/net/arp).
Previously the method was not checking whether the read line was empty/parseable or not.
ID: 2053188
=> utils_net: additional checks for arp table parsing

virttest/utils_conn.py
There are some security changes in openssl which prevents the connection
to old guests, e.g. RHEL6.
A workaround is set the crypto to LEGACY if necessary.
* Tue Mar 01 2022 Clemens Lang <cllang@redhat.com> - 1:3.0.1-15
- Allow SHA1 in SECLEVEL 2 if rh-allow-sha1-signatures = yes
- Resolves: rhbz#2060510
* Fri Feb 25 2022 Clemens Lang <cllang@redhat.com> - 1:3.0.1-14
- Prevent use of SHA1 with ECDSA
- Resolves: rhbz#2031742
=> Add update_crypto_policy function in utils_conn

virttest/utils_hotplug.py
Add deprecate message and docstring for recommended usage. No code changes.
For creating a memory device, we recommend another easy way to implement.
=> utils_hotplug: deprecate func

virttest/qemu_devices/qdevices.py, virttest/qemu_vm.py
1. Decouple the method "start_daemon()" from the method "cmdline()"
since there is no such cmdline is used for qemu binary to start
in fact and it is not reasonable from the logical side, but calling
the start_daemon method to run it.
2. For comparing the type of instance between dev2 and self,
the previous design compares the base class, not the type
of self, it maybe should compare the current type of self
to conform to the normal flow.
ID: 2039158
=> qdevices: Tweaks the way of starting daemon

virttest/utils_test/libvirt.py
Returning the command run result could be useful for the invoker to use
sometimes.
=> libvirt: add return result

avocado_vt/plugins/vt_bootstrap.py, avocado_vt/test.py
In `avocado-vg` package were still some logs using root logger. But
after https://github.com/avocado-framework/avocado/issues/5049 the
avocado logs only logs with namespace `avocado*` so the root logs are
not saved in avocado log files. This commit will fix the problem.
=> Remove root logger from avocado_vt package

virttest/utils_sriov.py
As kernel updates, the case will get error like
"Get nic enp94s0f0np0\neth0\neth1 operstate error". In fact, only
first one "enp94s0f0np0" is what we want, update the script to
support it.
=> Get the first interface name

virttest/utils_test/libvirt.py
when call libvirt.create_disk_xml(params)
=> Add copy_on_read attribute support into disk creation

selftests/unit/unittest_data/testcfg.huge/base.cfg, selftests/unit/unittest_data/testcfg.huge/subtests.cfg, virttest/qemu_devices/qcontainer.py, virttest/shared/cfg/base.cfg
usb device related parameters as bus or port were not being parsed correctly. The goal of this commit is twofold:
1. Corrects the way that usb-device parameters is parsed
2. Leverages the code change to use a more straightforward keyword for usb devices (i.e. it uses `usbdev_port/bus` instead of `usb_port/bus` for a better understanding of the configuration parameter target).
This changes should fix #3351. Making updates in tp-qemu cfgs is needed.
=> usbdev: changes in how parameters are parsed

spell.ignore, virttest/libvirt_xml/nodedev_xml.py
Add mediated device XML representation as node device.
The definition of the `NodedevXMLBase.set_cap` method shows that
in order to construct a valid node device xml we need to
1. construct a `CAPXML`
2. provide an implementation of the `XMLTreeFile.getroot` method
to substitute the `NodedevXMLBase` instance' xml tree's `<capability>`
element by the full xml tree as defined by 1.
Implement `MdevXML` subclass of `CAPXML` in order to meet 1.
Add `getroot` method to `CAPXML` to delegate to the instance's method and meet 2.
Finally, fix typo in the `NodedevXMLBase.del_cap` method.
=> nodedev_xml: Add XML representation for mediated devices

spell.ignore, virttest/env_process.py, virttest/shared/cfg/base.cfg, virttest/unittests/test_utils_misc.py, virttest/utils_misc.py, virttest/virt_vm.py
If a kernel message intentionally has a critical level to warn
customers early of future changes in the kernel with critical
impact, `verify_dmesg` and therefore a test run would currently
fail when checking for kernel messages with at least critical level.
Add a way to configure regular expressions whose matches will be
ignored when verifying kernel messages. The default behavior is left
untouched.
=> verify_dmesg: don't fail on expected messages

virttest/libvirt_xml/devices/hostdev.py
Add 'rom' and 'address' for Hostdev class.
Test results:
https://github.com/autotest/tp-libvirt/pull/4073#issue-1155093522
=> Support address and rom for hostdev

spell.ignore
The spell check fails because of 'vdpa' in docstring.
=> Add 'vdpa' to spell.ignore

virttest/virsh.py
Add a function to support 'virsh update-memory-device' command.
Test results: https://github.com/autotest/tp-libvirt/pull/4115#issue-1174801445
=> virsh: Support update-memory-device

virttest/utils_misc.py
**Test result**
/usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockcopy_options.positive_test.extended_l2_on.encrypt_disk --vt-connect-uri qemu:///system
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID : 7d62c328bb9cf8e141aa663750b802a04a947442
JOB LOG : /root/avocado/job-results/job-2022-03-07T06.48-7d62c32/job.log
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy_options.positive_test.extended_l …
=> utils_misc: fix get no extend_l2 value in get_image_info function

virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py, virttest/shared/cfg/base.cfg
Currently, VMs will generate a new vTPM device when running each TPM
test case. In the life cycle of the VM, the TPM device(s) of the VM
should be unique, and then the VM can be regarded as a real trusted
operating system.
ID: 2060233
=> qcontainer: Support reuse the existing vTPM device

avocado_vt/plugins/vt_resolver.py, avocado_vt/plugins/vt_runner.py
Avocado did a lot of refactorings which made runners standalone plugins
and change some runner paths. This commit update vt runner to be
compatible with those changes and the lts version as well.
Reference: https://github.com/avocado-framework/avocado/pull/5307, https://github.com/avocado-framework/avocado/pull/5326
=> Update vt runner after avocado changesNrunner update

virttest/utils_net.py
IPv6 addresses contain remote address and linklocal address, the old
pattern cannot capture both of them, Correct the pattern to make sure
all IPv6 types will be collected.
ID: 2074848
=> utils_net.get_net_if_addrs_win: Correct IP patterns

virttest/libvirt_xml/devices/tpm.py
Add XMLElementBool of 'sha1,sha256,sha284,sha512' for easy configure
entry, to support setup_attr of tpm device. Keep previous add/delete/etc
pcrbank_list methods for old cases and custom usage.
=> tpm.py: optimize pcrbank part to support setup_attr

virttest/utils_test/libvirt.py
We expect this command to always be executed, and then check the
result in a later step. So need to set ignore_status to True.
=> libvirt: Fix a parameter issue

virttest/nbd.py, virttest/qemu_storage.py, virttest/shared/cfg/base.cfg
This pull request is trying to merge 3 commits that implement the dependencies that a test case had on virttest (see bz-2047527).
The first two commits add the code needed to support image-opt generation for storage filters. More specifically, the first commit adds the needed backbone for image-opt generation for filters, and the second commit adds the needed support for the compress filter. Support for more filters can be easily added by adding a new private function named `_<filter_type>` into `_FilterConfigGatherer` class which reads params and returns an `OrderedDict` containing the key/value pairs that are meaningful to that filter.
The last commit adds the needed changes so the `nbd` module uses the image opts when a filter is used when exporting an image.
I'm not adding the bz ID …
=> compressed qemu-nbd: dependencies development for testcase

virttest/qemu_vm.py
When "tpms" is a global parameter and the case includes multiple VMs,
vTPM devices have resource competition, add the VM namespace to avoid
this scenario.
ID: 2090531
=> qemu_vm: Re-format the vTPM name to avoid resource competition

virttest/virsh.py
Enable event monitor for virsh reboot adn shutdown.
`type_specific.io-github-autotest-libvirt.agent_lifecycle.events: PASS (68.68 s)`
=> virsh: Update reboot/shutdown to use EventTracker.wait_event

virttest/virsh.py
--nvram option should not be added in this function because it is
very low level implementation and should be tranparent and clean.
=> virsh: remove improper nvram added

virttest/qemu_devices/qdevices.py
"pcie_direct_plug" cannot be kept in params all the time, otherwise it 
will be appended to the qemu command line. Setting this parameter as a
property when initializing a device is an easy fix but not the best 
solution.
ID: 2087062
=> qdevices: Make "pcie_direct_plug" work properly

virttest/utils_libvirt/libvirt_virtio.py
Add add_iommu_dev and create_iommu to enable vIOMMU on the guest.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.iommu.at_dt_hostdev.hostdev_interface.failover: PASS (212.51 s)
`
=> Add add_iommu_dev and create_iommu

virttest/env_process.py, virttest/shared/cfg/base.cfg, virttest/test_setup.py
"libvirtd_debug_level" can only custom the global log level to
collect all logs. Sometimes, users only want to capture
specific log information. Introduce a new parameter to custom
log filters, it can also reduce the log file size.
=> Support custom libvirt log filters

avocado_vt/utils.py, virttest/guest_agent.py, virttest/qemu_devices/qcontainer.py, virttest/qemu_monitor.py, virttest/qemu_vm.py, virttest/utils_net.py
* qcontainer: remove the warning of q35
* remove the import check of json module
* utils_net: init ovs instance only if needed
* ~~qemu_vm: remove the log of QDevice/QBus specification~~
* don't create `background-error.log` until there was any bg_err
* qemu_vm: only log thread-id of vcpus for debugging
=> Log improvement for qemu testing

virttest/shared/cfg/guest-hw.cfg
comment out remote_nfs expose settings, define them
in user cases.
id:2094709
=> guest-hw: remove nfs settings

virttest/qemu_vm.py, virttest/shared/cfg/base.cfg
Since qemu-7.0, a new iommu device named "virtio-iommu" has been
introduced to manage Direct Memory Access (DMA), the default behavior
is insert it into the pci(e).0 bus before all virtio devices, insert it
into pcie-root-port should also work so users can modify the parameters
to make it insert into pcie-root-port.
ID: 2087062
=> qemu_vm: Support virtio-iommu

virttest/libvirt_vm.py
=> [minor fix] libvirt_vm: Fix duplicate nvram options

virttest/libvirt_cgroup.py
=> libvirt_cgroup: add functions for cpusset.cpus

virttest/libvirt_cgroup.py
a) Rename reset_cpuset_cpus to set_cpuset_cpus
b) Add log to point out v2 cgroup doesn't have cpuset.cpus file
=> libvirt_cgroup.py: Improve cpuset APIS

virttest/libvirt_xml/vm_xml.py
Update undefine() to work well with guest with os_firmwork setting.
test result on 9.x:
` (1/1) type_specific.io-github-autotest-libvirt.vm_features.positive_test.kvm_hidden.enable: PASS (53.28 s)
`
=> Fix a guest undefine failure

virttest/libvirt_xml/devices/interface.py, virttest/utils_test/libvirt.py
```
(5/8) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start.negative.hostdev_interface.unsupported_virtualport: PASS (16.25 s)
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_coalesce.positive_testing.net_ovs.iface-bridge: PASS (10.68 s)
```
=> interface: Add support for virtualport

.cirrus.yml
This is a preparation for the Avocado-VT 98.0 tag/release, which is going to be a release compatible with the latest Avocado release (98.0).  Included here is:
* Pinning the test providers used for more predictable testing
* Adding two more real tp-qemu tests to CI
* Removing the waiver of failures with latest development Avocado, that is, it now requires that the latest Avocado-VT and Avocado be compatible.
More explanation about the last point can be found in the respective commit.
=> CI: Improve test providers coverage and prepare for 98.0 release

virttest/qemu_vm.py, virttest/shared/cfg/guest-hw.cfg
'virtio-rng-pci' is one type of virtio rng devices, the real name is not
unique, we have "virtio-rng-pci", "virtio-rng-pci-non-transitional",
"virtio-rng-pci-transitional", etc. And the device name in some
platforms is not the same. So we should not use the params namespace
"xxx_virtio-rng-pci", otherwise we need to configure the same virtio-rng
device with different parameters in diff platforms.
ID: 2098066
=> [minor fix] Cut out '-pci' from the namespace of virtio-rng device params

.github/workflows/ci.yml
Fix travis ci failure due to setuptool install
When install avocado framework, it needs required package: setuptool
But  ModuleNotFoundError: No module named 'setuptools_rust' if not proper pip is used
=> Fix travis ci failure due to setuptool install

virttest/qemu_capabilities.py, virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py, virttest/shared/cfg/base.cfg, virttest/virt_vm.py
After this patch, we can define a 4-level
CPU hierarchy on ARM like: 
cpus=*,maxcpus=*,sockets=*,clusters=*,cores=*,threads=*
ID: 2091483
Signed-off-by: zhenyzha <zhenyzha@redhat.com>
=> Add CPU cluster option support for aarch64

virttest/utils_libvirt/libvirt_virtio.py
IOAPIC is x86 only. Add this filter to avoid adding virtio-iommu failure
on aarch64.
=> libvirt_virtio: Require ioapic for x86

virttest/migration.py
If migration is not running (crashed or completed) when trying
to cancel, we'll get a an error from further down in the code,
more specifically from the type cast in `process.safe_kill`.
I've observed two possible test errors:
1. ValueError: invalid literal for int() with base 10: ''
2. TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
However, when we call cancel we usually want to test the behavior
of cancellation and possibly retrying. In these cases, now print
a specific error message about the migration not running.
If the test log shows the migration had already finished, we
can try to slow down the migration with things like decreasing
the bandwidth or creating dirty memory pages.
=> virttest/migration: improve error message when do_cancel fails

virttest/utils_sriov.py
The value of 'session' was set to 'None' incorrectly, so update
it in this PR.
Test result:
` (1/1) type_specific.io-github-autotest-libvirt.sriov.failover.abort_migration.hostdev_interface.with_precopy: PASS (298.92 s)
`
=> utils_sriov: Correct 'session' in add_connection()

virttest/virt_vm.py, virttest/vt_console.py
There could be other interactive interface shown on vm before
login prompt which we would like to skip. Making sure console is
responsive before sending any key to it could meet our needs.
=> vt_console:Make sure console is responsive before trying to login

virttest/qemu_storage.py
We take a small extra step in documenting this parameter wherever
it is available but ultimately one would want to define a command
format and reuse class attributes as much as possible.
=> Add support for shared image mode in qemu-img's snapshot list

virttest/qemu_vm.py
Amend the issue that "AttributeError: module 'qemu_migration'
has no attribute 'monitor'".
=> qemu_vm: Amend the issue of "no attribute monitor"

virttest/utils_zcrypt.py
Change the vfio_ap load functions to be run inside of a VM.
This is needed to test crypto passthrough in a nested setup.
=> utils_zcrypt: enable driver handling in VMs

virttest/libvirt_vm.py
Remove pm-utils as dependence package since guest-agent doesn't need it
In guest_agent, finding that pm-utils package can be not installed without additional repository config,
but all cases related to guest agent pass
=> Remove pm-utils as dependence package since guest-agent doesn't need it

virttest/utils_libvirt/libvirt_vmxml.py
In  virttest/utils_libvirt/libvirt_vmxml.py there was a missing
docstring for the option argument. This commit adds it.
Signed-off-by: Vaclav Hodina <vhodina@redhat.com>
=> Add missing docstring to check_guest_xml function

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/shared/cfg/base.cfg, virttest/shared/cfg/machines.cfg, virttest/utils_test/qemu/__init__.py
1. Ensure get accurate params for dimm device, avoid inrelevant params
be used by mistake
2. Distinguish attributes for different dimm_type
id: 2106656
=> dimm: get accurate device params and distinguish attributes by dimm_type

virttest/libvirt_xml/vm_xml.py
Add new element 'defaultiothread' which has two attributes as below:
` <defaultiothread thread_pool_min="8" thread_pool_max="16"/>`
=> vm_xml: add defaultiothread

virttest/utils_test/libvirt.py
In file virttest/utils_test/libvirt.py in function check_cmd_output a
debug log print has been added, to help with debugging. It shows you
what is the command that has been run and what is the output of the
command.
I just thought this would be helpful when I was debugging an issue and
needed to know what exectly avocado is executing.
It could save time by not having to add debugging printsouts.
=> Add debug print to check_cmd_output function

virttest/utils_libvirt/libvirt_usb.py
Add libvirt usb utils file
There are some common utils to manipulate usb devices,
so pull them into one indepentent file here
=> Add libvirt usb utils file

virttest/libvirt_xml/vm_xml.py
Previously sync method was calling undefine method based with the xml
that was given in argument. However when we were undefining a VM and the
vmxml did not have nvram in os part of xml, the option "--nvram" was not
added and the undefine failed.
This commit changes that and nvram is looked up in the xml that is
dumped from actively used xml. So if we're undefining a VM with nvram
the --nvram option will be added and a VM will be correctly undefined.
=> Update vm_xml.sync() method to correctly use nvram

virttest/utils_test/libguestfs.py
The `part_get_bootable` method returns str type object.
If it is compared with byte type object, it always return false.
It causes unexpected failures in libguestfs related tests.
We can check the behavior of get_bootable_part method with the following script:
```py
import virttest.utils_test.libguestfs
from virttest.utils_test.libguestfs import GuestfishTools
from pprint import pprint
from time import sleep
params = {
"disk_img": "/var/lib/avocado/data/avocado-vt/images/avocado-vt-vm2",
}
g = GuestfishTools(params)
g.run()
sleep(5)
pprint(g.get_bootable_part("/dev/vda"))          # Try to find the bootable part
g.part_get_bootable("/dev/vda", 1).stdout                      # 'false\n'
type(g.part_get_bootable("/dev/vda", 1).stdout)                # <class 'str'> …
```
=> libguestfs: get_bootable_part fails due to type mismatch

virttest/libvirt_xml/vm_xml.py
Generally we need to undefine using current vm xml object. But when vm is transient, it means current vm does not have a xml definition, we have to use the backed up vm xml to undefine as before.
=> vm_xml: fix sync for transient vm

virttest/env_process.py, virttest/qemu_devices/qdevices.py, virttest/shared/cfg/base.cfg, virttest/test_setup.py
Let me take libvirtd.log as the example. There is an issue reported to
libvirt project: https://gitlab.com/libvirt/libvirt/-/issues/71, the use
case is people will use non-root user to analyze the libvirt instance
log file in another system, but by default the permission of libvirtd
log files are 0600, which reject other users to open the log for
analyzing.
For logs collection in testing, they should not contain confidential
information or not exposed to the outside, so add read permission for
all users should not a dangerous operation.
ID: 2119630
=> Add read permission to a bit of log files

virttest/utils_conn.py
TCP SASL md5 test requires cyrus-sasl-md5 in both server and client.
Before this fix
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_tcp.positive_testing.sasl.allow_one_sasl_user.digest_md5: FAIL: Failed to connect libvirt daemon!!output: error: failed to connect to the hypervisor\nerror: authentication failed: authentication failed\n (91.50 s)
```
After
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_tcp.positive_testing.sasl.allow_one_sasl_user.digest_md5: PASS (112.80 s)
```
=> utils_conn.py: FIX TCP SASL md5 error

virttest/utils_v2v.py
Before this change, Users have to use both 'msg_content' and 'expect_msg' to set a log check. This way has a limit that if a same case expects to check both exist and nonexist logs, there is no way to specify both.
This patch adds new support 'msg_content_yes' and 'msg_content_no'. They can be used at the same time in a single case.
=> v2v: add 'msg_content_yes' and 'msg_content_no' support in check_log

virttest/libvirt_xml/vm_xml.py
In the past, there is only one attribute (id) supported in iothread, like
<iothread id="6"/>. But now thread_pool_min and thread_pool_max attributes
are added. And maybe more come in future. So old implementation can not meet
this requirement. This fix is to make this class extensible in future.
=> vm_xml: support new iothreadids element

spell.ignore, virttest/libvirt_xml/base.py
To remove influence of old implementations.
=> setup_attrs:Skip Getters if they are customized

virttest/env_process.py, virttest/test_setup.py
When the threads are terminated or the libvirt version is checked
frequently after the configuration files are restored, it will
report "OSError: [Errno 22] Invalid argument".
**Before the fix:**
RHEL-9.x-runtest-x86_64-function-sriov_migration/18
Test Name | Duration | Age
-- | -- | --
rhel.sriov.failover.abort_migration.hostdev_device.with_precopy | 4 min 21 sec | 5
rhel.sriov.failover.migration.hostdev_device.with_precopy | 6 min 0 sec | 5
rhel.sriov.failover.migration.hostdev_device.with_postcopy | 5 min 37 sec | 5
**After the fix:** 
RHEL-9.x-runtest-x86_64-function-sriov_migration/22
Test name | Duration | Status
-- | -- | --
failover.abort_migration.hostdev_device.with_precopy | 4 min 35 sec | Passed …
=> env_process: Fixup OSError

virttest/utils_test/libvirt.py
Add ignore_str param to check_logfile. Ignore specific str if needed.
=> libvirt.py: Add ignore_str param to check_logfile

spell.ignore, virttest/qemu_vm.py, virttest/shared/cfg/base.cfg, virttest/utils_net.py
Introduced a new VT param 'nic_romfile',
To disable rom loading for all nics:
nic_romfile = 'EMPTY_STRING'
To disable rom loading for nic1
nic_romfile_nic1 = 'EMPTY_STRING'
ID: 2119345
=> Add romfile option for NIC device

virttest/utils_test/qemu/__init__.py
utils_test: deletes unused imports
Deletes not used imports in order to avoid a CI failure in the future.
=> utils_test: deletes unused imports

virttest/libvirt_xml/vm_xml.py
`remove_all_boots` currently only removes the single `/os/boot` and not
the device element that let's us define boot order et al.
Let's remove all boot elements to have the function do what
it name suggests. This fixes also some cases that fail
if the guest definition is using the device specific boot element,
e.g. boot_integration.by_qemu_on_s390.boot_dev.check_menu.
The function is currently only used in the tp-libvirt by the
following test scripts so this patch will require successful
test runs for acceptance:
- libvirt/tests/src/bios/boot_integration.py
- libvirt/tests/src/bios/virsh_boot.py
- libvirt/tests/src/bios/boot_order_seabios.py
- libvirt/tests/src/virtual_network/iface_network.py
=> libvirt_xml/vm_xml: modify remove_all_boots to remove all boot elements

virttest/utils_libvirt/libvirt_numa.py
Sometimes we do not expect an exception is raised when the format is not qualified. Instead we need the function just bypass.
=> libvirt_numa: enhance the parsing

virttest/remote.py, virttest/utils_v2v.py
Any remote logging functionality that was added during the initial migration was not also fully migrated so we can move to using the aexpect remote methods instead.
=> Drop fully migrated functions from the leftover virttest remote module

avocado-plugins-vt.spec, docs/source/GetStartedGuide.rst, requirements-travis.txt, requirements.txt, setup.py, virttest/gluster.py, virttest/test_setup.py, virttest/utils_net.py, virttest/utils_test/__init__.py
Since Python 3.3+ provides `ipaddress` as the standard library for
IPv4/IPv6 manipulation, let's replace the third-party one (`netaddr`)
with it for a better maintainability.
=> replace netaddr with ipaddress

virttest/utils_misc.py
Introducing another check in `utils_misc.get_test_entrypoint_func` to make sure the `run` attribute of the test module is callable. The input module could have an attribute called run that is not callable (e.g. is holding a numerical value), so it looks like we should guard against that case.
This issue was elucidated during #3350 discussions and pylint check fixes. The pylint-disable comments introduced in the latter rely on the checks introduced on this PR, which has been split into this one since it didn't really match the scope of #3350.
=> utils_misc: Assert test entry point is in fact callable

virttest/libvirt_xml/devices/graphics.py
Test result:
Before fix:
```
(1/1) type_specific.local.virsh.domdisplay.have_passwd.no_options.readwrite.spice_t.with_ssl: ERROR: 'channel' (3.97 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-10-18T13.36-378f77f/results.html
JOB TIME   : 4.33 s
```
After fix:
```
(1/1) type_specific.local.virsh.domdisplay.have_passwd.no_options.readwrite.spice_t.with_ssl: PASS (5.48 s)
JOB HTML   : /root/avocado/job-results/job-2022-10-18T13.36-c454aa5/results.html
JOB TIME   : 5.84 s
```
=> graphics:Fix KeyError of method add_channel

virttest/utils_test/libvirt.py
Before fix:
```
(1/1) type_specific.io-github-autotest-libvirt.channel.functional.positive_tests.auto_gen_port.pty_type: ERROR: Cannot set attribute "path" to <class 'virttest.libvirt_xml.devices.character.CharacterBase.Source'> object.There is no such attribute. (5.74 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.channel.functional.positive_tests.auto_gen_port.pty_type: PASS (7.05 s)
```
=> Update reference of Channel xml class

avocado_vt/plugins/vt_init.py, avocado_vt/plugins/vt_list.py, avocado_vt/test.py, avocado_vt/utils.py, selftests/unit/test_wrappers.py, virttest/_wrappers.py, virttest/libvirt_xml/base.py, virttest/remote_commander/remote_runner.py, virttest/utils_test/__init__.py
Code changes in this PR work on the imp deprecation issue (#3323). It's divided in two commits:
1.  The `virttest._wrappers` module is created. The functionality needed for carrying on dynamic imports is added, as well as some related unittests.
2. The code from `avocado_vt` and `virttests` is changed from using imp/importlib to the new method.
Note:
The modules from `virttest.remote_commander` are not using `_wrappers.import_module`, but `importlib`. This has been left in this way since it can't be assumed that virttest is installed in the remote system in which the import is going to take place.
ID: 2042377
=> DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12

avocado_vt/plugins/vt_init.py
The vt_init.loader couldn't be reached by using the _wrappers.import_module method.
This commit rolls back the refactoring changes included in the vt_init.py file so avocado_vt can get back to work as supposed to while we find a more general fix to the issue.
ID: 2136437
=> hotfix for _wrappers.import_module not reaching vt_init.loader

virttest/qemu_migration.py, virttest/qemu_vm.py
Providing a python float even when converted to string will result
in a float number (with a decimal zero) to be passed to the qemu
monitor which will complain with
Error: Parameter 'downtime-limit' expects int64
and break the migration thus leading to incorrect system states
that were paused but cannot be continued and other harder to debug
issues down the line. It is better to convert to integer explicitly
here even if we multiply by a 1000.
Also use the correct default float downtime value which should be
300 ms (downtime-limit: 300 ms) when multiplied by 1000 and not
30 ms which is what the float would imply.
=> Fix the migration downtime parameter type and default value

virttest/utils_test/libvirt.py
Some of the original default args are []s which are mutable.This patch replaces them with Nones.
=> libvirt.check_result:Replace mutable default args with Nones

virttest/utils_libvirt/libvirt_virtio.py
No need to add additional features for virtio iommu, so udpate to only update features for intel iommu device.
```
(1/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.iommu.alias.auto_gen.virtio: PASS (19.06 s)
(2/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.iommu.alias.auto_gen.intel: PASS (19.31 s)
(3/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.iommu.alias.customized.virtio: PASS (19.22 s)
(4/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.iommu.alias.customized.intel: PASS (19.15 s)
```
=> libvirt_virtio: update to add features for intel iommu only

virttest/qemu_vm.py
This is more compatible behavior with the implementation of the inverse method save_to_file() and with it both methods will now only verify paused status before and after they execute.
=> Do not resume but verify paused status

virttest/qemu_vm.py, virttest/shared/cfg/base.cfg
Related to issue 3048:
https://github.com/avocado-framework/avocado-vt/issues/3048
=> Make background errors nonfatal as they often register unrelated events

virttest/env_process.py
We use the opportunity to also give these parameters clear names that also imply typical use case applications.
=> Make it possible to separately keep any vms before and after tests

spell.ignore, virttest/qemu_vm.py
It seems that if the vm is still in "paused (inmigrate)" status and similar, its monitor will completely ignore the "cont" monitor command and thus the vm will remain paused indefinitely, leading to later monitor validation no longer passing and breaking tests as a result.
=> Wait for proper monitor status before sending cont to monitor

virttest/iscsi.py
If the set_chap_auth_target function doesn't include authentication=1 attribute, this means it doesn't actually use chap function. This part has been more rigorously checked In new qemu version, so update it to fix some authentication failure.
=> iscsi.py: add authentication=1 to set_chap_auth_target function

virttest/qemu_vm.py
Loading a running vm's memory from file would require it to be paused first but would also work just fine without any prior vm. In some cases the user has to create a vm and pause it just to be able to satisfy the requirements of previously running and paused vm thus leading to overhead and circumventing more direct use of this functionality.
=> Allow the option of creating a vm firstly after loading from file

virttest/env_process.py, virttest/qemu_vm.py
In some cases the vm's memory and its images are known to be clean of corruption and we can save up to 2 minutes per test (for thousands of tests) if we destroy the vm faster before recreating it anew.
=> Allow destroying vms via monitor upon recreation

virttest/utils_test/libvirt.py
- Fix the bridge network xml creaation
- Enable network xml displayed for debugging
=> libvirt: fix_bridge_net_setup

virttest/iscsi.py
Reverts avocado-framework/avocado-vt#3561
There is some confused result after this PR is merged.
Moreover, even if we need authentication=1, we may not hard code the attribute, instead set this attribute under some condition, e.g. if enable_chap_authentication = 'yes', attr_cmd += "authentication=1
=> Revert "iscsi.py: add authentication=1 to set_chap_auth_target function"

virttest/utils_sriov.py
Remove '0000' to get more interfaces.
(1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.no_option.running_domain: PASS (29.64 s)
=> utils_sriov: Fix get_pf_info to get ifaces correctly

virttest/utils_backup.py
Previously the data will be dumped to /path/to/original_file.dmp. But when the original disk is a block device, such as /dev/sdb, the data will be dumped to /dev/sdb.dump which is not a suitable place. Or if the origial image is in a readonly dir, of course the data could not be dumped to that dir.
This patch is to fix above issues to use the tmp dir to save the dumped data when do data comparison.
=> inc_backup: Dump tmp data to tmp dir

avocado_vt/conf.d/vt.conf, avocado_vt/plugins/vt_resolver.py, avocado_vt/plugins/vt_runner.py, docs/source/GetStartedGuide.rst
This commit update vt runner config to be compatible with the changes applied to the mainstream and the lts version as well.
Reference: https://github.com/avocado-framework/avocado/pull/5494
=> Update vt runner config after avocado runner config update

virttest/shared/unattended/RHEL-8-devel.ks, virttest/tests/unattended_install.py
Install one or more packages separated by spaces using `kickstart_instlock_pkgs` parameter and lock version of these packages using `python3-dnf-plugin-versionlock`. Expected usage is part of `RHEL-8-devel.ks` file.
ID: 2135647
Signed-off-by: Lukas Kotek <lkotek@redhat.com>
=> unattended_install: allow pkgs installation and locking

virttest/qemu_vm.py
The current workaround is adding "_copied" string into the swtpm path for vTPM migration. When we do ping-pong migration few times, the socket path is longer than system limitation(107), which raises "Path for UnioIO socket is too long". But actually the even times' migration can use the source vTPM socket, so here add an action to roll back the tpm.
ID: 2145135
=> qemu_vm: Fix swtpm path too long for vTPM + ping-pong migration

avocado_vt/loader.py, avocado_vt/plugins/vt.py, avocado_vt/plugins/vt_init.py, avocado_vt/plugins/vt_list.py
The "loader" architecture has been removed in the latest Avocado commits (and will be reflected on Avocado version 100.0 and later).
This adds a conditional support for the loader based plugins, so that the latest Avocado-VT can still be used (hopefully for a short time) with Avocado versions having loader support.
Fixes: https://github.com/avocado-framework/avocado-vt/issues/3591
=> Add conditional support for loader based plugins

virttest/libvirt_xml/devices/disk.py
Add address attribute in DiskSource
In some scenario, it need enable address attributes something like below for DiskSource
```
<source type='pci' managed='yes' namespace='1' index='1'>
<address domain='0x0000' bus='0x17' slot='0x00' function='0x0'/>
</source>
```
=> Add address attribute in DiskSource

virttest/utils_netperf.py
Fix following error:
NetperfPackageError: Packeage Error: Compile failed: Could
not get exit status of command
=> Fix NetperfPackageError

virttest/iscsi.py, virttest/utils_test/libvirt.py
Allow enable authentication in iscsi setup
As per https://github.com/avocado-framework/avocado-vt/pull/3561, sometimes authentication = 1 attribute need be enabled
=> Allow enable authentication in iscsi setup

virttest/utils_libvirt/libvirt_vmxml.py
Add a support for creating a filesystem device in this function.
=> libvirt_vmxml: add filesystem support

virttest/utils_libvirt/libvirt_vmxml.py
Instead of setting them one by one.
=> libvirt_vmxml:Use librarian to get device class

virttest/utils_net.py
A regression was introduced by ddc3e37, which results in unexcepted exceptions being raised instead of the correct one during some situations.
ID:2133384
=> utils_net.get_ip_address_by_interface:fix a regression bug

.cirrus.yml
This marks the point where the latest development (HEAD of master branches) of Avocado-VT and Avocado are not guaranteed to be compatible (to he extent that is being tested here).
The goal here is to allow for Avocado core changes that will affect plugins without breaking Avocado-VT development.  The following is the proposed development cycles for Avocado:
1) Avocado 101.0 - bug fixes, improvements and core changes (possibly
affecting plugins)
2) Avocado 102.0 - bug fixes, improvements and core changes (possibly
affecting plugins)
3) Avocado 103.0 (LTS) - bug fixes, compatibility and usability
improvements only.
The compatibility check will be restored at the beginning of the Avocado 103.0 development cycle, resulting in a Avocado-VT and Avocado release that are compatible.
This reverts …
=> CI: reinstate the waiver of failures with latest Avocado

.github/workflows/ci.yml
Python 3.6 has been EOL'd for over a year. But some projects such as QEMU still have it as the mininum required Python versions, and this has kept us from deprecating it and dropping support for it.
Now Avocado itself has dropped support for Python 3.6, in light of a new effort going on to bump the minimum required version in QEMU.
Reference: https://lists.gnu.org/archive/html/qemu-devel/2023-01/msg04398.html
Reference: https://github.com/avocado-framework/avocado/pull/5591
=> Drop Python 3.6 support

virttest/qemu_monitor.py, virttest/qemu_vm.py
The force parameter is support since qemu7.1.
It needs to change relevant API to support it.
ID:2158370
=> Add force support for blockdev-change-media

virttest/qemu_vm.py, virttest/shared/cfg/base.cfg
1. "virtio_dev_xxx" are global settings for virtio devices, but they will
always be set if we define them, even if the device has set these
properties. The property setting by the device should be higher than
the global one.
2. `virtio_dev_xxx` will set properties to whole virtio devices, but some
devices cannot work well that property such as "vhost-user-fs-pci" +
"iommu_platform", so the new parameter `virtio_dev_filter` can filter
out some devices which we want to set those properties.
ID: 2111781
=> qemu_vm: Avoid overwrite existing virtio properties

virttest/qemu_storage.py
=> Add timeout for "qemu-img convert"

virttest/qemu_vm.py, virttest/shared/cfg/base.cfg
numa_hmat: updates initiator option
According to qemu-7.2 the initiator value
is not required anymore in -numa node option.
It is still mandatory to provide it for -numa hmat-lb, so this updated the script in order to take a new
configuration value from the auto case.
ID: 2158423
=> numa_hmat: updates initiator option

virttest/libvirt_cgroup.py
For both cgroup v1 and v2, all negative int are acceptable for the cfs_quota params, such as vcpu_quota, emulator_quota, global_quota and iothread_quota. And a negative value means the param is set as 'max' (or 'unlimited'). So we should not only match '-1' to 'max', but match negative int to 'max'.
=> Fix acceptable negative value range for cfs_quota params

spell.ignore, virttest/utils_test/libvirt.py
Tested via https://github.com/autotest/tp-libvirt/pull/4770
XML attributes are unordered. Therefore, the existing function `check_dumpxml`
can't be used if attribute order changes.
Add new function that leverages the existing xmltreefile property to
match xpath expressions instead.
=> libvirt: add helper function to find matches in Libvirt XML

spell.ignore, virttest/utils_zchannels.py
tested via https://github.com/autotest/tp-libvirt/pull/4722
This function is needed to select a specific device for tests instead of `get_first_unused_and_safely_removable` which makes certain assumptions.
=> utils_zchannels: add function to select info for a specific device

virttest/qemu_vm.py
Keep the same usage with libvirt
ID:2174625
Signed-off-by: Lei Yang leiyang@redhat.com
=> qemu_vm.activate_netdev: Change "vnet_hdr=Flase" to "vnet_hdr=True"

virttest/libvirt_xml/base.py
When the value we get with a certain key turns out to be None, we just ignore it and not return the data pair.
=> fetch_attrs:Do not return invalid values 'None'

virttest/shared/cfg/guest-hw.cfg
When vm's qemu process killed in some negative cases, the 'check_image' will pop a 'Leaked clusters' warning. This warning will be captured in postprocess of our cases and reported as a failure. But such check and warning is useless in these negative tests.
=> [incremental_backup] skip image check if qemu killed

virttest/libvirt_xml/network_xml.py, virttest/utils_libvirt/libvirt_network.py
IPV6 does now allow the existance of netmask attribute in network xml of libvirt. Therefore remove netmask when setting ip of network.
Add log to libvirt_network.create_or_del_network function to log network xml before create it.
Test result:
Package | 花的时间 | 失败 | (区别) | 跳过 | (区别) | Pass | (区别) | 总数
-- | -- | -- | -- | -- | -- | -- | -- | --
rhel | 6 hr 21 min | 29 | 29 | 15 |   | 369 | -29 | 413
rhel.virsh | 5 hr 9 min | 0 |   | 18 | 5 | 731 | -5 | 749
Rerun failed cases 
```
(01/29) type_specific.io-github-autotest-libvirt.virtual_network.iface_unprivileged.precreated.host_tap: PASS (58.50 s)
(02/29) type_specific.io-github-autotest-libvirt.virtual_network.iface_unprivileged.precreated.host_macvtap: PASS (47.00 s)
(03/29) …
```
=> network_xml:Remove netmask of IPXML instance if it's ipv6

virttest/test_setup/__init__.py
Extended multiple huge page settings methods,
Allow users to customize the selection of huge page sizes 
for testing. this patch will keep the default settings,
and add new methods to allow users to control the page size. 
The default value method is used to ensure compatibility 
when the user does not configure.
ID: 2167550
Signed-off-by: zhenyzha [zhenyzha@redhat.com](mailto:zhenyzha@redhat.com)
=> HugePageConfig:Extended multiple huge page settings

virttest/virt_vm.py
According to the comment left by Linus Torvalds in the development 
community "We're trying to get rid of BUG_ON() because it kills the 
machine. Not replace it with another bogus thing that kills a machine."
Therefore, in future kernel development, developers will not 
use BUG_ON() unless necessary.
On the other hand, the expansion of the detection range is a 
double-edged sword. 
I don't want to classify all end traces as kernel crashes.
So only widen the search if console has a complete "cut here" 
"end trace", remove the "BUG:" keyword.
ID: 2174339
Signed-off-by: zhenyzha [zhenyzha@redhat.com](mailto:zhenyzha@redhat.com)
=> verify_kernel_crash:Expand the scope of regularity checking

virttest/guest_agent.py
Add a new guest agent command 'guest-get-cpustats' to get guest CPU statistics
ID: 2166558
Signed-off-by: demeng <demeng@redhat.com>
=> guest_agent.py: Add new command 'guest-get-cpustats'

virttest/utils_stress.py
Test code should not download and compile code.
Assume that the program is available on the guest
or that it has been made available via a package
manager.
Skip compilation if the assumption is met.
=> utils_stress: Don't compile app if available

virttest/libvirt_xml/devices/input.py, virttest/libvirt_xml/devices/memballoon.py, virttest/libvirt_xml/devices/video.py, virttest/libvirt_xml/devices/vsock.py
For example:
```
>>> from virttest.libvirt_xml.devices import input
>>> input_dev = input.Input("tablet")
>>> input_dev.xml = """
...    <input type='tablet' bus='virtio'>
...       <driver iommu='on' ats='on' packed='on' page_per_vq='on'/>
...       <address type='pci' domain='0x0000' bus='0x09' slot='0x00' function='0x0'/>
...     </input>
... """
>>> input_dev.fetch_attrs()
{'driver_packed': 'on', 'type_name': 'tablet', 'address': {'attrs': {'type': 'pci', 'domain': '0x0000', 'bus': '0x09', 'slot': '0x00', 'function': '0x0'}, 'type_name': 'pci'}, 'input_bus': 'virtio'}
```
Can't get other driver attributes except the driver_packed. So update some related attributes in different devices.
=> Update virtio driver attributes in some devices

virttest/utils_libvirt/libvirt_bios.py
The guest will automatically add firmware type/features information to os xml when defining a guest. So for some test cases which need to remove uefi related os info, we also need to check and remove this firmware feature.
=> libvirt_bios: add to check firmware feature in os

virttest/utils_test/libvirt.py
Sometimes a case needs to operate 'libvirtd' daemon on modular environment, instead of using 'virtqemud' daemon. So a new parameter is added to enable this capability.
=> libvirt: new parameter to not convert daemon name

virttest/utils_package.py
This is to enable the capability to upgrade specified package version
=> utils_package: enable to upgrade pkg

Makefile, requirements-travis.txt
There's an effort to share more code between the "avocado-framework" projects, including the "autils" initiative.  Having common baselines of linters, code style, etc is very helpful.
This bumps the pylint version to match the one being used in Avocado. This change being only a version bump, it disables the checks E1102, E0203 and E0601, enabled/introduced on the newer pylint version.
=> Lint check: bump pylint version to match Avocado

virttest/virt_vm.py
remote module introduces the log_function argument 3 years ago, but VT didn't sync this change. So currently, if we use vm.copy_files_to/from functions, a lot of lines will be printed to the terminal.
Reference: avocado-framework/aexpect/pull/55
=> virt_vm: Set log_function for copy_files_**

virttest/utils_libvirt/libvirt_vmxml.py
This patch is to add a new function to enable the checking vmxml
using xpath way.
=> libvirt_vmxml: add func to match xml by xpath

virttest/libvirt_xml/devices/tpm.py
Add 'source' element with 'type', 'mode', 'path' attributes in tpm xml for external vtpm configuration.
=> tpm.py: add source elements for external vtpm

virttest/qemu_vm.py
When we perform a live migration on a single node, never remove the related resources of the source VM, because the target VM is still using these resources after migration, so let the target VM do it.
ID: 2184877
=> qemu_vm: Let target VM remove tmp files after a local migration

virttest/shared/unattended/RHEL-8-devel.ks, virttest/tests/unattended_install.py
1. Add a new parameter to install pkgs in "%packages" phase
2. Split instlock to 2 functions
1. Install pkgs in "%post" phase, supports specific nvr, url install
2. Lock pkgs you want
ID: 2182236
=> ks: Support install specific packages in the "%packages" step

virttest/qemu_vm.py, virttest/shared/cfg/base.cfg
virtio-gpu device now only support insert into pci(e).0 bus, but we it
can be insert to other buses, add this capability to it.
ID: 2185698
=> qemu_vm.py: Correct parent bus for virtio-gpu and virtio-iommu

virttest/test_setup/__init__.py
When the current framework is in setup(self), it first allocates
hugepages and then mounts it.
There will be a scene here, when the continuous memory is insufficient,
set_hugepages() will fail, so the mount operation will not be performed.
But the allocated huge pages are not released, like this:
echo 4 > /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
2
So add the hugepages release operation in this scenario.
ID: 2181945
Signed-off-by: zhenyzha [zhenyzha@redhat.com](mailto:zhenyzha@redhat.com)
=> HugePageConfig:Modify hugepages release operation

virttest/shared/unattended/RHEL-8-devel.ks
In the install_pkgs function on RHEL-8-devel.ks, missing "done" in the "for" loop, this will block the guest installation, fix it.
=> hotfix: syntax in the RHEL-8-devel.ks file

virttest/libvirt_xml/devices/character.py
Remove CharacterBase.Source.Seclabel and replace it with previously defined Seclabel class from devices.
=> Update character to reuse Seclabel from devices

virttest/libvirt_xml/vm_xml.py
vm_xml.py: add stateless attribute to VMOSXML
=> vm_xml.py: add stateless attribute to VMOSXML

virttest/utils_libvirt/libvirt_memory.py
This is to add a new function to support consuming free memory of the vm.
=> libvirt_memory: consume vm free memory

virttest/libvirt_xml/base.py
There are certain cases when the key exists but `not find()` still equals True. Update to fix this error.
=> setup_attrs:fix error of fail to find tag

virttest/cpu.py
ID: 2203027
QEMU8.0 support new cpu model 'SapphireRapids'.
=> x86_cpu_model:add new cpu model 'SapphireRapids'

avocado_vt/plugins/vt_resolver.py, contrib/create_lxc_container.sh
In particular, reduce the serial runs warning to non-LXC cases and provide a script for building LXC containers.
A sample run in an LXC container using the provided script:
```
[root@c5 avocado-vt]# avocado run --status-server-disable-auto --spawner=lxc boot
JOB ID     : 38d9994f13f675b5c63032c5673b8c32be689d50
JOB LOG    : /root/avocado/job-results/job-2023-05-08T20.36-38d9994/job.log
(1/1) io-github-autotest-qemu.boot: STARTED
(1/1) io-github-autotest-qemu.boot: PASS (26.73 s)
JOB HTML   : /root/avocado/job-results/job-2023-05-08T20.36-38d9994/results.html
JOB TIME   : 30.07 s
```
=> Allow parallel Avocado VT runs using LXC containers

virttest/nfs.py
Split 'exported_options' to a list to avoid incorrect searches.
=> nfs: Fix an issue in need_reexport

virttest/utils_libvirt/libvirt_network.py
Sometimes we need to use port to get expected network connection number.
=> libvirt_network: Add port to pattern string

virttest/utils_libvirt/libvirt_vmxml.py
The elements of `matches` do not equal to True which cause the expression to be False at any time which means it's ignoring non-matched text.
=> check_guest_xml_by_xpaths:Fix issue of ignoring mot-matched text

virttest/test_setup/__init__.py
This is to enable the capability to customize the hugepage mount path.
=> test_setup: enable customize hugepage mount path

virttest/shared/cfg/guest-os/Windows/Win10/i386.cfg
ID: 2215515
Don't need md5sum value for win10-32 os installation.
=> Windows: remove md5sum value of win10-32

virttest/qemu_devices/qdevices.py
Do not change the type of "detect-zeroes" in -blockdev for json format
ID: 2216076
=> qdevices: bug fixing

virttest/test_setup/__init__.py
If the setup process fails, func will raise an error and return. Meanwhile, if the system has created some other hugepages, they will remain on the host to consume memory.
Therefore, do the cleanup process after failing.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_hugepage.2M: ERROR: Cannot set the kernel hugepage setting to the target value of 500 hugepages. (10.47 s)
30
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_hugepage.2M: ERROR: Cannot set the kernel hugepage setting to the target value of 500 hugepages. (9.74 s)
0
```
=> hugepage_setup: Cleanup hugepage when setup process fails

virttest/test_setup/__init__.py, virttest/utils_misc.py
In the `cleanup` function, "start_ksmtuned" will start the 
ksmtuned.service, it controls and tunes the ksm service, but depends on 
the KSM_MONITOR_INTERVAL. So ksm is not closed immediately, but at some 
time in KSM_MONITOR_INTERVAL loop. Without this fix, the next test case 
may launch the guest with ksm enabled, which is not expected.
ID: 2215183
=> KSMConfig.cleanup: Ensure ksm to be disabled at the end of the case

virttest/utils_disk.py
The current regexp can not used for getting nvme disk, so update the regexp.
=> utils_disk: Fix regexp for getting first nvme disk

virttest/libvirt_xml/devices/console.py
log_file needs to be added
for https://github.com/autotest/tp-libvirt/pull/4966
=> add log_file to console xml

virttest/libvirt_xml/vm_xml.py
The current set_graphics_attr() can only handle the situation where the graphics device itself exists in the original xmltree.
Update the func so that it can also handle the situation where the graphics does not exist in the original xmltree.
Before:
```
(1/2) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.readonly.no_opt: ERROR: list index out of range (4.37 s)
(2/2) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.readonly.security_info_opt: ERROR: list index out of range (4.40 s)
```
After:
```
(1/2) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.readonly.no_opt: PASS (26.23 s)
(2/2) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.readonly.security_info_opt: PASS (26.81 …
```
=> Update func set_graphics_attr

virttest/virsh.py
Usually the options value should be started with --. The old codes added '--' in this utility function which is not suitable. We expect the client provides like '--config' to invoke this function as other functions do.
=> virsh: align same usage for emulatorpin

Makefile, scripts/regression.py, virttest/cartesian_config.py, virttest/unittest_utils/mock.py, virttest/utils_config.py, virttest/utils_gdb.py
Alternative solution for https://github.com/avocado-framework/avocado-vt/pull/3732
Ignore I1101 but fix E721
Fixes for E721 applied as indicated by https://github.com/PyCQA/pycodestyle/blob/1c2147c703e3b934675b270391fab03cb30d73a2/CHANGES.txt#L12
=> Fix static checker

virttest/libvirt_xml/nodedev_xml.py
Add support for attribute elements of the mediated device capability xml, e.g.:
```
<attr name='assign_adapter' value='3'/>
<attr name='assign_domain' value='43'/>
```
=> nodedev_xml: extend MdevXML with attr elements

virttest/utils_libvirt/libvirt_vmxml.py
Sometimes we do not need to raise an exception when not matched. So this patch is to add a parameter to enable the choice.
=> libvirt_vmxml: new param for not raising error

virttest/qemu_vm.py, virttest/shared/cfg/base.cfg
Memory: Add a new parameter "vm_mem_backend_path", this will controls
the "mem-path" in memory object
ID: 2187577
=> Add new parameter to support changing backend mem path

virttest/migration.py
Sometimes vm failed to get ip because address cache is NULL, so
need to update address cache before getting ip.
=> Fixup VMIPAddressMissingError

virttest/test_setup/__init__.py
The old  parameter name is userd by tp-qemu for other purpose and conflicted with below avocado-vt usage. https://github.com/autotest/tp-qemu/blob/master/qemu/tests/cfg/hugepage_mem_stress.cfg#L19C13-L19C26 https://github.com/avocado-framework/avocado-vt/blob/master/virttest/qemu_vm.py#L1107C49-L1107C49
=> test_setup: rename parameter for hugepage path

virttest/utils_libvirt/libvirt_vmxml.py
=> libvirt_vmxml:Add log to function modify_vm_device()

virttest/ppm_utils.py
We could see the following error popped up when enabling screendumps
> 'ImageFont' object has no attribute 'getsize'
so let's fix it.
Issue: https://github.com/avocado-framework/avocado-vt/issues/3748
=> Fix an issue of ppm_utils

avocado_vt/plugins/vt_runner.py
After switched to nrunner, whiteboard is missing from the result, so it is always empty to show. This commit add `WhiteboardMessage` to catch it.
ID: 2232529
=> vt_runner: Add missing whiteboard to the test status

virttest/_wrappers.py, virttest/env_process.py, virttest/utils_libvirtd.py, virttest/virsh.py
We do this by importing these modules conditionally within the modules of shared qemu and livbirt vm usage.
=> Reduce the libvirt logging verbosity (not needed for qemu vms)

virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py
thread-context: support new object thread-context
Includes support in avocado-vt for a new object:
thread-context. The intention of this new object
is to be used to make NUMA aware of the memory
preallocation threads.
ID: 2224513
=> thread-context: support new object thread-context

virttest/utils_misc.py
'die_id' is newly introduced in <cpu> in virsh capabilities output, like below
```
<cpus num='2'>
<cpu id='2' socket_id='2' die_id='0' core_id='0' siblings='2'/>
<cpu id='3' socket_id='3' die_id='0' core_id='0' siblings='3'/>
</cpus>
```
=> utils_misc: support die_id in topology

virttest/utils_disk.py, virttest/utils_libvirt/libvirt_disk.py
Partitions in /proc/partitions are not persistent which
can lead to problems when a test checks if a disk was cold
plugged.
Use persistent naming from /dev/disk/by-path which allows
us to easily identify those disks and partitions with
the attached disk by their libvirt <address/>.
Add and update other functions to be compatible with this way
of dealing with partitions.
=> utils_disk/libvirt_disk: add way to handle disk by path

virttest/qemu_vm.py
qemu_vm: includes support for all sandbox options
For sandbox on, includes the support of all the QEMU
options as they could be used in an auto case.
The process_sandbox function has been modified in
order to make easy the new options incorporation.
ID: 2224513
=> qemu_vm: includes support for all sandbox options

virttest/qemu_vm.py
qemu_vm: includes memory preallocation for hugepages
Using hugetlb memory without preallocation is a dangerous practice.
As confirmed, setting preallocation 'true' by default for all the
memory backed by hugepages.
=> qemu_vm: includes memory preallocation for hugepages

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py
There has been a regression issue since the patch https://github.com/avocado-framework/avocado-vt/pull/3710
This path's aim is to keep the original type of value for the `detect-zeroes`, not drop it from the blockdev options.
ID: 1320
=> qdevices: Fix the missing of the detect-zeroes

virttest/vt_utils/block.py, virttest/vt_utils/filesystem.py
Here's a new block module including the functions
about the block.
=> block_disk.py: Add a new utility for the block

virttest/utils_disk.py
Sometimes we may get wrong partition number, for example, "[  122.778138]  vdc: vdc1". So we need to ignore it.
To fix:
ShellCmdError: Shell command failed: 'parted -s &quot;/dev/vdc&quot; rm [  122.778138]  vdc: vdc1'    (status: 1,    output: &quot;Error: Partition doesn't exist.\n&quot;)
=> Fix partition number error

virttest/utils_test/libvirt.py
Add wait in create_scsi_disk method
In some extreme situation, loading scsi_debug module may not be returned smoothly, and it leads to failure in finding scsi device
=> Add wait in create_scsi_disk method

virttest/utils_libvirt/libvirt_memory.py, virttest/utils_test/libvirt.py
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.backing.mount_path
(1/3) type_specific.io-github-autotest-libvirt.memory.backing.mount_path.default: PASS (61.76 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.backing.mount_path.disabled: PASS (25.95 s)
(3/3) type_specific.io-github-autotest-libvirt.memory.backing.mount_path.customized: PASS (29.31 s)
```
=> add more flexible for consume_mem and check_qemu func

virttest/qemu_devices/qcontainer.py
For OVMF with SEV-ES support and OVMF with TDX support, the vm can be booted without vars file. Add a workaround, skip the processing of pflash vars file when ovmf_vars_files =.
ID: 1390
=> skip the processing of pflash vars file when it's not set

virttest/libvirt_xml/devices/filesystem.py
Add boot order attribute for filesystem device.
=> filesystem.py: add boot order attribute for filesystem device

virttest/_wrappers.py, virttest/cpu.py, virttest/env_process.py, virttest/libvirt_xml/base.py, virttest/migration.py, virttest/utils_test/__init__.py
This performs additional lazy imports necessary to avoid libvirt related messages for qemu-only usage and fixes the way it is done for some of the cases.
=> Complete the libvirt verbosity fix

virttest/utils_test/libvirt.py
Signed-off-by: Kowshik Jois B S <kowsjois@linux.ibm.com>
Description: The attribute "priority" expects an Integer value to be assigned. When there is nothing provided, it will have the value as None and results in test failures. Hence, modified the default value to 0 instead of None
=> libvirt.py: Default value for the attribute "priority"

virttest/test_setup/__init__.py
test_setup: fix TypeError in error message
Fixes the TypeError produced by the bad string formatting.
ID: 1488
=> test_setup: fix TypeError in error message

virttest/qemu_vm.py
qemu_vm: includes support for mem policy and host-nodes
Includes the support of the policy and host-nodes options
for the machine memory backend.
ID: 1398
=> qemu_vm: includes support for mem policy and host-nodes

virttest/qemu_devices/qdevices.py
The "sndbuf" option of `-netdev`, it requires size type, so if we assign a size like "1M", QNetdev should able to convert it to "1048576". On the other hand, in the first version, converting string to numeric was missing, so adding it as well this time.
ID: 1527
=> fix: Add missing conversion for "sndbuf" and other options for QNetdev

virttest/libvirt_xml/vm_xml.py
As <iothread> has <poll> as a child elemnet, we'd better to define <iothread> as a Class.
```
<iothreadids>
<iothread id="2"/>
<iothread id="4"/>
<iothread id="6"/>
<iothread id="8" thread_pool_min="2" thread_pool_max="32">
<poll max='123' grow='456' shrink='789'/>
</iothread>
</iothreadids>
```
=> vm_xml: update VMIothreadXML

virttest/shared/cfg/machines.cfg
General: update default indirect_image_blacklist for s390x, we could use
FCP SCSI as the system disk start from z15 as well.
ID: 1540
=> Machines: update default indirect_image_blacklist for s390x

virttest/shared/cfg/guest-hw.cfg
Upstream add an new nic model igb since qemu-8.0.0 which allow testing applications' SR-IOV features on a machine without a specific hardware.In order to cover more nic model,so QE sent a new patch to support this driver.
ID: 1543
Signed-off-by: Lei Yang leiyang@redhat.com
=> Support new nic driver igb on the framework

virttest/qemu_devices/qcontainer.py
In qcontainer.py, when creating snapshot images, will get the image size from params. But if the image_size is defined in different variants, the sn image size may smaller than the base image, which is incorrect. The easier way is empty the image_size in sn_params, to make the size of snapshot image align to the base one, as it's just a snapshot.
ID: 1529
=> fix: Empty "image_size" in sn_params when "image_snapshot = yes"

virttest/shared/scripts/virtio_console_guest.py
ID: 1427
Drop the 'six' dependency for making the tool used standalone.
=> virtio_console_guest:update code format to keep compatibility

virttest/env_process.py
During environment setup we discard vms that are not going to participate in a test but doing so gracefully results in a large timeout (60 seconds by default) for each one and slows down the test and overall test run significantly. As the discarded vm will either be fully reconstructed or restored from a clean state when it is needed again by a test, graceful shutdown is not needed and ridding ourselves of it will improve performance for free.
=> Change vm.destroy gracefulness for performance when discarding vms

virttest/qemu_vm.py
ID: 1552
Signed-off-by: Wenli Quan [wquan@redhat.com](mailto:wquan@redhat.com)
=> Add_pcidevice: format cmd line to json

virttest/cpu.py
ID: 1567
This CPU model also require the three cpu flags to boot up forcibly.
=> cpu: Add missed cpu model flags

virttest/migration.py
It takes longer to get the desired event in copy storage migration. So update event timeout.
=> Update event timeout for copy storage migration

virttest/libvirt_xml/devices/memory.py
Need address attr in Memory.target class
For https://github.com/autotest/tp-libvirt/pull/5293
=> add support for address in memory target

avocado_vt/test.py, virttest/env_process.py, virttest/ip_sniffing.py, virttest/libvirt_vm.py, virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/qemu_io.py, virttest/qemu_monitor.py, virttest/qemu_vm.py, virttest/remote.py, virttest/test_setup/__init__.py, virttest/utils_logfile.py, virttest/utils_misc.py, virttest/virt_vm.py
Most importantly, for better decoupling with aexpect we provide sessions with close hooks that should have the same effect of closing the open log file descriptors but in a more decoupled fashion.
The logging functionality in utils_misc has been fully deprecated for the sake of the same functionality in a fully devoted module.
=> Unify all logfile handling into utils_logfile

virttest/env_process.py, virttest/shared/cfg/base.cfg
=> VM_bootloader:provide bootloader's version for each arch 

virttest/utils_net.py
Without the session parameter, utils_misc.cmd_status_output() will always get default gateway from the host. Fix the issue by adding the parameter.
=> Fix the get_default_gateway

virttest/utils_net.py, virttest/utils_windows/virtio_win.py
Use netkvco.exe to replace the netsh netkvm command. netkvmco.dll is
removed from the release and converted to an executable, and
netkvmco.exe is added which terminates all the calls that previously
were terminated by netshell. Additionally, netkvmco.exe was introduced
in the prewhql 242 version.
ID: 1449
Signed-off-by: Wenkang Ji wji@redhat.com
=> netkvm: moving functionality of netkvmco.dll to netkvco.exe

virttest/utils_windows/virtio_win.py
This patch is a correction of avocado-framework/avocado-vt/pull/3788       
and fixes the undefined variable 'file_type' in _get_netkvmco_path.        
ID: 1449                                                                
Signed-off-by: wji <wji@redhat.com>
=> utils_windows/virtio_win: hotfix for netkvm

virttest/utils_net.py
When ovs management tool was not installed on the system, an error message would be emitted in some certain contexts due to there always be a corresponding check been executed no matter whether the tool was exactly required upon the users scenarios.
We had better to refactor this, but at the moment let us firstly workaround the issue by reducing the logging verbosity as such an error message did not make too much sense for the users.
=> Reduce logging verbosity of ovs initialization

virttest/utils_net.py
Add optional parameter in order to retrieve the default gateway for a specific interface.
On a system with two interfaces, the routes might look like
```
default via 10.172.161.254 dev enc1 proto dhcp src 10.172.160.70 metric 100
default via 192.168.126.1 dev enc2 proto dhcp src 192.168.126.48 metric 102
```
Filtering only by default will return two ips
```
10.172.161.254
192.168.126.1
```
The change allows us to select the interface and thus retrieve only
```
192.168.126.1
```
=> utils_net: get default gateway for specific interface

virttest/utils_logfile.py
utils_logfile.log_line currently uses 'w' mode to open log files, this causes some log contents missed when closing the log file. For example, when we close the log file, there are some contents in the cache and waiting for writing to the log, so need to reopen it, if use 'w' mode, old contents will be truncated.
ID: 1858
Suggested-by: Lukáš Doktor <ldoktor@redhat.com>
=> fix(utils_logfile.log_line): Open file with 'a' mode for safer writing

virttest/utils_v2v.py
Fix the failed case on not-getting value.
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.default_vsphere.esx_80.rhev.rhv_upload.it_vddk.vpx_uri: PASS (429.57 s)
=> v2v: fix the failed func TC "default_vsphere"

virttest/shared/cfg/guest-os/Windows.cfg, virttest/shared/cfg/guest-os/Windows/Win10/i386.cfg, virttest/shared/cfg/guest-os/Windows/Win7/i386.cfg, virttest/shared/cfg/guest-os/Windows/Win8/i386.cfg
1.Based on the lm and pae flag's usage, we need add it to 32bits Windows VM.
2.'q35' maps up to 2G RAM below 4G, 'pc' maps up to 3G RAM below 4G. So 32-bit windows just ignores the memory above 4G.
ID:1875
=> Add 2 cpu flags and limit the mem for 32bit windows VM

virttest/env_process.py, virttest/shared/cfg/virtio-win.cfg
Add a checkpoint here to check the virtio-win version, if the version is in the specified range, test will continue, if not, cancel the test.
ID:1594
=> Support to specify virtio-win's version range

virttest/utils_libvirt/libvirt_vmxml.py
Comments of available parameters for ignore_status are mismatched, so correct it.
=> Fix typo of parameter ignore_status comments for func check_guest_xml_by_xpaths

virttest/utils_net.py
When there is multipath ipv6 router, get_default_gateway() will report the default router as "RA" before, which is not expected. Update the function to report error when there is multipath ipv6 router.
=> Report error when there is multipath ipv6 router

.github/workflows/ci.yml
Avocado has recently dropped Python 3.7, among other reasons because it has been EOL'ed.
Now, Avocado-VT's CI is broken because it tries to install the latest Avocado from source and fails.  There are a number of possibilies here, including limiting the Avocado version for the Python 3.7 checks, but, given that Python 3.7 has been EOL'ed, the most logical action is to also remove it from Avocado-VT's CI checks.
While at it, let's also expand the coverage to the other currently supported Python versions.
Reference: https://devguide.python.org/versions/
=> CI: Update Python versions

avocado_vt/test.py
`pipes` was deprecated since version 3.11 so let's drop the use accordingly.
Issue: https://github.com/avocado-framework/avocado-vt/issues/3837
ID: 1787
=> Deprecate pipes module

virttest/utils_libvirt/libvirt_disk.py
Some tests add more than one new disk. Enable discovery of all new disks.
Used / tested in https://github.com/autotest/tp-libvirt/pull/5432
=> libvirt_disk: enable discovery of all new disks

selftests/unit/test_utils_env.py, virttest/env_process.py, virttest/qemu_virtio_port.py, virttest/shared/scripts/virtio_console_guest.py, virttest/tests/unattended_install.py
There are a few threading methods been deprecated since Python3.10, let's replace them according to the guide.
Reference: https://docs.python.org/3/whatsnew/3.10.html#deprecated
Issue: https://github.com/avocado-framework/avocado-vt/issues/3837
ID: 1791
=> Deprecate methods from threading module

.cirrus.yml
The Avocado 82.X LTS series has reached its EOL.  At the same time, there's an active branch for the 103lts development (103lts) where new releases like 103.1 will be tagged from.
=> CI: start testing with Avocado's 103lts branch and drop 82lts

virttest/qemu_devices/qdevices.py, virttest/qemu_monitor.py, virttest/qemu_vm.py
1. Use QNetdev to create a netdev device, and then hot-plug/unplug it
via simple_hotplug/unplug, this method will also verify if the plug
operation is completed.
2. Close origin file descriptors after getfd and close tap file
descriptors after netdev_add because qemu process retains access via
open fd, so we don't need to keep fds always open, otherwise, this will
cause fd to leak, and the qemu process takes a lot of fds.
3. Delete the tap device after netdev_del.
ID: 1400
=> refactor(qemu_vm): Use QNetdev to hot plug/unplug netdev devices

virttest/libvirt_xml/vm_xml.py
On x86_64, if we set <cpu>xxx</cpu> in vm xml and save, then libvirt could automatically
fill in the cpu mode. But on arm now, libvirt can not make it which cause vm fails to
boot with below error. Libvirt dev is working on cpu model, so it is not good time to
support this auto filling now. So we need a workaround here to set it explicitly.
=> vm_xml: set cpu mode

virttest/libvirt_vm.py, virttest/libvirt_xml/vm_xml.py
1. Add virsh instance in prepare_guest_agent
2. Update to be able to use serial vm login
3. Remove mandatory src_path assignment when no value is set
`(1/1) type_specific.io-github-autotest-libvirt.agent.auto_generated.unix_source_path.session_mode: PASS (86.10 s)
`
=> Update guest_agent functions for unprivileged vm

virttest/shared/cfg/guest-os/Windows.cfg
Currently, Windows VM will run into some failure, it is due to Windows OS bug, adjust our configuration to workaround it
ID:1933
=> Update default config for Windows guest which use seabios

virttest/utils_misc.py
In some test environments, we will get the following dmesg log:
dmesg log:[01;31m[K[[m[K[01;31m[KS[m[K[01;31m[Ku[m[K[01;31m
[Kn[m[K[01;31m[K [m[K[01;31m[KF[m[K[01;31m[Ke[m[K[01;31m[Kb
[m[K[01;31m[K [m[K[01; ...
So update code to avoid this issue.
=> Fix dmesg log issue

virttest/qemu_devices/qdevices.py
Based on the current code the igb device is plugged into pcie.0. But this is not meet QE's testing requirement, so add support for igb device to plug into pcie-root-port.
ID:2011
Signed-off-by: Lei Yang leiyang@redhat.com
=> qdevices: Add support for igb device to plug into pcie-root-port

virttest/utils_libvirt/libvirt_numa.py
Fix parsing of continuous numa nodes.
Parsing result without the patch:
```
21:35:15 DEBUG| numa_nodeset='x-y', node_list=[0, 1, 2, 3]
21:35:15 DEBUG| Parse output for numa nodeset: '0-1'
```
Testing result without the patch:
```
FAIL 1-type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_interleave.vcpu_auto -> TestFail: Expect cpuset.mems=0-1, but found 0-3
```
Parsing result with the patch:
```
22:48:25 DEBUG| numa_nodeset='x-y', node_list=[0, 1, 2, 3]
22:48:25 DEBUG| Parse output for numa nodeset: '0-3'
```
Testing result with the patch:
```
PASS 1-type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_interleave.vcpu_auto …
```
=> libvirt_numa: Fix parsing of continuous numa nodes

virttest/env_process.py, virttest/test_setup/libvirt_setup.py
As one of the steps of the planned `env_process.py:{pre,post}process` refactoring, this patch rewrites the setup/cleanup steps of the libvirtd debug log into an appropriate `Setuper` subclass. Then, it registers such class into the `setup_manager` in the relative order that was sitting on before refactoring the bridge setup/cleanup steps.
ID: 1469
=> env_process: Rewrite Libvirtd debug log setup/cleanup steps as a Setuper

virttest/test_setup/__init__.py
This is to add new capability to return a free hugepage number from kernel.
=> test_setup: get free hugepage number from kernel

virttest/utils_libvirt/libvirt_vfio.py
Update to be able to check mlx5_vfio_pci driver.
```
>>> libvirt_vfio.check_vfio_pci('0002:01:00.2')
True
>>> libvirt_vfio.check_vfio_pci('0002:01:00.2', expr_driver="vfio_pci")
File "<stdin>", line 1, in <module>
File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/utils_libvirt/libvirt_vfio.py", line 40, in check_vfio_pci
raise exceptions.TestFail(err_msg)
avocado.core.exceptions.TestFail: Get incorrect driver mlx5_vfio_pci, it should be vfio_pci.
>>> libvirt_vfio.check_vfio_pci('0002:01:00.2', expr_driver="mlx5_vfio_pci")
True
>>> 
```
=> libvirt_vfio: Update to support mlx5_vfio_pci

virttest/utils_net.py
To fix TypeError: __init__() missing 2 required positional arguments: 'cmd' and 'output'
=> Fixup:Missing args of ShellError

virttest/shared/cfg/guest-os/Windows.cfg
This issue was introduced by supporting machine type 9.4, add a limitation to not apply this workaround to all OS version
ID:2085
=> Add a limitation for the smbios setting

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/qemu_vm.py, virttest/shared/cfg/base.cfg, virttest/vt_iothread.py
qdevices.py: add new support to the parameter
Add new support to the parameter: iothread_vqs_mapping.
=> qcontainer.py: add new support to the parameter

virttest/qemu_devices/qcontainer.py
qcontainer: support for multiple thread contexts
Includes support for multiple thread_context
object inside the framework.
ID : 2009
=> qcontainer: support for multiple thread contexts

virttest/qemu_capabilities.py, virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py, virttest/shared/cfg/base.cfg, virttest/virt_vm.py
After this patch, we can define a 5-level CPU hierarchy on s390x like:
cpus=,drawers=,books=,sockets=,cores=,maxcpus=
ID: 2036
=> Add CPU drawers and books option support for s390x

virttest/shared/cfg/guest-os/Windows.cfg
The related problem no longer exists, so revert the previous temporary workaround commits.
ID:2109
=> Revert the workaround for smbios configuration

virttest/utils_test/libvirt.py
From libvirt document, The values of these attributes can be given in decimal, hexadecimal (starting with 0x) or octal (starting with 0) form.
In our script, the analyze of 'lsusb' output pass bus and address literally. If the bus num is greater or equal than 8, for instance '008', libvirt will report the error.
In the lsusb output, the bus value should be decimal, so just remove the leading zeros from the string to fix it.
=> USB: fix Invalid value for attribute 'bus' in element 'address'

virttest/virt_vm.py
File descriptor leaks of log handlers has been found within the `VM.wait_for_login` routine, due to there was no chance to hook the callback for closing the log files properly at the cleanup stage of the session objects upon login failed.
To fix the issue let's close the log files immediately while suppressing the errors during the login attempts.
ID: 2115
=> virt_vm: fix fd leaks upon login failed

virttest/qemu_devices/qcontainer.py
qcontainer: add dynamic-memslots support
Includes dynamic-memslots option for virtio-mem devices
ID: 2253
=> qcontainer: add dynamic-memslots support

virttest/env_process.py
A recent avocado commit(241c9cdf62f0162e24c37913ab37053971563ee4) enhanced cpu.get_family to return an integer for a AMD cpu, which can cause error, but get_family was declared to return a *name*, instead of an integer, which is confused. Added this commit as a workaround to bypass the error.
We expect a better solution for cpu.get_family later
=> env_process: Fix the issue of iterating an integer

virttest/utils_vdpa.py
Add a method to get vdpa device info.
` (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.vhostvdpa.nodedev: PASS (9.00 s)
`
=> utils_vdpa: Support to get vdpa devices info

docs/source/WritingTests/TestProviders.rst
Missing a `/` in the uri of the file protocol.
=> docs/TestProviders: fix a typo

virttest/libvirt_xml/nodedev_xml.py
Update nodedev_xml to support vdpa capability
` (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.vhostvdpa.nodedev: PASS (9.00 s)
`
=> nodedev_xml: Add vdpa capability class

virttest/utils_test/qemu/__init__.py, virttest/utils_windows/virtio_win.py
For INF isolation all win11 drivers are moved to DriverStore
(C:\WINDOWS\system32\DriverStore\FileRepository).
Each installation creates a new directory in
the DriverStore folder depending on the driver hash.
While for win10 drivers, there are no change.
So that, it's better to use Win32_SystemDriver to
check driver status, it's suitable for win10 and
win11 vm.
ID: 2220
=> Update driver status check method

virttest/utils_libvirt/libvirt_vmxml.py, virttest/utils_test/libvirt.py
Sometimes we do not need the VM is synced with the updated VM xml. So this is to add this option.
=> libvirt: support not to execute sync

virttest/utils_test/__init__.py
We don't need to import `libvirt` in `__init__.py` to directly access
classes/functions of `libvirt`. The change of
https://github.com/avocado-framework/avocado-vt/commit/f6adc5d34018ca68ceaf1d98b2698a5819f30442 could be affected by older
version of python.
---
Run a few tests which include code `utils_test.libvirt.xxxx()`
```
chardev_with_log_file.py
...
utils_test.libvirt.virsh_console_login(
access_session, params.get('username'), params.get('password'),
debug=True, timeout=20)
...
(1/2) type_specific.io-github-autotest-libvirt.chardev.log.console.pty: PASS (46.30 s)
(2/2) type_specific.io-github-autotest-libvirt.chardev.log.console.unix: PASS (45.75 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
``` …
=> Remove unused libvirt import of utils_test

virttest/libvirt_xml/nodedev_xml.py
VDPAXML class mistakenly moved some functions from PCIXML to itself.Move them back to fix the functions missing error.
=> Fixup:marshal_from_address not found error

virttest/utils_net.py
In the output of 'tc filter' command, there is a parent object between 'filter' and 'protocol all' in some cases.
Signed-off-by: Qian Jianhua <qianjh@fujitsu.com>
for example, in ovs_qos test case. the output of 'tc filter' command as below.
> filter ingress protocol all pref 1 matchall chain 0
filter ingress protocol all pref 1 matchall chain 0 handle 0x1
not_in_hw
action order 1:  police 0x2 rate 40Mbit burst 1000Kb mtu 64Kb action drop/continue overhead 0b linklayer unspec
ref 1 bind 1
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_ovs.net_ovs.ovs_qos.start:  FAIL: Qos test fail! (7.15 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_ovs.net_ovs.ovs_qos.start:  PASS (6.90 s)
```
=> Fixup: check 'tc filter' output

virttest/asset.py, virttest/utils_config.py
ConfigParser.readfp was removed in the latest python(3.12), so updating to use read_file().
=> Replace readfp with read_file

virttest/env_process.py, virttest/test_setup/networking.py
Refactoring the `ip_sniffing` thread setup/cleanup (start/stop) into a setuper. Then registering the brand new setuper in the `env_process` `_setup_manager`.
ID: 2390
=> env_process: Refactor ip_sniffer setup/cleanup into a Setuper

virttest/shared/deps/serial/windows_support.py
In Python 3, there is a clear distinction between string and bytes objects, so we need to convert the memoryview object to a bytes object. To fix this problem, we need to change the type of whole from a string to a bytes object.
ID: 2227
=> serial/windows_support.py: Fix data type conversion issue

virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py
s390x: Update bus on s390x from virtio-bus to virtual-css, we only use
virtual-css as the bus on s390x. virtio-bus is actually an adapter but
shown as bus in info qtree.
ID: 2383
=> Update virtual bus for s390 and s390x

virttest/libvirt_xml/other/__init__.py
Fixes module setup errors with avocado 104 python 3.9.
Should fix https://github.com/avocado-framework/avocado-vt/pull/3895
Workaround confirmed by @yanan-fu
=> libvirt_xml/other: add empty __init__.py file

virttest/env_process.py, virttest/test_setup/requirement_checks.py
Move the setup step in which it is ensured that some cmds are required for the upcoming test in env_process.{pre,post}process into a Setuper subclass. The env_process setup_manager will be in charge of running such checks from now on.
ID: 2428
=> env_process: Refactor cmds installed check into a Setuper

virttest/qemu_storage.py
Adapt the function according to different python versions
ID: 2413
=> qemu_storage: adapt the collection mapping function

virttest/utils_v2v.py
1) Some output modes don't need ovirt module, it should not be
mandatory. It's up to users who should prepare it if necessary.
2) Remove unused windows functions.
=> v2v: try import ovirt module and set ovirt to None if not found

virttest/utils_netperf.py
Starting from gcc 14.0, implicit function declarations are treated as errors by default [1], which caused the following failure been observed during the compilation.
> netlib.c:2343:9: error: implicit declaration of function ...
> ...
> make[3]: *** [Makefile:454: netlib.o] Error 1
One contributor has already sent a PR [2] to fix the issue to the netperf upstream, however, it has not been merged yet since a year ago. At the moment, let's just bypass this issue, while waiting for a regular fix to be done.
References:
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91092
[2] https://github.com/HewlettPackard/netperf/pull/74
ID: 2505
=> utils_netperf: bypass compilation failure

virttest/env_process.py
Refactor the procedure that made the "vms" parameter aware of the migrate_vms into a `Setuper` subclass.
That step will be managed `env_process::_setup_manager` from now on.
ID: 2429
=> env_process: Refactor procedure that adds migrate_vms to vms

virttest/qemu_vm.py
Sometimes, the VM may not step in dead immediately, so the first check may not detect the VM is dead.
It should check the VM status over time.
ID:2384
=> Fix VM creation checking issue

virttest/utils_net.py
The color charaters are hard to parse and affecting many tests. Add -c=never to remove color of ip command's output to fix the problem.
=> utils_net:Remove color of "ip" output

virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py
1. qcontainer: Introduce hostdev_define_by_params method to define a host device, it's
used for qemu. Currently, it only supports pci devices, something like
s390x's vfio-ap and vfio-ccw are not yet supported.
2. qemu_vm: Introduces the capability to assign host devices for guest.
The loop in the code iterates through the 'vm_hostdevs' parameter,
creating host devices based on the specified parameters.
ID: 1403
=> qemu_vm: Support assigning host devices to the guest

virttest/qemu_devices/qdevices.py, virttest/qemu_vm.py, virttest/shared/cfg/base.cfg, virttest/utils_net.py
passt is designed as a replacement for slirp (--netdev user), a new
approach implemented usermode networking which improves on security
and performance.
This patch enables the functionality to allow qemu VMs to use passt
as the network backends for nic devices.
=> Introduce nettype passt to qemu vm

virttest/libvirt_vm.py
According to the python 3.12 release notes, a SyntaxWarning will now be raised on invalid escape sequences
https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes
This will be upgraded to a "SyntaxError" in the future
This results in some regex strings, declared without the 'r' prefix generating warnings
I have only altered the regexs relevant to a few tests. There are many more regexs in the code that need this done.
Start marking regexs with the 'r' prefix
=> libvirt_vm.py: Fix Invalid Escape Sequence Warnings

virttest/env_process.py, virttest/test_setup/requirement_checks.py
Moving the logic that checked that the process was run as root into a `Setuper`. Functional changes aren't intended with this patch.
ID: 2430
=> env_process: Refactor running-as-root check into a Setuper 

virttest/qemu_monitor.py
The `blk` and the `inc` options were always set to the qmp migrate messagei, disrespecting the defaults set by qemu. However, the two options were removed since qemu 9.1.
This patch changes the building of the arguments for the new usage.
ID: 2596
=> qemu_monitor: set optional args on demand to qmp migrate

virttest/utils_test/libvirt.py
create_disk_xml() uses a disk.Disk() object to create a disk XML file. The disk.Disk() object, deletes the underlying XML when the object is garbage collected. The create_disk_xml() function only returns the XML filename, not the entire disk.Disk() object. As a result, the disk.Disk() object is garbage collected, and the underlying XML file is deleted.
This will result in any access to the XML file failing after a garbage collection cycle has been run.
Copy the contents of the XML file into a more permanent file.
=> libvirt.py -- Fix create_disk_xml() sometimes creates inaccessible file

virttest/libvirt_xml/devices/memory.py
need dynamicMemorySlots for memory target
For https://github.com/autotest/tp-libvirt/pull/5703
=> add support for dynamic memory slots

virttest/env_process.py, virttest/test_setup/migration.py
Move the setup step in which it is the environment is set up for libvirt migration tests in env_process.{pre,post}process into a Setuper subclass. The env_process setup_manager will be in charge of running such the setup/cleanup steps from now on.
ID: 2435
=> env_process: Refactor migration setup into a Setuper

virttest/utils_test/libvirt_device_utils.py
After libvirt commit 8dc04cafecd2, we can not config flock and posix_lock parameters any more. Remove them, and we do not need to care about the compatibility, since qemu do not support them from the beginning.
=> Update the lock parameters

virttest/utils_net.py
The option -c=never is unnecessary if the output doesn't need to be parsed. It might cause error, therefore remove it.
=> utils_net:Remove unnecessary -c=never of ip command

virttest/vt_console.py
To skip the UEFI guest reset process and prevent the forever waiting
Test with previously failed cases:
```
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.passt.connectivity_between_2vms.ip_portfw.root_user: PASS (202.79 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.passt.connectivity_between_2vms.ip_portfw.non_root_user: PASS (67.56 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```
```
(1/6) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device_unprivileged.one_fs.with_hugepages.two_guests.coldplug: PASS (86.80 s)
(2/6) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device_unprivileged.one_fs.with_memfd.two_guests.coldplug: PASS (83.90 s)
(3/6) …
```
=> vt_console:Skip waiting screen when login via console

virttest/env_process.py
The `migration_setup` variable existed in the `virttest.env_process` `postprocess` function. It wasn't used, though. It wasn't in some other patch in which related functionality was refactored into a Setuper.
Remove the variable from there as it's now redundant.
=> env_process: Remove forgotten migration_setup variable

virttest/utils_net.py, virttest/virt_vm.py
Few of the times it is seen that the ip address is not being fetch and the avocado runs were failed with error "ERROR: Failures occurred while postprocess:\n\n: Guest virt-tests-vm1 dmesg verification failed: Login timeout expired    (output: 'exceeded 240 s timeout, last failure: No ipv4 DHCP lease for MAC aa:bb:cc:dd:ee:ff') "
To handle this error the patch has been sent. The patch helps in obtaining ip address of the guest using "virsh-net-dhcp-leases default" command. If the guest mac address is found in the command output, the mac ipv4 address is obatined and updated in the address.cache
=> Obtaing the ip address of the guest and update address cache

virttest/shared/cfg/guest-os/Linux/Ubuntu/24.04.ppc64le.cfg
Creating a cfg file for Ubuntu 24.04, tested basic scenario as importing guest, running one test from lifecycle test bucket and removing guest using --guest-os Ubuntu.24.04.ppc64le  Please find the test results below.
root@localhost:/home/tests# python3 avocado-setup.py --run-suite guest_lifecycle_bck --guest-os Ubuntu.24.04.ppc64le --only-filter 'virtio_scsi virtio_net qcow2' --no-download
11:56:57 WARNING : Overriding user setting and enabling kvm bootstrap as guest tests are requested
11:56:57 INFO    : Check for environment
11:56:58 INFO    : Creating temporary mux dir
11:56:58 INFO    : 
11:56:58 INFO    : Running Guest Tests Suite lifecycle_bck
11:56:58 INFO    : Running: /usr/local/bin/avocado run --vt-type libvirt --vt-config …
=> Adding support for ubuntu 24.04 guest-os name and qcow2 image name.

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py
- qdevices: remove hook_drive_bus attribute
The `hook_drive_bus` attribute was introduced for handling parentship
between the `QDevice`s and theirs parent nodes. However, since that
time, it improperly made them seeing each other as the child, which
is senseless. This patch removes the attribute and the relevant code
accordingly.
- qcontainer: fix simple_unplug issue
This ensure that a device would be removed from the DevContainer
before its parent(s) been removed.
ID: 2408
=> Fix qemu simple_unplug issue

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/shared/cfg/base.cfg, virttest/storage.py
Introduce the image slices support to allow users assigning parts of the block devices to the VMs as storage backends.
Notes that this patch merely implements the support for qemu testing.
ID: 2644
=> Introduce image slices

virttest/env_process.py, virttest/test_setup/ppc.py
Refactor the preprocess/postprocess steps in virttest.env_process configuring the PowerPC systems SMT into a Setuper subclass. Use that class later on env_process and register it in the setup_manager.
ID: 2436
=> env_process: Configure SMT on Power by a Setuper

virttest/virt_admin.py
To ensure the virt-admin interactive shell is alive, a "uri" command is executed. However, the output of this command is ignored. This makes debugging a failure of this command hard.
Print the output of the error
=> virttest/virt_admin.py: Provide better Error Msg

virttest/nfs.py
Sometimes we don't need to mount dir after setup nfs server. So add
a parameter for this.
=> Add a parameter for nfs server

virttest/env_process.py, virttest/test_setup/vms.py
Yet another `env_process` refactoring patch. This time is targeted towards the piece of code destroying those vms that weren't requested by the current test configuration (and still exist in the environment).
ID: 2438
=> env_process: Destroy unrequested VMs via a Setuper

virttest/utils_sys.py
Added small utility function get_pids_for(\<list\>). This function reads the output of 'ps aux' and gets the pids for any process in \<list\>.
=> utils_sys.py: Add function for finding process PIDS

virttest/utils_libvirt/libvirt_memory.py
test results of test run containing this commit:
(1/1) type_specific.io-github-autotest-libvirt.memory.backing.page_locking_and_shared_pages.memory_allocation.page_default.ksm_default.lock_hard_limit.4k.2048: PASS (35.33 s)
=> Add consume memory repeat times

virttest/utils_ids.py
Previously use name in line to get user id and group id. In some cases, if there is one more name with same prefix in,it can get wrong user information
=> Fix check_idmap_xml_filesystem_device failure

virttest/shared/cfg/guest-os/Windows.cfg
Currently, cpu_model_flags's value is missing ',', it may cause
the issue that cpu_model_flags's can be parsed correctly.
ID: 2819
=> Update cpu_model_flags value

virttest/utils_net.py, virttest/virt_vm.py
An issue was introduced by https://github.com/avocado-framework/avocado-vt/pull/3935/commits/95377457678130adca7ba80c7f540117855a6998 which leads the failure of obtaining guest's ip addresses since not all of test scenarios requiring libvirt to manage the ip leases.
This patch merely reverted the problematic commit.
=> Fix ip addresses obtaining issue

virttest/virsh.py
Add 'Location' in output to serve tp-libvirt test checking.
=> virsh.py: add 'Location'

virttest/qemu_vm.py
- switched to using "ps -eL" for vhost thread detection, as vhost
threads are now created as separate threads and no longer appear in
"ps aux" output in the latest kernel. "ps -eL" also works with older
kernels.
- fix vhost_thread_pattern to capture LWP from "ps -eL" output
id: 2774
=> qemu_vm.py: update vhost thread matching pattern and process command

virttest/cpu.py
ID: 3974
Need to add versioned CPU models into category
=> x86_cpu_models: update cpu models category

virttest/env_process.py, virttest/test_setup/verify.py
The main goal of this patch is to add a new `Setuper` subclass named `VerifyHostDMesg`, then use it in the `env_process` `{pre,post}process` methods `setup_manager`.
Meanwhile, I'm renaming the `virttest.test_setup.os_posix.py` file into `virttest.test_setup.host_config`, as that would help maintaining the number of submodules under `virttest.test_setup` under a reasonable amount.
ID: 2437
=> Refactor host dmesg verification into a Setuper

virttest/vt_utils/block.py, virttest/vt_utils/filesystem.py, virttest/vt_utils/interrupted_thread.py, virttest/vt_utils/memory.py, virttest/vt_utils/pci_utils.py, virttest/vt_utils/qemu_utils.py
=> utils_misc module refactor

virttest/vt_utils/net/drivers/bridge.py, virttest/vt_utils/net/drivers/macvtap.py, virttest/vt_utils/net/drivers/ovs.py, virttest/vt_utils/net/interface.py, virttest/vt_utils/net/ip.py, virttest/vt_utils/net/mac.py, virttest/vt_utils/net/tap.py, virttest/vt_utils/tool.py
Refactor the utils_net.py:
1. Split net/if module from utils_net module.
=> net/if.py: refactor module

virttest/qemu_devices/qcontainer.py, virttest/shared/cfg/base.cfg
vm_secure_guest_object_options is used to define secure guest object options.
=> Added vm_secure_guest_object_options for secure guest object

virttest/utils_v2v.py
As rhel9.4.z hotfix, windows guests need around 10min to startup. Fix the timeout issue to extend 15min.
=> v2v: extend timeout for win guests

virttest/utils_config.py
for https://github.com/autotest/tp-libvirt/pull/5852
=> add support for PERSISTENT_ONLY in libvirt-guests

virttest/libvirt_xml/vm_xml.py
Signed-off-by: Julia Graham <jugraham@redhat.com>
Modified set_vm_vcpus() to support clusters.
=> vm_xml: set_vm_vcpus() support clusters

avocado_vt/plugins/vt.py, avocado_vt/plugins/vt_init.py, avocado_vt/test.py
In tp_libvrt testing, We've seen many occurrences where "Bad file descriptor" OSError was raised during clean up phase when an external command is executed via `avocado.utils.process` utility. It happens when `SubProcess` class wants to flush the stdout and stderr of the external command after finishes. These kinds of errors might lead to stdout and stderr data loss, but during the tp_libvrt testing it leads to false positive failures, which makes test evaluation harder.
This commit introduces a new config variable `omit_data_loss` which, when is enabled, will omit these errors, and they won't affect the overall test result.
Reference: https://github.com/avocado-framework/avocado/pull/6019
=> omit_data_loss config variable

virttest/utils_test/__init__.py
Signed-off-by: Kowshik Jois B S <kowsjois@linux.ibm.com>
=> Python3: replaced ConfigParser module

.cirrus.yml
We would like to have the latest avocado release (109) compatible with changes in latest avocado-vt. Therefore, we need to make the compatible check active in CI to avoid avocado and avocado-vt compatibility issues. This check will be waived again after the release.
Reference: https://github.com/avocado-framework/avocado/milestone/35
=> Enable compatibility testsing with latest avocado

virttest/libvirt_xml/devices/address.py
On s390x, there can be a zpci subelement which is used to determine properties inside the guest: uid corresponds to the domain and fid corresponds to the slot number.
=> libvirt_xml/devices/address: add optional zpci subelement

scripts/regression.py, virttest/asset.py, virttest/staging/utils_koji.py, virttest/tests/unattended_install.py, virttest/utils_config.py, virttest/utils_disk.py, virttest/utils_test/__init__.py
Signed-off-by: Kowshik Jois B S <kowsjois@linux.ibm.com>
=> ConfigParser: Removed py2 support

virttest/qemu_devices/qcontainer.py
iommufd-backed VFIO, for example:
-object iommufd,id=iommufd0 \
-device vfio-pci,host=01:00.0,iommufd=iommufd0
Multiple pcie device can use the same iommufd.
=> Enable IOMMUFD for VM device passthrough

virttest/libvirt_xml/vm_xml.py
Need to add new attribute
Before fix
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 vm_features.positive_test.hyperv.features_in_domcapabilities --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.vm_features.positive_test.hyperv.features_in_domcapabilities: ERROR: Cannot set attribute "xmm_input" to <class 'virttest.libvirt_xml.vm_xml.VMFeaturesHypervXML'> object.There is no such attribute. (7.58 s)
(1/1) type_specific.io-github-autotest-libvirt.vm_features.positive_test.hyperv.features_in_domcapabilities: ERROR: Cannot set attribute "xmm_input" to <class 'virttest.libvirt_xml.vm_xml.VMFeaturesHypervXML'> object.There is no such attribute. (7.63 s)
```
After fix
```
avocado run --vt-type …
```
=> add emsr_bitmap and xmm_input attributes in VMFeaturesHypervXML class

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py
Add log-level and remove enable_debug_mode parameter for virtiofsd 
ID: 2796
=> Add log-level and remove enable_debug_mode param

virttest/qemu_capabilities.py, virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py, virttest/shared/cfg/base.cfg
=> Add AMD SEV-SNP vm support

virttest/utils_net.py
ID:2979
Low version ip command has no this parameter "-c=never"
Remove -c=never,because default output without -c has no color code.
=> utils_net:remove -c=never for ip cmdline

virttest/env_process.py, virttest/test_setup/vms.py
This is part of the `env_process` `{pre,post}process` function refactoring. Now it was turn of the `{pre,post}process_vm_off_hook` execution steps.
I couldn't find any direct use-case in `avocado-vt` or [`tp-qemu`](https://github.com/autotest/tp-qemu) so I could test the patch. However, as I found in https://github.com/avocado-framework/avocado-vt/pull/2106 and https://github.com/avocado-framework/avocado-vt/issues/2134 these hooks seem to be a part of the [I2N plugin](https://github.com/intra2net/avocado-i2n).
I tried to ~~test~~ mock the way the [`i2n.cmd_parser`](https://github.com/intra2net/avocado-i2n/blob/master/avocado_i2n/cmd_parser.py) modifies the hooks through [`i2n.plugins.auto`](https://github.com/intra2net/avocado-i2n/blob/master/avocado_i2n/plugins/auto.py) and …
=> env_process: Refactor {pre,post}process_vm_off_hook execution

virttest/env_process.py, virttest/test_setup/kernel.py
KVM modules are reloaded and restored before and after running tests. That was done directly in the preprocess and postprocess functions in virttest.env_process. Write a Setuper subclass that implements those in setup/cleanup methods and register the setuper in the env_process setup_manager.
This is a patch from a larger patch series refactoring the env_process preprocess and postprocess functions. In each of these patches, a pre/post process step is identified and replaced with a Setuper subclass so the following can finally be met:
- Only cleanup steps of successful setup steps are run to avoid possible environment corruption or hard to read errors.
- Running setup/cleanup steps symmetrically during env pre/post process.
- Reduce explicit pre/post process function code length.
ID: 2934
=> env_process: Refactor kvm module reload/restore steps

virttest/utils_net.py
On serial sessions, kernel messages can clutter the output. aexpects 'safe' functions deal with this.
A test failed because of such clutter:
"""
Interface info :[   15.114033] block dm-0: the capability attribute has
been deprecated.ip -json addr
show[{"ifindex":1,"ifname":"lo","flags":["...
"""
leads to
"""
Failed to get interface info via "ip" command. Reason: Extra data: line 1 column 16 (char 15) """
The 'safe' option removes the "[   15... deprecated." so that the json
can be parsed correctly.
=> utils_net: make function safe for serial session

virttest/guest_agent.py
Add a new guest agent command 'gunetwork-get-routeats' to get route info of Guest.
ID: 2588
Signed-off-by: demeng <demeng@redhat.com>
=> guest_agent.py: Add new command 'guest-network-get-route'

virttest/utils_misc.py
if cpu toplogy file in sysfs is not found, AttributeError would be thrown, so add this exception.
Test result related with this pr:
(1/1) type_specific.io-github-autotest-libvirt.numa_capabilities.default: STARTED
(1/1) type_specific.io-github-autotest-libvirt.numa_capabilities.default: PASS (9.83 s)
=> Add AttributeError to exception when cpu topology file is not found

virttest/env_process.py, virttest/test_setup/requirement_checks.py
Another bunch of patches regarding the `env_process` `preprocess` and `postprocess` functionr refactoring patch series. In this one, those steps related to extracting, logging and checking required package versions are refactored.
I usually send 1 patch per PR. However, I'm sending a bunch of them together this time. This is due to the `version_info`, a variable that lived inside the `preprocess` function and that most of the version-check related steps used. I'm doing so not to modify the public API of the `env_process` submodule.
First `version_info` is made a global variable of the submodule, so both steps inside the `preprocess` and those being refactored can access it. Once all have been written into `Setuper`s, then the `version_info` variable is also migrated to the …
=> env_process: Tested package version check refactoring

virttest/migration_template.py
When we use migration option --xml or --persistent-xml, we need provide a existing xml file, but in _update_xmlfile_path_in_migrate_options() vmxml object is a local variable, it will be released after the _update_xmlfile_path_in_migrate_options()  is done, so the xml file with vmxml object is released at the same time.
That will cause the migration fail. So return the local variable would delay the destruction after the migration.
=> Return the local varriable to delay the desctruction of the xml file

virttest/libvirt_vm.py
test results related with help func:
(1/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_with_order: STARTED
(1/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_with_order: PASS (153.45 s)
(2/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_without_order: STARTED
(2/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_without_order: PASS (154.16 s)
=> Add cpu topology info support for dies and clusters

virttest/qemu_devices/qcontainer.py
Not providing a default behavior leads to use of variable without a value and thus cryptic errors regarding the simple fact that we have to provide an image format. It is also not recommended in any conditionals as it leads to undefined behaviors. Finally, in the case of multiple images we may have "image_format=" to use empty string which should be handled similarly to None (lack of any image_format parameter) or generally as the comment suggests to a meaningful default behavior.
=> Use raw image format by default for block devices

virttest/utils_libvirt/libvirt_pcicontr.py
In some cases, we need to get a free slot on a specific controller, so update the controller bus setting configurable.
` (08/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.pcie_to_pci_bridge_controller.virtio_non_transitional.virtio: PASS (57.08 s)
`
=> get_free_pci_slot: Make the value of controller bus configurable

virttest/utils_misc.py
For snapshot name with letter, func get_image_snapshot return nothing, so fix this scenario
=> Fix snapshot name with letter

virttest/qemu_devices/qcontainer.py
Explicitly set 'data_file' option to the blockdev format node,
in case there is an extra blockdev filter node.
ID: 3382
=> data_file: set 'data_file' to blockdev format node

virttest/qemu_devices/qdevice_format.py, virttest/qemu_devices/qdevices.py, virttest/qemu_vm.py
ID: 3253, 3262, 3269, 3393,3392,3388, 3431, 3432
=> add qdevice_format module

virttest/iscsi.py
Some tests need to simulate a multipath setup.
For this add a new parameter. If it is allowed to create multipath the export function that creates the iscsi objects will ignore if a backstor/fileio of the given name already exists.
=> iscsi: allow for multipath setup

virttest/env_process.py, virttest/test_setup/__init__.py, virttest/test_setup/memory.py
Creating a new Setuper subclass for setting and cleaning huge pages up. Removing the original code from virttest.env_process and replacing it instead with the new HugePagesSetup class being registered in the setup_manager.
_pre_hugepages_surp and _post_hugepages_surp were left in env_process. Their goal is to provide a mechanism in env_process to raise a TestFail in case pages were leaked during a test. If that mechanism was refactored into the setuper, the TestFail would be masked by just an Error due to the way setup_manager handles postprocess exceptions. Changing the way SetupManager handles that requires bigger discussion on how the test infrastructure should handle test status reports, which is a way broader topic that what this patch aims to be.
This is a patch from a larger patch …
=> env_process: Refactor huge pages setup/cleanup steps

virttest/env_process.py, virttest/test_setup/memory.py
Rewriting the transparent huge pages setup/cleanup steps into a setuper and registering it into the env_process setup_manager.
This is a patch from a larger patch series refactoring the env_process preprocess and postprocess functions. In each of these patches, a pre/post process step is identified and replaced with a Setuper subclass so the following can finally be met:
- Only cleanup steps of successful setup steps are run to avoid possible environment corruption or hard to read errors.
- Running setup/cleanup steps symmetrically during env pre/post process.
- Reduce explicit pre/post process function code length.
ID: 2939
=> env_process: Refactor transparent huge pages setup/cleanup

virttest/env_process.py, virttest/test_setup/kernel.py
Write the logic setting and cleaning Kernel Same-Page Merging up in virttest.env_process preprocess and postprocess into a Setuper, and register it in the env_process setup_manager.
This is a patch from a larger patch series refactoring the env_process preprocess and postprocess functions. In each of these patches, a pre/post process step is identified and replaced with a Setuper subclass so the following can finally be met:
- Only cleanup steps of successful setup steps are run to avoid possible environment corruption or hard to read errors.
- Running setup/cleanup steps symmetrically during env pre/post process.
- Reduce explicit pre/post process function code length.
Tested by `--tescase=ksm_services.ksmtuned,ksm_base,ksm_overcommit`:
```{bash}
(1/6) …
```
=> env_process: Refactor Kernel Same-Page Merging setup

virttest/utils_net.py
The command might output ip address with color characters which will break the script, like below.
Get ipv6 address of vm1: [34m2620:52:11:1601:982f:7bff:fe94:1415[0m
This is to disable the color characters in the outputs.
=> utils_net: disable color chars

virttest/utils_config.py, virttest/utils_test/libvirt_device_utils.py
1. libvirt_device_utils: handle additional filesystem parameters Add parameters to helper function that creates the filesystem xml.
2. utils_config: add new parameter to qemu.config The parameter is used to set enable debug log level output from virtiofsd when libvirt launches it.
=> virtiofs: enhance libvirt filesystem device functions

virttest/libvirt_xml/devices/disk.py
Now a new element dataStore has been implemented. So add it to disk.py.
=> Disk: add new dataStore element to disk.py

virttest/qemu_devices/qcontainer.py
According to the context, we should make sure both hmat-lb bandwidth and hmat-lb latency are defined
when define hmat-cache.
But both the conditions for defining are the same here, amend one with "hmat_lb_latency".
ID: 3494
=> Amend the conditions for defining hmat-cache

virttest/libvirt_xml/devices/video.py
Support below resolution sub element.
```
<video>
<model type='virtio' heads='1' primary='yes'>
<resolution x='507' y='510'/>
</model>
</video>
```
=> video: add resolution sub element

virttest/nfs.py
NFS service is named as nfs-server.service in Fedora, so in fedora also it should be starting nfs-server.service at place of nfs.service.
Signed-off-by: Anushree Mathur <anushree.mathur@linux.vnet.ibm.com>
=> Replacing nfs.service as nfs-server.service for fedora!

virttest/utils_test/__init__.py
Created function to update default kernel
=> utils_test: created function to update default kernel

virttest/utils_disk.py
cmd should be parted -s "/dev/sda" rm 1 instead of  parted -s "/dev/sda" rm sda1
For https://github.com/autotest/tp-libvirt/pull/6254/files 
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 virtual_disks.usb_startuppolicy_config.positive.coldplug.set_mandatory_startuppolicy.with_usb_device_plugged.start_guest --vt-connect-uri qemu:///system 
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.usb_startuppolicy_config.positive.coldplug.set_mandatory_startuppolicy.with_usb_device_plugged.start_guest: PASS (83.79 s)
```
=> update delete_partition function running cmd

virttest/libvirt_xml/vm_xml.py
Start a guest with emsr_bitmap, xmm_input, tlbflush-direct and tlbflush-ext
For https://github.com/autotest/tp-libvirt/pull/6267 
The showing xml
```
<hyperv mode="custom">
<tlbflush state="on">
<direct state="on"/>
<extended state="on"/>
</tlbflush>
</hyperv>
```
```
avocado run --vt-type libvirt --vt-machine-type q35 vm_features
(01/18) type_specific.io-github-autotest-libvirt.vm_features.positive_test.hyperv.features_in_domcapabilities: STARTED
(01/18) type_specific.io-github-autotest-libvirt.vm_features.positive_test.hyperv.features_in_domcapabilities: PASS (22.22 s)
(02/18) type_specific.io-github-autotest-libvirt.vm_features.positive_test.hyperv.tlbflush: STARTED
(02/18) type_specific.io-github-autotest-libvirt.vm_features.positive_test.hyperv. …
```
=> add support for new hyperv tag

virttest/libvirt_xml/vm_xml.py
virsh instance of virsh.Virsh has ignore_status set to False by default which would cause the failure of define in function sync() with wrong xml and could not revert to the original xml.
=> vm_xml:func sync() set ignore_status=True when trying to define vm

virttest/libvirt_xml/capability_xml.py
This is to add the support in virsh capabilities output for below
elements:
- interconnects
- cache under cell
LIke
```
<topology>
<cells num="2">
<cell id="0">
...
<pages unit="KiB" size="1048576">0</pages>
<cache level="1" associativity="direct" policy="writeback">
<size value="10" unit="KiB" />
<line value="8" unit="B" />
</cache>
<cache level="2" associativity="full" policy="writethrough">
<size value="128" unit="KiB" />
<line value="16" unit="B" />
</cache>
...
<interconnects>
<latency initiator="1" target="1" type="read" value="11" />
<latency initiator="1" target="1" type="write" value="12" />
<bandwidth initiator="1" target="1" type="read" value="103424" unit="KiB" />
<bandwidth initiator="1" target="1" type="write" value="104448" unit="KiB" />
</interconnects>
</topology>
```
=> capability_xml: enable cache element

.github/workflows/ci.yml
Workflows using the ubuntu-20.04 image label should be updated to ubuntu-latest, ubuntu-22.04, ubuntu-24.04 .
See https://github.com/actions/runner-images/issues/11101
=> ci.yml: update ubuntu and python version

virttest/migration_template.py
1. set connection obj auto_recover to False to avoid duplicate connection release
2. restore connection uri after migration clean up
related test results:
(1/6) type_specific.io-github-autotest-libvirt.migrate.migration_with_numa_topology.no_back_migration.without_postcopy.base_options.one_cluster_on_numa: STARTED
(1/6) type_specific.io-github-autotest-libvirt.migrate.migration_with_numa_topology.no_back_migration.without_postcopy.base_options.one_cluster_on_numa: PASS (414.32 s)
(2/6) type_specific.io-github-autotest-libvirt.migrate.migration_with_numa_topology.no_back_migration.without_postcopy.base_options.multi_cluster_on_numa: STARTED
(2/6) type_specific.io-github-autotest-libvirt.migrate.migration_with_numa_topology.no_back_migration.without_postcopy.base_options.multi_cluster_on_num …
=> Fix migration template bugs

.github/workflows/ci.yml
Reverts avocado-framework/avocado-vt#4113
This commit does not completely solve the CI problem, and some CI work still fails, please check the PR #4110 for details.
=> Revert "ci.yml: update ubuntu and python version"

virttest/storage.py
The backup directory depends on the setting of the parameter backup_dir,
we didn't add backup_dir as a parameter of the external data file, then
the root_dir is used because backup_dir = "", so adding backup_dir param
for the external data file can fix this.
ID: 3516
=> storage: Fix the external data file backup dir issue

.github/workflows/ci.yml, Makefile, requirements-travis.txt, spell.ignore, virttest/libvirt_xml/devices/disk.py, virttest/lvsb_base.py, virttest/qemu_devices/qcontainer.py, virttest/utils_ids.py, virttest/utils_libvirt/libvirt_monitor.py, virttest/utils_libvirt/libvirt_unprivileged.py, virttest/utils_net.py, virttest/utils_test/libvirt.py, virttest/utils_vdpa.py, virttest/vdpa_blk.py
ubuntu-20.04 runner image is unsupported since 2025-04-15, let's upgrade
to use ubuntu-24.04 runner.
Ref: actions/runner-images#11101
=> ci(runner): Update CI runner from 20.04 to 24.04

virttest/qemu_devices/qdevice_format.py
- Set "max-bytes" type to int32.
ID: 3739
=> update qdevice_format.py module

virttest/libvirt_xml/devices/disk.py, virttest/utils_config.py
1. Add the new elements for disk source:
- knownHosts
- identity
- ssl
- readahead
- timeout
- cookies
2. Add storage_use_nbdkit which can be used with ssh/https network disks in utils_config.py.
=> disk.py: add elements of ssh/https network disk

virttest/env_process.py, virttest/storage.py, virttest/test_setup/aexpect.py
The order in which `aexpect.kill_tail_threads` was called during env_process.postprocess changed while we were refactoring it. Now, tail threads were killed before the IPSniffer or other processes using Tail objects were cleaned up.
Calling `aexpect.kill_tail_threads` when it was supposed to: right after the IPSniffer is cleaned up.
ID: 3698
=> Env process refactoring kill tail threads

virttest/virt_vm.py
The get_cpu_count function is returning the output containing the escape sequence so the checks are failing, I have removed the escape sequence from the output then returned it!
Signed-off-by: Anushree Mathur <anushree.mathur@linux.vnet.ibm.com>
=> Removing the escape sequence from the output of get_cpu_count()!

spell.ignore, virttest/utils_test/__init__.py
0a3af4df93696284dbd9d3786a4041d9e749d22d was recently merged though there were CI check issues.
=> utils_test: fix code formatting issue from CI

virttest/qemu_devices/qdevice_format.py
For usb-storage and usb-tablet,
the "serial" value is "NO_EQUAL_STRING" now.
However, qemu wants "on" instead of "NO_EQUAL_STRING".
Meanwhile, the "port" type is int now.
However, qemu wants string type instead of int type.
ID: 3798
=> qdevice_format: change value of "usb-storage", "usb-tablet"

virttest/utils_logfile.py, virttest/utils_test/libvirt.py
- this will clear defined log_file - so the test will consider only the messages added in the test run.
- previous log can be backuped to the tmp dir if requrired (the restore not yet prepared)
add new backup_logfile method: used in clear_logfile, but it can be used just as is
+ minor refactor to process not only bollean str_in_log variable (as it comes from test in my case as str)
=> add new clear_logfile method:

spell.ignore, virttest/libvirt_xml/devices/librarian.py, virttest/libvirt_xml/devices/pstore.py
```python
>>> from virttest.libvirt_xml.devices import pstore
>>> p = pstore.Pstore.new_from_dict({"backend": "acpi-erst", "path": "/tmp/guest_acpi_esrt_large", "size": 8, "size_unit": "KiB"})
>>> str(p)
'<pstore backend="acpi-erst"><path>/tmp/guest_acpi_esrt_large</path><size unit="KiB">8</size></pstore>'
```
=> Add pstore devices in libvirt xml

virttest/bootstrap.py
Remove virt-manager as dependence when bootstraping virttools
virt-manager is UI version of virt-install, and virt-tools test cases doesn't really use it
=> Remove virt-manager as dependence when bootstraping virttools

virttest/remote.py
`SCPTransferFailedError` doesn't exist.
This was raised occasionally when the file couldn't be pulled. The documented intention was to create a local file in this case. So, do that, and log the Exception.
In my case it was `ExpectProcessTerminatedError`.
=> remote: handle error when remote file doesn't exist

virttest/utils_misc.py
The serial and device can be set both on scsi-hd.
-device '{"driver": "scsi-hd", ..., "serial": "stg5_serial", "device_id": "stg5_device"}' \
The device_id is mapped to ID_SERIAL
The serial is mapped to ID_SCSI_SERIAL in the udevadm info output
Currently we miss ID_SCSI_SERIAL in the search field. It will fail if we want to find a disk by serial instead of device_id
=> utils_misc:add ID_SCSI_SERIAL into get_linux_drive_path search field

spell.ignore, virttest/utils_net.py
Add a new option to support multiple default routes.
=> utils_net: support multiple default routes

virttest/qemu_vm.py
qemu_vm: add support for new on-fault mem-lock value
With the arrival of the value, on-fault, for the mem-lock
value, updates the code so now supports new string values
instead of only boolean ones.
ID: 3807
=> qemu_vm: add support for new on-fault mem-lock value

virttest/virsh.py
New command introduced in libvirt 11.2.0.
=> virsh: add hypervisor-cpu-models

virttest/utils_sriov.py
In some test cases, we need to use the specified PF.
`(10/12) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.vfio_variant_driver.multiple_ifaces.hostdev_device.mlx5_vfio: PASS (111.88 s)
`
=> sriov: Add a parameter to get the specified PF

avocado_vt/test.py, virttest/shared/cfg/base.cfg
For libvirt type VMs, store the VM log into the test debug directory. The motivating use case is to confirm if a guest has crashed.
=> avocado_vt/test: enable storage of VM logs

spell.ignore, virttest/utils_test/__init__.py
The original implementation introduced an unintended breaking change
that violates the current design principles and stability guarantees.
This revert restores the previous stable behavior until a corrected
approach is re-evaluated.
This reverts commit 065d4ac9442c50ef34531a00df4ad55795601db0
This reverts commit 0a3af4df93696284dbd9d3786a4041d9e749d22d
ID: 4023
=> Revert "utils-test:Add running htx-cmdline stress_type"

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/qemu_vm.py
=> Add device address parameter for s390x

virttest/test_setup/__init__.py
b4a6f2700a97e31a0bd3e04394fa0e27ff22606e added remote capability for remote but forgot to set a default value for the new parameter.
This change fixes
```
ERROR: HugePageConfig.__init__() missing 1 required positiona
l argument: 'session'
```
=> test_setup: fix HugePageConfig

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/qemu_storage.py, virttest/storage.py, virttest/vhost_user_blk.py
=> avocado-vt: add support for virtio-blk-vhost-user

virttest/utils_stress.py
This patch will allow us to send vms as paramter to VMStressEvents
Through this change, we can specify in which vms we want to run the stress_events
If vms parameter is not specified, then default vms from env will be considered
Thus, there will not be any error in the dependant files
Signed-off-by: Misbah Anjum N [misanjum@linux.vnet.ibm.com](mailto:misanjum@linux.vnet.ibm.com)
=> utils-stress:Update script to take vms parameter

virttest/env_process.py, virttest/test_setup/rng_egd.py
Replace the steps setting and cleaning EGD up into a Setuper that is registered into the setup_manager in env_process.
This is a patch from a larger patch series refactoring the env_process preprocess and postprocess functions. In each of these patches, a pre/post process step is identified and replaced with a Setuper subclass so the following can finally be met:
- Only cleanup steps of successful setup steps are run to avoid possible environment corruption or hard to read errors.
- Running setup/cleanup steps symmetrically during env pre/post process.
- Reduce explicit pre/post process function code length.
This patch shouldn't introduce any regression or breaking change.
With `--testcase=boot --rng_type=virtio_rng.rng_egd`:
```
(1/1) …
```
=> env_process: Refactor EGD setup

spell.ignore, virttest/iscsi.py, virttest/shared/cfg/base.cfg, virttest/utils_net.py
- Add a new class to supporting iscsi with the multi targets.
- Update the create_iSCSI function.
ID: 3457
=> update iscsi.py module

README.rst, docs/source/GetStartedGuide.rst, docs/source/contributing/Guidelines.rst
This commit adds badges for the GitHub Actions CI, Cirrus CI, black code
style and the PyPI version to the README file. It also fixes a typo.
Adding the DeepWiki badge to the README file enables the auto-refresh
feature for the project's documentation on DeepWiki. This ensures that
the documentation stays up-to-date with the latest changes in the
repository.
Closes #4145
ID: 4151
=> docs: add CI, Cirrus, black, DeepWiki and PyPI badges

virttest/guest_agent.py
Add a new guest agent command 'guest-get-load' to
get cpu load average info of Guest.
ID: 3534
=> guest_agent: Add new command 'guest-get-load'

virttest/utils_netperf.py
Netperf client couldn't start on systems with more than 256 cpus. This impacts the ability to run `netperf_stress` tests and possible some other more in those systems.
This patch tries to alleviate the issue by modifying the number of maximum cpus supported by netperf prior to the binary compilation.
To do so, the patch is divided in two commits:
1. To compile netperf, first the source code needs to be decompressed. Then, the code is compiled into a binary. Both commands were run through the same remote session. The first commit in this patch splits the pre-compilation and compilation steps into two different steps. That way, we could modify netperf's source code on-the-go if needed.
2. The second commit adds a mechanism to detect whether the system running netperf has a number of CPUS …
=> netperf_stress: Support running netperf clients on systems with more than 256 CPUs

virttest/utils_zcrypt.py, virttest/virsh.py
Add nodedev-update function. This is needed to test the update of a
passed through crypto device on s390x.
In utils_zcrypt: For easier debugging use "card.domain" as the string representation of
an entry in the logs.
=> virsh: add nodedev-update

virttest/utils_libvirt/libvirt_disk.py
Reverts avocado-framework/avocado-vt#4161
=> Revert "libvirt_disk: Add "/sysroot" as root mountpoint"
