avocado/core/plugins/virt_test.py
Now avocado main Test class is inside the avocado main entry point.
=> avocado-vt: Update according to recent avocado API change

avocado/core/plugins/virt_test.py, avocado/core/plugins/virt_test_list.py
That were changed in another round of the API updates.
=> avocado-vt: Update API calls

README.md, README.rst
So we help new users getting the hang of avocado-vt.
=> avocado-vt: Add a getting started section to the top level README file

README.rst
=> README.rst: A few reStructuredText corrections

MANIFEST.in, Makefile, avocado-plugins-vt.spec, setup.py
=> avocado-vt: Update to release 0.25.0

docs/source/GetStartedGuide.rst, docs/source/conf.py, docs/source/index.rst
Also, update README.rst to contain the setup step
relative to the virt-test suite location.
=> docs: Add RPM based setup procedure

avocado/core/plugins/virt_test.py
This is a follow up to PR #20.
=> [V2] plugins.virt_test: Don't sys.exit in plugin

virttest/utils_misc.py
=> fix find command issue in utils_misc module

virttest/openvswitch.py
=> fix syntax issue in openvswitch module

avocado/core/plugins/virt_test_bootstrap.py
Thanks to Andrei Stepanov for noticing it.
=> bootstrap plugin: Remove duplicate assignment

avocado/core/plugins/virt_test.py
=> Fix custom config

avocado-plugins-vt.spec, setup.py
Fix a couple of little spec file bugs lying around before the 0.27.1 release
=> RPM spec file fixes

virttest/cartesian_config.py
`join': process correct dic name when merge two copies of the same sub-tree
`suffix': drop all suffixes if same variable with different suffuxes have same
value
Improve performance for `join'
=> Fixes for join, suffix operators

avocado/core/plugins/vt.py, test-providers.d/io-github-spiceqa-spice.ini, virttest/bootstrap.py, virttest/standalone_test.py
tp-spice is tests set supposed to be run as a part of avocado-vt
In charge:
Andrei Stepanov <astepano@redhat.com>
Tomas Jamrisko <tjamrisk@redhat.com>
=> Add SpiceQA test provider

docs/source/conf.py
Add the ability to generate virttest package docs.
=> docs: Add automated API documentation generation

virttest/utils_test/qemu.py
id: 1261771
Previous PR under virt-test: autotest/virt-test#2310
=> virttest/utils_test.qemu: Add func() for setup runlevel in guest.

test-providers.d/io-github-spiceqa-spice.ini
I have done some reorganization to tp-spice cartesian configs.
=> Update tp-spice ini file, edit configs list

shared/cfg/guest-hw.cfg
=> shared/cfg/guest-hw.cfg: Rename Host_RHEL using new rule

shared/deps/serial/VirtIoChannel_guest_send_receive.py, shared/deps/serial/serial_host_send_receive.py
=> Fix typos that leads receive wrong size

shared/cfg/guest-os/Linux/SLES.cfg, shared/cfg/guest-os/Linux/Ubuntu.cfg
add grub_file parameter for SLES and ubuntu,
ID:1122759
=> add grub_file parameter for SLES and Ubuntu

shared/cfg/guest-os/Linux/Fedora/21.x86_64.cfg, shared/cfg/guest-os/Linux/JeOS/21.x86_64.cfg, virttest/bootstrap.py, virttest/tests/unattended_install.py
Fix some problems encountered when trying unattended install through URL method.
=> Fixes to unattended install (URL method)

shared/cfg/guest-os/Windows/Win10.cfg, shared/cfg/guest-os/Windows/Win10/i386.cfg, shared/cfg/guest-os/Windows/Win10/x86_64.cfg, shared/unattended/win10-32-autounattend.xml, shared/unattended/win10-64-autounattend.xml, shared/unattended/win10-64-autounattend_ovmf.xml
=> virt-test : Add windows 10 support

virttest/qemu_qtree.py
=> virttest/qemu_qtree.py: Get the disks error log for debugging

virttest/utils_v2v.py
Move this function from test case as it's more like a common function,
so other cases which need boot windows guest can reuse it.
=> utils_v2v: Add windows VM init function

Makefile, debian/changelog
We have a new 0.29.0 build out, this PR updates the deb build files with the appropriate values.
=> Ubuntu build updates

virttest/storage.py
=> virttest/storage.py: fix error message typo

virttest/utils_disk.py
s/suport/support/g
s/orign/original/g
=> virttest/utils_disk: Fix typo

docs/source/extra/DownloadableImages.rst
Add some pointers on how JeOS and Winutils files are created
in our documentation.
=> docs: Add some details on how to create JeOS and Winutils files

shared/cfg/guest-os/Linux/Ubuntu/14.04.3-server.i386.cfg, shared/cfg/guest-os/Linux/Ubuntu/14.04.3-server.x86_64.cfg, shared/unattended/Ubuntu-14-04-3.preseed
ID: 1265899
Create the cfg file for Ubuntu version 14.04.3
=> Add cfg file for Ubuntu-14.04.3

virttest/utils_params.py
=> add copy_from_keys support 

virttest/qemu_vm.py
=> make a numa node support  multi-cpus options

shared/cfg/cdkeys.cfg
This keys better work for specified ISO images at
shared/unattended/*.xml
=> Switch default keys for Win8.1, XP

shared/cfg/cdkeys.cfg
Use key for version specified at ./shared/cfg/guest-os/Windows/Win10/*
=> Switch cdkey for Win10

test-providers.d/io-github-spiceqa-spice.ini
Configs for tp-spice have been reorganised.
=> Update test-provider ini file for tp-spice

virttest/gluster.py
gluster volume stop/delete command promote user to confirm the
operation, the code should handle stdin and input the confirmation
string. Otherwise, the command will timeout.
=> virttest.gluster: echo the confirm infomation for gluster volume stop/delete command.

virttest/qemu_vm.py
=> make guest NUMA node support memdev option

shared/cfg/guest-os/Linux.cfg, shared/cfg/guest-os/Windows.cfg, shared/cfg/guest-os/Windows/Win10/i386.cfg, shared/cfg/guest-os/Windows/Win10/x86_64.cfg, shared/cfg/guest-os/Windows/Win2003/i386.cfg, shared/cfg/guest-os/Windows/Win2003/x86_64.cfg, shared/cfg/guest-os/Windows/Win2008/i386.cfg, shared/cfg/guest-os/Windows/Win2008/x86_64.cfg, shared/cfg/guest-os/Windows/Win7/i386.cfg, shared/cfg/guest-os/Windows/Win7/x86_64.cfg, shared/cfg/guest-os/Windows/Win8/i386.cfg, shared/cfg/guest-os/Windows/Win8/x86_64.cfg
=> Add memory hotplug/unplug related test configuration

shared/cfg/guest-os/Linux.cfg, shared/cfg/guest-os/Windows.cfg
Signed-off-by: Mike Cao <bcao@redhat.com>
=> Add some config for driver_load job

selftests/unit/test_qemu_devices.py, virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/qemu_devices/utils.py
Hello guys,
I finally looked at the selftests error outputs and it seems there were couple of long forgotten issues. Please read the descriptions of the individual patches for details.
Regards,
Lukáš
=> Couple of selftest-related fixes

virttest/remote.py
=> Ehancement nc remote copy function

virttest/ovs_utils.py
This commit refers to the codes of utils_net.ping.
=> virttest/ovs_utils: Do not distinguish between IPv4 and IPv6

selftests/unit/test_utils_net.py, virttest/cartesian_config.py, virttest/propcan.py, virttest/remote_commander/remote_interface.py, virttest/utils_test/__init__.py, virttest/utils_test/qemu.py, virttest/video_maker.py
Hello guys,
this should make travis(inspekt) happy about our code quality. Please review carefully the `propcan` patches as I'm not 100% sure about the correctness of my changes (I believe the proposed fixes are the best solution, although I might have missed some issues...)
Regards,
Lukáš
=> Couple of recent pylint fixes

virttest/tests/unattended_install.py
Method setup_unattended_http_server was not being used anywhere.
=> Fix: create http server in http_ks tests.

shared/cfg/base.cfg, virttest/env_process.py, virttest/test_setup.py
=> Add strace qemu process support

requirements-travis.txt, virttest/defaults.py, virttest/libvirt_xml/vm_xml.py
Now we're going to start being picky about unused imports. Brace yourselves.
=> Update to inspektor 0.2.0

shared/cfg/guest-os/Windows/Win8.cfg
removed "+sep", bug 821741 is fixed
=> enforce_quit:Win8 guest lack of 'enforce' params to the cmd line

.travis.yml, requirements-travis-python26.txt, selftests/unit/test_utils_config.py, virttest/unittest_utils/mock.py
Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>
=> .travis.yml: Add python 2.6 to test matrix

virttest/utils_test/qemu.py
=> add memory hotplug/hotunplug base test support

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/qemu_vm.py
Add memory/pc-dimm device support in avocado-vt
=> Add memory hotplug/unplug support

docs/source/GetStartedGuide.rst
I had sent quick start guide on avocado/avocado-vt to
'avocado-devel@redhat.com'. Based on response I received,
have added few points from my guide to the existing avocado-vt
documentation. This PR is to review the same.
=> [PATCH] Update getting started avocado-vt documentation

shared/unattended/OpenSUSE-13.xml
Sending OpenSUSE-13.xml as requested.
=> Adding OpenSUSE-13.xml (same file as OpenSUSE-12.xml)

virttest/utils_net.py
When IPv6Manager sets up IPv6 environment, the setup() does not check if the specified address exists already on the host which sometimes may cause IfChangeAddrError exception.
When IPv6Manager cleans up IPv6 environment, the cleanup() does not check if the specified address is added by avocado-vt which also may cause IfChangeAddrError.
=> virttest/utils_net.py: Update setup() and cleanup() for IPv6 address

virttest/utils_test/__init__.py
Add remote vm manager to implement remote vm access, ip check and commands running in vm
=> virttest.utils_test: add remote VM manager

virttest/utils_misc.py
=> virttest/utils_misc.py: Add func() for getting disk drive letter in windows guest.

virttest/test_setup.py, virttest/utils_misc.py
=> Enable shell param for the commands includes redirection

shared/cfg/host-kernel-base.cfg, shared/cfg/host-kernel/Host_Fedora.cfg, shared/cfg/host-kernel/Host_RHEL.cfg, shared/cfg/host-kernel/Host_RHEL/5.cfg, shared/cfg/host-kernel/Host_RHEL/5/10.cfg, shared/cfg/host-kernel/Host_RHEL/5/11.cfg, shared/cfg/host-kernel/Host_RHEL/5/7.cfg, shared/cfg/host-kernel/Host_RHEL/5/8.cfg, shared/cfg/host-kernel/Host_RHEL/5/9.cfg, shared/cfg/host-kernel/Host_RHEL/6.cfg, shared/cfg/host-kernel/Host_RHEL/6/1.cfg, shared/cfg/host-kernel/Host_RHEL/6/2.cfg, shared/cfg/host-kernel/Host_RHEL/6/3.cfg, shared/cfg/host-kernel/Host_RHEL/6/4.cfg, shared/cfg/host-kernel/Host_RHEL/6/5.cfg, shared/cfg/host-kernel/Host_RHEL/6/6.cfg, shared/cfg/host-kernel/Host_RHEL/6/7.cfg, shared/cfg/host-kernel/Host_RHEL/7.cfg, shared/cfg/host-kernel/Host_RHEL/7/0.cfg, shared/cfg/host-kernel/Host_RHEL/7/1.cfg, shared/cfg/host-kernel/Host_RHEL/7/2.cfg, shared/cfg/host-kernel/host-kernel-check.cfg
=> Add host-kernel cfg

shared/cfg/guest-os/Linux/OpenSUSE/42.1.x86_64.cfg, shared/unattended/OpenSUSE-Leap-42.1.xml
I should have mentioned I did test unattended install with the OpenSUSE-Leap-42.1.xml file being submitted here.  Thank you !
=> Request to add OpenSUSE Leap 42.1.x86_64.cfg and its xml file for unattended install

shared/cfg/guest-os/Windows.cfg
=> shared/cfg/guest-os/Windows.cfg: Add some config for migrate_multi_host

virttest/qemu_monitor.py
=> virttest/qemu_monitor.py: Add cmd "qom-set" and cmd "qom-get".

virttest/libvirt_vm.py
1) Check the result of attach_disk
2) Fix typo
=> virttest/libvirt_vm: check the result of attach_disk

virttest/utils_misc.py
Signed-off-by: XueQiangWei <xuwei@redhat.com>
=> add Haswell-noTSX and Broadwell-noTSX

virttest/qemu_vm.py
=> fix logical error in add numa node

avocado_vt/plugins/vt.py
During plugin initialization we look-out the qemu-bin. There was an
incorrect exception catched to ignore failure which this patch fixes.
Additionally the default value was "Could not find one", which fails
when we try to run avocado with custom qemu (using --vt-qemu-bin)
because obviously this path does not exists. This patch supplies None
and only sets this value in the help text.
=> vt: Avocado-vt is not enabled when qemu-bin is not found

virttest/utils_misc.py
This function provides a method to get target drive path in guest by serial or wwn.
ID: 1279721 1279719 1272397
=> utils_misc: add get_linux_drive_path function

virttest/utils_spice.py
EPEL rpms have been moved to a new location and 
modifying the utils_spice.py file to use this new location
of the EPEL rpm. 
Reviewed-By: Swapna Krishnan <skrishna@redhat.com>
=> Update utils_spice.py to use new location of epel

docs/source/CartesianConfig.rst, docs/source/GlusterFs.rst, docs/source/InstallOptionalPackages.rst, docs/source/InstallWinVirtio.rst, docs/source/ListingGuests.rst, docs/source/MultiHostMigration.rst, docs/source/Networking.rst, docs/source/PerformanceTesting.rst, docs/source/RunQemuUnittests.rst, docs/source/VirtualEnvMultihost.rst, docs/source/WritingTests/DevelEnvSetup.rst, docs/source/WritingTests/TestProviders.rst, docs/source/cartesian/CartesianConfigReference-KVM-cd_format.rst, docs/source/cartesian/CartesianConfigReference-KVM-drive_format.rst, docs/source/cartesian/CartesianConfigReference-KVM-file_transfer_client.rst, docs/source/cartesian/CartesianConfigReference-KVM-image_format.rst
Complement update changes made by @clebergnu.
=> More doc updates

shared/cfg/guest-os/Windows.cfg
=> Add devcon params to driver_load_stress test case

virttest/qemu_vm.py
=> virttest/qemu_vm.py: Add log for migrate_cancel

virttest/qemu_vm.py
Add new function to get the qemu threads.
ID: 1297288
=> virttest/qemu_vm.py: Add new func get_qemu_threads()

avocado_vt/test.py, shared/control/xfstests.control, virttest/env_process.py, virttest/libvirt_vm.py, virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py, virttest/utils_disk.py, virttest/utils_misc.py, virttest/utils_net.py, virttest/utils_params.py, virttest/utils_test/libguestfs.py, virttest/utils_test/libvirt.py, virttest/utils_test/qemu.py, virttest/virt_vm.py
[v1]  #338 
Changes:
- Fixed wrong rename in autotest imported error.
Please wait for the avocado-framework/avocado#972 to be merged first.
=> Renaming avocado TestNAError exception to TestSkipError [v2]

virttest/utils_test/libvirt.py
Add a function in PoolVolumeTest to create volume by xml file.
=> virttest.utils_test.libvirt: Create volume by xml file.

virttest/utils_misc.py
=> Run 'set' command by shell

virttest/utils_misc.py
sometimes need to get device info with regular expression
e.g virtio-win-*
ID: 1299366
=> update key and val to one option in get_win_disk_vol

virttest/test_setup.py, virttest/utils_misc.py
id: 1204060
Previous PR under virt-test is:
autotest/virt-test#2277
=> virttest/test_setup.py: check 1G hugepage support.

avocado_vt/test.py, selftests/unit/test_test.py
Changes required on the Avocado-VT side to keep it in sync with the proposed changes in: https://github.com/avocado-framework/avocado/pull/986
=> Clebergnu test cleanup sync

virttest/qemu_vm.py
=> qemu_vm: fix typo

virttest/utils_test/qemu.py
Add check Link layer step for rdma migration.
ID: 1253528
=> virttest/utils_test/qemu.py: Add check Link layer for rdma migration

virttest/test_setup.py
1. Not all cases which calling HugePageConfig() have these parameters,
or the 'expected_hugepage_size' is invalid, then so we shoule skip these
two check steps .
2. Fix missing decorator bug.
=> virttest/test_setup: Skip check if parameters are not given or invalid

virttest/utils_test/__init__.py
=> virttest.utils_test: Check ssh key pair before create them

virttest/utils_misc.py
=> utils_misc: Add a function to get a processor list

avocado_vt/loader.py
This patch adjusts the code to work with the new non-View logging
approach.
This needs to be merged together with avocado-framework/avocado#1040
=> avocado_vt: Stop using the removed "View" for logging

virttest/libvirt_xml/devices/filesystem.py
=> libvirt_xml: Implement filesystem XML

shared/cfg/guest-os/Windows.cfg
=> Windows.cfg: add the cfg for case balloon_hotplug.

virttest/qemu_monitor.py, virttest/qemu_vm.py
=> qemu_vm: Add balloon function to VM class

virttest/remote.py, virttest/virt_vm.py
=> virttest: drop duplicate debug info

virttest/utils_misc.py
=> utils_misc: small enhancement for normalize_data_size function

shared/cfg/guest-os/Windows.cfg
=> Windows.cfg: Add windows cfg for case 'driver_load_stress.with_netkvm'.

virttest/qemu_monitor.py, virttest/qemu_vm.py, virttest/utils_test/qemu.py
1. Add set/get migrate_capabilitiy function
2. Add migrate_capabilities parameter for migrate()
=> virttest/qemu_vm.py: Add migrate_capabilities parameter for migrate()

virttest/utils_net.py
1. drop duplicate warning info
2. optimize check device list
=> virttest.utils_net: optimize verify_ip_address_ownership function

shared/cfg/guest-os/Linux/SLES/12.1.x86_64.cfg
=> Add cfg file for SLES 12.1

virttest/utils_misc.py, virttest/utils_test/qemu.py
=> utils_test.qemu: move VM and guest memory basic functions out

virttest/ssh_key.py
Add one function to set local host key to remote known_hosts in order to
avoid of prompting when remote host sshes to local host back.
Fix to add parameter 'prompt' for remote_login function
=> ssh_key: Add one new function and a minor fix

virttest/virt_vm.py
=> utils_test.qemu: fix login timeout when check guest memory

shared/cfg/guest-os/Windows/Win10/i386.cfg, shared/cfg/guest-os/Windows/Win10/x86_64.cfg, shared/cfg/guest-os/Windows/Win2003/i386.cfg, shared/cfg/guest-os/Windows/Win2003/x86_64.cfg, shared/cfg/guest-os/Windows/Win2008/i386.cfg, shared/cfg/guest-os/Windows/Win2008/x86_64.cfg, shared/cfg/guest-os/Windows/Win2012/x86_64.cfg, shared/cfg/guest-os/Windows/Win7/i386.cfg, shared/cfg/guest-os/Windows/Win7/x86_64.cfg, shared/cfg/guest-os/Windows/Win8/i386.cfg, shared/cfg/guest-os/Windows/Win8/x86_64.cfg
=> guest-os/Windows: add some cfg for case balloon_service.

virttest/remote_commander/remote_runner.py
=> Revert right location for /tmp in remote_commander

shared/cfg/guest-hw.cfg, shared/unattended/CentOS-7-0.ks, shared/unattended/RHEL-7-series.ks, shared/unattended/RHEL-7-spice.ks
=> configuration clean up

virttest/ssh_key.py
Searching local known_hosts for the local host key is not a good
solution as it maybe does not exist or does not include the host key
required. The new implementation is to use ssh-keyscan to search the
host key using given host ip, which is much general solution.
=> ssh_key: Fix remote known_hosts file setup

virttest/ovirt.py, virttest/ssh_key.py, virttest/utils_test/libvirt.py, virttest/utils_v2v.py
Please check each commit for detail.
=> several update for v2v tests

shared/scripts/rh_perf_log_hostinfo_script.sh
ID: 1325758
Signed-off-by: Maosheng Zhang <mazhang@redhat.com>
=> Correct command and directory in rh_perf_log_hostinfo_script.sh

virttest/qemu_storage.py
=> Fix TypeError in qemu_storage module on python2.6

virttest/utils_test/libvirt.py
=> utils_test/libvirt: Fix a typo

virttest/utils_test/libvirt.py
Existing connect_libvirtd function has limited patterns to match in the
command output. Those patterns can not satisfy all demands. The fix
provides a new mapping including the patterns and corresponding
responses, which makes the application which calls this function
specify the patterns and responses it needs.
=> libvirt.py: add extra patterns to connect libvirtd

virttest/remote_commander/remote_master.py
=> Add a warning to remote_commander about a hidden pitfall.

virttest/utils_test/libvirt.py
for attaching ide disks to guest
=> Add target option 'ide' to 'attach_disks' function

virttest/utils_test/libvirt.py
Pass through the parameter 'ignore_status' to migration process in order
to get the CmdResult object even when the migration fails instead of
getting a CmdError exception object. The CmdResult including the stderr
will be useful for the caller to parse and search specific messages.
=> utils_test.libvirt: Support to return CmdResult

virttest/utils_test/qemu.py, virttest/virt_vm.py
Fix windows guest report wrong memory size issue
=> hotfix for memory hotplug test in windows guest

virttest/utils_net.py
Regression introduced in commit b0679df699289180287e379834815dcfdbac0f67
=> Fix log message with not enough arguments in utils_net.py

Makefile
=> Makefile: implement "make requirements" target

shared/cfg/guest-os/Windows.cfg
Update shell_client to telnet for rng_bat case
=> Update shell_client to telnet for rng_bat case

test-providers.d/io-github-spiceqa-spice.ini
=> Rename configs for spice-tp.

shared/control/scsi_testsuite_with_patch.control
Apply additional patch to avoid the failures, depend on: https://github.com/autotest/autotest-client-tests/pull/66
ID: 1168787
=> shared.control.scsi_testsuite_with_patch.control: apply additional patch to avoid the failures

test-providers.d/io-github-spiceqa-spice.ini
=> Rename configs for tp-spice.

virttest/guest_agent.py
add guest-sync-delimited guest-set-user-password guest-get-vcpus guest-set-vcpus command  support
id:1328001 1327995 1327990
=> updated more functions that should be supported by qemu guest agent

virttest/qemu_monitor.py, virttest/qemu_vm.py
Signed-off-by: QianqianZhu qizhu@redhat.com
id:1330414
=> Update params for drive-mirror

virttest/utils_net.py
=> utils_net: Fix referenced before assignment error

virttest/qemu_monitor.py, virttest/qemu_vm.py
=> virttest.qemu_monitor.py: Update params for live_snapshot().

virttest/qemu_monitor.py
=> virttest.qemu_monitor: fix sytax error when pick monitor from env

shared/cfg/guest-os/Linux/Fedora/23.ppc64le.cfg
Added guest os config file for Fedora 23 ppc64le guest
=> Added the Fedora 23 ppc64le guest support

virttest/qemu_monitor.py
=> virttest.qemu_monitor: Add event "BALLOON_CHANGE" check for balloon operation.

shared/cfg/guest-os/Linux/RHEL/6.8.cfg, shared/cfg/guest-os/Linux/RHEL/6.8/i386.cfg, shared/cfg/guest-os/Linux/RHEL/6.8/x86_64.cfg
Add guest RHEL.6.8 related cfg files after its release.
ID: 1340343
=> Add guest RHEL.6.8 related cfg files

virttest/remote_commander/remote_master.py, virttest/remote_commander/remote_runner.py
=> Fix passing args & kargs for remote commander.

scripts/cd_hash.py, scripts/download_manager.py, virttest/utils_misc.py
1) virttest.utils_misc: add param for __init__ of LoggingConfig
2) avocado.core.log had been merged into avocado.core.output,
and there's no configure() any more.
so replace it with virttest.utils_misc.LoggingConfig.configure().
3) "View" had been removed for logging,
so let the code to work with the new non-View logging approach.
=> Fix ImportError and AttributeError for both  cmd_hash.py and download_manager.py

virttest/utils_v2v.py
1. update code of building v2v command line
2. add function of check_log for v2v
3. update get_vm_xorg to check if xorg log exists
=> utils_v2v: functional complementarity

virttest/qemu_monitor.py
=> virttest.qemu_monitor: Add cmd "system_powerdown".

virttest/utils_test/qemu.py
Add function to check verifier status
=> check driver verifier status before enable it

virttest/virt_vm.py
=> virttest.virt_vm: optimize wait_for_serial_login function

virttest/remote.py, virttest/utils_test/__init__.py, virttest/virt_vm.py
=> virttest.utils_test: optimize run_file_transfer test

shared/cfg/guest-os/Windows.cfg
=> Update shell_client of driver_load_stress.with_rng to telnet

docs/source/CartesianConfig.rst, docs/source/DownloadableImages.rst, docs/source/HowTestsAreRun.rst, docs/source/InstallWinVirtio.rst, docs/source/ListingGuests.rst, docs/source/Networking.rst, docs/source/RegressionTestFarm.rst, docs/source/WritingTests/DevelEnvSetup.rst
Spend few hours reading the doc and found some nits related to
typo, format, ref, etc., this fix did not include update on the
setup and testing.
=> Fix nits in the doc

virttest/qemu_monitor.py
=> virttest.qemu_monitor: add cmd "closefd".

virttest/remote.py
Check the value of variable before using it.
=> remote: fix logical error in function transfer

virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py
Refer the PR of #588 , I resubmitted it again.
This is part of code change.
=> Qemu support for s390x 1/3 (code change)

shared/cfg/guest-hw.cfg
Refer the PR of #588 , I resubmitted it again.
This is part of guest hw cfg.
=> Qemu support for s390x 2/3 (guest hw cfg) 

shared/cfg/machines.cfg
Refer the PR of #588 , I resubmitted it again.
This is part of machine cfg
=> Qemu support for s390x 3/3 (machine cfg) 

virttest/utils_test/libvirt.py
For 'bandwidth' checking, the output is different betweent RHEL6 and
RHEl7, so we need normalize the date before compare.
And update the checking logic to make it more clear.
=> Bug fix and code update for check_blockjob

virttest/utils_misc.py
Once get the correct file path, break the loop
=> utils_misc: get_bootloader_cfg break the loop

virttest/utils_test/qemu.py
Both session and vm params are used in setup_win_driver_verifier and clear_win_driver_verifier,
drop session, as it can be get with vm
=> Clean dup params

avocado_vt/plugins/vt_joblock.py
When the file content can't be parsed to int, it does not report the
file which caused the problem.
This patch handles the exception parse to int error and raises an
exception containing the lock file.
Signed-off-by: Amador Pahim <apahim@redhat.com>
=> avocado-vt: joblock does not show filename when it fails to read pid

shared/cfg/guest-os/Windows.cfg
Error 0xc0000135 when test with nc
=> Update shell_client of viorng_in_use to telnet

virttest/libvirt_xml/vm_xml.py
Set graphic attributes in guest xml.
Add virsh_instance parameter for function add_security_info.
=> vm_xml: add function set_graphics_attr

virttest/utils_test/__init__.py
1. Fix checking rsa private and public key on remote host instead of
local host because it is to execute the logon guest on remote host
instead of local host
2. Add some ssh option to avoid host key checking
3. Return the command execution result if required
4. Enable to avoid raising an exception when command execution occurs an
error
5. Fix syntax error
=> utils_test: Fix RemoteVMManager

virttest/qemu_monitor.py, virttest/qemu_vm.py
Add pause_block_job and resume_block_job.
Signed-off-by:  Qianqian Zhu qizhu@redhat.com
=> Add pause_block_job and resume_block_job.

shared/cfg/guest-os/Linux.cfg, shared/cfg/guest-os/Windows.cfg
=> shared.cfg: remove duplicate test configuration

virttest/utils_net.py
skip "IndexError" if a interface isn't belong the VM (eg,
virbr0, sit0 and so on). Update IP pool only status of the
interface is up. Add ipv6 support.
=> virttest: rework update_mac_ip_address function

virttest/test_setup.py
This patch addresses below two current issues
1. If SR-IOV VF device creation fails on the KVM host
due to some reason, then current code not throwing any error
messages to users.
2. Return value from sr_iov_setup function is not considered
to validate if SR-IOV VF creation on host succeeded or not.
=> Throw an error if SR-IOV VF device creation on host fails

virttest/guest_agent.py
These functions are about : set-time, get-time, network-interface, fstrim
ID:1327985 1327988 1327992 1327998
=> add new functions for guest agent to use by tp-qemu

virttest/utils_test/__init__.py
1) Add new parameter (shell_prompt & timeout)
2) Change the count ECHO_REQUEST packets (4->5)
3) Update the log
2)&3) refer to RemoteVMManager.check_network()
=> utils_test: update check_dest_vm_network()

virttest/qemu_monitor.py
=> add set/get cache size function for HumanMonitor and QMPMonitor

virttest/utils_test/__init__.py
Introduced by commit b139d5f ("utils_test: update
check_dest_vm_network()").
=> utils_test: Fix undefined name 'ip'

shared/scripts/virtio_console_guest.py
The get_sigio_poll_return currently reports immediately, which might not
be desired as signals are asynchronous and there might be delay between
the action and the signal being emitted. This patch uses hardcoded 5s
interval to wait if the expected signals are emitted or it fails with
details.
This solves a real problem on ppc64le, which sometimes delivers the
POLLOUT after the check. With this patch it works well.
=> shared.scripts.virtio_console_guest: Wait for sigio signals

virttest/utils_test/libvirt.py
Sometimes there is a need to execute some commands when the migration is
in progress. So this enables the capability.
=> utils_test.libvirt: Do other function during migration

virttest/qemu_devices/qdevices.py, virttest/qemu_vm.py
CharDevice class will generate chardev device in qemu from given params dict automatically. But this version still not support hotplug and unplug, this part will finish later.
Thanks,
Xu
=> Add CharDevice class in qdevices

virttest/qemu_storage.py, virttest/utils_misc.py
1. Add option for subcommand convert of qemu-img
2. Add option for image infomation
Signed-off-by: Ping Li pingl@redhat.com
=> Add options for qemu-img

shared/cfg/guest-os/Linux/Ubuntu/16.04-server.s390x.cfg, shared/unattended/Ubuntu-16-04.preseed
Add new 16.04 ubuntu image version for s390x
=> Add new 16.04 ubuntu image version for s390x

.travis.yml, Makefile, requirements-travis-python26.txt, requirements-travis.txt
=> requirements: Use the latest inspektor in travis

virttest/remote_commander/remote_runner.py
As required by the newest version of inspektor and its dependencies.
=> PEP8 style fixes

shared/cfg/guest-os/Windows.cfg
=> Update shell_client of rng test to telnet

virttest/qemu_monitor.py
=> virttest.qemu_monitor.py: Add event "WAKEUP" check for system_wakeup cmd.

shared/unattended/SLES-11-SP2.xml, shared/unattended/SLES-12.xml
Add script to create interface config file and up the interface.
ID:1361416
=> SLES-11-SP2.xml: SLES guest's non-eth0 interface support

shared/cfg/guest-os/Linux/Fedora/24.ppc64le.cfg, shared/unattended/Fedora-24-ppc64le.ks
Added config and kickstart file for Fedora24 ppc64le
guest support
=> Added support for Fedora24 ppc64le guest

virttest/remote.py
Correct log info for scp operation between guest and host.
ID:1361403
=> remote: Correct scp info

shared/cfg/guest-hw.cfg
=> shared.cfg: virtio_rng device params cleanup

virttest/qemu_monitor.py
=> virttest.qemu_monitor: add cmd "transaction".

virttest/utils_net.py, virttest/virt_vm.py
Up to this moment vm.get_address() went through all host's NICs to get
VM's address. This was very time consuming for hosts with several NICs.
It was because each call vm.wait_for_login() always called
vm.get_address(). Wich, in its turn, could be paused for 1 minute for
'wrong' interface.
=> Run vm.get_address() method on certain interfaces.

virttest/utils_test/libvirt.py
Signed-off-by: Harish <harisrir@linux.vnet.ibm.com>
Added code for creating pool xml with wwpn and wwnn
=> Support for adding wwpn while preparing pool

virttest/qemu_vm.py
Added support for s390x virtio-balloon-ccw
#680
=> Added support for s390x virtio-balloon-ccw

shared/cfg/guest-os/Windows.cfg
random.exe cmd could not be  analysis correct with nc
=> Update shell_client of virtio_rng to telnet

setup.py
changed version string to latest released 41.0
=> Fixup: changed version str to latest released 41.0

virttest/utils_v2v.py
Same with input mode 'disk' and 'ova'
=> utils_v2v:add support for input mode 'libvirtxml' on command building

virttest/guest_agent.py
=> virttest.guest_agent.py: Check return value of _sync().

shared/cfg/guest-os/Linux/CentOS/7.2.cfg, shared/cfg/guest-os/Linux/CentOS/7.2/ppc64le.cfg, shared/unattended/CentOS-7-2.ks
Added configurations files to support
centos 7.2 ppc64le guest install.
=> Added support for centos 7.2 ppc64le guest

virttest/utils_net.py
Original code has bug that IndexError  will raise when get IP mac map in windows guest,  this patch will fix the bug.
Thanks,
Xu
=> Fix bug when get IP mac maps in windows guest

selftests/unit/test_qemu_devices.py, shared/cfg/guest-hw.cfg, shared/cfg/machines.cfg, virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py
This is a new version of #657, original #657 can be reopen now because my mistake. sorry for inconvenient.
=> virttest: add Q35 machine type with bridge devices support

virttest/lvm.py
1. Correct function logic
2. Use polling to remove logical volume device
3. When create a new physical volume device and Volume Group, bind them in setup_vg()
Signed-off-by: Ping Li pingl@redhat.com
ID: 1375876
=> lvm: fix logical error

virttest/libvirt_storage.py
=> libvirt_storage: Catch failure when get volume list

virttest/env_process.py
fix typo, destroing ->destroying
=> fix typo in env_process.py file

shared/cfg/machines.cfg
=> shared.cfg: disable q35 legacy guests support

virttest/libvirt_vm.py
Added mammemory option support for virt-install
Added a method to check if a sub-option present in the
virt-install command line for a given parameter
=> Added maxmemory option support for virt-install

virttest/virt_vm.py
=> virt_vm: Add a new function to get VM nic index

shared/cfg/virtio-win.cfg
=> shared.cfg.virtio-win: instead ide with ahci if machine type is q35

virttest/guest_agent.py
=> Add function guest-info

virttest/test_setup.py
Huge pages value is not reflecting in
'/proc/sys/vm/nr_hugepages'
1. While reading the value from nr_hugepages file, new line need
to be handled
2. File open and close need to be handled properly.
This patch addresses the above issues.
Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>
=> Huge pages value is not reflecting in 'nr_hugepages'

shared/cfg/guest-hw.cfg
ID: 1370354
Signed-off-by: Xu Tian xutian@redhat.com
=> shared.cfg: update ovmf boot code file path

virttest/utils_test/qemu/__init__.py, virttest/utils_test/qemu/migration.py
Signed-off-by: Xueqiang Wei xuwei@redhat.com
=> virttest.utils_test.qemu: move migration codes to a single file

virttest/qemu_monitor.py
Signed-off-by: Xueqiang Wei xuwei@redhat.com
=> add set/get_migrate_parameter function for HumanMonitor and QMPMonitor

virttest/utils_misc.py, virttest/utils_test/qemu/__init__.py
virttest.utils_misc:add a function "get_used_mem"
virttest.utils_test.qemu: add a function "get_guest_used_mem"
=> virttest:Optimize code for windows guest balloon test

virttest/libvirt_vm.py
Install package and remove package in guest was not working for
ubuntu, this patch fixes it.
Added get_distro() API to get Guest distro name.
=> Fixup libvirt_vm.py

virttest/libvirt_vm.py
=> libvirt_vm: Fix a typo

test-providers.d/io-github-autotest-qemu.ini, virt.py, virttest/asset.py, virttest/bootstrap.py, virttest/utils_test/__init__.py
=> avocado-vt: update path for multi_host_migration test

virttest/utils_net.py
SpiceQE team net config does not incorporate virbr0
Fix because of backtrace:
```
15:49:09 DEBUG| Removing VM guest NIC ifname t0-ijn0H9 from bridge 
15:49:09 DEBUG| Host does not support OpenVSwitch: Command 'ovs-vswitchd' could not be found in any of the PATH dirs: ['/usr/lib64/qt-3.3/bin', '/bin', '/sbin', '/usr/bin', '/usr/local/sbin', '/root/bin', '/usr/libexec', '/mnt/tests/spice/qe-tests/avocado/scripts', '/mnt/tests/spice/qe-tests/avocado-vt/virttest', '/usr/sbin', '/usr/local/bin']
15:49:09 ERROR| Fail to create qemu command:
15:49:09 ERROR| Original Traceback (most recent call last):
File "/mnt/tests/spice/qe-tests/avocado-vt/virttest/qemu_vm.py", line 2637, in create
self.devices = self.make_create_command()
File …
```
=> fix for netdst parameter left empty

virttest/utils_test/libvirt.py
=> utils_test.libvirt: A new function to check virsh command option

virttest/qemu_storage.py
Support strict mode  for qemu_img compare
ID: 1395550
=> virttest.qemu_storage: Support strict mode  for qemu_img compare

virttest/utils_misc.py
utils_misc:
1.modify pattern for used_mem match of win2008 guest.
Signed-off-by: Aihua Liang  <aliang@redhat.com>
ID:1396326
=> utils_misc:modify used_mem match pattern for win2008 guest

shared/cfg/guest-os/Linux.cfg, shared/cfg/guest-os/Windows.cfg, virttest/qemu_monitor.py, virttest/qemu_vm.py
Signed-off-by: Xiyue Wang xiywang@redhat.com
=> Add API for block commit

virttest/env_process.py, virttest/utils_disk.py
=> Ensure libvirtd service is running before run guestfs tools

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py
Add support for nvdimm device
ID: 1400770
=> Add support for nvdimm device

virttest/utils_test/libvirt.py
mpath pool was not supported in pre_pool method, now add it.
Sign-off by: Yi Sun (lentosun@163.com)
=> Add support for mpath pool in "pre_pool" method

virttest/libvirt_xml/network_xml.py
Signed-off-by: chhu <chhu@redhat.com>
=> network_xml: Raise exception when create network fail

shared/cfg/guest-os/Linux/Fedora/25.ppc64le.cfg
Added guest config for Fedora 25 ppc64le
=> Added support for Fedora 25 ppc64le guest

shared/cfg/guest-os/Windows.cfg
ID: 1380234
Signed-off-by: xiywang <xiywang@redhat.com>
=> Live commit: Add with_stress (heavyload) to Windows.cfg 

shared/unattended/win2008-32-autounattend.xml, shared/unattended/win2008-64-autounattend.xml, shared/unattended/win2008-64-autounattend_ovmf.xml, shared/unattended/win2008-r2-autounattend.xml, shared/unattended/win2008-r2-autounattend_ovmf.xml, shared/unattended/win2012-autounattend.xml, shared/unattended/win2012-autounattend_ovmf.xml, shared/unattended/win2012r2-autounattend.xml, shared/unattended/win2012r2-autounattend_ovmf.xml, shared/unattended/win7-32-autounattend.xml, shared/unattended/win7-64-autounattend.xml, shared/unattended/win7-64-autounattend_ovmf.xml, shared/unattended/win8-32-autounattend.xml, shared/unattended/win8-64-autounattend.xml, shared/unattended/win8-64-autounattend_ovmf.xml
Signed-off-by: Xu Tian xutian@redhat.com
=> update windows guest telnet idle timeout and maxconn

shared/deps/finish/finish.bat
=> shared.deps: fix typo in finish.bat

virttest/utils_misc.py
host_cpu_model equal to the first of cpu_support_model
need to put the more advance cpu model at the beginning.
id: 1403716
=> Update the order of cpu model

virttest/qemu_monitor.py
=> qemu_monitor.py: Add bitmap and live backup command.

virttest/qemu_devices/qcontainer.py
Signed-off-by: Jing Zhao <jinzhao@redhat.com>
ID: 1408783
=> Add the support of multiple root port for q35

virttest/env_process.py, virttest/qemu_vm.py
Fix memory leak when boot multi-VMs, optimized add_memory function. Also include some small bug fix and pep8 fix.
ID: 1406238
=> Fix memory over commit  issue

shared/control/parallel_dd.control
=> fix Parallel dd fails in ppc

virttest/qemu_vm.py
If bus is False ask qemu to decide bus of the virtio port device to avoid qdevice convert false to off when call set_param;
ID:1403664
=> Fix bug virtio port bus is off

virttest/qemu_vm.py
=> virttest.qemu_vm: make parent bus of device configurable

virttest/test_setup.py
Migration test may fail if SMT is not turned off on Power8
machine, so this patch adds support to disable SMT on remote
Power8 machines and to clean up for reverting default setting
=> Turn off SMT in remote machine for Power8

shared/cfg/base.cfg
=> shared.cfg: fix typo in base.cfg

virttest/libvirt_vm.py
Added support for using custom kernel, initrd and
kernel args params to virt-install command line
This will help us booting VM with custom
complied kernel
=> Added virt-install kernel and initrd params support

shared/cfg/guest-os/Linux/RHEL/7.3.cfg, shared/cfg/guest-os/Linux/RHEL/7.3/x86_64.cfg
=> guest-os: Add RHEL.7.3 guest for x86.

virttest/qemu_vm.py
At present, the reboot timeout of VM.reboot funtion was divided into two
parts with the same value (timeout/2), one limited shutdown duration and
the other limited boot duration. It make cause an issue since the two
kinds duration is less likely be averaged. This patch makes reboot
timeout be allotted rationally.
ID: 1404115
=> virttest.qemu_vm: allot timeout rationally within the reboot function

shared/cfg/guest-os/Linux/SLES/12.1.ppc64le.cfg, shared/unattended/SLES-12.xml
Add SLES.12.1.ppc64le relevant configurations.
ID: 1365445
=> unattended: add SLES.12.1.ppc64le relevant configurations

scripts/scan_results.py
add coloured result in the test status info, so the results will be more noticeable.
ID: 1414639
=> avocado-vt: add coloured result in the test status info

shared/cfg/guest-os/Linux/RHEL/7.3/ppc64.cfg, shared/cfg/guest-os/Linux/RHEL/7.3/ppc64le.cfg
Signed-off-by: Qunfang Zhang <qzhang@redhat.com>
ID: 1412434
=> Guest-os: Add RHEL7.3 ppc64 and ppc64le guests.

virttest/nfs.py
=> Fixup nfs.py

avocado_vt/plugins/vt_joblock.py, scripts/github/github_issues.py, scripts/regression.py, shared/deps/run_autotest/boottool.py, shared/deps/serial/windows_support.py, virttest/asset.py, virttest/cartesian_config.py, virttest/libvirt_vm.py, virttest/libvirt_xml/accessors.py, virttest/libvirt_xml/vm_xml.py, virttest/openvswitch.py, virttest/qemu_monitor.py, virttest/remote_commander/remote_runner.py, virttest/ssh_key.py, virttest/test_setup.py, virttest/utils_libvirtd.py, virttest/utils_net.py, virttest/utils_sasl.py, virttest/utils_spice.py, virttest/utils_test/qemu/migration.py, virttest/version.py
=> avocado-vt: fix pep8 error E722

scripts/scan_results.py
a summary for test results is added when using scan_resultts.py
ID: 1416269
=> avocado-vt: add summarise_records to summarse the test records.

virttest/utils_test/libvirt.py
1. iptables have to permit libvirt to perform migration,
so 49152 to 49216 ports have to be enabled in iptables.
2. In remote Power8 machine, SMT have to be turned off.
=> Pre-setup for migration to succeed

virttest/utils_test/libvirt.py
=> utils_test/libvirt: Add a function to set disk attributes

virttest/virsh.py
Signed-off-by: chhu <chhu@redhat.com>
=> virttest.virsh: Add function set_user_password

virttest/virt_vm.py
With it may case the arm guest start hang on a manage screen
=> No need to sendline as the handle_promotes already deal with it

CODING_STYLE
HI All,
Copied coding style file from auotest project to here and some small update,  please help to review. And any comments on it are welcome.
Thanks,
Xu
=> avocado-vt: add coding style file

virttest/env_process.py
=> virttest/env_process: delete useless code

virttest/tests/unattended_install.py
=> Fix auto_ip lookup for unattended_install.py.

virttest/utils_misc.py
=> utils_misc: Get meminfo for all nodes

virttest/utils_net.py
Network testcases require distro specific network configuration files
and the parameters done during tests.
Signed-off-by: Sudeesh John <sudeesh@linux.vnet.ibm.com>
=>  APIs for distro specific VM network configurations

virttest/libvirt_xml/vm_xml.py
Add the class:VMVCPUsXML to handle vcpus xml elements:
<vcpus>
<vcpu id='0' enabled='yes' hotpluggable='no' order='1'/>
<vcpu id='1' enabled='yes' hotpluggable='yes' order='2'/>
<vcpu id='2' enabled='no' hotpluggable='yes' order='3'/>
</vcpus>
Signed-off-by: Chenli Hu chhu@redhat.com
=> vm_xml.py: Add class to handle vcpus xml elements

virttest/utils_misc.py
=> extend the timeout of getting used mem

virttest/utils_params.py
=> virttest.utils_params: remove duplicate elements

virttest/qemu_monitor.py
The `Monitor` object is usually part of `VM`, but at the same time it
requires `VM` in order to be created. This brings circular dependency
which breaks pickle makes it impossible to load the state of the running
VM. There are two ways, one is to clean `Monitor` to not contain `VM`,
which would be cleaner, but it'd require changes to all places where
`Monitor` is created and as this would be a very intrusive change
probably breaking many downstream versions, let's simply fake the VM
object and create a dummy class with the important information (the
name) stored there. It's not nice, but it allows keeping the API
unchanged.
This patch is necessary in order to be able to load the env file with a
running VM, eg. for keep_guest_running feature, or when cleaning-up is
disabled and the test …
=> virttest.qemu_monitor: Avoid circular dependency

virttest/libvirt_xml/vm_xml.py
Signed-off-by: Chenli Hu <chhu@redhat.com>
=> vm_xml.py: Minor changes for VMVCPUSXML

virttest/utils_npiv.py
This utils file is used for npiv related operations, such as:
nodedev create/destroy, mpath pool xml prepare, find online
vhbas, etc.
sign-off by: Yi Sun (lentosun@163.com)
=> Add utils_npiv python file

Makefile, avocado-plugins-vt.spec
This is a collection of fixes and (hopeful) improvements that will affect users of the `avocado-plugins-vt` RPM package.
---
Changes from v1 (#910):
* Dropped commit about qemu subpackage
=> Packaging improvements [v2]

virttest/qemu_vm.py
Added vCPU device based cpu hotplug and unplug functionality
Signed-off-by: Nageswara R Sastry rnsastry@linux.vnet.ibm.com
=> Added vCPU device based cpu hotplug/unplug

virttest/libvirt_xml/vm_xml.py
=> Deal with guest undefine in aarch

virttest/remote.py
sometimes, linux kernel print messages into console
impact match login prompt, send a new line then try
again to avoid this kind of unexpect login timeout.
=> remote: fix unexpect serial login timeout

virttest/nfs.py
Configuring nfs remotely might fail if host key expires,
this patch handles and updates it that avoids offending
of host
=> nfs.py: handling host key verification failure

virttest/ssh_key.py
If test requires to use rsa key to configure ssh_key,
this PR adds support for this.
=> ssh_key: provision to use rsa key for configuring ssh_key setup

virttest/virt_admin.py
=> Modified cmd name client_disconnect to client-disconnect.

virttest/utils_net.py
get_sorted_net_if() and get_net_if() can be used to get network
interfaces of remote machines
=> utils_net: support to check network interfaces of remote machine

virttest/qemu_vm.py, virttest/virt_vm.py
Windows serial session like sokect session will disconnect during guest reboot and no message will print to console, during guest reboot, so reset serial to false to avoid ExpectTimeoutError exception.
ID: 1431921
=> virttest.qemu_vm: fix ExpectTimeoutError in reboot

virttest/bootstrap.py
=> virttest.bootstrap: fix keyerror 'type'

virttest/libvirt_xml/vm_xml.py
This patch enables the support for considering
topology xml change during vcpu changes in xml.
Before this patch xml fails to define incase
of cpu topology present in the xml.
=> Added cpu topology support for vcpu change method

virttest/libvirt_xml/vm_xml.py
=> vm_xml: Correct the xmltreefile name

virttest/tests/unattended_install.py
Tests using nfs setup (setup_local_nfs) expects image to be available in nfs shared path, which have to be taken care manually instead if image is available in data directory it can be copied and used.
=> Unattended install: copy image from data directory to NFS shared directory

shared/control/stress_memory_heavy.control, virttest/env_process.py, virttest/utils_test/__init__.py
Complement to https://github.com/avocado-framework/avocado/pull/1879
(https://github.com/avocado-framework/avocado/pull/1877#discussion_r107629413)
=> Remove *memtotal methods

virttest/utils_misc.py
=> virttest.utils_misc: ignore unicode encode errors

virttest/virsh.py
Added method to support virsh.setvcpu tests
=> Added support for virsh setvcpu

virttest/utils_net.py
It is unreasonable to update MAC address of the virtnet according to address in guest OS one by one. NIC index if virtnet not always equal NIC index in guest OS. This commit skip update virtnet, only update VM address_cache.
=> virttest.utils_net: refactor function update_mac_ip_address

virttest/utils_misc.py
=> virttest.utils_misc: fix unicode decode errors

virttest/utils_net.py, virttest/virt_vm.py
Add step to try to login guest via serial console and update VM address cache if wait for get VM address  failed, so that we can avoid some unexpected  test error.
=> refactor get_address and wait_for_login functions

virttest/qemu_vm.py
We need to test whether SPICE plaintext channels are properly created.
Can you check @will-Do @xutian @Andrei-Stepanov ?
=> qemu_vm: add spice plaintext channel option

virttest/utils_misc.py
Configuring selinux for ubuntu fails the test case, so it is handled to
avoid from API, selinux will remain disabled in ubuntu as it is not supported
or selinux commands will not be available. so selinux can be configured only if is 
available and enabled.
=> utils_misc: Avoid configuring Selinux for Ubuntu

virttest/nfs.py
Add nfs service to firewall to permit mounting nfs directory
from remote machine.
=> Support to ensure firewall to permit nfs service

selftests/unit/test_qemu_devices.py, virttest/qemu_devices/qbuses.py, virttest/qemu_devices/qcontainer.py
Add prefix 0x for hex type address, and increased pci-bridge numbers from 20 to 31
=> Fix address type convert issue

virttest/utils_test/libvirt.py
=> Fixup the make partition step when create disk pool

virttest/virt_vm.py
=> virttest.virt_vm: fix typo

virttest/utils_test/qemu/__init__.py
=> virttest.utils_test.qemu: Fix typo in setup_win_driver_verifier

virttest/virt_vm.py
=> virttest.virt_vm: fix exception not catch issue

avocado_vt/test.py
Avocado-vt supports "params" and "avocado_params". In recent Avocado the
"params" is a property therefor we can use super(VirtTest).params to get
to it's value, but on 36lts the "params" is variable stored during
__init__. This was workaround previously by set of hacks, this version
replaces it with storing the values in `self.__params` and
`self.__avocado_params` during `__init__` making the whole process
easier to follow (and hopefully with less bugs in it).
=> avocado_vt: Fix the params handling

docs/source/WritingTests/WritingSimpleTests.rst
And, also fix the list index number re-count problem.
=> docs: Add test status description section for writing simple tests

virttest/qemu_vm.py
This patch makes checking VM's shutdown event by listening the "RESET"
event from QMP (if supported) as the default way in the reboot
function.
ID: 1439059
=> qemu_vm: enhancement of the reboot function

shared/cfg/guest-os/Windows.cfg, shared/cfg/guest-os/Windows/Win10/i386.cfg, shared/cfg/guest-os/Windows/Win10/x86_64.cfg, shared/cfg/guest-os/Windows/Win2012/x86_64.cfg, shared/cfg/guest-os/Windows/Win2016/x86_64.cfg, shared/cfg/guest-os/Windows/Win8/i386.cfg, shared/cfg/guest-os/Windows/Win8/x86_64.cfg
shared.cfg.guest-os:
1.add iso installation label "check_block_size.4096/512_512" in windows.cfg
2.add iso installation label "check_block_size" for win8/10/2012/2016
Signed-off-by:Aihua Liang<aliang@redhat.com>
ID:1134252
=> Windows:add iso installation lable "check_block_size"

virttest/qemu_qtree.py
=> virttest.qemu_qtree: fix index issue when parse_info_qtree on qemu-kvm

virttest/utils_spice.py
Increasing timeout for epel install as sometimes it times out. 
Reviewed By: Swapna Krishnan <skrishna@redhat.com>
=> utils_spice: Increase timeout for epel install

virttest/qemu_monitor.py
=> qemu_monitor: specify vm name when print monitor debug log.

virttest/libvirt_vm.py
pm-utils is not common in all distributions in
default repo and fails to install and breaks the flow
of guest agent test cases, even if we do not require
functionalities given by pm-utils.
So, added ignore_status param for package installation
method and and updated the pm-utils install in guest agent
setup accordingly.
=> Fixup: pm-utils install failure for guest agent tests

shared/cfg/guest-os/Linux/SLES/12.2.x86_64.cfg
Add support for SLES12 sp2 guest (x86_64)
id:1459763
=> Add support for SLES12 sp2 guest (x86_64)

virttest/utils_test/libvirt.py
With this change, we can define a secret with create_secret()
and set base64 encoded password to it with set_secret_pwd()
Sign-offed by: Yi Sun(yisun@redhat.com)
=> Add secret operation in libvirt.py

virttest/libvirt_vm.py
This patch enables hugepages option of virt-install to start the guest
with HP and set HPs in host required by guest so that we can use
unattended_install to boot guest with hugepage backed by setting param
"hugepage = yes" in cfg.
=> libvirt_vm: enablement to boot hugepage backed guest

virttest/qemu_monitor.py, virttest/qemu_vm.py
=> qemu_vm: add backing_file option for block_stream.

virttest/env_process.py, virttest/test_setup.py
Added support for enabling libvirtd debug log
per test based on the user params.
Usage:
Set "enable_libvirtd_debug_log = True" param in test config inorder
to capture libvirtd log into a file, bydefault it sets the log level to '1'
which is debug, same can be controlled by param, "libvirtd_debug_level" and
by default it stores as libvirtd.log into specific test debug directory
and the same can be controlled by param, "libvirtd_debug_file"
E.g:-
libvirtd_debug_level = 3
libvirtd_debug_file = "/tmp/libvirtd.log"
=> Added support to enable libvirtd log for tests

shared/cfg/guest-os/Linux/OpenSUSE/42.2.x86_64.cfg, shared/unattended/OpenSUSE-Leap-42.2.xml
Signed-off-by: Lin Ma <lma@suse.com>
=> Add OpenSUSE Leap 42.2 guest and OpenSUSE-Leap-42.2.xml

shared/cfg/guest-os/Linux/RHEL/7.3/aarch64.cfg
=> Guest-OS: add RHEL 7.3 for aarch64

virttest/utils_misc.py
Based on the card name pci devices in host or hotplugged devices in
guest, PCI id and interfaces can be retrieved using these APIs
=> utils_misc: APIs to get pci and interface info from host/guest

virttest/qemu_monitor.py, virttest/qemu_vm.py
=> block_stream: Add kwargs for later expansion.

virttest/utils_net.py
Enable APIs to provide distro specific network config file and create network
script in host and guest
=> utils_net: enable get_network_cfg_file() and create_network_script() for host

virttest/tests/unattended_install.py
Now, the iso images are placed in `data_dir` of avocado-vt. However,
the code of copying to `local_dir` finds these images in `test.bindir`,
which is `root_dir` of avocado-vt, then the following error would be
reported:
IOError: [Errno 2] No such file or directory:
'/usr/share/avocado-plugins-vt/isos/linux/RHEL7.3-Server-x86_64.iso'
This patch is going to fix the above issue.
ID: 1470534
=> unattended_install: fix bug of copying iso image to local_dir

virttest/libvirt_vm.py
This patch enables option for virt-install to start the guest
with Numa nodes using unattended_install and execute other tests
by setting param "numa = yes" in cfg.
=> libvirt_vm: enablement to boot guest with Numa nodes

virttest/test_setup.py
Removed redundant codes and made some cleanups to refactor sriov_setup()
and sriov_cleanup() methods
=> test_setup: refactor sriov_setup() and sriov_cleanup()

virttest/utils_config.py
=> Update the libvirt-guests configuration file.

requirements-travis.txt, selftests/checkall
Fix the command usage after inspecktor package updated.
=> selftests: fix inspekt command error

virttest/utils_net.py
Handle create_network_script() returns without creating network script
file if it already exists in hosts/guests
=> utils_net: avoid creating network script if it already exists

virttest/libvirt_storage.py
libvirt_storage: Add support of pool_autostart, to get
pool autostart status
=> Add support of pool_autostart

shared/cfg/guest-hw.cfg, virttest/test_setup.py
Add support to boot guest with pf/vf on x86_64 host.
ID: 1468525, 1468528
=> Add support to boot guest with pf/vf on x86_64 host.

virttest/virsh.py
=> Add perf function in virttest/perf.py

virttest/utils_test/__init__.py
Added framework support to run avocado tests inside guest
=> RFC: Added support to run avocado tests inside guest

virttest/test_setup.py
Improve sr_iov_setup process to make sure the driver is installed.
ID: 1488321
=> Improve the process of sr_iov_setup

virttest/libvirt_vm.py, virttest/qemu_vm.py, virttest/utils_net.py, virttest/virt_vm.py
This patch set is going to make the login related functionalities more robust.
=> Enhancement of login related functionalities

shared/cfg/guest-os/Linux/RHEL.cfg
=> block_hotplug.block_scsi: it's supported from Host_RHEL6.6

virttest/qemu_devices/qcontainer.py
BZ:1486598
qcontainer:modify to choose right scsi_hba for scsi device on s390x platform
Signed-off-by: Xujun Ma <xuma@redhat.com>
=> qcontainer:modify to choose right scsi_hba for scsi device on s390x platform

virttest/utils_test/__init__.py
id: 1490280
Signed-off-by: Sitong Liu siliu@redhat.com
=> utils_test.__init__: Correct time format error

shared/cfg/base.cfg, virttest/env_process.py, virttest/utils_misc.py, virttest/utils_test/qemu/__init__.py
Modified verify_host_dmesg method to accomodate
guest dmesg verification aswell.
=> Added support for guest dmesg verify

virttest/virt_vm.py
Added VM method to verify dmesg
=> Added method to verify VM dmesg

virttest/utils_test/libvirt.py
selinux configuration on ubuntu fails and interrupts the testcases
so consider it to avoid it for ubuntu. For negative scenarios to be
enabled 'enable_selinux_ubuntu' param can be set
=> libvirt: configure selinux for nfs on distro other than ubuntu

backends/v2v/cfg/convert_source.cfg
Support vmware esx6.5 branch by v2v
Signed-off-by: Kun Wei <kuwei@redhat.com>
=> Add esx6.5 branch by v2v

virttest/utils_misc.py
Add method to get numa nodes with memory
=> Add method to get numa nodes with memory

virttest/utils_conn.py
Qemu provides a native TLS support now. This change is to add this
support based on existing implementation for libvirt supporting TLS. The
main changes are the different file naming style comparing to libvirt,
such as 'ca-cert.pem' instead of 'cacert.pem'. Another change is some
unnecessary server configrations are removed.
=> virttest.utils_conn: Add qemu native TLS support

virttest/qemu_vm.py
get reboottimeout value from config file
id:1469050
Signed-off-by: Xiangchun Fu xfu@redhat.com
=>  virttest.qemu_vm:add 'reboottime' option support

virttest/test_setup.py
1. Remove dmesg info in log
2. Remove unused option when modprobe driver
ID: 1496365
=> virttest.test_setup: Improve log info for sr_iov test

shared/cfg/guest-os/Linux/RHEL/7.4.cfg, shared/cfg/guest-os/Linux/RHEL/7.4/ppc64.cfg, shared/cfg/guest-os/Linux/RHEL/7.4/ppc64le.cfg, shared/cfg/guest-os/Linux/RHEL/7.4/x86_64.cfg
=> Guest-os: Add RHEL7.4 guest os configuration

virttest/utils_conn.py
Currently TLS connection setup CA server on remote host and CA client on
local host which is to enable the connenction from local host to remote
host. Now there is a need to connect from remote host to local host
using TLS connection. And the expected result is a failure due to no CA
client setup on remote host. So the fix is to only setup CA server on
local host for now.
Signed-off-by: Dan Zheng dzheng@redhat.com
=> virttest.utils_conn: Add CA server setup locally

virttest/qemu_vm.py, virttest/test_setup.py
Update test_setup.py to set vf only when test vf cases.
ID: 1489264
=> virttest.test_setup: Set vf only when test vf cases

virttest/utils_test/libvirt.py
=> enable source file replacement in set_vm_disk method

virttest/utils_conn.py
Roughly remove the authorized_keys on server is too rude and even wrong
when it has been existing before testing. So this is to correct the
recover method to this file by backing up and restore.
=> virttest.utils_conn: Correct recovery of SSH

virttest/utils_test/qemu/__init__.py
Before using virtio-win driver, it's better to check if it's installed and running. So create a function to check it basically.
ID: 1455810
=> virttest.utils_test.qemu: check virtio-win drivers' state for windows guest

virttest/utils_misc.py
Different qemu versions may have different cmd params, we'll need
to get qemu versions' info. This commit add get_qemu_version and
compare_qemu_version, and use them in get_image_info and
get_image_snapshot to avoid qemu lock introduced by rfe bz1378241.
=> Add qemu version methods in virttest/utils_misc

virttest/libvirt_xml/nodedev_xml.py
Add xml implementation for product infor and max
supported vfs of sriov pci device.
=> Add xml implementation for product info and max vfs

virttest/utils_test/libvirt.py
ensure that changed had been written back
=> add diskxml.xmltreefile.write() at end of create_disk_xml

virttest/libvirt_xml/devices/hostdev.py
Add support for sgio, rawio, readonly, shareable attributes.
Add support for iscsi protocol xml.
Add support for authentication xml.
=> Fully cover xml attributes for scsi hostdev

virttest/utils_hotplug.py
1. Removed autotest dependancy for utils.
2. Multiple fixups for affinity check on output
format parsing.
3. Skip guest vcpu check for paused vms.
=> Multiple fixup for affinity and guest vcpu checks

virttest/utils_config.py
associated elements in san lock config are added
=> Add libvirt san lock config class

virttest/qemu_vm.py
define is_panicked() to check if the guest is panicked.
id:1457076
=> qemu_vm.py: add "is_panicked()" in qemu vm class

virttest/libvirt_xml/capability_xml.py
Add method to get cells with memory
=> Add method to get cells with memory

virttest/libvirt_vm.py
Monitor interface helps to achieve qemu monitor commands to be
executed from libvirt VM object, generic tests from libvirt and
qemu repositories can use it seamlessly.
=> libvirt_vm: Interface for qemu monitor using libvirt VM

virttest/iscsi.py
Suppose there are 2 iscsi, but the case just want to cleanup one
of them. To use confirm=True will break the other iscsi config.
=> iscsi: limit to cleanup all

virttest/qemu_storage.py
=> qemu_storage: updated to display qemu-img check cmd and its output

virttest/libvirt_xml/vm_xml.py
it also affect 1 usage in tp-libvirt so need to merge them all at the same time
=> update for further usage in bandwidth value get

virttest/libvirt_xml/vm_xml.py
This patch refactors set_cpu_mode method to adopt to
VMCPUXML and added support to modify various cpu xml
tags and add support 'check' cpu attribute.
=> Refactor set_cpu_mode method and add new cpuxml attribute

virttest/utils_hotplug.py
This patch adds method to get parsed cpustats output of
given guest domain.
=> Add method to get parsed cpustats output of guest

virttest/libvirt_vm.py
Probability, the repo local database is broken.
Try to clean it and re-install
=> Update for package installation on guest

backends/v2v/cfg/convert_destination.cfg
Just update some password
Signed-off-by: weikunzz <kuwei@redhat.com>
=> Update v2v some resource host possword

virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py
Three more fixes to improve situation (not only) for s390x machines.
=> misc fixes (not only) related to s390x

virttest/remote.py
this patch enable ssh through specific interface, when u have more than
one interface u can specify specific interface to ssh, and it remove
pep8 errors
Signed-off-by: prudhvi <mprudhvi@linux.vnet.ibm.com>
=> ssh through specific interface

avocado_vt/test.py, selftests/unit/unittest_data/testcfg.huge/guest-os.cfg, shared/cfg/guest-os/Linux.cfg, shared/cfg/guest-os/Linux/Ubuntu.cfg, shared/cfg/machines.cfg, virttest/qemu_vm.py, virttest/staging/utils_cgroup.py, virttest/staging/utils_memory.py
Most fixes are generic and usual related to outdated sources.
=> Bunch of fixes found while running all tests on s390x

virttest/bootstrap.py
Currently we can only distinguish between host and guest by using either
major or minor release version (where Host strings have prefixes) or
architecture (which is prefixedd by Host_arch_). Anyway still filters
like "no Fedora" effectively disable the test from being executed from
Fedora host even when using RHEL guest and vice versa.
This patch adds variant (not prefix!) "Host" to host os name and "Guest"
to guest os name. This change itself won't affect any existing code, but
it will allow writing "no Host.$distro" and "no Guest.$distro"
filters, which will only be applied on Host or Guest.
=> virttest: Distinguish between Host and Guest OS

virttest/libvirt_xml/vm_xml.py
1) add boot manipulations to VMXML class
2) modify VMOSXML to add more os options
3) modify VMFeaturesXML to add smm option
4) fixup the bad first argument given to super()
=> vm_xml: Add manipulations for guest boot options

virttest/utils_net.py
change to character translation for re.findall
id:1510767
=> set_link.py: get correct ipv4 ip for guest

virttest/libvirt_xml/network_xml.py
Add hostdev network xml implementation.
=> Add hostdev network xml implementation

shared/cfg/guest-os/Linux/SLES/12.3.x86_64.cfg
=> guest-os: Add support for SLES12 sp3 guest(x86_64)

virttest/utils_test/libvirt.py
As part of migration test, guest should be pingable before and after
migration, so introduced ping_vm() API to be leveraged by the
migration tests
=> utils_test/libvirt: add API for pinging VM before and after migration

virttest/utils_misc.py
Try to use the better way to get the info
=> Update get_image_info function

virttest/libvirt_vm.py, virttest/virsh.py
=> Add support of new virsh command domfsinfo

virttest/staging/lv_utils.py
Provide mpath naming convention between lvname and mpath name
=> lv_utils: Add manipulations to mpath

virttest/libvirt_vm.py
reuse utils_package for install/remove packages and remove existing
redundant code.
=> libvirt_vm: use utils_package for package installation

virttest/utils_misc.py
/usr/lib/libvirt/cpu_map.xml give each model definition.
One model is one set of features.
Add one function to get features for one specific CPU model
=> utils_misc: add function to get feature list for one CPU model

virttest/iscsi.py
Tests gets interrupted if iscsi target and initiator packages are not available,
handle it to install the package and proceed.
=> iscsi: Handle create_iSCSI() to install iscsi target and initiator packages

virttest/libvirt_vm.py, virttest/qemu_vm.py, virttest/virt_vm.py, virttest/vt_console.py
=> serial: rework serial user interfaces

virttest/utils_disk.py
=> GuestFSModiDisk: let guestfs set variable backends.

scripts/github/github_issues.py, scripts/koji_pkgspec.py, selftests/unit/test_propcan.py, shared/deps/run_autotest/boottool.py, virttest/build_helper.py, virttest/cartesian_config.py, virttest/guest_agent.py, virttest/http_server.py, virttest/installer.py, virttest/libvirt_vm.py, virttest/libvirt_xml/sysinfo_xml.py, virttest/lvsb_base.py, virttest/qemu_monitor.py, virttest/staging/utils_cgroup.py, virttest/staging/utils_koji.py, virttest/video_maker.py, virttest/virt_vm.py
and use 'xx' in dict alternatively
replace dict.has_key('xx') with 'xx' in dict
=> Python 3: replace dict.has_key() function

virttest/utils_package.py
Probability, the repo local database is broken.
Try to clean it and re-install
=> Update for package installation

virttest/vt_console.py
=> vt_console: add set_linesep

avocado_vt/test.py, virt.py, virttest/env_process.py, virttest/rss_client.py, virttest/utils_misc.py
Converts raise E, V to raise E(V),
and raise E, V, T to six.reraise(E, V, T)
=> Python 3: To translate raise

virttest/tests/unattended_install.py, virttest/utils_disk.py
=> Python 3: Replace octal numbers

virttest/env_process.py, virttest/ip_sniffing.py, virttest/lvsb.py, virttest/ovirt.py, virttest/passfd.py, virttest/passfd_setup.py, virttest/qemu_devices/qbuses.py, virttest/qemu_devices/qdevices.py, virttest/remote_build.py, virttest/remote_commander/messenger.py, virttest/remote_commander/remote_master.py, virttest/remote_commander/remote_runner.py, virttest/scheduler.py, virttest/staging/__init__.py, virttest/step_editor.py, virttest/tests/__init__.py, virttest/utils_env.py, virttest/utils_misc.py, virttest/utils_net.py, virttest/utils_npiv.py, virttest/utils_test/qemu/__init__.py, virttest/utils_v2v.py, virttest/virt_vm.py
Fix encountered relative import issues.
=> Python 3: Fix relative import issues

virttest/env_process.py, virttest/ip_sniffing.py, virttest/lvsb.py, virttest/ovirt.py, virttest/passfd.py, virttest/passfd_setup.py, virttest/qemu_devices/qbuses.py, virttest/qemu_devices/qdevices.py, virttest/remote_build.py, virttest/remote_commander/messenger.py, virttest/remote_commander/remote_master.py, virttest/remote_commander/remote_runner.py, virttest/scheduler.py, virttest/staging/__init__.py, virttest/step_editor.py, virttest/tests/__init__.py, virttest/utils_env.py, virttest/utils_misc.py, virttest/utils_net.py, virttest/utils_npiv.py, virttest/utils_test/qemu/__init__.py, virttest/utils_v2v.py, virttest/virt_vm.py
Reverts avocado-framework/avocado-vt#1381
=> Revert "Python 3: Fix relative import issues"

docs/source/conf.py, scripts/regression.py, shared/scripts/cmd_runner.py, virttest/nfs.py, virttest/qemu_vm.py, virttest/staging/utils_cgroup.py, virttest/utils_conn.py, virttest/utils_misc.py, virttest/utils_net.py, virttest/utils_test/__init__.py, virttest/utils_test/libguestfs.py
=> Python 3: Replace commands module to avocado.util.process

virttest/asset.py, virttest/libvirt_xml/devices/base.py, virttest/libvirt_xml/nwfilter_protocols/base.py, virttest/remote_commander/messenger.py, virttest/unittest_utils/mock.py, virttest/utils_config.py, virttest/xml_utils.py
=> Python 3: Update StringIO()

selftests/unit/test_cartesian_config.py, shared/scripts/virtio_console_guest.py, virttest/base_installer.py, virttest/cartesian_config.py, virttest/http_server.py, virttest/iscsi.py, virttest/openvswitch.py, virttest/postprocess_iozone.py, virttest/ppm_utils.py, virttest/qemu_devices/qdevices.py, virttest/qemu_monitor.py, virttest/qemu_vm.py, virttest/test_setup.py, virttest/tests/unattended_install.py, virttest/unittest_utils/mock.py, virttest/utils_misc.py, virttest/utils_net.py, virttest/utils_test/libvirt.py, virttest/utils_test/qemu/migration.py
=> Python 3: Update map(), filter(), zip()

shared/control/install_pkg.control, shared/control/stress_memory_heavy.control, shared/control/xfstests.control, virt.py, virttest/utils_test/qemu/migration.py
=> Python 3: Remove parts of autotest

virttest/staging/backports/simplejson/decoder.py
=> Python 3: Removes implicit tuple parameter unpacking

avocado_vt/test.py, scripts/github/pulls_applied.py, scripts/regression.py, shared/scripts/virtio_console_guest.py, virt.py, virttest/cartesian_config.py, virttest/element_path.py, virttest/element_tree.py, virttest/ovs_utils.py, virttest/postprocess_iozone.py, virttest/remote_commander/remote_interface.py, virttest/remote_commander/remote_master.py, virttest/remote_commander/remote_runner.py, virttest/staging/backports/simplejson/decoder.py, virttest/unittest_utils/mock.py, virttest/utils_config.py, virttest/utils_gdb.py, virttest/utils_libguestfs.py, virttest/utils_misc.py, virttest/utils_npiv.py, virttest/utils_test/libvirt.py, virttest/video_maker.py
This optional fixer performs several transformations
that make Python code more idiomatic.
=> Python 3: Update codes style

avocado_vt/test.py, scripts/github/pulls_applied.py, scripts/regression.py, shared/scripts/virtio_console_guest.py, virt.py, virttest/cartesian_config.py, virttest/element_path.py, virttest/element_tree.py, virttest/ovs_utils.py, virttest/postprocess_iozone.py, virttest/remote_commander/remote_interface.py, virttest/remote_commander/remote_master.py, virttest/remote_commander/remote_runner.py, virttest/staging/backports/simplejson/decoder.py, virttest/unittest_utils/mock.py, virttest/utils_config.py, virttest/utils_gdb.py, virttest/utils_libguestfs.py, virttest/utils_misc.py, virttest/utils_npiv.py, virttest/utils_test/libvirt.py, virttest/video_maker.py
Reverts avocado-framework/avocado-vt#1400
=> Revert "Python 3: Update codes style"

selftests/unit/test_libvirt_xml.py, virttest/staging/backports/simplejson/decoder.py, virttest/utils_net.py
=> Python 3: Renames unicode to str

virttest/funcatexit.py
=> Python 3: Fixes function attributes that have been renamed

.travis.yml
=> Python 3: Add Travis-CI checks (allowing failure)

virttest/utils_net.py
Fix the issue introduced by commit da933a3.
ID: 1554655
=> utils_net: Fix the issue of arping

selftests/unit/test_libvirt_xml.py, virttest/libvirt_xml/devices/redirdev.py, virttest/test_setup.py
=> Python 3: Converts the old metaclass with six

shared/scripts/ksm_overcommit_guest.py, shared/scripts/virtio_console_guest.py, virttest/remote_commander/remote_runner.py, virttest/staging/backports/collections/namedtuple.py
=> Python 3: Converts the exec statement to the exec() function

selftests/unit/test_propcan.py, virttest/staging/backports/simplejson/encoder.py
=> Python 3: Replace long to int

shared/scripts/ksm_overcommit_guest.py, shared/scripts/virtio_console_guest.py, virttest/remote_commander/remote_runner.py, virttest/staging/backports/collections/namedtuple.py
Reverts avocado-framework/avocado-vt#1401
=> Revert "Python 3: Converts the exec statement to the exec() function"

virttest/qemu_devices/qdevices.py
=> Python 3: Fixes dictionary iteration methods(2nd)

virttest/virsh.py
=> virsh.py: Fix the regex error

virttest/env_process.py
Modify 'svirt_install' to 'svirt_virt_install' according to the
cfg changed in the tp-libvirt.
Signed-off-by: yafu <yafu@redhat.com>
=>  Modify install type 'svirt_install' to 'svirt_virt_install'

virttest/xml_utils.py
not supported in python3
use open()function to replace previous functions provided by file
=> Python 3: Remove file dependence in xml_utils.py since file as class is removed

selftests/unit/test_xml_utils.py, shared/scripts/check_cpu_flag.py, shared/scripts/virtio_console_guest.py, virttest/asset.py, virttest/test_setup.py, virttest/utils_misc.py, virttest/utils_net.py
=> Python 3: Replace file() with open()

shared/scripts/ksm_overcommit_guest.py, shared/scripts/virtio_console_guest.py, virttest/remote_commander/remote_runner.py, virttest/staging/backports/collections/namedtuple.py
=> Python 3: Converts the exec statement to the exec() function(2nd)

virttest/virsh.py
=> snapshot_info: Fix the wrong equation

selftests/unit/test_qemu_devices.py
=> test_qemu_devices: fixed pylint check error E0632

virttest/env_process.py, virttest/ip_sniffing.py, virttest/lvsb.py, virttest/ovirt.py, virttest/passfd.py, virttest/passfd_setup.py, virttest/remote_build.py, virttest/remote_commander/messenger.py, virttest/remote_commander/remote_master.py, virttest/remote_commander/remote_runner.py, virttest/scheduler.py, virttest/staging/__init__.py, virttest/step_editor.py, virttest/tests/__init__.py, virttest/utils_env.py, virttest/utils_misc.py, virttest/utils_net.py, virttest/utils_npiv.py, virttest/utils_test/qemu/__init__.py, virttest/utils_v2v.py, virttest/virt_vm.py
Fix encountered relative import issues.
=> [RESEND] Python 3: Fix relative import issues

scripts/github/cache_populate.py, scripts/github/example.py, scripts/github/label_issues.py, scripts/github/pulls_applied.py, scripts/github/stale_pulls.py, scripts/github/unassigned_issues.py, virttest/unittest_utils/mock.py
=> Python 3: Fix the __future__ line

virttest/utils_selinux.py
Reverts avocado-framework/avocado-vt#1438
=> Revert "Python 3 : fix bootstrap issue due to process.run return bytes instea…"

virttest/virt_vm.py
=> Virt_vm: add macvtap device check for verify_dmesg.

virttest/lvsb_base.py
=> Python 3: one dict.haskey fixer

scripts/perf.conf, shared/scripts/pktgen_perf.sh
pktgen_perf test case.
ID: 1470602
=> Add script pktgen_perf.sh and update perf.conf file for performance

virttest/staging/backports/simplejson/ordered_dict.py, virttest/utils_env.py, virttest/utils_params.py
=> Python 3: Replace UserDict module to collections.UserDict

virttest/element_tree.py, virttest/storage.py, virttest/utils_misc.py
=> Python 3: cmp function is removed in Python3

virttest/utils_test/qemu/__init__.py
add session for setup_win_driver_verifier and encapsulate it.
id:1557143
=> utils_test.qemu: add session for setup_win_driver_verifier

virttest/logging_manager.py, virttest/utils_misc.py
=> Python 3: port autotest.client.utils.AsyncJob()

virttest/utils_v2v.py
get parameters (log pattern to search for, log is expected or not)
directly from config file.For expected message list, return False if any
message is NOT shown.For not expected message list, return False if any
message is shown.
=> utils_v2v:update check_log function

docs/source/conf.py, scripts/regression.py, shared/scripts/cmd_runner.py, virttest/nfs.py, virttest/staging/utils_cgroup.py, virttest/utils_conn.py, virttest/utils_net.py, virttest/utils_test/__init__.py, virttest/utils_test/libguestfs.py
=> Python 3: Update commands module

virttest/libvirt_xml/devices/interface.py, virttest/libvirt_xml/vm_xml.py, virttest/utils_test/libvirt.py
1. Add property for interface xml
2. Update get_iface_by_mac by getting more values for iface
3. Add new func for vm iface modify and vm boot order change
=> Add func for interface test

virttest/libvirt_vm.py
console_manager should update the console status
=> cleanup_serial_console: Update for console manager

virttest/utils_test/qemu/__init__.py
=> Added test as an init param for class GuestSuspend

virttest/asset.py, virttest/compat_52lts.py, virttest/http_server.py, virttest/staging/utils_koji.py, virttest/utils_test/__init__.py, virttest/virsh.py
1. Add a new method to do the change
2. Decodes the url bytes result to str
=> Python 3: Decodes bytes to str

.travis.yml
=> Travis.yaml: Add filter W605

.travis.yml
=> Travis.yaml: Disable W605 for style

virttest/remote.py, virttest/virsh.py
=> Python 3: Force stdout or stderror to be text(2nd)

virttest/libvirt_xml/vm_xml.py
=> Add hpt_resizing for 'features' tag

virttest/utils_test/__init__.py
As part of the utilities to run Autotest tests on guests, Avocado-VT
will copy Autotest libraries to the guest. Besides those stock
Autotest libraries, it will overwrite Autotest's own version of
boottool.py.
This causes problem on most guests because now Avocado-VT (including
its own boottool.py) require the six library, which won't be present
on most guests.
Since the reason for doing so is a workaround for specific (and old)
packaged versions of Autotest, let disable it by default.  This is
candidate for complete removal, though.
Reference: https://github.com/avocado-framework/avocado-vt/issues/1508
=> run_autotest(): make overwriting of boottool.py optional and disabled

virttest/vt_console.py
=> vt_console: add status_test_command and read_up_to_prompt

virttest/utils_conn.py
Actually ConnLoginError need two parameters,but one only given
=> fix Type_error issue in initializing ConnLoginError

virttest/env_process.py
It will check all the images at one time in image check
procedure, then delete images need to be remove.
This will solve problems occurred when checking and removing
chained images one by one.
id: 1560377
=> env_process: Separate image check and remove in postprocess

virttest/element_tree.py
=>  Python 3: Update deprecated string.join

avocado_vt/test.py
=> Python 3: Remove autotest(2nd)

virttest/virt_vm.py
=> virt_vm: Fix NameError in funtion wait_for_login

virttest/test_setup.py
Introduced function to enable the link for VF's of SR-IOV Mellanox InfiniBand Controller.
We need to perform specific steps in-order to enable the link for the VF's in-case of the InfiniBand Controller.
=> Introduced function to enable the link for VF's of SR-IOV Mellanox InfiniBand Controller

shared/cfg/guest-os/Linux/RHEL/7.5.cfg, shared/cfg/guest-os/Linux/RHEL/7.5/ppc64.cfg, shared/cfg/guest-os/Linux/RHEL/7.5/ppc64le.cfg, shared/cfg/guest-os/Linux/RHEL/7.5/s390x.cfg, shared/cfg/guest-os/Linux/RHEL/7.5/x86_64.cfg
=> guest-os: Add RHEL7.5 guest os configuration

virttest/xml_utils.py
Add tell function into TempXMLFile under xml_utils
=> Add tell function into TempXMLFile

virttest/qemu_vm.py
=> qemu_vm: cancel test if provided mem is less than min_mem

shared/cfg/guest-os/Windows/Win10/i386.cfg, shared/cfg/guest-os/Windows/Win10/x86_64.cfg, shared/cfg/guest-os/Windows/Win2008/i386.cfg, shared/cfg/guest-os/Windows/Win2008/x86_64.cfg, shared/cfg/guest-os/Windows/Win2012/x86_64.cfg, shared/cfg/guest-os/Windows/Win2016/x86_64.cfg, shared/cfg/guest-os/Windows/Win7/i386.cfg, shared/cfg/guest-os/Windows/Win7/x86_64.cfg, shared/cfg/guest-os/Windows/Win8/i386.cfg, shared/cfg/guest-os/Windows/Win8/x86_64.cfg
balloon_service: Add balloon service command
1.Add stop_balloon_service command for all windows guests;
2.Add all balloon serivce command to balloon_hotplug case.
ID: 1456110,1456106, 1456109
=> balloon_service: Add balloon service command

shared/deps/serial/VirtIoChannel_guest_send_receive.py, shared/deps/serial/serial_host_send_receive.py, virttest/ppm_utils.py, virttest/utils_net.py
=> Python 3: struct.pack() update

avocado_vt/options.py, etc/avocado/conf.d/vt.conf
Please see the actual changes in commit messages.
=> avocado_vt: Few options related fixes

virttest/base_installer.py
The test's "srcdir" property is deprecated and is planned to be
removed no later than May 11 2018. So replaced test.srcdir with
test.workdir.
Also changed variable name accordingly.
Please refer to:
avocado-framework/avocado#2509
id: 1568659
=> base_installer: replace test.srcdir with test.workdir

virttest/libvirt_xml/vm_xml.py
Sometimes VM with existing topology definition will break
when change in vcpus inside guest, this patch will help
to correct by introducing new function param.
=> Add support for topology correction

virttest/utils_misc.py
Add this common operation in avocado-vt, consider
it maybe useful for others
=> utils_misc: Add function get_pid()

virttest/passfd.c, virttest/passfd_setup.py
=> passfd: Support python 3

shared/cfg/guest-os/Linux.cfg
=> Delete file_system for case multi_disk

virttest/virsh.py
=> [python3] Fix for memtune list output in get method

avocado_vt/loader.py
Sometimes it might be hard to say why no Avocado-vt tests were
discovered. Let's add a "!VT" test type and in case of verbose discovery
use it to report why the discovery failed.
=> avocado_vt.loader: Report more info on verbose discovery

virttest/qemu_vm.py
=> Python 3: drop usage of raw unicode str

backends/v2v/cfg/convert_source.cfg
1.esx5.1 has out the testing frame
2.Add new esx6.7 version
Signed-off-by: kuwei <kuwei@redhat.com>
=> V2v:Delete esx5.1 and add esx6.7

virttest/libvirt_xml/devices/watchdog.py
Signed-off-by: yafu <yafu@redhat.com>
=> Add alias tag for watchdog device

virttest/asset.py, virttest/element_tree.py
=> [python3] Fix string no attribute error

virttest/utils_package.py
=> Python3: virttest/utils_package: fix str

virttest/utils_test/libvirt.py
Add support for vcpu hotplug through qemu monitor for powerpc
guests
=> Add support for vcpu hotplug through qemu monitor for powerpc

virttest/utils_hotplug.py
Add method to detect qemu package type to check for
vcpu hotunplug feature support
=> Add method to detect qemu package to check for feature support

virttest/rss_client.py
=> Python3 : bytes/str changes in rss_client

virttest/libvirt_xml/devices/video.py
=> Add two attributes to tag model

shared/cfg/base.cfg, virttest/test_setup.py
Improve set_hugepages() to enable setting hugepages on target numa nodes
=> test_setup: Enable setting hugepages on target nodes

virttest/env_process.py, virttest/test_setup.py
Fix TypeError: option values must be strings
=> [python3] Fix error when testing after change for log_level

virttest/guest_agent.py, virttest/qemu_monitor.py
=> Python 3: bytes/str updates for qemu monitors

virttest/qemu_monitor.py
=> qemu_monitor: Flush the log file after recorded new content

virttest/utils_misc.py
=> Python 3: replace decoding error

virttest/utils_stress.py
This commit adds both multi disk and multi network hotplug
to multivms with stress running inside guest
=> Add disk and network hotplug stress events

virttest/qemu_vm.py
After aexpect commit e6636d8 being merged, file descriptors should
be explicitly passed to the child process, so here edit `qemu_vm`
accordingly.
=> qemu_vm: Fix fd passing issue

virttest/qemu_vm.py
According to 6ea73ef.
Reverts: 0b84ea8
=> Revert "qemu_vm: Fix fd passing issue"

virttest/utils_test/__init__.py
abstract Stress() base class for VMStress and HostStress to reuse
the existing design for running stress (using configurable
params - stress, stress-ng, LTP, etc.,) in VM, host, remote host
and remove autotest dependency.
Reviewed-by: qizhu <qizhu@redhat.com>
Reviewed-by: Aihua Liang <aliang@redhat.com>
Acked-by: qizhu <qizhu@redhat.com>
Acked-by: Aihua Liang <aliang@redhat.com>
=> utils_test/__init__: Stress() to support VM, host, remote host

virttest/qemu_vm.py
id: 1347198
add attribute qmp_monitors in qemu_vm
=> qemu_vm.py: add attribute qmp_monitors

virttest/qemu_vm.py
Add support for option "deflate-on-oom" and "guest-stats-polling-interval"
id: 1572866, 1573806
=> qemu_vm: add more option support for balloon device

virttest/env_process.py
use join to wait for thread's completion.
=> env_process.py: use Thread.join

virttest/ssh_key.py
OpenSSH 7.0 disables ssh-dss keys by default,
so set the default ssh-rsa
Ref: https://www.openssh.com/txt/release-7.0
=> Update the default public key

virttest/utils_test/__init__.py
=> utils_test: fix error when get hardware time

virttest/libvirt_xml/vm_xml.py
Add support for newer pseries capabilities features
Reference: https://www.mail-archive.com/libvir-list@redhat.com/msg158480.html
=> Add support for newer pseries capabilities features

virttest/utils_test/__init__.py
=> utils_test: disable useless nohup output file

virttest/utils_misc.py
=> Add rsyslog service start function

virttest/utils_v2v.py
The new function can pass a 'errors' argument which is same as
errors in 'str.decode([encoding[, errors]])'.
=> Add a new check_exist_function for v2v

virttest/remote.py
currently APIs like copy_files_to(), copy_files_from() allow files to
be copied to, from remote <-> local. This patch add support to configure
scp to copy recursively/non recursively for directories/files to be copied 
with param.
=> remote: support recursive/non recursive scp to copy directory/file

virttest/utils_misc.py, virttest/virt_vm.py
APIs retrieves the sosreport and saves it in avocado debug log
directory by default, for guest/remote host it generates the sosreport
in temp dir and copies it to the local host debug log directory/path
given
=> APIs to retrieve sosreport of host/guest/remote host

virttest/qemu_devices/qcontainer.py
=> qcontainer.simple_hotplug(): only set pci.0 as bus to pci device

virttest/defaults.py
=> defaults: Check for arch for default asset

virttest/utils_time.py
Add timezone sync between host and guest, and clocksource
setting method in guest and host.
ID: 1445708
=> utils_time: Add common methods for timer device to avocado-vt

virttest/libvirt_vm.py
=> libvirt_vm: Update migrate func to pass 'readonly' argument

virttest/utils_test/libvirt.py
=> Add func to get disk alias

virttest/utils_net.py
1. Enable get host and windows guest locallink ipv6
2. Add extra notes for caculating ipv6 by mac
ID: 1566963
Signed-off-by: Pei Zhang <pezhang@redhat.com>
=> Improve ipv6 locallink support for windows

backends/v2v/cfg/convert_destination.cfg
=> Add default pool arguments for dest_none

virttest/utils_version.py
In python3, comparing non-numerical objects of different type raises
a TypeError by default. Correct the logic to check the version in
the interval when the lower boundary or upper boundary doesn't
exist.
ID: 1608691
=> utils_version: Update to logic to check version in the interval

virttest/libvirt_storage.py
Added option param for the virsh pool build call
=> Minor fix for build pool

virttest/utils_stress.py
Add support for host stress events, which would help
us to run multiple events in host in parallel to events for
guest and stress.
=> Add support for host stress events

virttest/qemu_devices/qcontainer.py
=> qcontainer: optimize unplug device verification process

backends/v2v/cfg/convert_destination.cfg, virttest/utils_v2v.py
=> Support -o rhv-upload option for virt-v2v

virttest/utils_time.py
=> utils_time: update sync_timezone api for linux

virttest/libvirt_xml/devices/console.py, virttest/libvirt_xml/devices/serial.py
=> Adding alias property for different devices

virttest/utils_v2v.py
=> Disconnect ovirt connection in cleanup function

virttest/libvirt_xml/devices/interface.py, virttest/libvirt_xml/nwfilter_binding.py, virttest/virsh.py
virsh command: add 4 virsh command support
- nwfilter_binding (create, delete, list, dumpxml)
add object: add object for nwfilter binding create params
xml format
Signed-off-by: qiulzhan <qiulzhan@redhat.com>
=> Add virsh command support and Add a new object in nwfilter_xml

virttest/qemu_vm.py
q35 machine has the different cmdline for floppy devices, this patch
corrects the usage for it.
ID: 1613133
=> qemu_vm: Correct the cmdline of floppy devices for q35

virttest/utils_misc.py
* Add the missing cpuflags to some amd models.
* Add new cpu model-flags mapping
ID: 1607363
=> Update cpu model-flags mapping

virttest/libvirt_vm.py
Add support for memory hotplug virt-install options
=> Add support for memory hotplug virt-install options

shared/scripts/wait_for_quit.py
=> there is no six module, no need to import it in wait_for_quit

shared/cfg/base.cfg, virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/utils_test/qemu/__init__.py
1. Support "merge", "dump", "discard-data" option for memory backend
2. Improve memdev verify process
ID:  1559278, 1559279, 1470549
=> virttest.qemu_devices: Improve memory hotplug verification

virttest/env_process.py
Power9 compat mode workaround is not needed for
processor revisions >= DD2.2, hence this patch
handles that condition and removes unwanted params
for smt switch and move whole logic check for smt
changes for only powerpc cpus.
=> Handle power9 compat mode workaround with pvr check

virttest/virsh.py
=> Add detach-device-alias virsh cmd

virttest/qemu_virtio_port.py
Note: the test cases still fail for other issue within virtio_console_guest(or maybe qemu issue, investigating).
id: 1610670
=> qemu_virtio_port: Adopt guest 'python' command to python3

virttest/test_setup.py, virttest/utils_net.py
Since not all distributions would support the `bridge_utils` tool,
we have to look for the alternative tools for better compatibility.
ID: 1622460
=> Replace the `bridge_utils` tool

virttest/utils_test/libvirt.py
the func check_result called the name "check_result"
but it can only check stderr result. Add stdout check
so it can check stderr and stdout both
Signe-off-by: qiulzhan <qiulzhan@redhat.com>
=> expand func check_result

virttest/utils_v2v.py
=> Add a general function to cleanup constant files

virttest/utils_test/__init__.py
stress tool might need some dependencies packages to be installed
before installing the tool, this patch enables a param that hold the
list of packages to be installed.
=> utils_test: install dependency packages for the stress tool

shared/scripts/rh_perf_envsetup.sh, shared/scripts/rh_perf_log_hostinfo_script.sh
=> Replace 'brctl' with alternatives for perf scripts

virttest/libvirt_xml/base.py, virttest/libvirt_xml/network_xml.py, virttest/utils_net.py, virttest/xml_utils.py
The new update for net-update cases related to this patch
1. add index for several functions as in network xml it can have several ip sections
2. add connection for network xml
3. change the get_active, del_active func for undefined check as undefined network
also can be actived and be deactived
4. add function del_element and get_interface_connection
5. change get_net_if for getting more judgement to get interface
6. add timeout for get_guest_ip_addr
=> Update for network related tests

virttest/utils_disk.py, virttest/utils_numeric.py
=> Update disk format related function

virttest/virt_vm.py
=> Add online param to count total sys memory including the offlines

virttest/utils_hotplug.py
The idea is to move commanly used memory hotplug functions
in libvirt_mem.py to virttest/utils_hotplug.py so that it
can be used by all.
As part of it I have ported cream_mem_xml function.
Once this is accepted I will try to port all other fuctions
too.
Signed-off-by: Hariharan T.S <hari@linux.vnet.ibm.com>
=> Memory Hotplug Generic API's

virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py
=> Fix issue of setting option for pc-dimm failed in hotplug_memory()

virttest/utils_test/libvirt.py
After libvirt 3.9.0, auth element can be placed into source element,
use one parameter auth_in_source to diff them.
=> add auth element placed in source part support when create disk xml

virttest/staging/utils_memory.py
=> utils_memory: Correct type

virttest/libvirt_xml/devices/librarian.py
=> Add vsock in DEVICE_TYPES

virttest/utils_numeric.py
`normalize_data_size` returns scientific notation number string
when the number is very small, this pacth fixed this issue.
id: 1642346
=> fixed a scientific notation issue

shared/scripts/virtio_console_guest.py, virttest/qemu_virtio_port.py
=> virtio_port: fix python3 format issues during data transfer

virttest/ovirt.py
=> Replace ovirtsdk with ovirtsdk4

virttest/qemu_storage.py
1. added qemu-img resize wrapper
2. fixed some style issues
id: 1641497
=> qemu_storage: added a resize method

virttest/guest_agent.py
Add function of guest-file-open/read/write/flush/seek/close.
ID: 1468931 1468524 1468933 1468932 1552417 1552418
=> virttest.guest_agent: Add function of guest-file

virttest/libvirt_xml/devices/memory.py, virttest/libvirt_xml/vm_xml.py
=> Add memorybacking/ memory xml to support discard

virttest/utils_disk.py
=> modify regular expression to match windows disk

virttest/utils_test/libvirt.py
=> add method to check dom uuid compliance with RFC

virttest/utils_test/libvirt.py
Add this common func considering it may be
useful for other tests
=> Add check_dumpxml

virttest/qemu_storage.py
Added a qemu-img map wrapper.
id: 1646843
=> qemu_storage: added a map method

virttest/libvirt_xml/vm_xml.py
Per automation need for tp-libvirt #1825
=> vm_xml: Add tseg attribute in VMFeaturesXML

virttest/utils_conn.py
=> Add change qemu conf for TLSConnection in utils_conn

virttest/utils_config.py
=> Add 'namespaces' parameter in qemu.conf

virttest/virsh.py
=> Add virsh cmd hypervisor-cpu-compare

virttest/test_setup.py
=> test_setup: check if set hugepages on target node successfully

avocado-plugins-vt.spec
To allow building RPM packages on Fedora 29.
=> SPEC: updated macros to Python 2

virttest/test_setup.py
=> Minorfix: Fixup the compare type

virttest/env_process.py, virttest/utils_net.py
Adopt migration setup to map hostname and ipaddress of the hosts in
source and target for virsh to resolve and migrate without error.
virsh throws error if it fails to resolve the IP during migration
```
error: Unable to resolve address 'ltc-fire4' service '49152': Name or service not known`
```
=> virsh requires hostname to resolved with IP for migration

virttest/env_process.py
Make sure all test keyvals updated by
gather all keyvals and update once and add
libvirt version support aswell.
=> Fixup: update test keyval

virttest/utils_hotplug.py, virttest/virt_vm.py
Add method to validate cpus and memory in numa node during
hotplug operation
=> Add support for guest numa node verification for hotplug

virttest/libvirt_vm.py, virttest/utils_test/libvirt.py
This reverts commit c8de82a32e6ed30c3751ff4bb64646491c4aec6a.
=> Revert c8de82a to get things working

virttest/utils_hotplug.py
=> Minorfix: Fixup the type error in Python3

virttest/utils_test/libvirt.py
iptables is a low level command. And firewall-cmd is more convenient for
management which can compatible with more low level commands. So it is
more preferable.
=> Replace iptables with firewall-cmd

virttest/utils_npiv.py
When device-mapper-multipath installed, it doesn't generate default
config file in /etc/multipath.conf, this will cause some cases failed
due to multipath commands failed. Add a method to prepare the config
file.
=> Add a method to prepare multipath config file

shared/cfg/guest-os/Linux/RHEL/7.6.cfg, shared/cfg/guest-os/Linux/RHEL/7.6/ppc64.cfg, shared/cfg/guest-os/Linux/RHEL/7.6/ppc64le.cfg
Add powerpc guest config for RHEL 7.6
=> Add powerpc guest config for RHEL 7.6

shared/cfg/guest-os/Linux/RHEL/7.6/x86_64.cfg
id: 1654557
signed-off-by: Yanan Fu <yfu@redhat.com>
=> guest-os: Add RHEL7.6 guest-os configuration for x86_64

virttest/env_process.py
=> fix python3 compatibility issue

virttest/libvirt_xml/vm_xml.py
=> Add vm title element in VMXMLBase

virttest/guest_agent.py
=> virttest.guest_agent: Fix issue that qga can't get response with '\xff' on python3

virttest/utils_hotplug.py
Add method to get load percentage of system(host/guest)
=> Add method to get load of system

virttest/utils_time.py
Add methods to get/set the ntp on guest/host
=> Add methods to get/set the ntp state on guest/host

virttest/libvirt_vm.py
Instead of waiting 300s for a failed result
=> Set wait time to 15s to install pm-utils

virttest/utils_windows/system.py
Checking if a file is existing in windows guest, reture true if yes.
ID: 1455812
=> utils_windows: Add file existing check function for windows

virttest/utils_config.py
=> Add a new option in LibvirtdSysConfig

virttest/utils_gdb.py
=> Replace method of checking 'type' with 'isinstance' 

virttest/guest_agent.py
=> virttest.guest_agent: Add function of guest-exec and guest-exec-status

virttest/test_setup.py
=> test_setup: clear memory caches before set hugepages

virttest/utils_time.py
Enable serial login in some cases and strip control code for
console session.
ID: 1649190
=> utils_time: enable serial login

virttest/utils_test/__init__.py
The run_avocado() function attempt to install Avocado framework
and plugins in case they aren't present in the guest. However,
currently it assumes the guest has python2 installed, which
isn't always true. So this change the function to check what
python version is installed on guest (python3 is preferred), then
use the correct binary.
It was introduced the find_python() function in the library
that should be used to check and return the python binary
installed (None otherwise) in the guest.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
=> virttest/utils_test: use correct python on run_avocado()

virttest/libvirt_xml/devices/memory.py
=> Fix missing args of address of memory class

virttest/virsh.py
- managedsave-dumpxml
- managedsave-define
- managedsave-edit
=> Add virsh command of managedsave

virttest/libvirt_xml/devices/iommu.py, virttest/libvirt_xml/devices/librarian.py
=> Add device type 'iommu'

virttest/utils_test/__init__.py
currently update_boot_option() doesn't check whether the kernel parameters
passed as input is already existing and whether it is really required
to be added or not, the parameters can be in any order and when multiple
parameters are given as input. This patch ensures to check the existing
kernel parameters in /proc/cmdline and perform add/remove based on it.
=> utils_test: add check to update_boot_option() for add/remove actual args

shared/cfg/virtio-win.cfg
=> virtio-win: add virtio drivers paths for Win10 OS

virttest/utils_test/libvirt.py
- Add option to determine to return xml object or xml file path
- Replace outdated function invoking
=> libvirt:Update function create_hostdev_xml

virttest/utils_test/libvirt.py
We need to set correct vm name for wait_for_migration_start() in case --dname is specified in virsh options.
To achieve this, we will have to change the parameter of check_vm_state() from vm object to vm_name
=> Wait for migration start

virttest/utils_test/libvirt.py
All test cases recommended to be executed in Enforcing mode, this
will make sure selinux related bugs could be exposed. But existing
code set selinux in Permissive mode, this should be fixed.
=> Not setting selinux to permissive by default when prepare nfs

virttest/staging/utils_memory.py
reuse the utils_memory APIs to work for remote machines by refactoring
it with remote session.
=> utils_memory: refactor APIs to work with remote session

virttest/libvirt_xml/devices/serial.py
=> Add pci address element and attributes to serial device

virttest/libvirt_xml/vm_xml.py
=> Add perf and event config in domain xml

virttest/libvirt_xml/devices/memory.py
- Add nested xml 'label' to 'target'
- Add element 'path' to 'source'
=> Update Memory class of libvirt devices

virttest/utils_hotplug.py
domstats output provides guest vcpu details, this
patch adds an method to test it for vcpu hotplug
validation.
=> Add vcpu hotplug validation on domstats output

virttest/qemu_vm.py
The issue:
qemu_vm.py:4428:21: E117 over-indented (comment)
=> Fix the issue of lint check

virttest/libvirt_vm.py
Currently, guest numa assignment takes the numa nodes as input
and assigns equal amount of cpu and memory to all nodes,
in real time we will/can have the memory less, sparse numa
nodes, so this patch addresses it by user defined numa nodes
and fallback to old implementation if no numa node definition
given.
This would be helpful to catch issues like
https://github.com/linuxppc/linux/issues/184
Usage:
For example, to get the below guest numa nodes layout inside guest user
has the params as follows
available: 4 nodes (0-3)
node 0 cpus: 0 2
node 0 size: 0 MB
node 0 free: 0 MB
node 1 cpus: 1 3
node 1 size: 0 MB
node 1 free: 0 MB
node 2 cpus: 4 5
node 2 size: 8162 MB
node 2 free: 7699 MB
node 3 cpus: 6 7
node 3 size: 0 MB
node 3 free: 0 MB
node distances:
node   0   1   2   3
0:  10  40  40 …
=> Add generic support for guest numa assignment for libvirt/virt-install

avocado-plugins-vt.spec
- Add support for release builds in addition to snapshot builds
- Add python 3 package and thus support for python 3 RPMs
=> Spec extensions

virttest/cartesian_config.py
=> Fix resource warnings due to open file in the Cartesian config

virttest/qemu_monitor.py
1. Update the method block_resize for compatibility
with blockdev.
2. Add a new method blockdev_open_tray.
3. Add a new method blockdev_close_tray.
4. Add a new method blockdev_remove_medium.
5. Add a new method blockdev_insert_medium.
6. Add a new method blockdev_change_medium.
7. Add a new method blockdev_add.
8. Add a new method blockdev_del.
ID: 1543688
=> qemu_monitor: Add and update qmp api for blockdev

virttest/libvirt_vm.py
reuse update_boot_option() in set_kernel_console() to configure console
parameter with kernel cmdline.
=> libvirt_vm: use update_boot_option() to avoid redundant code

virttest/env_process.py
This will have an effect if explicitly requested
=> Dump extra files at the test results directory during postprocessing

virttest/remote.py
=> Update the remote login function for ssh key

virttest/utils_misc.py
=> Update function:check_if_vm_vcpu_match to allow str input

virttest/libvirt_xml/devices/disk.py
Libvirt starts to support scsi-3 PR function by a <reservations> tag
since version 4.4.0. Add it to virtual disk's xml.
=> Add <reservations> tag for virtual disk xml

shared/cfg/guest-os/Windows/Win10/i386.cfg, shared/cfg/guest-os/Windows/Win10/x86_64.cfg, shared/cfg/guest-os/Windows/Win2008/i386.cfg, shared/cfg/guest-os/Windows/Win2008/x86_64.cfg, shared/cfg/guest-os/Windows/Win2012/x86_64.cfg, shared/cfg/guest-os/Windows/Win2016/x86_64.cfg, shared/cfg/guest-os/Windows/Win2019/x86_64.cfg, shared/cfg/guest-os/Windows/Win7/i386.cfg, shared/cfg/guest-os/Windows/Win7/x86_64.cfg, shared/cfg/guest-os/Windows/Win8/i386.cfg, shared/cfg/guest-os/Windows/Win8/x86_64.cfg
=> Add balloon service configuration for case balloon_memhp

.travis.yml
Involved by https://github.com/avocado-framework/avocado/pull/3060
=> Fix travis CI python2.7 failure

virttest/storage.py
=> fix a variable typo

virttest/virsh.py
There is one option for virsh define named "--validate"
=> Add options for virsh define

shared/cfg/guest-os/Linux.cfg, virttest/utils_misc.py, virttest/virt_vm.py
The cpu will not auto to online in fedora
=> Update the cpu check function

virttest/qemu_vm.py
=> qemu_vm: fix `status_test_command` error

virttest/libvirt_xml/devices/graphics.py
=> Add passwdValidTo configuration for graphics

virttest/test_setup.py
Add 2 functions to achieve following:
1.set kernel hugepages
2.get the number of certain hugepages totally allocated by kernel
Update 1 function:
1. get the number of free hugepages for given NUMA node
=> test_setup: add several functions to handle hugepages

shared/cfg/base.cfg, virttest/env_process.py
id: 1691263
Signed-off-by: Xiyue Wang <xiywang@redhat.com>
=> env_process: add param of enable_guest_iommu to guest kernel line

virttest/remote.py
This is a function dedicated to run a command on remote host.
=> libvirt: Add an utility to run remote command

virttest/virsh.py
=> virsh: Add migrate_getmaxdowntime function

virttest/utils_net.py, virttest/virt_vm.py
`verify_ip_address_ownership()` fails when ip address of VM is queried
after it is migrated to target host and cause the tests to error, handle
it using session to check on the remote host.
=> utils_net: verify_ip_address_ownership() on remote host if VM is migrated

virttest/utils_test/libvirt.py
As post migration check, pinging the vm to verify its network status and
vm availability is performed but vm.get_address() would fail to get
IP address by querying verify_ip_address_ownership() as it checks from
source host, so handle it by passing remote host session object to
make it work
=> utils_test/libvirt: post migration check query vm address from remote host

virttest/libvirt_xml/vm_xml.py
=> Add 'hpt' xml to vmfeatures

virttest/libvirt_xml/vm_xml.py
=> Add func set_vm_features to set features of vmxml

virttest/utils_hotplug.py
add parameter vcpu and options to get more info
Signed-off-by: Jin Li <jil@redhat.com>
=> affinity_from_vcpupin should take more parameters for virsh vcpupin

shared/cfg/base.cfg, virttest/env_process.py
=> env_process: Add kernel option iommu=pt for guest

avocado_vt/test.py
=> Fix typo in VT test docstring

virttest/libvirt_xml/devices/hostdev.py, virttest/libvirt_xml/vm_xml.py, virttest/utils_npiv.py, virttest/utils_test/libvirt.py
the attribute in class Hostdev should be unified with other device class
Signed-off-by: Jin Li <jil@redhat.com>
=> change the attribute of class Hostdev from hostdev_type to type

virttest/libvirt_vm.py
Add serial session support for VM reboot
=> Add serial session support for VM reboot

virttest/utils_net.py
check queues and msi via traceview
bz:1485225
=> utils_net.py: add traceview check for windows guests

virttest/env_process.py
=> cleanup_iommu: Cleanup iommu in postprocess stage

virttest/utils_test/qemu/__init__.py
=> Set value to args timeout

virttest/utils_disk.py
=> utils_disk: update package python-libguestfs for python3

virttest/qemu_devices/qcontainer.py
=> qcontainer: Add timeout arg to function simple_unplug

.travis.yml
=> Distinguish the avocado branch on travis CI for different python version

virttest/qemu_vm.py
Running `vm.reboot` while migrating the machine occasionally results in `virttest.qemu_monitor.MonitorSocketError: Could not receive data from monitor    ([Errno 104] Connection reset by peer)`. This is caused by using QMP monitor of the source (dead) VM.
While fixing that I also noticed changed behavior after 3c2f6241a that always uses QMP go_down method when available, even though the `shell` method defines it's own check_down method (that in fact does not suffer the migration issue). The first commits changes the logic to only use QMP when no better method is defined.
=> virttest.qemu_vm: Fix reboot when used with migration

virttest/utils_disk.py, virttest/utils_test/libvirt.py
This function to get the disk by given serial string.
Need to check ID_SERIAL in VM if disk is attached with serial property.
=> Add a function to get disk by serial string

virttest/utils_test/__init__.py
Making multivm stress [server-client] function as api in utils_test/__ini__.py.
So that other tests can utilize the same
=> Add multivm stress function as api

virttest/qemu_monitor.py
id:1718821
defined three methods to add, remove, and clear bitmap:
add_block_dirty_bitmap
remove_block_dirty_bitmap
clear_block_dirty_bitmap
Those three functions delegate call to _operate_dirty_bitmap.
=> QMPMonitor: support bitmap persistent

virttest/libvirt_xml/devices/redirdev.py
add attributes type, bus, source, protocol, alias and address
=> Add device class redirdev

virttest/qemu_monitor.py
=> small fix in coding style

virttest/libvirt_xml/vm_xml.py
Currently, numa cell is not updated when there is a
modification for vcpu numbers due to which numa
check during vcpu hotplug tests fails, this patch tries to
update the numa config accordingly.
Libvirt does not complain currently about the mismatch in
numa cell vcpus vs maxvcpus, below bug is raised for the
same.
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1656762
=> Fixup: Update numa cell based on modified vcpu number

virttest/cartesian_config.py
Fixes on typos and one more serious fix on regex operators' support for the suffix application at previous time instance.
=> Cartesian config fixes

shared/cfg/base.cfg, shared/cfg/machines.cfg, virttest/qemu_devices/qcontainer.py, virttest/qemu_devices/qdevices.py, virttest/qemu_vm.py, virttest/virt_vm.py
1. qdevices: Add Serial Bus representation
2. qcontainer: Add a wrapper for serial device creation
id: 1588423
=> Chardev: refactor chardev creation, for better multiple backend support

virttest/utils_time.py
=> utils_time: remove unnecessary clause

virttest/utils_test/libvirt.py
Post migration checks have to be done after every migration to
check whether VM is reachable in target, whether VM underwent
any reboots during migration and its expected state have to be
checked.
=> utils_test/libvirt: add post_migration_check() in MigrationTest

virttest/utils_net.py
As the current algorithm randomly picks only one byte to generate
a MAC address, there are unignorable MAC collisions during multiple
job instances running in the same LAN simultaneously.
This patch introduces a new generation algorithm which is based on
UUID1 combined with SHA256 and expands the random field size, and
that would significantly reduce the probability in theory.
Fixes: https://github.com/avocado-framework/avocado-vt/issues/2121 https://github.com/avocado-framework/avocado-vt/issues/1695
ID: 1716303
=> Introduce a new MAC generation algorithm

backends/v2v/cfg/convert_source.cfg, virttest/utils_v2v.py
1) Support -i vmx -it ssh for v2v
2) Reformat some codes
=> Add -i vmx -it ssh support for v2v

virttest/utils_test/libvirt.py
Need to check reason for domain state in some migration cases.
=> Enhance check_vm_state() to check reason for the state

virttest/tests/unattended_install.py
=> Add new mechanism to upgrade system during installation

virttest/libvirt_xml/devices/hostdev.py, virttest/libvirt_xml/devices/memory.py, virttest/libvirt_xml/devices/rng.py, virttest/utils_test/libvirt.py
1. update for hostdev, memory,  rng xml
2. update create xml func for each device
=> Update for alias test on xml and func

virttest/ovirt.py
Fixed: TestError: Failed to connect to windows guest: 'NoneType' object has
no attribute 'lower'
From log, esx6.0-win2019-x86_64 has beenconfigured with multiple interfaces
since the last success of the same script.
L0458 DEBUG| [stderr]  Bridge "VM Network" mac: 00:50:56:b7:fb:7d [e1000e]
L0458 DEBUG| [stderr]  Bridge "VM Network" mac: 00:50:56:b7:f9:0c [e1000]
L0458 DEBUG| [stderr]  Bridge "VM Network" mac: 00:50:56:b7:5d:1f [vmxnet3]
And then from the log timestamp, the utils_misc.wait_for function returns
in 100ms instead of 900s, it's very strange.
14:30:47,840 virt_vm  L1167 DEBUG| Attempting to log into 'esx6.0-win2019-x86_64UGX' (timeout 900s)
14:30:47,970 virt_vm  L1160 ERROR| Can't get guest network status information, reason: No console available.
Look into the ovirt.py, we can …
=> Fix getting mac problems for multi interfaces of vmware guests

virttest/utils_test/libvirt.py
This PR corrects #2153 which missed one update.
=> update argument for check_vm_state in libvirt
